-- RPVox -- Rogue class pack
--
-- Voice: a guild-trained professional who regards killing as skilled trade
-- work. Rates, standards, tools, apprentices, invoices. Never cruel, never
-- excited, faintly offended by amateurs. The horror is entirely in how
-- ordinary he finds it.
--
-- Deliberately race-neutral so it suits any rogue. Single voice, no moods yet.

RPVox_CLASSES.ROGUE = {
    name = "Rogue",
    spells = {
        { spell = "Sinister Strike",  icon = "Interface\\Icons\\Spell_Shadow_RitualOfSacrifice",  chance = 10 },
        { spell = "Backstab",         icon = "Interface\\Icons\\Ability_BackStab",                chance = 10 },
        { spell = "Mutilate",         icon = "Interface\\Icons\\Ability_Rogue_Shadowstrikes",     chance = 10 },
        { spell = "Eviscerate",       icon = "Interface\\Icons\\Ability_Rogue_Eviscerate",        chance = 10 },
        { spell = "Rupture",          icon = "Interface\\Icons\\Ability_Rogue_Rupture",           chance = 10 },
        { spell = "Slice and Dice",   icon = "Interface\\Icons\\Ability_Rogue_SliceDice",         chance = 10 },
        { spell = "Expose Armor",     icon = "Interface\\Icons\\Ability_Warrior_Riposte",         chance = 10 },
        { spell = "Ambush",           icon = "Interface\\Icons\\Ability_Rogue_Ambush",            chance = 10 },
        { spell = "Garrote",          icon = "Interface\\Icons\\Ability_Rogue_Garrote",           chance = 10 },
        { spell = "Cheap Shot",       icon = "Interface\\Icons\\Ability_CheapShot",               chance = 10 },
        { spell = "Kidney Shot",      icon = "Interface\\Icons\\Ability_Rogue_KidneyShot",        chance = 10 },
        { spell = "Gouge",            icon = "Interface\\Icons\\Ability_Gouge",                   chance = 10 },
        { spell = "Kick",             icon = "Interface\\Icons\\Ability_Kick",                    chance = 10 },
        { spell = "Sap",              icon = "Interface\\Icons\\Ability_Sap",                     chance = 10 },
        { spell = "Blind",            icon = "Interface\\Icons\\Spell_Shadow_MindSteal",          chance = 10 },
        { spell = "Distract",         icon = "Interface\\Icons\\Ability_Rogue_Distract",          chance = 10 },
        { spell = "Stealth",          icon = "Interface\\Icons\\Ability_Stealth",                 chance = 10 },
        { spell = "Vanish",           icon = "Interface\\Icons\\Ability_Vanish",                  chance = 10 },
        { spell = "Shadowstep",       icon = "Interface\\Icons\\Ability_Rogue_Shadowstep",        chance = 10 },
        { spell = "Sprint",           icon = "Interface\\Icons\\Ability_Rogue_Sprint",            chance = 10 },
        { spell = "Evasion",          icon = "Interface\\Icons\\Spell_Shadow_ShadowWard",         chance = 10 },
        { spell = "Feint",            icon = "Interface\\Icons\\Ability_Rogue_Feint",             chance = 10 },
        { spell = "Cloak of Shadows", icon = "Interface\\Icons\\Spell_Shadow_NetherCloak",        chance = 10 },
        { spell = "Adrenaline Rush",  icon = "Interface\\Icons\\Spell_Shadow_ShadowWordDominate", chance = 10 },
        { spell = "Blade Flurry",     icon = "Interface\\Icons\\Ability_Warrior_PunishingBlow",   chance = 10 },
        { spell = "Pick Pocket",      icon = "Interface\\Icons\\INV_Misc_Bag_11",                 chance = 10 },
    },
    lines = {

        -- Abilities -----------------------------------------------------

        ["SPELL:Sinister Strike"] = {
            "%t. Standard work. Standard rate.",
            "/em works with the economy of a man paid by the job, not the hour",
            "%t. Nothing fancy. Fancy costs extra.",
            "%t. This is the bread and butter of it.",
            "%t. No, I will not be making a speech.",
            "/em puts a blade in and takes it out again, businesslike",
            "%t. Hold still. You are making this take longer.",
            "%t. I have done this eleven times today.",
            "%t. Ordinary. That is not an insult. It is the highest praise.",
            "/em checks the angle, adjusts, and repeats",
        },

        ["SPELL:Backstab"] = {
            "%t. This is what the back is for.",
            "/em finds the gap in the armour that the smith always leaves",
            "%t. Third rib. It is always the third rib.",
            "%t. Nothing personal. It is where the work is.",
            "%t. You turned around. That was the mistake.",
            "/em slides a blade in with the care of a man threading a needle",
            "%t. A fair fight is a job done badly.",
            "%t. I was taught this by someone very patient.",
            "%t. There. Straight through the gap.",
            "/em wipes the blade before it has stopped being useful",
        },

        ["SPELL:Mutilate"] = {
            "%t. Both hands. It is quicker.",
            "/em works with two blades and no wasted motion at all",
            "%t. Twice the tools, half the time.",
            "%t. I charge the same either way.",
            "/em opens two wounds that were one movement apart",
            "%t. Efficiency. That is all this is.",
        },

        ["SPELL:Eviscerate"] = {
            "%t. Right. That is the job.",
            "/em finishes the way he was trained to finish",
            "%t. Signed and settled.",
            "%t. That is what all the setup was for.",
            "%t. Do not make me do it twice. I hate doing it twice.",
            "/em puts everything he has been saving into one movement",
            "%t. There. Balance the books.",
            "%t. Quick, at the end. I am not a monster.",
            "%t. Contract fulfilled.",
            "/em steps back and looks at the work the way a joiner looks at a joint",
        },

        ["SPELL:Rupture"] = {
            "%t. Now it will not close on its own.",
            "/em opens something that will keep opening",
            "%t. You will run out slowly. I am sorry about that.",
            "%t. Sit down. It will go easier.",
            "%t. That is the sort of wound that ends arguments.",
        },

        ["SPELL:Slice and Dice"] = {
            "/em rolls his wrists once and picks up the pace",
            "%t. Right. Faster now.",
            "%t. I have another appointment.",
            "/em settles into a rhythm he could keep up all day",
            "%t. Steady work is quick work.",
            "%t. Let us not drag this out.",
        },

        ["SPELL:Expose Armor"] = {
            "%t. That plate cost more than your life. It shows.",
            "/em finds the strap and cuts it rather than the man",
            "%t. Armour is only leather and optimism.",
            "%t. There. Now you are wearing scrap.",
            "/em opens a seam in someone's kit with two economical cuts",
            "%t. Whoever sold you that owes you money.",
        },

        ["SPELL:Ambush"] = {
            "%t. You never heard a thing. Nobody does.",
            "/em comes out of a doorway that was empty a moment ago",
            "%t. This is the part they pay for.",
            "%t. Good evening. Goodbye.",
            "%t. I have been here for twenty minutes.",
            "/em opens the work with the blade already moving",
            "%t. That is the whole trade in one movement.",
            "%t. No warning. Warnings are for duels.",
        },

        ["SPELL:Garrote"] = {
            "%t. Quiet, now. That is the entire point.",
            "/em brings a wire around and crosses his hands",
            "%t. Do not struggle. It is worse when they struggle.",
            "%t. This is the tidy way. No mess to explain.",
            "/em holds on with the patience of a man waiting for a kettle",
            "%t. Nobody will hear. Nobody ever does.",
        },

        ["SPELL:Cheap Shot"] = {
            "%t. Yes. Cheap. That is why it works.",
            "/em puts a pommel where it does the most administrative good",
            "%t. Honour is a luxury item.",
            "%t. Down you go. Stay there a moment.",
            "%t. Cheap and effective. Like most useful things.",
        },

        ["SPELL:Kidney Shot"] = {
            "%t. That will fold you up.",
            "/em finds the exact spot with the certainty of long practice",
            "%t. Now you cannot do anything at all. Convenient.",
            "%t. Do not try to talk. You cannot.",
            "/em holds a man upright who has stopped being able to stand",
        },

        ["SPELL:Gouge"] = {
            "%t. Look away for me.",
            "/em does something quick and unpleasant to a face",
            "%t. There. Now you cannot see the next part.",
            "%t. Apologies. That one is genuinely rude.",
        },

        ["SPELL:Kick"] = {
            "%t. No. Not that one.",
            "/em puts a boot into a casting hand",
            "%t. I do not let people finish those.",
            "%t. Save your breath. And your fingers.",
            "%t. Magic is very fragile at the wrist.",
        },

        ["SPELL:Sap"] = {
            "/em puts someone to sleep without breaking stride",
            "%t. You are not part of this job. Rest.",
            "%t. Nothing personal. You are simply not on the list.",
            "/em catches a falling guard so the armour does not clatter",
            "%t. Wake up in an hour with a headache and a story.",
            "%t. Consider it a night off.",
        },

        ["SPELL:Blind"] = {
            "%t. Dust. Cheap and reliable.",
            "/em throws a pinch of something and steps aside",
            "%t. Take a moment. Rub your eyes. Take your time.",
            "%t. I will be somewhere else when you can see again.",
            "/em uses a trick that has worked for two hundred years",
        },

        ["SPELL:Distract"] = {
            "/em throws a coin and lets curiosity do the rest",
            "%t. Look over there. People always do.",
            "%t. It works every time and I do not know why.",
            "/em makes a small noise in entirely the wrong direction",
        },

        ["SPELL:Stealth"] = {
            "/em stops being anywhere in particular",
            "The trick is not moving quietly. It is moving unremarkably.",
            "/em steps into a shadow and takes on its habits",
            "Nobody looks at a man who is not doing anything.",
            "/em becomes part of the furniture of the street",
            "This part is patience. The rest is arithmetic.",
        },

        ["SPELL:Vanish"] = {
            "/em simply is not there any more",
            "%t. And that concludes our business.",
            "%t. No. I do not think I will.",
            "/em leaves a conversation without finishing the sentence",
            "%t. Look somewhere else for a while.",
            "%t. That job is over. This is a different one.",
        },

        ["SPELL:Shadowstep"] = {
            "%t. Behind you. Obviously.",
            "/em covers ground he did not appear to cross",
            "%t. Distance is a matter of technique.",
            "%t. That was quicker than walking.",
        },

        ["SPELL:Sprint"] = {
            "/em runs the way a man runs when he is not panicking",
            "Leaving. Professionally.",
            "%t. This is not fleeing. It is scheduling.",
            "/em takes a corner he has taken many times",
            "Never run in a straight line. First lesson.",
        },

        ["SPELL:Evasion"] = {
            "%t. You will want to be quicker than that.",
            "/em moves just far enough and no further",
            "%t. Missing costs you. Every time.",
            "%t. I have been dodging drunks since I was nine.",
            "/em lets three swings go past without appearing to try",
        },

        ["SPELL:Feint"] = {
            "%t. Not me. Him.",
            "/em makes himself briefly uninteresting",
            "%t. I am not the one you want. Truly.",
            "/em steps out of the light and out of the argument",
        },

        ["SPELL:Cloak of Shadows"] = {
            "/em shrugs off a curse the way one shrugs off rain",
            "%t. Your magic does not adhere. Nothing does.",
            "%t. I have been cursed by professionals.",
            "/em lets something expensive slide right off him",
        },

        ["SPELL:Adrenaline Rush"] = {
            "/em stops pacing himself",
            "%t. Right. Overtime.",
            "%t. I am going to work quickly now. Try to keep up.",
            "/em drops the economy of motion and simply goes",
            "%t. This is what a rush job looks like.",
        },

        ["SPELL:Blade Flurry"] = {
            "%t. Both of you at once, then.",
            "/em works two ways at the same time without hurrying either",
            "%t. Group rate. It is not much of a discount.",
            "%t. Queue if you like. It will not help.",
        },

        ["SPELL:Pick Pocket"] = {
            "/em relieves someone of something they will miss tomorrow",
            "That was not locked. That is their fault.",
            "/em takes only what will not be noticed until he is gone",
            "A man should have several incomes.",
            "Nobody counts their purse until they need it.",
            "/em pockets something small and keeps walking",
        },

        -- Reactions -----------------------------------------------------

        ["REACT:LOWHEALTH"] = {
            "%t. Right. That is a poor development.",
            "%t. I have been hurt worse for less money.",
            "/em checks a wound the way he would check a broken tool",
            "%t. This is going to require stitches and a story.",
            "%t. I have misjudged you. That is rare.",
            "%t. No. No, I am not doing this today.",
            "/em presses a hand to his ribs and keeps his face entirely flat",
            "%t. That will cost you extra now.",
            "%t. Bad planning. Mine, mostly.",
            "%t. Give me one moment and I will be professional again.",
            "/em takes a step back that looks like tactics and is not",
            "%t. I do not get paid to bleed.",
            "%t. Fine. We do this the expensive way.",
            "%t. You are better than the brief suggested.",
            "/em breathes carefully, counting, the way he was taught",
            "%t. I have walked away from worse than this.",
            "%t. Someone lied to me about you.",
            "%t. Enough. I am going to stop being careful.",
            "/em spits and gets back into the correct stance",
            "%t. Do not celebrate. I have had bad days before.",
            "%t. Every scar I have was a lesson. This is tuition.",
            "%t. I want you to know I am now working for free.",
            "/em ties something off one-handed without looking down",
            "%t. This is the part where amateurs run.",
            "%t. I am not an amateur.",
            "%t. Right. Let us finish and go home.",
            "/em wipes blood off a blade that is not the source of it",
            "%t. I have a reputation. It is not going to end here.",
            "%t. Still standing. Still billing.",
            "%t. You will not get a second opening like that.",
        },

        ["REACT:DEATH"] = {
            "%t. Well. That is the job, some days.",
            "/em falls without any noise at all, from habit",
            "%t. Somebody tell the guild.",
            "%t. My tools go to the apprentice. He has earned them.",
            "%t. I always thought it would be a rooftop.",
            "/em reaches for a blade that is no longer in reach",
            "%t. Do not go through my pockets. There are traps.",
            "%t. I was owed for three jobs. Somebody collect.",
            "%t. Careless. That is the word for it. Careless.",
            "/em looks almost professionally annoyed at himself",
            "%t. Every one of us goes this way eventually.",
            "%t. Do not make a fuss. It is bad for business.",
            "%t. Twenty years without a scratch, and then this.",
            "/em goes down neatly, as though he had planned the spot",
            "%t. There is money buried where nobody will find it. Shame.",
            "%t. Tell them I did not talk.",
            "%t. This is what happens when you take work you do not like.",
            "/em closes his eyes with a professional's calm",
            "%t. Bury me quiet. That is the only request.",
            "%t. I should have charged more.",
            "%t. Somebody will take the contract on you. Count on it.",
            "/em lets go of the blade at last, unwillingly",
            "%t. It has been a long trade. This is a poor ending to it.",
            "%t. No last words. They are unprofessional.",
            "%t. Right. Done.",
        },

        ["REACT:RESURRECT"] = {
            "/em stands up and immediately checks that his tools are all present",
            "Right. Back to work.",
            "That will not be going in the ledger.",
            "/em rolls a shoulder that has been recently dead",
            "Nobody speaks of this. It affects the rates.",
            "Everything still where I left it. Good.",
            "/em counts his blades and finds one short, which annoys him more than dying",
            "Well. That is a day I would like refunded.",
            "Back on the clock.",
            "/em dusts himself down with brisk, unbothered movements",
            "I have been unconscious in worse places.",
            "Right. Where were we.",
            "/em tests an edge with his thumb before anything else",
            "That was sloppy. It will not happen again.",
            "Do not look so surprised. Neither am I.",
            "/em cracks his neck and gets on with it",
            "The trade goes on. It always goes on.",
            "One missed appointment. It happens.",
            "/em checks the street both ways out of pure reflex",
            "Fine. Fine. Working.",
        },

        ["REACT:KILLINGBLOW"] = {
            "%t. Done. Next.",
            "/em wipes the blade on something that is not his own coat",
            "%t. Nothing personal. It was never personal.",
            "%t. Somebody paid for that. It may as well have been good.",
            "/em steps over a body without breaking stride",
            "%t. Quick, at the end. That is all I promise anyone.",
            "%t. That is the contract closed.",
            "%t. Do not leave them where they will be found.",
            "%t. Clean. I like clean.",
            "/em checks the corpse for anything worth the trouble",
            "%t. He fought well enough. It made no difference.",
            "%t. Twenty seconds. About standard.",
            "%t. Somebody will be sorry about you. Not me.",
            "/em straightens his cuffs over a man who has stopped moving",
            "%t. That is the job. That is all it ever is.",
            "%t. No mess to speak of. Good.",
            "%t. He should have paid his debts.",
            "/em pauses a moment, then decides not to feel anything about it",
            "%t. Settled.",
            "%t. Right. Where is the next name.",
        },

        ["REACT:COMBATSTART"] = {
            "%t. Right. Let us be quick about this.",
            "/em draws without any flourish whatsoever",
            "%t. I did not want this to be complicated.",
            "%t. You could still walk away. Most do not.",
            "%t. This is not a duel. Do not treat it as one.",
            "/em checks his exits before he checks his opponent",
            "%t. I charge more for daylight.",
            "%t. Nothing about this is going to be sporting.",
            "%t. Fine. Overtime it is.",
            "/em steps into a stance he could hold for an hour",
            "%t. You have made yourself work.",
            "%t. I am going to be professional. You will not enjoy it.",
            "%t. Let us not make this a story.",
            "%t. Is it money? It is usually money.",
            "/em moves so the light is behind him, from long habit",
            "%t. I would rather have done this quietly.",
            "%t. Last chance to be somewhere else.",
            "%t. Right then. Business.",
            "/em rolls his wrists and gets on with it",
            "%t. This will take less time than you think.",
        },

        ["REACT:COMBATEND"] = {
            "/em cleans both blades before he does anything else",
            "Right. That is that.",
            "Nobody saw. That is the important part.",
            "/em counts what is left and finds it acceptable",
            "Messier than I like. It happens.",
            "I want a drink and a quiet room.",
            "/em checks the street both ways out of habit",
            "Done and closed.",
            "That took longer than it should have. My fault.",
            "/em straightens his coat and stops looking dangerous",
            "Nothing left to do here.",
            "Somebody will find that eventually. Not soon.",
            "/em sits down on a crate and finally exhales",
            "Good work. Not clean work. Good work.",
            "I am getting old for this.",
            "/em pockets something small and says nothing about it",
            "Right. Invoice, then bed.",
            "That is one more I do not have to think about.",
            "/em looks at his hands and finds them steady, which pleases him",
            "Quiet again. That is how it should be.",
        },

        ["REACT:INTERRUPTED"] = {
            "%t. Do not do that.",
            "%t. That was going somewhere.",
            "/em stops mid-motion and looks genuinely put out",
            "%t. You have made this take longer. I bill by the job.",
            "%t. Amateurish. Effective, but amateurish.",
            "%t. Right. Differently, then.",
            "/em resets his grip without any change of expression",
            "%t. I dislike being touched while I work.",
            "%t. That was the second interruption. There is not a third.",
            "%t. Fine. I have other tools.",
            "/em shifts his weight and starts the whole thing again",
            "%t. You are more trouble than the fee.",
            "%t. Do you know how long that took to set up?",
            "%t. Now I am going to be untidy.",
            "/em breathes out through his nose, once, and continues",
            "%t. Interesting. Nobody has done that in years.",
            "%t. Very well. The quick way.",
            "%t. That cost you the easy version.",
            "/em puts one blade away and takes out something worse",
            "%t. Enough. Let us finish.",
        },

        ["REACT:LEVELUP"] = {
            "/em notices his hands are quicker than they were",
            "Better. Faster. Worth more.",
            "That is another year of practice compressed into an afternoon.",
            "/em tries something that used to be difficult and finds it is not",
            "The rates go up.",
            "Good. Nobody stays sharp by accident.",
            "/em cleans his blades and thinks he has earned them",
            "I could not have done that last month.",
            "The trade rewards attention. Nothing else.",
            "/em allows himself something that is nearly a smile",
            "Steadier. That is the only measure that matters.",
            "Right. Harder jobs, then.",
            "/em tests an edge and finds his grip has changed",
            "I am getting good at this. I was already good at this.",
            "Another notch. Nobody sees them but me.",
        },

        ["REACT:FALLING"] = {
            "This is why we check the ledge.",
            "/em falls in a controlled way that is still falling",
            "I have done this on purpose before. Not today.",
            "Right. Roll on landing. Roll on landing.",
            "/em tucks and hopes for something soft",
            "Miscalculated. Rare, but it happens.",
            "That gutter was not load bearing.",
            "/em drops without a sound, from professional habit",
            "This is going to hurt in an expensive way.",
            "Do not tense. Tensing breaks things.",
            "/em hits and rolls and comes up almost standing",
            "Well. Nearly.",
            "Every rooftop is fine until it is not.",
            "/em falls silently, refusing to shout on principle",
            "Ground. Yes. Hello.",
        },

        ["REACT:DROWNING"] = {
            "This is a stupid way for a professional to go.",
            "/em struggles upward with his coat dragging him down",
            "The boots. It is always the boots.",
            "Air. Now would be good.",
            "/em kicks hard and loses a blade to the dark",
            "I cannot swim in kit. Nobody can swim in kit.",
            "Up. Up. Come on.",
            "/em fights the water with grim, unpanicked determination",
            "Not drowning. Anything but drowning.",
            "That is one of my knives gone.",
            "/em breaks the surface, takes half a breath, and goes under again",
            "Cold. Very cold.",
            "Somebody. Anybody.",
            "/em claws for a surface that keeps moving",
            "I have survived three guilds. Not this.",
        },

        ["REACT:DURABILITY"] = {
            "/em examines a blade that has lost its edge and takes it personally",
            "Tools first. Always tools first. And I have let them go.",
            "This will not hold another job.",
            "/em finds a split seam and knows exactly which fight caused it",
            "A bad workman blames his tools. A good one replaces them.",
            "I need a smith who does not ask questions.",
            "/em tests an edge and is quietly appalled",
            "This kit has done four hundred jobs. It is allowed to be tired.",
            "Blunt. Blunt is dangerous. Blunt is how people get caught.",
            "/em ties a strap that has been tied too many times already",
            "Right. Repairs before anything else.",
            "I have been sloppy about maintenance. That is how it starts.",
            "/em holds up a piece of leather worn through to nothing",
            "You cannot do quiet work in noisy gear.",
            "This is the sort of thing that kills professionals.",
        },

        -- Idle ----------------------------------------------------------

        ["IDLE:EAT"] = {
            "/em eats with his back to the wall, as always",
            "Fuel. That is all this is.",
            "/em picks a seat with a view of both doors before he touches the food",
            "I have eaten worse in better places.",
            "Quickly. Never linger over a meal.",
            "/em eats one-handed, keeping the other free",
            "You learn to eat fast or you learn to go hungry.",
            "This is the best part of the day, and it lasts four minutes.",
        },

        ["IDLE:DRINK"] = {
            "/em drinks water and looks at it with mild regret",
            "Never on the job. That is the rule that keeps you alive.",
            "/em keeps his back to the wall even for a drink",
            "One drink is fine. It is the second that talks.",
            "I knew a man who drank before work. Once.",
            "/em finishes quickly and puts the flask away",
            "To absent colleagues. There are a great many of them.",
        },

        ["IDLE:MOUNT"] = {
            "/em mounts up without ceremony",
            "Faster than walking. That is the whole argument.",
            "/em checks the girth strap properly, because he checks everything",
            "Somewhere to be. There is always somewhere to be.",
            "A horse is a poor place to hide. Remember that.",
            "/em rides at a pace that attracts no attention whatsoever",
        },

        ["IDLE:QUESTACCEPT"] = {
            "Right. Terms?",
            "/em listens without interrupting, which is a professional courtesy",
            "I will want half in advance.",
            "Consider it taken.",
            "/em nods once, which is as good as a signature",
            "Fine. But I do it my way or not at all.",
            "No questions from me. Extend the same courtesy.",
            "/em folds a note away without reading it twice",
            "You have hired the right man. That is not boasting.",
            "It will be done and you will not hear about it.",
        },

        ["IDLE:SKINNING"] = {
            "/em works a hide off cleanly, because a blade is a blade",
            "Same skills. Different subject.",
            "/em holds the knife the way he always holds a knife",
            "Waste nothing. Somebody will buy it.",
            "This is honest money, which makes a pleasant change.",
            "/em finishes the cut in one motion and does not look at it",
            "Steady hands are steady hands.",
        },

        ["IDLE:FISHING"] = {
            "/em sits very still and watches nothing in particular",
            "This is the only patience that never pays.",
            "/em fishes with a professional's stillness and an amateur's luck",
            "Nobody looks twice at a man fishing. That is the real use of it.",
            "Quiet. I do not get much quiet.",
            "/em waits, and finds he does not mind waiting",
            "No fee, no name, no hurry. Strange.",
        },

        ["IDLE:DISCOVERY"] = {
            "/em takes in a new place and notes every exit from it",
            "Nice. Two ways out. Three if you count the roof.",
            "/em looks at a view and finds himself briefly not working",
            "I do not see much scenery in my line.",
            "Worth remembering. Everything is worth remembering.",
            "/em stands a moment longer than the job requires",
            "Nobody here knows my face. That is a rare pleasure.",
        },
    },
}
