-- RPVox -- Priest-Lyrics class pack
--
-- Voice: song-lyric puns. Every line bends a well-known rock, hip hop or
-- R&B hook into the spell being cast. Kept in the addon rather than in saved
-- variables so it survives reinstalls and can live in version control.

RPVox_CLASSES = RPVox_CLASSES or {}

RPVox_CLASSES.PRIEST_LYRICS = {
    name = "Priest-Lyrics",
    class = "PRIEST",
    spells = {
        { spell = "Lesser Heal",               icon = "Interface\\Icons\\Spell_Holy_LesserHeal",               chance = 10 },
        { spell = "Heal",                      icon = "Interface\\Icons\\Spell_Holy_Heal",                     chance = 10 },
        { spell = "Greater Heal",              icon = "Interface\\Icons\\Spell_Holy_GreaterHeal",              chance = 10 },
        { spell = "Flash Heal",                icon = "Interface\\Icons\\Spell_Holy_FlashHeal",                chance = 10 },
        { spell = "Binding Heal",              icon = "Interface\\Icons\\Spell_Holy_BlindingHeal",             chance = 10 },
        { spell = "Renew",                     icon = "Interface\\Icons\\Spell_Holy_Renew",                    chance = 10 },
        { spell = "Prayer of Healing",         icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing02",        chance = 10 },
        { spell = "Prayer of Mending",         icon = "Interface\\Icons\\Spell_Holy_PrayerOfMending",          chance = 10 },
        { spell = "Circle of Healing",         icon = "Interface\\Icons\\Spell_Holy_CircleOfRenewal",          chance = 10 },
        { spell = "Power Word: Shield",        icon = "Interface\\Icons\\Spell_Holy_PowerWordShield",          chance = 10 },
        { spell = "Lightwell",                 icon = "Interface\\Icons\\Spell_Holy_SummonLightwell",          chance = 10 },
        { spell = "Desperate Prayer",          icon = "Interface\\Icons\\Spell_Holy_Restoration",              chance = 10 },
        { spell = "Resurrection",              icon = "Interface\\Icons\\Spell_Holy_Resurrection",             chance = 10 },
        { spell = "Pain Suppression",          icon = "Interface\\Icons\\Spell_Holy_PainSupression",           chance = 10 },
        { spell = "Power Word: Fortitude",     icon = "Interface\\Icons\\Spell_Holy_WordFortitude",            chance = 10 },
        { spell = "Prayer of Fortitude",       icon = "Interface\\Icons\\Spell_Holy_PrayerOfFortitude",        chance = 10 },
        { spell = "Divine Spirit",             icon = "Interface\\Icons\\Spell_Holy_DivineSpirit",             chance = 10 },
        { spell = "Prayer of Spirit",          icon = "Interface\\Icons\\Spell_Holy_PrayerofSpirit",           chance = 10 },
        { spell = "Shadow Protection",         icon = "Interface\\Icons\\Spell_Shadow_AntiShadow",             chance = 10 },
        { spell = "Prayer of Shadow Protection", icon = "Interface\\Icons\\Spell_Holy_PrayerofShadowProtection", chance = 10 },
        { spell = "Inner Fire",                icon = "Interface\\Icons\\Spell_Holy_InnerFire",                chance = 10 },
        { spell = "Fear Ward",                 icon = "Interface\\Icons\\Spell_Holy_Excorcism",                chance = 10 },
        { spell = "Power Infusion",            icon = "Interface\\Icons\\Spell_Holy_PowerInfusion",            chance = 10 },
        { spell = "Inner Focus",               icon = "Interface\\Icons\\Spell_Frost_WindWalkOn",              chance = 10 },
        { spell = "Dispel Magic",              icon = "Interface\\Icons\\Spell_Holy_DispelMagic",              chance = 10 },
        { spell = "Mass Dispel",               icon = "Interface\\Icons\\Spell_Arcane_MassDispel",             chance = 10 },
        { spell = "Cure Disease",              icon = "Interface\\Icons\\Spell_Holy_NullifyDisease",           chance = 10 },
        { spell = "Abolish Disease",           icon = "Interface\\Icons\\Spell_Nature_NullifyDisease",         chance = 10 },
        { spell = "Levitate",                  icon = "Interface\\Icons\\Spell_Holy_LayOnHands",               chance = 10 },
        { spell = "Mind Soothe",               icon = "Interface\\Icons\\Spell_Holy_MindSooth",                chance = 10 },
        { spell = "Mind Vision",               icon = "Interface\\Icons\\Spell_Holy_MindVision",               chance = 10 },
        { spell = "Shackle Undead",            icon = "Interface\\Icons\\Spell_Nature_Slow",                   chance = 10 },
        { spell = "Mind Control",              icon = "Interface\\Icons\\Spell_Shadow_ShadowWordDominate",     chance = 10 },
        { spell = "Fade",                      icon = "Interface\\Icons\\Spell_Magic_LesserInvisibilty",       chance = 10 },
        { spell = "Smite",                     icon = "Interface\\Icons\\Spell_Holy_HolySmite",                chance = 10 },
        { spell = "Holy Fire",                 icon = "Interface\\Icons\\Spell_Holy_SearingLight",             chance = 10 },
        { spell = "Holy Nova",                 icon = "Interface\\Icons\\Spell_Holy_HolyNova",                 chance = 10 },
        { spell = "Shoot",                     icon = "Interface\\Icons\\INV_Wand_01",                         chance = 10 },
        { spell = "Mind Blast",                icon = "Interface\\Icons\\Spell_Shadow_UnholyFrenzy",           chance = 10 },
        { spell = "Shadow Word: Pain",         icon = "Interface\\Icons\\Spell_Shadow_ShadowWordPain",         chance = 10 },
        { spell = "Shadow Word: Death",        icon = "Interface\\Icons\\Spell_Shadow_DemonicFortitude",       chance = 10 },
        { spell = "Mind Flay",                 icon = "Interface\\Icons\\Spell_Shadow_SiphonMana",             chance = 10 },
        { spell = "Psychic Scream",            icon = "Interface\\Icons\\Spell_Shadow_PsychicScream",          chance = 10 },
        { spell = "Shadowform",                icon = "Interface\\Icons\\Spell_Shadow_Shadowform",             chance = 10 },
        { spell = "Vampiric Embrace",          icon = "Interface\\Icons\\Spell_Shadow_UnsummonBuilding",       chance = 10 },
        { spell = "Vampiric Touch",            icon = "Interface\\Icons\\Spell_Holy_Stoicism",                 chance = 10 },
        { spell = "Silence",                   icon = "Interface\\Icons\\Spell_Shadow_ImpPhaseShift",          chance = 10 },
        { spell = "Shadowfiend",               icon = "Interface\\Icons\\Spell_Shadow_Shadowfiend",            chance = 10 },
        { spell = "Devouring Plague",          icon = "Interface\\Icons\\Spell_Shadow_BlackPlague",            chance = 10 },
        { spell = "Touch of Weakness",         icon = "Interface\\Icons\\Spell_Shadow_DeadofNight",            chance = 10 },
        { spell = "Hex of Weakness",           icon = "Interface\\Icons\\Spell_Shadow_FingerOfDeath",          chance = 10 },
        { spell = "Shadowguard",               icon = "Interface\\Icons\\Spell_Nature_LightningShield",        chance = 10 },
        { spell = "Starshards",                icon = "Interface\\Icons\\Spell_Arcane_StarFire",               chance = 10 },
        { spell = "Elune's Grace",             icon = "Interface\\Icons\\Spell_Holy_ElunesGrace",              chance = 10 },
        { spell = "Feedback",                  icon = "Interface\\Icons\\Spell_Shadow_RitualOfSacrifice",      chance = 10 },
        { spell = "Chastise",                  icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing",          chance = 10 },
        { spell = "Symbol of Hope",            icon = "Interface\\Icons\\Spell_Holy_SymbolOfHope",             chance = 10 },
        { spell = "Consume Magic",             icon = "Interface\\Icons\\Spell_Nature_Purge",                  chance = 10 },
    },
    lines = {

        ["MELEE"] = {
            "Hit me with your best shot, %t.",
            "I fought the law and the law was a mace, %t.",
            "Another one bites the mace, %t.",
            "Let's get physical, %t. Light forgive me.",
            "Beat it. With a blunt object, %t.",
            "Turn the other cheek? Not today, %t.",
            "Smack that, %t. Holy edition.",
            "Another one bites the dust, %t, and I did it with a blunt instrument.",
            "I fought the law, %t, and the law had a mace.",
            "You spin me right round, %t, and then I hit you.",
            "Can't touch this? I am literally touching this, %t.",
            "Sweet dreams are made of this, %t. Apparently.",
            "Under pressure, %t, and out of range of anything useful.",
            "Should I stay or should I go, %t? I am staying. Regrettably.",
            "Bad to the bone, %t. Bad at this, specifically.",
            "Can't touch this? I am literally touching this.",
            "Under pressure, and out of range of anything useful.",
        },

        ["REACT:LOWHEALTH"] = {
            "I get knocked down, %t. Then I heal myself.",
            "Somebody save me. Oh. That's my job, %t.",
            "Livin' on a prayer, %t. Professionally.",
            "Stayin' alive, %t. Barely.",
            "Bridge over troubled water, %t. I am the bridge.",
            "Everybody hurts. Me especially, %t.",
            "I will survive, %t.",
            "Say a little prayer for me, %t.",
            "Under pressure, %t.",
            "Ain't no sunshine down here, %t.",
            "Hold on, I'm coming. To myself, %t.",
            "Lean on me? There is nobody left to lean on, %t.",
            "Hit me one more time and find out, %t.",
            "Hurts so good. No it does not, %t.",
            "Still standing, %t.",
            "I get knocked down. Then I heal myself.",
            "Bridge over troubled water. I am the bridge.",
        },

        ["REACT:DEATH"] = {
            "Another one bites the dust. Me, this time.",
            "Knockin' on heaven's door. I have the key.",
            "Hello darkness, my old friend.",
            "Spirit in the sky. On my way.",
            "Comfortably numb.",
            "Fade to black.",
            "Dust in the wind.",
            "Goodbye yellow brick road.",
            "Don't fear the reaper. We have met.",
            "The show must go on. Without me.",
            "See you again. Sooner than you think.",
            "Tears in heaven. I'll ask around.",
            "Free fallin'. Straight down.",
            "Ashes to ashes.",
            "That's all she wrote.",
        },

        ["REACT:RESURRECT"] = {
            "Back in black.",
            "Get up. Stand up.",
            "Return of the mack.",
            "Reunited and it feels so good.",
            "Rise up.",
            "Ain't no stopping me now.",
            "I will always love you, whoever did that.",
            "Thank you. Next.",
            "Livin' on a prayer. It worked.",
            "Started from the bottom. Literally the floor.",
        },

        ["REACT:KILLINGBLOW"] = {
            "Another one bites the dust, %t.",
            "Say goodbye, %t.",
            "Hit the road, %t.",
            "Bye bye bye, %t.",
            "Rest in peace, %t. Sincerely.",
            "Ashes to ashes, %t.",
            "Sorry. Not sorry, %t.",
            "Beat it, %t.",
            "Killing me softly? No, %t. Loudly.",
            "Dust in the wind, %t.",
            "Who's next, %t?",
            "The Light works in mysterious ways, %t.",
            "That's the way, uh huh, I like it, %t.",
            "Killing me softly? No. Loudly.",
            "That's the way, uh huh, I like it.",
        },

        ["REACT:COMBATSTART"] = {
            "It's the final countdown, %t.",
            "Welcome to the jungle, %t.",
            "Eye of the tiger, %t.",
            "Enter sandman, %t.",
            "Bring the noise, %t.",
            "Let's get ready to rumble, %t.",
            "Lose yourself, %t.",
            "Say your prayers, %t.",
            "You picked the wrong priest, %t.",
            "It's about to go down, %t.",
            "Here we go again, %t.",
            "Onward, %t.",
            "It's the final countdown.",
            "You picked the wrong priest.",
        },

        ["REACT:COMBATEND"] = {
            "We are the champions.",
            "Celebrate good times. Come on.",
            "Let's stay together. Nobody die again.",
            "Take it easy.",
            "Another one down.",
            "Good times. Bad times.",
            "Cool it now.",
            "The party's over.",
            "Walk it off.",
            "Peace at last.",
        },

        ["REACT:INTERRUPTED"] = {
            "You interrupted my hymn, %t.",
            "Stop. In the name of the Light, %t.",
            "Rude, %t.",
            "Killing me softly with that kick, %t.",
            "Say it ain't so, %t.",
            "Don't stop the music, %t. Too late.",
            "That was mid-verse, %t.",
            "You shook me, %t.",
            "Cry me a river, %t. I am casting it again.",
            "Ain't that a shame, %t.",
            "You interrupted my hymn.",
            "Cry me a river. I am casting it again.",
        },

        ["REACT:LEVELUP"] = {
            "Movin' on up.",
            "Higher and higher.",
            "Stronger.",
            "The only way is up.",
            "Level up.",
            "Ain't no stopping me now.",
            "Bigger. Better. Brighter.",
            "I get up. And I keep going.",
        },

        ["REACT:FALLING"] = {
            "Free fallin'.",
            "Gravity is working against me.",
            "Levitate would have been clever four seconds ago.",
            "Down, down, down.",
            "Jump. Go ahead. Regret it.",
            "I'm falling and I cannot get up.",
            "Catch me now or explain it later.",
            "Rocket man. Bad landing.",
        },

        ["REACT:DROWNING"] = {
            "Under the sea. Not by choice.",
            "Rolling in the deep. Far too deep.",
            "Bridge over troubled water. Any bridge.",
            "I went chasing waterfalls. Bad idea.",
            "Air. Just a little bit of air.",
            "Swim. Just swim.",
            "Walking on water was the plan.",
            "Nobody's watching me drown out here.",
        },

        ["REACT:DURABILITY"] = {
            "Sharp dressed man. Formerly.",
            "Torn.",
            "Rags to rags.",
            "Material girl needs a repair vendor.",
            "These robes have seen the Light and a lot of teeth.",
            "Every seam coming apart.",
            "Dressed for considerably less.",
            "Shabby. Not chic.",
            "Wear and tear. Mostly tear.",
        },

        ["IDLE:EAT"] = {
            "Eat it. Just eat it.",
            "Hungry like the wolf.",
            "Cheeseburger in paradise.",
            "Just a little bit.",
            "Break bread with me.",
            "Feed me.",
        },

        ["IDLE:DRINK"] = {
            "Sip sip. Pass it along.",
            "Red red wine.",
            "Cheers to that.",
            "One more sip and I am back.",
            "Holy water. Probably.",
            "Drinking alone again.",
        },

        ["IDLE:HEALTHSTONE"] = {
            "I want a new drug. This one works.",
            "Feeling good.",
            "Better now.",
            "Sweet emotion. Sweet health.",
            "That's the good stuff.",
        },

        ["IDLE:MANAPOTION"] = {
            "Blue. Da ba dee.",
            "Down the hatch.",
            "Mana on demand.",
            "Spirit in a bottle.",
            "One blue, coming up.",
        },

        ["IDLE:FISHING"] = {
            "Nothing but a good time.",
            "Sittin' on the dock of the bay.",
            "Fishers of men. And also fish.",
            "Wasting away again.",
            "Patience. Sweet, sweet patience.",
            "Nothing biting. Still beats questing.",
        },

        ["IDLE:MINING"] = {
            "I've been working on the mine.",
            "Take this pick and shove it.",
            "Rock and roll. Mostly rock.",
            "Digging in the dirt.",
            "Diamonds in the rough. Mostly rough.",
        },

        ["IDLE:HERBALISM"] = {
            "Flower power.",
            "Every rose has its thorn.",
            "Kiss from a rose.",
            "Build me up, buttercup.",
            "Bed of roses. Taking it apart.",
        },

        ["IDLE:SKINNING"] = {
            "Leather and lace. Mostly leather.",
            "Bad to the bone. And the hide.",
            "Sorry, wolf.",
            "Working for the weekend. And the pelt.",
            "Forgive me. Again.",
        },

        ["IDLE:MOUNT"] = {
            "Born to be wild.",
            "Life is a highway.",
            "Ride on.",
            "Wild horses.",
            "Fast car.",
            "Hit the road.",
            "Take it easy. But faster.",
        },

        ["IDLE:QUESTACCEPT"] = {
            "I'm on my way.",
            "Say the word. It's done.",
            "Ain't no mountain high enough.",
            "Ask and you shall receive.",
            "Sign me up.",
            "I'll do it my way.",
            "Whatever you want. Whatever you need.",
        },

        ["IDLE:QUEST"] = {
            "Job done. Pay the man.",
            "We are the champions.",
            "Done and dusted.",
            "Time to get paid.",
            "That's all, folks. And the gold, please.",
            "Mission accomplished.",
        },

        ["IDLE:DISCOVERY"] = {
            "I still haven't found what I'm looking for. But this is nice.",
            "What a wonderful view.",
            "Wide open spaces.",
            "On the road again.",
            "New place, who this.",
            "Somewhere over the hill.",
        },

        ["IDLE:CRAFT:Alchemy"] = {
            "Shaken. Not stirred.",
            "Bubble, bubble. Mostly trouble.",
            "Mixing it up.",
            "Better living through chemistry.",
        },

        ["IDLE:CRAFT:Blacksmithing"] = {
            "Stop. Hammer time.",
            "Bang a gong.",
            "We built this city on hammering.",
            "Beat it. Into shape.",
        },

        ["IDLE:CRAFT:Cooking"] = {
            "It's getting hot in here.",
            "Too hot in the kitchen.",
            "Cooking up something good.",
            "Burn, baby, burn. On purpose this time.",
        },

        ["IDLE:CRAFT:Enchanting"] = {
            "Abracadabra.",
            "I put a spell on it.",
            "Under my spell.",
            "Sprinkle a little magic dust.",
        },

        ["IDLE:CRAFT:Engineering"] = {
            "She blinded me with science.",
            "It might explode. It usually explodes.",
            "Bang. That was supposed to happen.",
            "Blame it on the blast cap.",
        },

        ["IDLE:CRAFT:First Aid"] = {
            "Doctor, doctor, give me the news.",
            "Fix you.",
            "Wrap it up.",
            "Bandage on. Walk it off.",
        },

        ["IDLE:CRAFT:Jewelcrafting"] = {
            "Diamonds are forever.",
            "Shine bright.",
            "Cut it. Polish it. Sell it.",
            "Ice on ice.",
        },

        ["IDLE:CRAFT:Leatherworking"] = {
            "Leather and lace.",
            "Working the hide. Working the weekend.",
            "Born to be wild. Also to be a belt.",
            "Tough as leather.",
        },

        ["IDLE:CRAFT:Tailoring"] = {
            "Sharp dressed man.",
            "Material girl. Material priest.",
            "Stitched up.",
            "Every thread in its place.",
        },

        ["IDLE:CRAFT:Smelting"] = {
            "Feel the heat.",
            "I melt with you.",
            "Burning down the ore.",
            "Turn up the furnace.",
        },

        ["SPELL:Lesser Heal"] = {
            "Just a little bit, %t. That is all this rank is good for.",
            "A little bit of healing and a lot of respect, %t.",
            "Lesser Heal, %t. The name is doing a lot of honest work there.",
            "I'll be there for you, %t. Modestly. Very modestly.",
            "Small love, small heal, %t. Take what you are given.",
            "A little bit of love, %t. Very little. That is the rank.",
            "Every little thing counts, %t, and this is the littlest thing.",
            "Don't stop believin', %t, but do lower your expectations.",
            "It's not much, %t, but it's honest work.",
            "Hold on, %t. Hold on to a very small amount of health.",
            "Signed, sealed, delivered, %t. Barely.",
            "Lesser Heal, %t. The clue is in the name.",
            "Lesser Heal. The name is doing a lot of honest work there.",
            "Every little thing counts, and this is the littlest thing.",
        },

        ["SPELL:Heal"] = {
            "Lean on me, %t, when you're not strong. That is literally the job description.",
            "You've got a friend, %t, and the friend has a mana bar.",
            "Ain't no mountain high enough to keep me from getting a Heal to you, %t.",
            "Stand by me, %t. Stand behind me, ideally.",
            "Heal the world, %t. Starting with you, ending with my mana.",
            "Ain't no sunshine when you're down, %t. Here comes some.",
            "I'll be there for you, %t, when the rain starts to pour.",
            "With a little help from your friends, %t. I am the friend.",
            "Let me be your shelter, %t.",
            "Bridge over troubled water, %t. The mid-range version.",
            "I got you, babe, %t.",
            "Heal, %t. Reliable, unglamorous, always there.",
            "Lean on me, when you're not strong. That is literally the job description.",
            "Ain't no mountain high enough to keep me from getting a Heal to you.",
        },

        ["SPELL:Greater Heal"] = {
            "And I will always love you, %t, but you have to stop standing in things.",
            "Like a bridge over troubled water, %t, I will lay me down. Then I will need a drink.",
            "Ain't no mountain high enough, ain't no health bar low enough, %t.",
            "You wanted a hero, %t? Look at the mana bar and be grateful.",
            "Lean on me heavily, %t. This is the expensive one.",
            "One love, %t, one heart, one very large heal.",
            "Reach out, %t. I'll be there.",
            "You raise me up, %t. Now I raise you up. That is the arrangement.",
            "Greater Heal, %t. Everything I have, all at once.",
            "Rescue me, %t? Fine. Just this once. Again.",
            "Stand by me, %t, and I will stand by the mana bill.",
            "This is the big one, %t. Do not waste it.",
            "And I will always love you, but you have to stop standing in things.",
            "Ain't no mountain high enough, ain't no health bar low enough.",
        },

        ["SPELL:Flash Heal"] = {
            "Hold on, %t, I'm coming. Hold on, this is going to cost me everything.",
            "I will try to fix you, %t, but you have to stop breaking.",
            "Flash Heal, %t. No time to explain, no time to cast anything better.",
            "Right now, right here, %t. Ask me for mana later.",
            "Quick fix, %t. Emphasis on quick, no promises on fix.",
            "In the nick of time, %t.",
            "Don't stop me now, %t. I am having a terrible time.",
            "Signed, sealed, delivered, %t. In under two seconds.",
            "Flash Heal, %t. Expensive, instant, necessary.",
            "Faster than a speeding anything, %t.",
            "I got you, %t. Barely, but I got you.",
            "No time to think, %t. Only time to cast.",
            "Hold on, I'm coming. Hold on, this is going to cost me everything.",
            "Flash Heal. No time to explain, no time to cast anything better.",
        },

        ["SPELL:Binding Heal"] = {
            "One for you and one for me, %t. We're all in this together.",
            "Lean on me, %t, and I will quietly lean back. Nobody has to know.",
            "Binding Heal, %t. Sharing is caring and I am running low.",
            "Both of us at once, %t. Efficiency is its own kind of love.",
            "You and me, %t. Mostly me, if I am honest.",
            "You and me against the world, %t. The world is winning.",
            "Two birds, one stone, %t.",
            "Me and you and a mana bar, %t.",
            "Binding Heal, %t. The selfish one that isn't selfish.",
            "Reunited, %t. Both of us, upright.",
            "I get by with a little help from myself, %t.",
            "Everybody hurts, %t. Including the healer.",
            "One for you and one for me. We're all in this together.",
            "Binding Heal. Sharing is caring and I am running low.",
        },

        ["SPELL:Renew"] = {
            "Time after time, %t, it keeps ticking away on you.",
            "Renew, %t. It goes on and on and on, like the good ones do.",
            "Ain't no stopping it now, %t. It has got the moment and it is ticking.",
            "Every little thing, over time, is gonna be all right, %t.",
            "Drip by drip, %t. Patience is a healing spell.",
            "Rolling on, %t. It just keeps rolling on.",
            "Slow and steady, %t. Like a good bassline.",
            "Renew, %t. Set it and forget it.",
            "Little by little, %t. That is how it works.",
            "And the beat goes on, %t.",
            "Give it time, %t. Give it a little time.",
            "Tick, tick, tick, %t. In your favour, for once.",
            "Time after time, it keeps ticking away on you.",
            "Ain't no stopping it now. It has got the moment and it is ticking.",
        },

        ["SPELL:Prayer of Healing"] = {
            "Everybody hurts, %t. Everybody, all at once, apparently.",
            "Come together, right now, %t. Preferably inside my range.",
            "We are family, %t, and the whole family stood in the fire.",
            "Prayer of Healing, %t. One prayer, four ungrateful recipients.",
            "Everybody dance now, %t. Everybody heal now. Same thing.",
            "All together now, %t.",
            "Lean on me, all of you, %t. At once. Apparently.",
            "Prayer of Healing, %t. Four people, one cast, one enormous bill.",
            "Everybody's talking at me, %t, and everybody is also on fire.",
            "Reach out and touch somebody's health bar, %t.",
            "One more time, %t. All of you.",
            "Get up, everybody, %t. Get up.",
            "We are family, and the whole family stood in the fire.",
            "Everybody's talking at me, and everybody is also on fire.",
        },

        ["SPELL:Prayer of Mending"] = {
            "It bounces, %t, like a rubber ball, and it comes back to you.",
            "Pass it on, %t. Pass it on down the line.",
            "Prayer of Mending, %t. One heal, five owners, nobody says thank you.",
            "It jumps around, %t. Jump, jump.",
            "Sharing the love, %t. Whether you asked for it or not.",
            "Round and round it goes, %t.",
            "Prayer of Mending, %t. It keeps on giving and nobody notices.",
            "Here comes the bounce, %t.",
            "You spin me right round, %t, and then you heal somebody else.",
            "Pass the parcel, %t. Everybody wins.",
            "It goes around, %t. It comes around.",
            "One cast, five saves, %t. My favourite arithmetic.",
            "It bounces, like a rubber ball, and it comes back to you.",
            "Prayer of Mending. One heal, five owners, nobody says thank you.",
        },

        ["SPELL:Circle of Healing"] = {
            "It's the circle of life, %t, and it moves us all. Mostly it moves my mana.",
            "Everybody in the circle, %t. Nobody outside gets anything.",
            "We are family, %t. All of you, all at once, one button.",
            "Circle of Healing, %t. Stand closer and I will love you more.",
            "Ring around the party, %t. Group up and stop wandering.",
            "Come together, right now, %t. Over me.",
            "Circle of Healing, %t. Group up or get nothing.",
            "Round and round, %t. Everybody in it.",
            "We go together, %t. Like whatever that song says.",
            "Stand closer, %t. That is not affection, that is range.",
            "Everybody in, %t. Nobody out.",
            "One button, five people, %t. Worth every drop.",
            "It's the circle of life, and it moves us all. Mostly it moves my mana.",
            "We are family. All of you, all at once, one button.",
        },

        ["SPELL:Power Word: Shield"] = {
            "You can stand under my umbrella, %t. Ella. Ella.",
            "Hit me with your best shot, %t. Fire away. It is a bubble.",
            "This one is bulletproof, %t. Nothing you have is getting through.",
            "Power Word: Shield, %t. Can't touch this, and now neither can they.",
            "Bubble up, %t, and try not to look so pleased about it.",
            "Ain't nothing gonna break my stride, %t. Or yours, briefly.",
            "Shields up, %t. We are weathering this storm.",
            "Power Word: Shield, %t. And no, you cannot have another one yet.",
            "Beat it, %t. It will not get through anyway.",
            "Solid as a rock, %t.",
            "Try me, %t. Actually, try that.",
            "Nothing gets in, %t. That is the entire pitch.",
            "This one is bulletproof. Nothing you have is getting through.",
            "Bubble up, and try not to look so pleased about it.",
        },

        ["SPELL:Lightwell"] = {
            "This little light of mine, %t. I'm gonna let it stand there being ignored.",
            "There's a light over at the Lightwell, %t. Nobody has ever clicked it.",
            "It is right there, %t. It is free. It is right there.",
            "Lightwell, %t. Placed in hope, abandoned in practice.",
            "Somebody. Anybody. Click the well, %t.",
            "I can see the light, %t. Nobody else can, apparently.",
            "Lightwell, %t. Standing there. Waiting. Forever.",
            "You light up my life, %t. If only somebody would use you.",
            "Turn on the light, %t. Please. Anyone.",
            "It is free healing, %t, and it is right there.",
            "Nobody clicks it, %t. Nobody has ever clicked it.",
            "Hope is a thing with a click box, %t.",
            "This little light of mine. I'm gonna let it stand there being ignored.",
            "It is right there. It is free. It is right there.",
        },

        ["SPELL:Desperate Prayer"] = {
            "I say a little prayer for me, %t. Somebody has to.",
            "Whoa, we're halfway there, %t. Livin' on a prayer, and this is the prayer.",
            "Desperate Prayer, %t. The name is not being dramatic. That is the situation.",
            "Somebody save me, %t. Oh. It's me. It is always me.",
            "Praying is the whole plan now, %t. There is no second plan.",
            "Down on my knees, %t. Literally.",
            "Desperate Prayer, %t. Emphasis firmly on desperate.",
            "Save me, %t. Somebody. Anybody. Me, then.",
            "Last chance, %t. Making it count.",
            "Nothing left but faith and this button, %t.",
            "Pray for me, %t. Do not bother, I did it myself.",
            "When you're going through hell, keep going, %t.",
            "Desperate Prayer. The name is not being dramatic. That is the situation.",
            "Praying is the whole plan now. There is no second plan.",
        },

        ["SPELL:Resurrection"] = {
            "Get up, stand up, %t. Don't give up the fight.",
            "Back in black, %t. Try to stay that way this time.",
            "Reunited and it feels so good, %t. Now go and do it again.",
            "Rise up, %t. And maybe stand somewhere else.",
            "Return of the mack, %t. Buff yourself before you run in.",
            "Rise, %t. Rise up.",
            "Wake me up, %t. Well. I woke you up.",
            "Resurrection, %t. Do not make me do that twice.",
            "Come back to me, %t.",
            "Second chance, %t. Use it better than the first.",
            "Alive again, %t. You're welcome.",
            "Get on your feet, %t.",
            "Reunited and it feels so good. Now go and do it again.",
            "Return of the mack. Buff yourself before you run in.",
        },

        ["SPELL:Pain Suppression"] = {
            "No more drama, %t. Not for the next eight seconds.",
            "Comfortably numb, %t. Enjoy it while it lasts.",
            "Pain Suppression, %t. I cannot stop it, I can only turn it down.",
            "Take the pain away, %t. Temporarily. Everything is temporary.",
            "Hurt less, %t. That is the entire spell and it is enough.",
            "Nothing hurts for a moment, %t. Enjoy it.",
            "Pain Suppression, %t. Borrowed time, and I am the lender.",
            "Hold on, %t. Just hold on.",
            "The pain won't last, %t. Neither will this.",
            "Numb, %t. Beautifully numb.",
            "Eight seconds of peace, %t. Spend them well.",
            "I've got you, %t. For now.",
            "Pain Suppression. I cannot stop it, I can only turn it down.",
            "Hurt less. That is the entire spell and it is enough.",
        },

        ["SPELL:Power Word: Fortitude"] = {
            "What doesn't kill you makes you stronger, %t. This helps with the first part.",
            "Stand by me, %t, and stand a good deal longer than you would have.",
            "Power Word: Fortitude, %t. Bigger, better, considerably beefier.",
            "You've got a friend, %t, and now you've got stamina.",
            "Tough as nails, %t. Well. Tougher than you were.",
            "Stand tall, %t.",
            "Power Word: Fortitude, %t. Now go and get hit less badly.",
            "Bigger, stronger, harder to kill, %t.",
            "Built to last, %t.",
            "Every little bit helps, %t. This is a big bit.",
            "You're gonna need this, %t. You always do.",
            "Stamina, %t. The unglamorous buff.",
            "What doesn't kill you makes you stronger. This helps with the first part.",
            "Power Word: Fortitude. Bigger, better, considerably beefier.",
        },

        ["SPELL:Prayer of Fortitude"] = {
            "We are family, %t, and the whole family is getting stamina.",
            "Everybody gets one, %t. It's a family affair.",
            "Prayer of Fortitude, %t. One reagent, five people, nobody says thank you.",
            "One for all, %t. Now stop asking me individually.",
            "All of you, tougher, %t. Do not waste it.",
            "All of you at once, %t. Group buffs, group problems.",
            "Prayer of Fortitude, %t. The reagent is not free, you know.",
            "Everybody's tougher now, %t. Behave accordingly.",
            "One cast, whole party, %t.",
            "Stand tall, all of you, %t.",
            "You're welcome, %t. Collectively.",
            "Nobody thank me at once, %t.",
            "We are family, and the whole family is getting stamina.",
            "Prayer of Fortitude. One reagent, five people, nobody says thank you.",
        },

        ["SPELL:Divine Spirit"] = {
            "Gonna have a friend in Jesus? No, %t. You have got a spirit buff.",
            "Spirit in the sky, %t. Spirit in your mana bar, more usefully.",
            "I'm a soul man, %t. That is not a boast, it is a specialisation.",
            "Divine Spirit, %t. More mana, more soul, more of everything.",
            "Feel the spirit, %t. Then go and spend it.",
            "Spirit, %t. The stat nobody appreciates.",
            "Divine Spirit, %t. Your mana bar will thank me.",
            "Soul to soul, %t.",
            "Deeper wells, %t. That is all this is.",
            "Take my spirit, %t. Give it back in casts.",
            "Feeling spiritual, %t?",
            "Regeneration, %t. The slow kind. The good kind.",
            "Gonna have a friend in Jesus? No. You have got a spirit buff.",
            "I'm a soul man. That is not a boast, it is a specialisation.",
        },

        ["SPELL:Prayer of Spirit"] = {
            "Spirit in the sky, %t, and spirit for everybody standing near it.",
            "Everybody gets soul today, %t.",
            "Prayer of Spirit, %t. We are family, spiritually and expensively.",
            "One for all, %t. The reagent cost is my problem, not yours.",
            "All of you, deeper, %t. Use it well.",
            "Everybody gets spirit, %t. Everybody.",
            "Prayer of Spirit, %t. Expensive, communal, unappreciated.",
            "Deeper wells all round, %t.",
            "One for everyone, %t. Stop asking twice.",
            "Spirits up, %t. Mana up.",
            "You're welcome, %t. All of you.",
            "That reagent cost more than your boots, %t.",
            "Spirit in the sky, and spirit for everybody standing near it.",
            "Prayer of Spirit. We are family, spiritually and expensively.",
        },

        ["SPELL:Shadow Protection"] = {
            "Fear of the dark, %t? Not while I am standing here.",
            "Ain't no sunshine when it's gone, %t, but there ain't no shadow either.",
            "Shadow Protection, %t. The dark can't touch this.",
            "Nothing from the shadow is reaching you now, %t.",
            "Whatever is coming out of the dark, %t, it arrives smaller.",
            "Here comes the dark, %t. It bounces off.",
            "Shadow Protection, %t. Bring on the night.",
            "The dark is not your problem now, %t.",
            "Shadows fall, %t. Not on you.",
            "Warded, %t. Go and be brave about it.",
            "Nothing from the night, %t.",
            "Turn out the lights, %t. It will not matter.",
            "Fear of the dark? Not while I am standing here.",
            "Whatever is coming out of the dark, it arrives smaller.",
        },

        ["SPELL:Prayer of Shadow Protection"] = {
            "Fear of the dark, all of you, %t? Handled. Collectively.",
            "Everybody's covered, %t. Every single one of you.",
            "Prayer of Shadow Protection, %t. We are family, and the family is warded.",
            "One for all, %t. That is a lot of reagent for people who stand in things.",
            "The whole group, %t. Nobody has to be afraid of the dark.",
            "All of you warded, %t. Bring on the night.",
            "Prayer of Shadow Protection, %t. The whole group, the whole reagent.",
            "Nobody fears the dark today, %t.",
            "Shadows fall, %t. On nobody here.",
            "Group warded, %t. Behave.",
            "Turn out the lights, %t. Nobody cares.",
            "One cast, five saves, %t.",
            "Prayer of Shadow Protection. We are family, and the family is warded.",
            "Prayer of Shadow Protection. The whole group, the whole reagent.",
        },

        ["SPELL:Inner Fire"] = {
            "This priest is on fire, %t, and it is entirely internal.",
            "Light my fire, %t. From the inside, where it does the most good.",
            "Inner Fire, %t. Burning up in here and armoured out there.",
            "I've got a fire inside, %t. It is technically armour.",
            "Burning up, %t. Do not read anything into it.",
            "Feel the burn, %t. Internally.",
            "Inner Fire, %t. It looks like armour because it is.",
            "Something's burning, %t. Me. On purpose.",
            "Fire in my soul, %t. Armour on my back.",
            "Lit from within, %t.",
            "Burning bright, %t.",
            "I'm on fire, %t. It's fine. It's a buff.",
            "This priest is on fire, and it is entirely internal.",
            "Inner Fire. Burning up in here and armoured out there.",
        },

        ["SPELL:Fear Ward"] = {
            "Don't fear the reaper, %t. Certainly don't run from him.",
            "Fear of the dark, %t? Warded. Stand your ground.",
            "Fear Ward, %t. Whatever screams at you next, you are staying put.",
            "Nothing to fear now, %t. That is not encouragement, it is a buff.",
            "Hold the line, %t. You literally cannot do otherwise.",
            "Nothing scares you now, %t. Nothing.",
            "Fear Ward, %t. When they scream, you stay.",
            "Be not afraid, %t. Literally, you cannot be.",
            "Hold your nerve, %t. It is covered.",
            "No running today, %t.",
            "Fear is cancelled, %t.",
            "Scream all you like, %t. He is not moving.",
            "Don't fear the reaper. Certainly don't run from him.",
            "Fear Ward. Whatever screams at you next, you are staying put.",
        },

        ["SPELL:Power Infusion"] = {
            "I've got the power, %t, and now for a little while you do.",
            "Turn it up, %t. All the way up. That is the whole spell.",
            "Power Infusion, %t. Can't hold us now.",
            "Feel the power, %t. Use it before it leaves.",
            "Go on then, %t. Show me what that was worth.",
            "Take the power, %t. Use it now.",
            "Power Infusion, %t. Fifteen seconds of being important.",
            "Let it rip, %t.",
            "Everything faster, everything cheaper, %t.",
            "Go on then, %t. Impress me.",
            "The power is yours, %t.",
            "Don't waste it, %t. I am watching.",
            "I've got the power, and now for a little while you do.",
            "Power Infusion. Fifteen seconds of being important.",
        },

        ["SPELL:Inner Focus"] = {
            "This one's on the house, %t. Free of charge, literally.",
            "Inner Focus, %t. Nothing but a free spell and a good feeling.",
            "Focus, %t. Just a little bit, just for one cast.",
            "No mana, no cost, no complaints, %t.",
            "Free. That is the entire appeal, %t.",
            "Free of charge, %t. My favourite price.",
            "Inner Focus, %t. One perfect cast, no bill.",
            "Nothing up my sleeve, %t, and nothing out of my mana bar.",
            "On the house, %t.",
            "One for free, %t. Do not get used to it.",
            "Cost me nothing, %t. Costs you plenty.",
            "Concentrate, %t. Just this once.",
            "This one's on the house. Free of charge, literally.",
            "Focus. Just a little bit, just for one cast.",
        },

        ["SPELL:Dispel Magic"] = {
            "Shake it off, %t. Shake it right off.",
            "Dispel Magic, %t. Whatever they put on you is coming straight back off.",
            "Cleaning out my closet, %t, and now yours.",
            "No more drama, %t. Not the magical kind, anyway.",
            "Free your mind, %t. The rest will follow.",
            "Off it comes, %t.",
            "Dispel Magic, %t. Whatever that was, it is gone.",
            "Clean slate, %t.",
            "Wash it away, %t.",
            "Not on my watch, %t.",
            "Take it off, %t. Take it all off.",
            "Nothing sticks to you today, %t.",
            "Cleaning out my closet, and now yours.",
            "Dispel Magic. Whatever that was, it is gone.",
        },

        ["SPELL:Mass Dispel"] = {
            "Everybody shake it off, %t. All of you, at once.",
            "Mass Dispel, %t. No more drama anywhere in this postcode.",
            "Free your minds, %t. All of them. It is a big spell.",
            "Clean up, %t. Everything in that circle, gone.",
            "Whatever all of you are carrying, %t, put it down.",
            "Everybody clean, %t.",
            "Mass Dispel, %t. That whole circle, wiped.",
            "All of it, gone, %t.",
            "Wash it all away, %t.",
            "Clean slate for everyone, %t.",
            "Not on my watch, %t. Not any of it.",
            "Whatever all of you had, %t, you do not now.",
            "Free your minds. All of them. It is a big spell.",
            "Whatever all of you are carrying, put it down.",
        },

        ["SPELL:Cure Disease"] = {
            "Doctor, doctor, give me the news, %t. Actually, never mind. Cured.",
            "Bad case of something, %t. Not anymore you don't.",
            "Cure Disease, %t. That was disgusting and now it is gone.",
            "All better, %t. Try to be more careful about what touches you.",
            "Whatever that was, %t, we are not discussing it again.",
            "Clean bill of health, %t.",
            "Cure Disease, %t. Whatever crawled onto you is dead.",
            "Wash your hands, %t. Too late, I did it for you.",
            "That's better, %t.",
            "Gone, %t. Do not touch it again.",
            "Feeling better, %t? You should be.",
            "Sick no more, %t.",
            "Doctor, doctor, give me the news. Actually, never mind. Cured.",
            "Cure Disease. That was disgusting and now it is gone.",
        },

        ["SPELL:Abolish Disease"] = {
            "Doctor, doctor, again, %t. This one keeps working after I leave.",
            "Abolish Disease, %t. Gone, and staying gone, and gone again after that.",
            "Bad case of loving you? Worse, %t. Much worse. Handled.",
            "Whatever it is, %t, it keeps leaving. That is the upgrade.",
            "It will not stick this time, %t. That is the whole point.",
            "Gone, and gone again, %t.",
            "Abolish Disease, %t. It keeps cleaning after I stop.",
            "Whatever it is, %t, it cannot keep up.",
            "Three times over, %t. Nothing survives that.",
            "Persistent? So am I, %t.",
            "Clean, %t. And staying clean.",
            "Try coming back, %t. It will not.",
            "Doctor, doctor, again. This one keeps working after I leave.",
            "It will not stick this time. That is the whole point.",
        },

        ["SPELL:Levitate"] = {
            "You're walking on air, %t. Try not to enjoy it too much.",
            "Float on, %t. Just float on.",
            "Levitate, %t. Free fallin'? No. Free floatin'.",
            "Higher and higher, %t. Or at least considerably slower downward.",
            "Your feet don't touch the ground now, %t. Mind the reagent cost.",
            "Up where we belong, %t.",
            "Levitate, %t. Mind the reagent.",
            "Light as a feather, %t.",
            "Off the ground, %t. Try to look dignified.",
            "Drifting, %t.",
            "You're flying, %t. Sort of.",
            "Gravity is optional today, %t.",
            "You're walking on air. Try not to enjoy it too much.",
            "Your feet don't touch the ground now. Mind the reagent cost.",
        },

        ["SPELL:Mind Soothe"] = {
            "Relax, %t. Don't do it. Whatever it was, don't.",
            "Don't worry, %t. Be happy. Look the other way.",
            "Mind Soothe, %t. Nothing to see, nobody worth chasing.",
            "Take it easy, %t. Take it very, very easy.",
            "Calm down and look elsewhere, %t. There we are.",
            "Nothing to see, %t. Move along.",
            "Mind Soothe, %t. Go back to sleep.",
            "Easy now, %t.",
            "Look the other way, %t. Good.",
            "Peace, %t. Temporarily.",
            "Simmer down, %t.",
            "You never saw us, %t.",
            "Relax. Don't do it. Whatever it was, don't.",
            "Mind Soothe. Nothing to see, nobody worth chasing.",
        },

        ["SPELL:Mind Vision"] = {
            "Somebody's watching you, %t. It's me. It has been for a while.",
            "I can see clearly now, %t, and I am seeing it through your eyes.",
            "Private eyes, %t. They're watching you. Well. One of them is.",
            "Mind Vision, %t. Do carry on. Pretend I am not here.",
            "Borrowing your eyes for a moment, %t. You won't feel a thing.",
            "Seeing double, %t. Through your eyes.",
            "Mind Vision, %t. Do not mind me.",
            "I spy, %t.",
            "Watching from the inside, %t.",
            "Eyes on you, %t. Literally yours.",
            "Show me what you see, %t.",
            "I'm in, %t.",
            "Somebody's watching you. It's me. It has been for a while.",
            "Private eyes. They're watching you. Well. One of them is.",
        },

        ["SPELL:Shackle Undead"] = {
            "Stop, %t. In the name of the Light, before you break my group.",
            "Shackle Undead, %t. Can't touch this, and can't move either.",
            "Stand still and stand there, %t. We will get to you.",
            "Chained, %t. Do not make me recast this.",
            "You are having a time out, %t. A long one.",
            "Stay put, %t.",
            "Shackle Undead, %t. Sit there and think about it.",
            "Not you, %t. Not yet.",
            "Wait your turn, %t.",
            "Bound, %t. Do not struggle.",
            "One at a time, %t.",
            "Hold still, %t. This is for everyone's good.",
            "Stop. In the name of the Light, before you break my group.",
            "Stand still and stand there. We will get to you.",
        },

        ["SPELL:Mind Control"] = {
            "Under my thumb, %t. That's where you are now.",
            "I put a spell on you, %t, and now you're mine.",
            "Mind Control, %t. Walk this way. No, that way.",
            "You're a puppet on a string, %t, and I am holding the string.",
            "Say my name, %t. You will. You will say exactly what I want.",
            "Do as I say, %t.",
            "Mind Control, %t. Walk. Now walk further.",
            "You belong to me, %t.",
            "Sympathy for the priest, %t.",
            "Dance, %t.",
            "Off the cliff, %t. Go on.",
            "Every step you take, %t, I am taking it for you.",
            "Mind Control. Walk this way. No, that way.",
            "Say my name. You will. You will say exactly what I want.",
        },

        ["SPELL:Fade"] = {
            "Fade to black, %t. Nothing here worth hitting.",
            "Now you see me, now you don't, %t. Go and bother the tank.",
            "Fade, %t. I was never the interesting one anyway.",
            "Where'd I go, %t? Nowhere. You just stopped caring.",
            "Look away, %t. Look at literally anyone else.",
            "Nothing to see here, %t.",
            "Fade, %t. Go and hit the tank.",
            "I'm not the one you want, %t.",
            "Look away, %t. Keep looking away.",
            "Invisible in plain sight, %t.",
            "Forget about me, %t.",
            "Wrong target, %t.",
            "Fade to black. Nothing here worth hitting.",
            "Fade. I was never the interesting one anyway.",
        },

        ["SPELL:Smite"] = {
            "Let there be light, %t. Directly into your face.",
            "Hit me with your best shot? No, %t. Mine first.",
            "Smite, %t. Beat it, but sanctified.",
            "Bang bang, %t. But holy, and therefore fine.",
            "Straight to the face with the Light, %t. It is a classic for a reason.",
            "Holy light, %t. Right in the face.",
            "Smite, %t. Old fashioned and effective.",
            "Blinded by the light, %t.",
            "Take that, %t. Righteously.",
            "The Light says no, %t.",
            "One more for the faith, %t.",
            "Straight down the middle, %t.",
            "Let there be light. Directly into your face.",
            "Straight to the face with the Light. It is a classic for a reason.",
        },

        ["SPELL:Holy Fire"] = {
            "Burn, baby, burn, %t. Righteously, though, so it doesn't count.",
            "I fell into a burning ring of fire, %t. Then I pushed you in.",
            "Great balls of holy fire, %t.",
            "Holy Fire, %t. Come on baby, light my fire, the consecrated one.",
            "This priest is on fire, %t, and so, now, are you.",
            "Light my fire, %t. The holy one.",
            "Holy Fire, %t. It burns and it keeps burning.",
            "Set you on fire, %t. Consecrated fire, mind.",
            "The Light is warm, %t. Very warm.",
            "Sacred flame, %t.",
            "Burning for you, %t. Not romantically.",
            "Fire and faith, %t.",
            "Burn, baby, burn. Righteously, though, so it doesn't count.",
            "This priest is on fire, and so, now, are you.",
        },

        ["SPELL:Holy Nova"] = {
            "Everybody dance now, %t. Everybody take a little damage now.",
            "Holy Nova, %t. Healing and hurting in one button, like a professional.",
            "Boom, %t. But polite. But still boom.",
            "Ring around everybody, %t. Friends get one thing, you get another.",
            "Light it up all around, %t. Nobody is left out.",
            "Everybody, %t. All at once.",
            "Holy Nova, %t. Expensive, and everybody loves it.",
            "Light in every direction, %t.",
            "Heal and harm, %t. Same button.",
            "Nova, %t. Do not stand too close.",
            "It goes off in all directions, %t.",
            "One for everyone, %t. Whether you wanted it or not.",
            "Everybody dance now. Everybody take a little damage now.",
            "Holy Nova. Expensive, and everybody loves it.",
        },

        ["SPELL:Shoot"] = {
            "Shot through the heart, %t, and you're to blame. I'm out of mana.",
            "Bang bang, %t. That is all that is left in the tank.",
            "Out of mana and into indignity, %t. Nothing but a bad time.",
            "Ain't too proud to beg, %t, and not too proud to use a stick.",
            "Pew, %t. Years of theology, and pew.",
            "Wand, %t. That is what we have come to.",
            "Out of everything, %t. Except this stick.",
            "Shoot, %t. Slowly. Sadly.",
            "Conserving mana, %t. Do not comment.",
            "Plink, %t.",
            "It counts as damage, %t. Barely.",
            "Years of scripture, %t, and a stick.",
            "Shot through the heart, and you're to blame. I'm out of mana.",
            "Out of mana and into indignity. Nothing but a bad time.",
        },

        ["SPELL:Mind Blast"] = {
            "I just can't get you out of my head, %t. So I am putting something into yours.",
            "Mind Blast, %t. Straight to the brain, no stops on the way.",
            "Mind games, %t. Very short ones.",
            "Get out of my head, %t. And now get out of your own.",
            "Boom, %t. That was the inside of your skull.",
            "Straight to the head, %t.",
            "Mind Blast, %t. My favourite noise.",
            "Think fast, %t.",
            "Head games, %t.",
            "That was your brain, %t. Was.",
            "Blast off, %t.",
            "Right between the ears, %t.",
            "I just can't get you out of my head. So I am putting something into yours.",
            "Boom. That was the inside of your skull.",
        },

        ["SPELL:Shadow Word: Pain"] = {
            "Love hurts, %t, but this hurts considerably more and for longer.",
            "Shadow Word: Pain, %t. It goes on and on and on.",
            "Hurts so good, %t. Not for you. For me.",
            "Slow burn, %t. The best ones always are.",
            "Just a little bit of pain, %t, every few seconds, forever.",
            "It's a slow poison, %t.",
            "Shadow Word: Pain, %t. Set it and forget it.",
            "Tick, tick, tick, %t. BOOM!",
            "Every second, a little more, %t.",
            "It's still working, %t. It is always working.",
            "You'll feel that for a while, %t.",
            "Patience, %t. It gets worse.",
            "Love hurts, but this hurts considerably more and for longer.",
            "Just a little bit of pain, every few seconds, forever.",
        },

        ["SPELL:Shadow Word: Death"] = {
            "Another one bites the dust, %t. Say goodbye.",
            "Shadow Word: Death, %t. It kills me a little too. Literally.",
            "Last words, %t. Yours, not mine, hopefully.",
            "This one hurts us both, %t, but it hurts you conclusively.",
            "Finish him, %t. That is not a suggestion, it is the spell.",
            "Last one, %t.",
            "Shadow Word: Death, %t. It hurts me too, but less.",
            "Finishing move, %t.",
            "The end, %t.",
            "Goodnight, %t.",
            "That's all she wrote, %t.",
            "Down you go, %t.",
            "Finish him. That is not a suggestion, it is the spell.",
            "Shadow Word: Death. It hurts me too, but less.",
        },

        ["SPELL:Mind Flay"] = {
            "You just can't get me out of your head, %t. That is rather the point.",
            "Mind Flay, %t. Slow, unpleasant, and entirely inside your skull.",
            "Mind games, %t. This one takes a few seconds.",
            "Drip, drip, straight into the brain, %t.",
            "I am in there now, %t, and I am taking my time.",
            "In your head, %t, and staying there.",
            "Mind Flay, %t. Slow, steady, unpleasant.",
            "Channelling, %t. Do not interrupt.",
            "Peeling it back, %t.",
            "This takes a moment, %t. Enjoy the moment.",
            "Still going, %t.",
            "Head first, %t.",
            "You just can't get me out of your head. That is rather the point.",
            "I am in there now, and I am taking my time.",
        },

        ["SPELL:Psychic Scream"] = {
            "Run, %t. Everybody run. That was the idea.",
            "Psychic Scream, %t. Bye bye bye, all of you.",
            "Somebody scream, %t. Everybody scream. There we are.",
            "Everybody out, %t. Come back when you have calmed down.",
            "Off you go, %t. All of you, in four directions.",
            "Everybody panic, %t.",
            "Psychic Scream, %t. Off you go, all of you.",
            "Scatter, %t.",
            "Not today, %t. Come back later.",
            "Four directions, %t. Pick one.",
            "Get out, %t.",
            "Nobody stays, %t.",
            "Somebody scream. Everybody scream. There we are.",
            "Off you go. All of you, in four directions.",
        },

        ["SPELL:Shadowform"] = {
            "I see a red door and I want it painted black, %t.",
            "Back in black, %t. And no, I cannot heal you now.",
            "Shadowform, %t. Hello darkness, my old friend.",
            "Welcome to the dark side, %t. There are no bandages here.",
            "No more healing, %t. Sorry. Not sorry.",
            "Lights out, %t.",
            "Shadowform, %t. Do not ask me for a heal.",
            "Into the dark, %t.",
            "Darker than black, %t.",
            "No more Mister Nice Priest, %t.",
            "The shadow takes over, %t.",
            "This is who I really am, %t.",
            "I see a red door and I want it painted black.",
            "Shadowform. Hello darkness, my old friend.",
        },

        ["SPELL:Vampiric Embrace"] = {
            "I get by with a little help from your suffering, %t.",
            "Your pain is my gain, %t, and everyone else's too.",
            "Vampiric Embrace, %t. Love bites. It bites the whole group better.",
            "Sharing is caring, %t, and you are doing the sharing.",
            "Everything that happens to you now feeds somebody, %t.",
            "Everything hurts you, %t, and heals us.",
            "Vampiric Embrace, %t. Group healing by proxy.",
            "Your loss, our gain, %t.",
            "Bleed for the team, %t. My team.",
            "Thanks for the blood, %t.",
            "It's a group effort, %t. You are the group.",
            "Suffering, redistributed, %t.",
            "Vampiric Embrace. Love bites. It bites the whole group better.",
            "Everything that happens to you now feeds somebody.",
        },

        ["SPELL:Vampiric Touch"] = {
            "Love bites, %t. This one bites and keeps the change.",
            "Vampiric Touch, %t. Taking a little off the top, continuously.",
            "Every little thing you have is mine now, %t.",
            "Just a little touch, %t, and it does not stop.",
            "You are paying my mana bill, %t. You do not get a say.",
            "Draining you slowly, %t.",
            "Vampiric Touch, %t. My mana bar says thank you.",
            "Every tick pays me, %t.",
            "Taking a cut, %t.",
            "You're funding this, %t.",
            "Slow drain, %t. Steady income.",
            "Nothing personal, %t. Just mana.",
            "Love bites. This one bites and keeps the change.",
            "You are paying my mana bill. You do not get a say.",
        },

        ["SPELL:Silence"] = {
            "Hello darkness, my old friend, %t. Now you try it.",
            "Silence, %t. Shut up and dance? Just the first part.",
            "Nothing to say now, %t. Nothing at all.",
            "The sound of silence, %t. It suits you enormously.",
            "Hush, %t. That is the whole spell and it is beautiful.",
            "Not a word, %t.",
            "Silence, %t. It is golden.",
            "Quiet on the set, %t.",
            "Shhh, %t.",
            "No more casting, %t.",
            "You had a lot to say, %t. Not now.",
            "Enjoy the quiet, %t.",
            "Hello darkness, my old friend. Now you try it.",
            "Hush. That is the whole spell and it is beautiful.",
        },

        ["SPELL:Shadowfiend"] = {
            "Say hello to my little friend, %t. He eats mana bars.",
            "Who let the fiend out, %t? I did. Obviously I did.",
            "Shadowfiend, %t. Bad kitty. Very good kitty, actually.",
            "Sic 'em, %t. Bring me back something blue.",
            "He is not friendly and he is not staying long, %t.",
            "Go get 'em, %t.",
            "Shadowfiend, %t. Bring me back a mana bar.",
            "Release the fiend, %t.",
            "He's hungry, %t.",
            "Off you go, little one, %t.",
            "Don't look at it, %t. It bites.",
            "Ten seconds of chaos, %t.",
            "Say hello to my little friend. He eats mana bars.",
            "Shadowfiend. Bad kitty. Very good kitty, actually.",
        },

        ["SPELL:Devouring Plague"] = {
            "A plague on both your houses, %t. Mostly yours.",
            "Devouring Plague, %t. It eats you and I get better. Everyone wins.",
            "Bad to the bone, %t. And then through the bone.",
            "Slow burn, %t. Very slow, and it feeds me the whole way.",
            "This one is on a long timer, %t. Get comfortable.",
            "It's eating you, %t. Slowly.",
            "Devouring Plague, %t. Long, slow and profitable.",
            "Rot, %t.",
            "Every tick feeds me, %t.",
            "This one is on a timer, %t. A long one.",
            "Sickness, %t. The gift that keeps giving.",
            "You will not shake this, %t.",
            "This one is on a long timer. Get comfortable.",
            "Devouring Plague. Long, slow and profitable.",
        },

        ["SPELL:Touch of Weakness"] = {
            "Touch me and regret it, %t. That is the arrangement now.",
            "Touch of Weakness, %t. You are getting weaker just standing there.",
            "Whatever you hit me with, %t, it comes back smaller.",
            "Just a little touch, %t, and a lot less of you.",
            "Go on, %t. Swing. See what it costs you.",
            "Weaker with every swing, %t.",
            "Touch of Weakness, %t. Hit me and find out.",
            "Diminishing returns, %t.",
            "You're fading, %t.",
            "Less and less, %t.",
            "That cost you, %t.",
            "Try again, %t. It will hurt less. For me.",
            "Touch me and regret it. That is the arrangement now.",
            "Whatever you hit me with, it comes back smaller.",
        },

        ["SPELL:Hex of Weakness"] = {
            "You're weaker now, %t, and it is only going one direction.",
            "Hex of Weakness, %t. Everything you do lands softer.",
            "Feeling small, %t? Good. That is working.",
            "A hex on you, %t. Nothing personal. Entirely personal.",
            "Less of you every second, %t.",
            "Cursed and shrinking, %t.",
            "Hex of Weakness, %t. Everything lands softer from here.",
            "Feeble, %t.",
            "Down, down, down you go, %t.",
            "You've got nothing, %t.",
            "Smaller by the second, %t.",
            "The hex is on, %t.",
            "Good luck with that, %t.",
            "You're weaker now, and it is only going one direction.",
            "Hex of Weakness. Everything lands softer from here.",
        },

        ["SPELL:Shadowguard"] = {
            "Touch me and get zapped, %t. Your choice entirely.",
            "Shadowguard, %t. Careful. It bites back.",
            "Shocking, %t. Genuinely, electrically shocking.",
            "Guard up, %t. Come and find out what that means.",
            "Every hit you land costs you something, %t.",
            "Charged up, %t. Come and touch it.",
            "Shadowguard, %t. Every hit costs you.",
            "Zap, %t.",
            "It bites back, %t.",
            "Careful now, %t.",
            "Three charges, %t. Use them wisely. Or do not.",
            "That was your idea, %t.",
            "Touch me and get zapped. Your choice entirely.",
            "Shocking. Genuinely, electrically shocking.",
        },

        ["SPELL:Starshards"] = {
            "There's a starman waiting in the sky, %t, and he is dropping things on you.",
            "Starshards, %t. Wish upon a star. Bad wish.",
            "Shards from the sky, %t. One after another after another.",
            "Star fall, %t. Directly onto your head.",
            "Elune is looking at you, %t, and she is not pleased.",
            "The sky is falling, %t. On you.",
            "Starshards, %t. Elune sends her regards.",
            "Down they come, %t.",
            "Falling stars, %t. Sharp ones.",
            "Look up, %t. Actually, do not.",
            "Moonlight and shrapnel, %t.",
            "One after another, %t.",
            "There's a starman waiting in the sky, and he is dropping things on you.",
            "Shards from the sky. One after another after another.",
        },

        ["SPELL:Elune's Grace"] = {
            "I see a bad moon rising, %t. It is rising for you.",
            "Elune's Grace, %t. Under the moonlight, everything misses.",
            "Dodge this, %t. Or rather, watch me dodge that.",
            "The moon is on my side tonight, %t.",
            "Aim all you like, %t. The moon says no.",
            "The moon is watching, %t.",
            "Elune's Grace, %t. Try hitting me now.",
            "Missed, %t. And again.",
            "Blessed by the moon, %t.",
            "Not tonight, %t.",
            "Moonlight makes me hard to hit, %t.",
            "Swing away, %t.",
            "I see a bad moon rising. It is rising for you.",
            "Dodge this. Or rather, watch me dodge that.",
        },

        ["SPELL:Feedback"] = {
            "Feedback, %t. Turn it down or lose the mana.",
            "Bring the noise, %t. On second thought, don't.",
            "That's the sound of your spell failing, %t. Loudly.",
            "Too loud, %t. Every note is costing you.",
            "Cast at me and hear yourself, %t.",
            "Turn it down, %t.",
            "Feedback, %t. Cast at me and pay for it.",
            "That is the sound of failure, %t.",
            "Screech, %t.",
            "Every spell costs you double, %t.",
            "Noise, %t. Expensive noise.",
            "Play it again, %t. Go on.",
            "Feedback. Turn it down or lose the mana.",
            "That's the sound of your spell failing. Loudly.",
        },

        ["SPELL:Chastise"] = {
            "You've been a bad boy, %t. Go and stand over there.",
            "Stop, %t. In the name of the Light. Literally in its name.",
            "Chastise, %t. Consider this a time out with consequences.",
            "Sit down, %t. We will discuss this when I am finished.",
            "That is quite enough out of you, %t.",
            "Behave, %t.",
            "Chastise, %t. Stand there and reflect.",
            "Enough, %t.",
            "Naughty, %t.",
            "Sit still, %t.",
            "The Light is disappointed, %t.",
            "Time out, %t. A real one.",
            "You've been a bad boy. Go and stand over there.",
            "Chastise. Consider this a time out with consequences.",
        },

        ["SPELL:Symbol of Hope"] = {
            "Don't stop believin', %t. And here is some mana to believe with.",
            "Symbol of Hope, %t. Hope is all I've got and I am sharing it.",
            "Keep the faith, %t. Keep the mana too.",
            "Everybody gets a little something back, %t.",
            "Hold on to that feeling, %t. And that mana.",
            "Hold on to that feeling, %t.",
            "Symbol of Hope, %t. Mana for the faithful.",
            "Faith pays, %t.",
            "A little something back, %t.",
            "Hope in a bottle, %t.",
            "Keep going, %t. Here is the fuel.",
            "Never give up, %t.",
            "Don't stop believin'. And here is some mana to believe with.",
            "Hold on to that feeling. And that mana.",
        },

        ["SPELL:Consume Magic"] = {
            "Om nom, %t. That was your buff and now it is my mana.",
            "Eat it, %t. Just eat it. I did.",
            "Consume Magic, %t. Thank you. Next.",
            "That's mine now, %t. You were not using it properly.",
            "Whatever that was, %t, it tasted like mana.",
            "Yoink, %t.",
            "Consume Magic, %t. Your buff, my mana.",
            "Delicious, %t.",
            "That was tasty, %t.",
            "Gone, %t. And useful to me.",
            "Waste not, %t.",
            "Thanks for that, %t.",
            "Om nom. That was your buff and now it is my mana.",
            "Whatever that was, it tasted like mana.",
        },
    },
}
