-- RPVox -- mood pack: HAPPY (Priest)
--
-- Lines are stored plain; the addon prefixes each with [happy] when seeding.
-- Voice: the Forsaken priest in high spirits. Not sunny -- delighted. He is
-- enjoying himself, the joke is usually death, and he is in on it.

RPVox_MOOD_LINES = RPVox_MOOD_LINES or {}

RPVox_MOOD_LINES.HAPPY = {
    name  = "happy",
    class = "PRIEST",

    ["REACT:LOWHEALTH"] = {
        "%t. Oh, this is going well!",
        "Look at all that blood. Mine, apparently, %t.",
        "%t. Ha! Nearly had me.",
        "%t. This is the exciting part.",
        "%t. Don't stop now, we're just getting somewhere.",
        "%t. A flesh wound. Most of me is flesh wound.",
        "%t. Marvellous. Truly marvellous.",
        "You are doing wonderfully. Keep at it, %t.",
        "/em laughs, wetly",
        "%t. I haven't felt this alive in decades.",
        "%t. More! I want to see what breaks first.",
        "%t. Splendid work. Honestly.",
        "%t. Careful, I'm enjoying this.",
        "%t. The suspense is delicious.",
        "%t. One of us is having fun. It's me.",
        "%t. Nearly finished! How thrilling.",
        "%t. Oh, that's a big one.",
        "You've found something important. Good eye, %t.",
        "/em grins through the blood",
        "%t. Whoops.",
        "%t. This body was rubbish anyway.",
        "%t. Ooh. That's new.",
        "Do it again, I want to be sure, %t.",
        "%t. I feel positively fragile. How novel!",
        "%t. Bits falling off. Very entertaining.",
        "%t. Excellent. A challenge at last.",
        "%t. Now we're getting somewhere.",
        "You're closer than anyone's been in years, %t!",
        "Look at me go, %t.",
        "%t. Still upright, still delighted.",
        "%t. This is my favourite part.",
        "A little more and you'll have a story, %t.",
        "Oh, I like you, %t.",
        "/em cackles, entirely inappropriately",
        "%t. Nothing important. Probably a lung.",
        "%t. Terribly exciting.",
        "You'll be so pleased with yourself, %t.",
        "The whispers are cheering. For you, I think, %t.",
        "%t. Hah! Nearly.",
        "%t. That was a beauty.",
        "%t. Wonderful form on that swing.",
        "%t. I could do this all afternoon.",
        "%t. Falling apart is half the fun.",
        "Keep it up and I'll owe you a drink, %t.",
        "%t. Oh good, we're bleeding now.",
        "%t. That'll bruise. Somewhere.",
        "I'm having a lovely time, thank you, %t.",
        "Do carry on, %t!",
        "%t. Nearly out! How exciting for us both.",
        "%t. The Dark Lady loves a comeback.",
        "/em wipes blood away and smiles wider",
        "%t. Isn't this fun?",
        "%t. What a mess. What a wonderful mess.",
        "Bravo, %t. Really.",
        "You've earned that one, %t.",
        "%t. Ha! Good. Good!",
        "%t. So close. So very close.",
        "%t. I do love an underdog.",
        "%t. This is the best fight I've had all week.",
        "%t. Nearly folded there. Cheeky.",
        "%t. What a way to spend a morning.",
        "%t. I'm running low and having a splendid time.",
        "Do your worst. Please, %t.",
        "%t. That one went right through!",
        "%t. Oh, superb.",
        "Look at us. Both trying so hard, %t.",
        "You'd almost think I could die, %t.",
        "%t. Delightful.",
        "%t. That'll teach me. It won't.",
        "%t. Nothing beats a near thing.",
        "You're spoiling me, %t.",
        "%t. One more good one and I'm finished!",
        "%t. Absolutely wonderful.",
        "/em staggers, still laughing",
        "Careful, I'll start liking you, %t.",
        "%t. This is genuinely thrilling.",
        "%t. So THIS is what fear feels like. Interesting!",
        "Nearly there, %t!",
        "%t. Ha! Not yet.",
        "%t. I've never enjoyed losing more.",
        "You've torn something loose. Good for you, %t.",
        "%t. The best afternoon in years.",
        "%t. Well done! Truly.",
        "%t. Oh, we're both committed now.",
        "%t. That's the spirit!",
        "%t. Almost! Almost!",
        "%t. I would applaud but I need the hands.",
        "%t. Now it's a proper fight.",
        "You lovely, violent thing, %t.",
        "I'm smiling. Can you tell, %t?",
        "%t. Nearly through the last of me.",
        "%t. Isn't it glorious?",
        "Keep going, I want to see how this ends, %t!",
        "%t. Practically nothing left. How fun.",
        "%t. That was worth the trip.",
        "You've quite made my day, %t.",
        "One good push, %t!",
        "%t. Right to the edge. Wonderful.",
        "%t. I have never been happier to be nearly dead.",
        "%t. Ha! What a fight!",
    },

    ["REACT:DEATH"] = {
        "%t. Ha! Got me.",
        "%t. Oh, well played.",
        "%t. Worth it!",
        "%t. That was a good one!",
        "Ten out of ten, %t.",
        "/em falls over, delighted",
        "%t. Encore!",
        "See? Told you it wouldn't take, %t.",
        "%t. Splendid. Absolutely splendid.",
        "Off I go again, %t!",
        "Do it prettier next time, %t.",
        "%t. Bravo!",
        "%t. Right in front of everyone. Cheeky.",
        "%t. What a way to go. Again.",
        "I'll be back before you've cleaned the blade, %t.",
        "%t. Best death I've had this month.",
        "%t. Marvellous form!",
        "%t. Ha! Straight through.",
        "%t. That's the fun part done.",
        "%t. Oh no, whatever shall I do.",
        "%t. Curtains! For an hour or so.",
        "You've earned that, %t.",
        "%t. Well struck!",
        "%t. I did enjoy that.",
        "%t. Second time's a charm.",
        "%t. Not bad at all.",
        "/em goes limp mid-chuckle",
        "%t. That tickled.",
        "%t. Full marks.",
        "%t. Wonderful. Now the boring bit.",
        "%t. Ah, the old familiar dark. Hello again!",
        "You've done me a favour, really, %t.",
        "%t. Excellent work, truly.",
        "Down I go! Whee, %t.",
        "%t. Somebody write that one down.",
        "%t. Beautifully done.",
        "%t. That's going in the memoirs.",
        "%t. Hah! Straight off my feet.",
        "%t. Lovely. Do it again sometime.",
        "%t. I felt that one. Nearly.",
        "%t. So dramatic!",
        "%t. A proper ending, that.",
        "You're quite good at this, %t.",
        "Thank you. Genuinely, %t.",
        "%t. Fair. Entirely fair.",
        "%t. What a finish!",
        "%t. Better than the last one.",
        "%t. Oh, that was satisfying.",
        "%t. I have no complaints.",
        "Style points, %t.",
        "See you shortly, and cheerfully, %t.",
        "%t. Perfect. Simply perfect.",
        "%t. I love this part.",
        "You've a talent, %t.",
        "%t. That was almost artistic.",
        "Down, and grinning, %t.",
        "%t. Don't look so worried, I'm fine.",
        "%t. A good clean kill! Rare, that.",
        "%t. Delightful.",
        "%t. Ha! And again!",
        "%t. Right. Off to the graveyard.",
        "%t. That'll do nicely.",
        "The dark and I have an arrangement, %t.",
        "%t. Nicely handled.",
        "You should be very pleased, %t.",
        "%t. Oh, that was fun.",
        "%t. Ha! Timber.",
        "Give me a moment and we'll go again, %t.",
        "%t. I've had worse mornings. Many.",
        "%t. Superb.",
        "%t. That was the best bit of the day.",
        "%t. Cheerio!",
        "%t. Excellent aim.",
        "%t. Not a bad way to spend an afternoon.",
        "%t. The whole thing was a lark.",
        "%t. Very nicely done indeed.",
        "That's one for you, %t.",
        "Ha! You've killed a dead man. Congratulations, %t!",
        "%t. Wonderful. Let's do it again.",
        "%t. Top marks all round.",
        "/em dies laughing, literally",
        "%t. I regret nothing.",
        "%t. Better than lying about being tired.",
        "You caught me fair, %t.",
        "%t. Well! That happened.",
        "%t. A fine end to a fine scrap.",
        "Do enjoy it. It won't last, %t.",
        "%t. Ha! Beautiful.",
        "%t. That's my cue.",
        "No hard feelings, %t.",
        "%t. Charming.",
        "Down goes the priest. Hooray, %t.",
        "You've a good arm on you, %t.",
        "%t. Delighted, honestly.",
        "%t. The best kind of losing.",
        "%t. That'll be all from me. Briefly.",
        "%t. Ha! What a day.",
        "%t. Marvellous ending.",
        "%t. Right through the middle. Lovely.",
        "See you in a tick, %t.",
    },

    ["REACT:RESURRECT"] = {
        "Back! Miss me?",
        "Ha! Told you, %t.",
        "Right, where were we!",
        "/em bounces upright with unseemly energy",
        "Wonderful. All the pieces present.",
        "Good morning, world.",
        "That was a lovely nap.",
        "Refreshed! Sort of.",
        "Up and about again.",
        "Did anyone see where I put my dignity?",
        "Back in business!",
        "Splendid. Everything still attached.",
        "Ha! The old trick works.",
        "Better than ever. Well. Similar.",
        "Marvellous. Onward!",
        "Nothing like a short death to clear the head.",
        "Right! Who's next?",
        "Hello again, everyone.",
        "Cracking. Let's go.",
        "Up we get.",
        "Alive-ish and delighted.",
        "That was fun. Let's not repeat it. Let's repeat it.",
        "Ha! Still here.",
        "New day, same corpse.",
        "Feeling wonderful, thank you for asking.",
        "The dark sent me back with compliments.",
        "Ready and grinning.",
        "Whoever raised me: excellent choice.",
        "/em dusts himself off, humming",
        "Back on the job!",
        "Ha! Death, nil. Me, several.",
        "Very good. Where's the fight?",
        "That went better than expected.",
        "All limbs accounted for. Roughly.",
        "Never better!",
        "Right! Onwards and upwards.",
        "I do love a comeback.",
        "Ha! Surprise.",
        "What a lovely afternoon for it.",
        "Second wind, third life.",
        "Fit as a very old fiddle.",
        "Up, up! Things to do.",
        "That was restful, actually.",
        "Wonderful. Nothing hurts. Everything hurts. Wonderful.",
        "The whispers welcomed me back.",
        "Ha! Missed the whole boring bit.",
        "Back and in fine spirits.",
        "Excellent. Let's get on with it.",
        "Nothing beats getting up again.",
        "/em stretches with an alarming series of clicks",
        "Ready for another go!",
        "Ha! Good as new. Nearly.",
        "Charming little death, that.",
        "Where's %t? I owe them thanks.",
        "Right then! Business.",
        "Splendid morning to be upright.",
        "That's better.",
        "Back among the living. Loosely speaking.",
        "Ha! Reassembled.",
        "Delighted to be back.",
        "Feeling frisky.",
        "The grave gets bored of me quickly.",
        "Onwards! Cheerfully!",
        "Hello, legs. Good to see you.",
        "Ha! Nothing missing.",
        "What a marvellous inconvenience that was.",
        "Right as rain. Cold rain.",
        "Back for more!",
        "Excellent. I was getting bored down there.",
        "Wonderful. Absolutely wonderful.",
        "Ha! Alive again, more or less.",
        "That was a short holiday.",
        "Up and grinning.",
        "Splendid! Onward.",
        "Nothing like it.",
        "Ha! Again, again.",
        "Delightful. Let's continue.",
        "Fresh corpse, same cheer.",
        "Good as ever. Which is to say, dreadful.",
        "Ha! Back in the world.",
        "What a lovely trick this is.",
        "Ready! Willing! Slightly decomposed!",
        "Marvellous. I'd forgotten how this goes.",
        "Very good indeed.",
        "Back up. Cheerfully so.",
        "Ha! There we are.",
        "Everything works. Mostly.",
        "Excellent. Point me at something.",
        "Right! Where's the trouble?",
        "Splendid to be standing.",
        "Ha! Nothing keeps me down.",
        "Wonderful morning for a resurrection.",
        "Back, and in high spirits.",
        "That's the way!",
        "Ha! Let's have another go.",
        "Upright and thoroughly pleased.",
        "Very nice. Very nice indeed.",
        "Ha! Encore.",
        "Right! Onward, cheerfully.",
        "Ha! Back on my feet and thrilled about it.",
    },

    ["REACT:KILLINGBLOW"] = {
        "%t. There we go!",
        "%t. Lovely.",
        "%t. Well! That's that.",
        "Sleep well, %t.",
        "Ha! Down you go, %t.",
        "/em beams at the corpse",
        "%t. Beautifully done, if I say so.",
        "%t. That was satisfying.",
        "%t. Splendid.",
        "%t. Oh, that's the one.",
        "%t. Right through. Marvellous.",
        "Thank you, that was fun, %t.",
        "%t. Nicely finished!",
        "%t. Another happy ending.",
        "%t. Ha! Timber.",
        "You were lovely. Now be quiet, %t.",
        "%t. That'll do beautifully.",
        "%t. Charming.",
        "%t. One down and grinning.",
        "%t. Perfect.",
        "%t. Wonderful work all round.",
        "Ha! Got you, %t.",
        "Down and dusted, %t.",
        "%t. That was very nearly art.",
        "Well played, %t. Do rest.",
        "%t. Delightful.",
        "%t. Oh, well done me.",
        "%t. Neat as anything.",
        "%t. There. Isn't that better?",
        "%t. Ha! Lovely.",
        "/em hums a little tune over the body",
        "%t. Splendid finish.",
        "%t. Nothing personal, and thoroughly enjoyable.",
        "%t. That's one for the collection.",
        "%t. Beautiful.",
        "%t. Very good indeed.",
        "%t. Ha! Straight down.",
        "You made that fun. Thank you, %t.",
        "Off you pop, %t.",
        "%t. Marvellous.",
        "Cheerio, %t.",
        "%t. That was a joy.",
        "%t. Ha! Tidy.",
        "%t. One less. How pleasant.",
        "%t. Excellent.",
        "%t. There's a good corpse.",
        "%t. Nicely, nicely done.",
        "%t. What a lovely sound that was.",
        "%t. Ha! Finished.",
        "%t. Lovely stuff.",
        "%t. That went splendidly.",
        "Down, and I'm delighted, %t.",
        "%t. Very neat.",
        "%t. Ha! Perfect timing.",
        "%t. Sweet dreams.",
        "%t. Wonderful. Next!",
        "%t. That was quite good fun.",
        "%t. Ha! Down.",
        "You did try. That counts, %t.",
        "%t. Charming little scrap.",
        "%t. Excellent work, everyone.",
        "%t. That's the way.",
        "%t. Ha! Beautiful.",
        "Rest easy, you were fun, %t.",
        "%t. Marvellous ending.",
        "Down and cheerful, %t.",
        "%t. That's better.",
        "%t. Ha! Neatly done.",
        "%t. Splendid, splendid.",
        "%t. One more happy result.",
        "%t. Very satisfying, that.",
        "Ha! Off you go, %t.",
        "Lovely fight, %t. Truly.",
        "%t. There. All done.",
        "%t. Wonderful.",
        "%t. Ha! Lights out.",
        "%t. That was a treat.",
        "%t. Nicely finished, if I do say so.",
        "Down you go, and thank you, %t.",
        "%t. Ha! Excellent.",
        "%t. A pleasure, genuinely.",
        "%t. That'll do very nicely.",
        "%t. Splendid work.",
        "%t. Ha! And rest.",
        "%t. Marvellous fun.",
        "%t. One down, cheerfully.",
        "%t. Ha! There.",
        "%t. Very good. Very good indeed.",
        "%t. That was thoroughly enjoyable.",
        "Down! Lovely, %t.",
        "%t. Ha! Well struck, me.",
        "Off to the dark with you, %t.",
        "%t. Excellent result.",
        "%t. That's the spirit. Gone, but the spirit.",
        "%t. Ha! Delightful.",
        "%t. Beautifully concluded.",
        "%t. One more for the tally. Hooray.",
        "%t. Ha! Lovely work.",
        "Sleep, %t. You were splendid.",
        "%t. Ha! A tidy little ending.",
    },

    ["REACT:COMBATSTART"] = {
        "%t. Oh good, a fight!",
        "%t. Wonderful! Company.",
        "%t. Ha! At last.",
        "%t. Right! Let's have some fun.",
        "%t. How exciting.",
        "/em rubs his hands together",
        "%t. Splendid. I was getting bored.",
        "Come on then, cheerfully, %t.",
        "Delighted to make your acquaintance, %t.",
        "%t. This should be a treat.",
        "%t. Marvellous! Trouble.",
        "%t. Ha! Something to do.",
        "%t. Oh, yes. Let's.",
        "%t. What a lovely day for it.",
        "Come along, %t.",
        "%t. Excellent. En garde and all that.",
        "%t. Ha! Here we go.",
        "%t. I do enjoy this bit.",
        "%t. Wonderful. Let's make a mess.",
        "%t. Right! Chins up, everyone.",
        "%t. How thoroughly diverting.",
        "Ha! You'll do nicely, %t.",
        "%t. Splendid timing, I was restless.",
        "Come on. It'll be fun. For one of us, %t.",
        "%t. Oh, marvellous.",
        "%t. A fight! My favourite.",
        "%t. Ha! Lovely.",
        "Let's be quick and cheerful about it, %t.",
        "%t. Delightful. Proceed.",
        "%t. Ha! I was hoping for this.",
        "/em cracks his knuckles with relish",
        "Come here, you, %t.",
        "%t. Wonderful! An audience too.",
        "Right, %t, best behaviour.",
        "%t. Excellent. Let's see what happens.",
        "%t. Ha! Trouble at last.",
        "%t. This will be entertaining.",
        "%t. Splendid. Shall we?",
        "Oh, I like the look of you, %t.",
        "%t. Ha! Perfect.",
        "Come on then, make it interesting, %t.",
        "%t. Marvellous, a proper scrap.",
        "%t. How lovely. Violence.",
        "%t. Ha! Delighted.",
        "Do try, it's more fun that way, %t.",
        "%t. Excellent! Places, everyone.",
        "%t. Ha! Wonderful.",
        "%t. Right! Off we go.",
        "%t. This is going to be good.",
        "%t. Oh, splendid.",
        "%t. Ha! Company at last.",
        "Come on, cheer up, it's only a fight, %t.",
        "%t. Delightful. Let's begin.",
        "%t. Wonderful! I'll try to make it quick. No I won't.",
        "%t. Ha! Here we are then.",
        "%t. How thrilling.",
        "%t. Right, let's enjoy ourselves.",
        "%t. Marvellous. A challenge, perhaps?",
        "%t. Ha! Good.",
        "Come along, %t, don't be shy.",
        "%t. Splendid. This will be fun.",
        "%t. Oh, do let's.",
        "%t. Ha! At last, something interesting.",
        "%t. Excellent. I've been itching.",
        "%t. Wonderful, wonderful.",
        "%t. Ha! Come on then.",
        "%t. Lovely. A fight before lunch.",
        "%t. Right! Best foot forward.",
        "%t. Delighted, truly.",
        "%t. Ha! Let's have it.",
        "Marvellous. Do your worst, %t.",
        "Come on. I'll be gentle. I won't, %t.",
        "%t. Splendid! At last.",
        "%t. Ha! Yes.",
        "%t. Oh, this is a treat.",
        "Right, %t. Impress me.",
        "%t. Wonderful, a proper morning's work.",
        "%t. Ha! Excellent.",
        "Do come closer, %t.",
        "%t. How marvellous.",
        "%t. Ha! Something to do at last.",
        "%t. Right! Cheerfully, now.",
        "Splendid. Let's see you dance, %t.",
        "%t. Ha! Perfect timing.",
        "%t. Delightful, delightful.",
        "Come on then. I've been so bored, %t.",
        "%t. Excellent. Here we go.",
        "%t. Ha! Marvellous.",
        "Wonderful, %t. Shall we?",
        "%t. Right! Fun time.",
        "%t. Ha! Trouble, and I'm thrilled.",
        "%t. Oh, splendid stuff.",
        "Let's make an afternoon of it, %t.",
        "%t. Ha! Come along.",
        "%t. Delighted. Truly delighted.",
        "%t. Marvellous! Begin.",
        "%t. Ha! Wonderful.",
        "%t. This will be a lark.",
        "%t. Right! In we go.",
        "%t. Ha! Best news all morning.",
    },

    ["REACT:COMBATEND"] = {
        "Well! That was fun.",
        "Splendid work, everyone.",
        "Ha! Lovely.",
        "That'll do nicely.",
        "What a good time.",
        "/em dusts off his sleeves, thoroughly pleased",
        "Marvellous. Same again?",
        "Very enjoyable, thank you.",
        "Ha! Finished already?",
        "Right! What's next?",
        "That was a treat.",
        "Wonderful. Anyone hurt? Anyone alive?",
        "Ha! Good fun.",
        "Splendid little scrap.",
        "Delightful. Onward.",
        "I did enjoy that.",
        "Ha! All done.",
        "Beautifully handled.",
        "What a lovely mess.",
        "Excellent. Let's find another.",
        "Ha! Over already.",
        "That was quite the entertainment.",
        "Marvellous. Cheerio, corpses.",
        "Very good indeed.",
        "Ha! Well fought, all.",
        "Right, tidy up and off we go.",
        "That was thoroughly diverting.",
        "Splendid! Next.",
        "Ha! Good work.",
        "Lovely. Absolutely lovely.",
        "What a nice bit of violence.",
        "Ha! Done and dusted.",
        "Wonderful. I'm in a fine mood now.",
        "That perked me right up.",
        "Ha! Excellent.",
        "Right! Onwards, cheerfully.",
        "Delightful little fight.",
        "Splendid. Shall we find more?",
        "Ha! Over too soon.",
        "Very satisfying.",
        "That was worth getting up for.",
        "Ha! Marvellous.",
        "Wonderful fun.",
        "Right! Where to next?",
        "Ha! All quiet.",
        "Splendid stuff.",
        "That was a good one.",
        "Delighted with that.",
        "Ha! Nicely finished.",
        "Lovely work all round.",
        "What a cheerful little massacre.",
        "Ha! Done.",
        "Excellent. I feel much better.",
        "Marvellous. Off we go.",
        "That was fun. Let's do it again.",
        "Ha! Splendid.",
        "Very nice indeed.",
        "Right! Good result.",
        "Ha! Well handled.",
        "Delightful.",
        "That'll keep me smiling.",
        "Ha! Finished.",
        "Wonderful little fight, that.",
        "Splendid outcome.",
        "Ha! Neat and tidy.",
        "I'm in an excellent mood now.",
        "That was a nice bit of exercise.",
        "Ha! Very good.",
        "Marvellous. Onward!",
        "Right, who wants to go again?",
        "Ha! Lovely stuff.",
        "That did the trick.",
        "Excellent little scrap.",
        "Ha! All done and grinning.",
        "Splendid, splendid.",
        "What fun that was.",
        "Ha! Good.",
        "Delightful. Let's move on.",
        "Very enjoyable.",
        "Ha! Done nicely.",
        "That cheered me right up.",
        "Marvellous work.",
        "Ha! Over.",
        "Wonderful. Now, lunch. Metaphorically.",
        "Right! Cheerfully onward.",
        "Ha! Good fight.",
        "Splendid ending.",
        "That was a joy.",
        "Ha! Nicely done, all.",
        "Excellent result.",
        "Lovely. Let's find trouble.",
        "Ha! Fun while it lasted.",
        "Delighted, truly.",
        "Marvellous little bout.",
        "Ha! Tidy.",
        "That was very good fun.",
        "Right! Onward and upward.",
        "Ha! Splendid work.",
        "Wonderful. Onward, then.",
        "Ha! A thoroughly pleasant outcome.",
    },

    ["REACT:INTERRUPTED"] = {
        "%t. Ha! Cheeky.",
        "%t. Oh, well done!",
        "%t. Rude, but clever.",
        "Ha! You got me, %t.",
        "%t. Marvellous timing.",
        "/em laughs, genuinely impressed",
        "%t. Splendid. Do that again.",
        "%t. Ooh! Nice one.",
        "%t. Ha! Fair enough.",
        "You are good at this, %t.",
        "%t. Cheeky little thing.",
        "%t. Ha! Right in the middle.",
        "Bravo, %t.",
        "%t. Excellent reflexes.",
        "%t. Ha! I'll allow it.",
        "%t. Very nicely done.",
        "%t. Oh, that's annoying. Well done.",
        "%t. Ha! Clever.",
        "You've been practising, %t!",
        "%t. Splendid. Now let me finish.",
        "%t. Ha! Nearly had it.",
        "%t. Delightful. Try again.",
        "%t. Marvellous cheek.",
        "Ha! You little terror, %t.",
        "%t. Well played, truly.",
        "%t. That was worth watching.",
        "%t. Ha! Fine, fine.",
        "You do keep me entertained, %t.",
        "%t. Excellent work.",
        "%t. Ha! Right, no more Mr. Nice Corpse.",
        "%t. Very good! And futile.",
        "%t. Ha! Impressive.",
        "Do that once more, I dare you, %t.",
        "%t. Splendid effort.",
        "%t. Ha! Charming.",
        "%t. Nicely spotted.",
        "You're quick! Good for you, %t.",
        "Ha! I like you more each minute, %t.",
        "%t. Marvellous. Again?",
        "%t. That was fun, actually.",
        "%t. Ha! Well timed.",
        "%t. Delightfully rude.",
        "You've got a knack, %t.",
        "%t. Ha! Caught me talking.",
        "%t. Splendid. I'll simply start over.",
        "%t. Very sporting.",
        "%t. Ha! Nice try, and a good one.",
        "%t. Excellent! Now watch this.",
        "You have my full attention. Congratulations, %t!",
        "%t. Ha! Cheek.",
        "%t. Beautifully judged.",
        "%t. Marvellous, marvellous.",
        "Ha! You're enjoying this too, %t.",
        "%t. Splendid interruption.",
        "%t. Very good! Now stop it.",
        "%t. Ha! Alright, alright.",
        "%t. That was neat.",
        "%t. Delightful. Do keep trying.",
        "%t. Ha! Well then.",
        "You cheeky thing, %t.",
        "%t. Excellent timing, truly.",
        "%t. Ha! Spoiled it.",
        "%t. Splendid! And useless.",
        "%t. That's the spirit.",
        "%t. Ha! Fine. The short version, then.",
        "%t. Nicely interrupted.",
        "%t. Marvellous manners.",
        "%t. Ha! Good one.",
        "You're a delight, %t.",
        "%t. Very well done.",
        "%t. Ha! I'll remember that fondly.",
        "Splendid cheek, %t.",
        "%t. Excellent. Encore?",
        "%t. Ha! Right in the middle again.",
        "%t. Lovely reflexes.",
        "%t. That was quite good.",
        "Ha! You win that one, %t.",
        "%t. Delightful nuisance.",
        "%t. Marvellous. And again, please.",
        "%t. Ha! Fair play.",
        "You do make this fun, %t.",
        "%t. Splendid attempt.",
        "%t. Ha! Nearly finished it.",
        "Very sharp of you, %t.",
        "%t. Excellent! Truly.",
        "%t. Ha! Well caught.",
        "%t. Charmingly rude.",
        "%t. That deserves a nod.",
        "%t. Ha! Alright then.",
        "Splendid work, %t.",
        "%t. Marvellously irritating.",
        "Ha! Point to you, %t.",
        "%t. Very nice. Now watch.",
        "%t. Delighted, oddly.",
        "%t. Ha! Naughty.",
        "%t. Excellent little trick.",
        "%t. That was worth it.",
        "%t. Ha! Try it again.",
        "%t. Splendid. Where was I?",
        "Ha! You are a menace and I adore it, %t.",
    },
}
