-- RPVox -- mood pack: GRIM (Mage), second batch
--
-- Appends to the sets defined in RPVoxMoods_MageGrim.lua rather than
-- replacing them, so the two files together give each spell a deep pool.

RPVox_MOOD_LINES = RPVox_MOOD_LINES or {}
RPVox_MOOD_LINES.MAGE_GRIM = RPVox_MOOD_LINES.MAGE_GRIM
    or { name = "grim", class = "MAGE" }

local EXTRA = {

    ["SPELL:Frostbolt"] = {
        "%t. Another degree gone.",
        "You are cooling from the inside, %t.",
        "There is no warmth coming to help you, %t.",
        "%t. Slow. Slower. Stopped.",
        "%t. The cold takes the fingers first. Then the argument.",
        "Nothing you wear will hold this out, %t.",
        "%t. I could do this from further away. I choose not to.",
        "%t. Winter, delivered by hand.",
        "You are becoming brittle, %t.",
        "%t. The frost is thorough. I am thorough.",
        "%t. That will not thaw.",
        "There is no heat left in you worth counting, %t.",
        "Feel your reaction time leaving, %t.",
        "%t. This is what patience does to a body.",
        "%t. Cold is the oldest weapon and the most honest.",
        "You will stop before I do, %t.",
        "%t. The ice reaches deeper each time.",
        "%t. Nothing about this requires urgency.",
        "You are already slowing. Notice it, %t.",
    },
    ["SPELL:Fireball"] = {
        "Burn quietly, %t.",
        "%t. There is nothing left after fire. That is the appeal.",
        "You are a very brief candle, %t.",
        "%t. Heat does not negotiate with flesh.",
        "%t. That will not stop burning on my account.",
        "%t. Combustion is the simplest ending.",
        "%t. Nothing survives sufficient temperature.",
        "You will come apart at the seams, %t.",
        "%t. Fire is indifferent. I directed it.",
        "%t. There is no armour against physics.",
        "Watch what you become, %t.",
        "%t. The flame does the work. I do the aiming.",
        "You are fuel arranged in a shape, %t.",
        "%t. That will leave nothing to bury.",
        "%t. Reduced, precisely as intended.",
        "%t. Nothing about that was excessive.",
        "%t. The heat gets to the marrow eventually.",
        "You will be ash before you finish the thought, %t.",
        "Burn. It is the fastest arithmetic I know, %t.",
    },
    ["SPELL:Arcane Missiles"] = {
        "%t. Sequence complete.",
        "%t. Nothing intervenes in a proof.",
        "You cannot argue with delivery, %t.",
        "%t. Each one was decided before I began.",
        "%t. The arcane is not a weapon. It is a certainty.",
        "%t. There is no shelter from mathematics.",
        "You are being resolved, %t.",
        "%t. That is what precision sounds like.",
        "%t. Nothing wasted. Nothing missed.",
        "The pattern completes whether you move or not, %t.",
        "You have no counter to inevitability, %t.",
        "%t. One after another, exactly as written.",
        "%t. This is the purest form of what I do.",
        "%t. There is no luck in this discipline.",
        "The equation closes around you, %t.",
        "%t. Nothing about that was chance.",
        "You cannot outrun something that does not travel, %t.",
        "%t. Delivered. In full. As always.",
        "%t. The arcane finishes what it starts.",
    },
    ["SPELL:Fire Blast"] = {
        "%t. Instantly, and without comment.",
        "%t. That required nothing of me.",
        "You had no time. That was deliberate, %t.",
        "%t. A reflex, not a decision.",
        "%t. Cheap. Effective. Repeatable.",
        "%t. There is more of that available.",
        "%t. Nothing about it was elaborate.",
        "You do not merit a full working, %t.",
        "%t. Immediate consequence, correctly applied.",
        "%t. That is what I do while thinking of something else.",
        "%t. No incantation. No warning. No appeal.",
        "%t. The fire answers instantly. Consider why.",
        "You flinched. Note that I did not, %t.",
        "That is the smallest thing I can do to you, %t.",
        "%t. Punctuation, nothing more.",
        "%t. Quick, and entirely intentional.",
        "%t. There is no defence against instant.",
        "%t. That cost me almost nothing.",
        "Take it and reconsider your position, %t.",
    },
    ["SPELL:Pyroblast"] = {
        "%t. That took six seconds and ends everything.",
        "I wanted you to see it coming, %t.",
        "%t. Preparation always wins.",
        "%t. There is nothing after that.",
        "You watched me build your ending, %t.",
        "%t. The long working is never a bluff.",
        "%t. That is what deliberation produces.",
        "%t. Nothing survives a considered decision.",
        "You had time to run. You spent it badly, %t.",
        "%t. A conclusion delivered from a great height.",
        "That is the ceiling of what I will show you, %t.",
        "%t. Everything before this was courtesy.",
        "%t. The sky is a tool like any other.",
        "You are now a crater and a lesson, %t.",
        "%t. I do not hurry the important things.",
        "%t. That was calculated to the last digit.",
        "%t. Nothing about it was theatrical. It was necessary.",
        "%t. The demonstration concludes.",
        "You will not require a second one, %t.",
    },
    ["SPELL:Blizzard"] = {
        "%t. The whole area. All at once.",
        "%t. Nowhere in that circle is survivable.",
        "You brought numbers. I brought weather, %t.",
        "%t. The cold does not count heads.",
        "Stay grouped. Please, %t.",
        "%t. That ground is mine for the duration.",
        "%t. Nothing walks out of that intact.",
        "%t. Everyone receives their portion.",
        "Freeze in any order you like, %t.",
        "%t. A localised extinction event.",
        "%t. There is no formation that survives this.",
        "%t. The storm is indiscriminate. I am not.",
        "You are all inside the same conclusion, %t.",
        "%t. Scatter. It is the only correct answer.",
        "%t. That is what area denial means.",
        "%t. Nothing living should remain in there.",
        "%t. The cold falls until I stop it.",
        "You cannot outlast falling ice, %t.",
        "%t. Uninhabitable. As designed.",
    },
    ["SPELL:Frost Nova"] = {
        "%t. Held.",
        "You will remain exactly there, %t.",
        "That is the end of your approach, %t.",
        "%t. Now the distance is mine again.",
        "Struggle if you like. The ice does not care, %t.",
        "You are pinned inside my calculations, %t.",
        "%t. Nothing advances from that position.",
        "%t. I decide where this fight happens.",
        "You came too close. That is corrected, %t.",
        "%t. Frozen, and entirely aware of it.",
        "%t. That is the trap, closed.",
        "Watch me walk away from you, %t.",
        "%t. The ice holds long enough. It always does.",
        "You will spend this fight standing still, %t.",
        "%t. There is nothing to do but wait for it.",
        "That is what proximity earns you, %t.",
        "%t. Rooted, and running out of time.",
        "The ground has you now, %t.",
        "Stay. It is easier for both of us, %t.",
    },
    ["SPELL:Blink"] = {
        "%t. Out of reach. Permanently.",
        "You are chasing a conclusion, not a man, %t.",
        "%t. Distance is a resource. I control it.",
        "%t. Reach for me again. See how it goes.",
        "Nothing keeps me where you want me, %t.",
        "%t. The geometry has always favoured me.",
        "You will arrive late for the rest of this fight, %t.",
        "%t. I am never where the swing lands.",
        "%t. Space is negotiable. My position is not.",
        "That was your one opening, %t.",
        "%t. Repositioned. Continue failing.",
        "You cannot close on the arcane, %t.",
        "%t. There. Further, and better placed.",
        "%t. The distance resets whenever I choose.",
        "Nothing about your approach was sound, %t.",
        "You are too slow for this discipline, %t.",
        "Gone before the decision reached you, %t.",
        "%t. That is how one refuses to be touched.",
        "Try again from over there, %t.",
    },
    ["SPELL:Polymorph"] = {
        "%t. Set aside.",
        "You are stored for later, %t.",
        "Nothing you were is required at the moment, %t.",
        "%t. Be quiet. Be simple.",
        "%t. That is a considerable improvement.",
        "%t. I have removed the parts that argued.",
        "Wait your turn, %t.",
        "You are a complication, temporarily solved, %t.",
        "%t. There. Manageable.",
        "Consider the ease with which I did that, %t.",
        "You will be restored when it suits me, %t.",
        "%t. One variable, shelved.",
        "Nothing about you was worth preserving, %t.",
        "%t. Chew. Reflect.",
        "%t. That is what happens to the inconvenient.",
        "%t. Simplified to the essentials.",
        "You have been filed, %t.",
        "Struggle. It only prolongs the wool, %t.",
        "I will return to you shortly. Or not, %t.",
    },
    ["SPELL:Counterspell"] = {
        "%t. Denied.",
        "You do not get to finish that, %t.",
        "Nothing you begin will conclude, %t.",
        "%t. That was derivative anyway.",
        "%t. Silence. It is an improvement.",
        "Your casting ends where I decide, %t.",
        "%t. I know that spell better than its author.",
        "%t. Not while I am here.",
        "You are disarmed in the only way that matters, %t.",
        "There is nothing left of your working, %t.",
        "%t. That is what expertise looks like.",
        "Try something within your competence, %t.",
        "%t. The arcane obeys the better practitioner.",
        "Cancelled. Permanently, if you prefer, %t.",
        "You will not speak magic again this fight, %t.",
        "%t. That was sloppy. Now it is gone.",
        "Nothing about your technique surprised me, %t.",
        "%t. Interrupted. Comprehensively.",
        "Do not attempt that again, %t.",
    },
    ["SPELL:Ice Block"] = {
        "%t. Unavailable.",
        "%t. Nothing reaches me. Nothing ever has.",
        "Spend everything you have. I will wait, %t.",
        "That was your window. Watch it close, %t.",
        "%t. This is scheduling, not fear.",
        "You have accomplished precisely nothing, %t.",
        "I will be out in a moment. You will still be there, %t.",
        "%t. The ice is absolute.",
        "%t. Continue. It is entertaining from in here.",
        "%t. That burst was wasted entirely.",
        "Nothing you do in the next six seconds matters, %t.",
        "%t. A pause, entirely on my terms.",
        "You cannot hurt what is not present, %t.",
        "%t. Perfect clarity, and perfectly safe.",
        "Come closer. It will not help, %t.",
        "%t. That is the sound of futility.",
        "%t. I am simply elsewhere for a moment.",
        "%t. The working holds. It always holds.",
        "%t. Now. Where were we.",
    },
    ["SPELL:Evocation"] = {
        "Do not interrupt, %t.",
        "%t. This is the pause before the ending.",
        "I am gathering what finishes you, %t.",
        "You have seconds. Spend them running, %t.",
        "The reservoir refills. Yours cannot, %t.",
        "Nothing you do stops this, %t.",
        "%t. That noise is my advantage returning.",
        "You cannot outlast an infinite source, %t.",
        "Wait. It will be worth watching, %t.",
        "Every second here is one you lose later, %t.",
        "%t. The arcane always comes back to me.",
        "This is the quiet you should fear, %t.",
        "%t. Restoring. Then concluding.",
        "You should be leaving, %t.",
        "%t. Nearly full. Prepare yourself.",
        "There is no version where you outlast this, %t.",
        "%t. I am never truly empty.",
        "Consider what happens when I finish, %t.",
        "%t. Nearly ready. Nearly finished.",
    },
    ["SPELL:Arcane Intellect"] = {
        "Think faster. It will not be enough, %t.",
        "You are marginally less useless now, %t.",
        "%t. Use it well. I will not repeat the favour.",
        "%t. A better mind, on loan and at interest.",
        "That is more cleverness than you arrived with, %t.",
        "%t. I improve my instruments. Nothing more.",
        "Do something worthy of the enhancement, %t.",
        "%t. The mind is the only part worth reinforcing.",
        "%t. There. Adequate. Barely.",
        "You will need every bit of that, %t.",
        "Consider it an investment in my own convenience, %t.",
        "%t. Sharper. Now keep up.",
        "%t. That should reduce the errors.",
        "%t. Nothing about this is generosity.",
        "You are more useful to me clever, %t.",
    },
    ["SPELL:Conjure Water"] = {
        "%t. From nothing. Consider that.",
        "I create matter. You consume it, %t.",
        "%t. That is the difference between us, illustrated.",
        "Take it. It costs me nothing at all, %t.",
        "Reality is more negotiable than you think, %t.",
        "%t. Nothing here existed a moment ago.",
        "Do not mistake capability for generosity, %t.",
        "%t. The arcane provides because I command it.",
        "%t. Water. Trivial. Like most requests.",
        "You drink what I decide to make, %t.",
        "Consider what else can be conjured, %t.",
    },
    ["SPELL:Conjure Food"] = {
        "%t. Matter, on demand.",
        "You eat because I permit it, %t.",
        "Nothing here is real. It will still sustain you, %t.",
        "%t. This is the least of what I can do.",
        "Take it and say nothing, %t.",
        "%t. I make food from air. Reflect on that.",
        "The arcane feeds you. Not kindness, %t.",
        "%t. Fuel. Nothing more.",
        "Do not thank me. Simply eat, %t.",
        "Consider the implications and be quiet, %t.",
        "It is enough to keep you working, %t.",
    },
    ["SPELL:Shoot"] = {
        "%t. Even empty, I am the greater threat.",
        "%t. Small wounds, accumulated properly.",
        "I do not require power to finish you, %t.",
        "You will die by increments, %t.",
        "%t. Patience is the weapon. This is only the delivery.",
        "%t. Every splinter is accounted for.",
        "%t. Nothing about me is ever truly unarmed.",
        "%t. The wand does not tire. Neither does the intent.",
        "Count them. It changes nothing, %t.",
        "%t. Slow is not the same as harmless.",
        "You are bleeding out on a schedule, %t.",
        "%t. This will be sufficient. It always is.",
        "Hold still. It only takes a hundred, %t.",
        "%t. The arithmetic still favours me.",
        "You cannot wait me out, %t.",
        "%t. Crude tools obey me as readily as fine ones.",
        "%t. One splinter at a time, then.",
        "It will finish you eventually. That is enough, %t.",
        "Even this is more than you deserve, %t.",
    },

    -- Quests --------------------------------------------------------------

    ["IDLE:QUESTACCEPT"] = {
        "I will do it because it is efficient, not because you asked, %t.",
        "Consider it arranged.",
        "You want results. You have come to the correct practitioner.",
        "Very well. It will be done properly.",
        "I do not fail contracts.",
        "Speak the terms and stop wasting my time.",
        "It is already solved. I merely have to go there.",
        "Nothing about this will require a second attempt.",
        "Fine. Where, and what is in the way?",
        "I will handle it. Do not follow.",
        "That is beneath me. I will still do it correctly.",
        "Understood. Expect no report.",
        "You have hired something considerably above your means.",
        "It is done. Formalities remain.",
    },
    ["IDLE:QUEST"] = {
        "Finished. Precisely as specified.",
        "Pay me and do not ask how.",
        "It was never in doubt.",
        "That is concluded. Permanently.",
        "You wanted it done. It is done, %t.",
        "There were complications. They were removed.",
        "Nothing survived that needed to.",
        "Consider the matter closed.",
        "I do not leave loose ends.",
        "The task is complete. The details are mine.",
        "Efficient. As always.",
        "You will not need to ask again.",
        "That is what competence looks like.",
        "Take it. We are finished here.",
    },
}

for key, list in pairs(EXTRA) do
    local set = RPVox_MOOD_LINES.MAGE_GRIM[key]
    if type(set) == "table" then
        for _, line in ipairs(list) do table.insert(set, line) end
    else
        RPVox_MOOD_LINES.MAGE_GRIM[key] = list
    end
end
