-- RPVox -- mood lines for the Priest's support spells.
-- Loaded after the mood packs; these attach extra trigger sets to them.

RPVox_MOOD_LINES = RPVox_MOOD_LINES or {}
for _, m in ipairs({ "HAPPY", "SERIOUS", "WEARY", "GRIM" }) do
    RPVox_MOOD_LINES[m] = RPVox_MOOD_LINES[m] or { name = m:lower(), class = "PRIEST" }
end

local H = RPVox_MOOD_LINES.HAPPY
local S = RPVox_MOOD_LINES.SERIOUS
local W = RPVox_MOOD_LINES.WEARY
local G = RPVox_MOOD_LINES.GRIM

-- Power Word: Shield ------------------------------------------------------

H["SPELL:Power Word: Shield"] = {
    "There you are! Nice and safe, %t.",
    "%t. Ha! Try getting through that.",
    "%t. Wrapped up like a present.",
    "%t. Splendid. Now go be reckless.",
    "/em pats the shield into place with satisfaction",
    "Ha! Bounce off, would you, %t.",
    "%t. Lovely bit of work, that.",
    "%t. There! Practically invincible.",
    "Marvellous. Off you go, %t.",
    "%t. Ha! Nothing gets through me.",
    "Do enjoy the invulnerability, %t.",
    "%t. Splendid! Very shiny.",
    "%t. Ha! Safe as houses.",
    "%t. That'll hold. Probably!",
    "%t. Wonderful. Now misbehave.",
    "Ha! A bubble for you, %t.",
    "%t. Delightful. Very sturdy.",
    "%t. There. Don't waste it!",
    "%t. Ha! Shielded and lovely.",
    "%t. Splendid work if I say so.",
    "Go on! Be brave now, %t.",
    "%t. Ha! That should do it.",
    "%t. Marvellous. Have fun.",
    "%t. There we are. All wrapped up.",
    "Ha! Nothing touches you, %t.",
}
S["SPELL:Power Word: Shield"] = {
    "%t. Shielded. Hold position.",
    "%t. That will absorb the next blow.",
    "Applied, %t.",
    "%t. Use it. It does not last.",
    "/em sets the ward with practised economy",
    "Protection is on you. Advance, %t.",
    "%t. Correctly placed.",
    "%t. That should hold the opening strike.",
    "%t. Warded. Continue.",
    "Do not waste the absorption, %t.",
    "%t. The shield holds. Move up.",
    "%t. Standard protection. Applied.",
    "That is your margin. Use it well, %t.",
    "%t. Shielded and ready.",
    "%t. Efficient. Next.",
    "Take the front. You are covered, %t.",
    "%t. Applied correctly.",
    "%t. It will hold long enough.",
    "%t. That is one less casualty.",
    "%t. Warded. Proceed.",
    "%t. Protection confirmed.",
    "Hold the line. You are shielded, %t.",
    "%t. That is the correct use of the spell.",
    "Applied. Watch your positioning, %t.",
    "%t. Covered. Advance.",
}
W["SPELL:Power Word: Shield"] = {
    "%t. There. A little protection.",
    "%t. It will hold. Briefly. As always.",
    "%t. Fine. Take the ward.",
    "%t. One more shield in a long line of them.",
    "/em sets the ward without looking up",
    "%t. There. Now try not to die.",
    "%t. It never holds long enough.",
    "%t. Fine. Warded.",
    "%t. I have cast this ten thousand times.",
    "%t. There. Whatever good it does.",
    "%t. It will break. They always break.",
    "%t. One more thing to maintain.",
    "%t. Fine. Covered.",
    "Take it. Do not thank me, %t.",
    "%t. It buys a moment. Nothing more.",
    "%t. There. Applied.",
    "%t. Another ward. Another minute.",
    "%t. It works. It always works.",
    "Fine. Off you go, %t.",
    "%t. One more small mercy.",
    "%t. It will not last. Nothing does.",
    "%t. There. Shielded, for now.",
    "%t. The usual protection.",
    "%t. Fine. Move along.",
    "%t. It holds until it doesn't.",
}
G["SPELL:Power Word: Shield"] = {
    "Nothing reaches you while I am watching, %t.",
    "Stand behind the word, %t.",
    "I could not shield myself. I can shield you, %t.",
    "Let it break on you and not through you, %t.",
    "/em sets the ward with cold deliberation",
    "You are difficult to kill now. Be worth it, %t.",
    "%t. That will hold. It always holds.",
    "%t. The Light still answers me. It should not.",
    "%t. Nothing gets past that.",
    "You will feel the blow. Not the ending, %t.",
    "%t. Wear this. It fits better than it did on me.",
    "%t. Faith hardened into a wall.",
    "%t. I keep what is mine alive.",
    "%t. The dark protects what it uses.",
    "Nothing touches you while I stand here, %t.",
    "Do something worthy of it, %t.",
    "That is a wall between you and the ground, %t.",
    "Take it. Do not waste my work, %t.",
    "%t. Guarded. Now stop bleeding on my working.",
    "%t. The word is spoken. It holds.",
    "You are under my protection. Understand what that means, %t.",
    "Nothing kills you but me. Not today, %t.",
    "%t. That will outlast their strength.",
    "%t. Shielded. Now be useful.",
    "%t. The ward holds because I say so.",
}

-- Renew -------------------------------------------------------------------

H["SPELL:Renew"] = {
    "%t. There! Grow back.",
    "%t. Ha! Knitting away nicely.",
    "%t. Lovely. All better shortly.",
    "Splendid. Off you pop, %t.",
    "/em waves a hand and something starts mending",
    "Ha! Look at you healing, %t.",
    "%t. Marvellous. Very tidy.",
    "%t. There! Patched and cheerful.",
    "%t. Ha! Isn't the body clever.",
    "Do enjoy the mending, %t.",
    "%t. Wonderful. It will keep working.",
    "%t. Ha! Better already.",
    "%t. Splendid! Growing back.",
    "%t. That's the stuff.",
    "%t. Ha! Marvellous work.",
    "%t. There. Good as new. Nearly.",
    "%t. Delightful. Very green.",
    "%t. Ha! Stitching itself up.",
    "%t. Wonderful. Carry on!",
    "%t. There! No trouble at all.",
    "%t. Ha! Lovely.",
    "%t. Splendid healing, that.",
    "Off you go, mending merrily, %t.",
    "%t. Ha! Excellent.",
    "%t. There. Isn't that better!",
}
S["SPELL:Renew"] = {
    "%t. Healing applied. Hold position.",
    "%t. That will mend over time.",
    "%t. Steady recovery. Continue.",
    "Applied, %t.",
    "/em applies the healing with clinical care",
    "It will work while you fight, %t.",
    "%t. Efficient healing. Nothing wasted.",
    "That should stabilise you, %t.",
    "%t. Recovery in progress.",
    "Hold the line. You will mend, %t.",
    "%t. Applied correctly.",
    "%t. That is sustained healing. Use the time.",
    "%t. Stabilising.",
    "%t. Continue. It is working.",
    "%t. Standard practice. Applied.",
    "You will recover. Stay in position, %t.",
    "%t. Healing over time. Confirmed.",
    "%t. That is the correct call.",
    "%t. Mending. Continue the advance.",
    "%t. Applied. Next.",
    "Steady. It will hold you, %t.",
    "%t. Recovery underway.",
    "%t. That should be sufficient.",
    "%t. Treated. Return to the line.",
    "%t. Healing confirmed. Proceed.",
}
W["SPELL:Renew"] = {
    "%t. There. It will mend eventually.",
    "%t. Slowly. Everything heals slowly.",
    "%t. Fine. Grow back.",
    "%t. One more patch on one more body.",
    "/em applies the healing without much attention",
    "%t. It works. Give it time.",
    "%t. There. Nothing quick about it.",
    "%t. Fine. Mend.",
    "%t. I have healed thousands. They all bleed again.",
    "%t. There. That will do something.",
    "%t. It takes its time. So does everything.",
    "%t. Fine. Applied.",
    "%t. Another patch job.",
    "%t. It will close. Badly, but it will close.",
    "%t. There. Wait for it.",
    "%t. One more mending in a long line.",
    "%t. Fine. Carry on.",
    "%t. It works whether I care or not.",
    "%t. There. Slowly, now.",
    "%t. Nothing dramatic. Just healing.",
    "%t. Fine. Give it a moment.",
    "%t. The usual. Applied.",
    "%t. It mends. They always mend. Then they break.",
    "%t. There. Done.",
    "%t. Slowly. As always.",
}
G["SPELL:Renew"] = {
    "Your body remembers how to be whole. Mine does not, %t.",
    "Grow back. I envy you the ability, %t.",
    "%t. The Light works slowly through cold hands.",
    "%t. Mending. Not undoing. Nothing undoes.",
    "/em forces the healing through with visible effort",
    "Stay standing. That is all I ask, %t.",
    "Rot postponed. Nothing more, %t.",
    "I keep you whole because I cannot be, %t.",
    "That will hold you together. For now, %t.",
    "Take it. It is the closest I come to kindness, %t.",
    "%t. Living flesh knits. Remember that I noticed.",
    "You heal. I only accumulate, %t.",
    "%t. The Shadow permits this much.",
    "%t. Warmth, seeping in. I remember warmth.",
    "It mends because I require you standing, %t.",
    "Do not waste what I put into you, %t.",
    "%t. That is life, loaned at interest.",
    "You will be whole. I will not, %t.",
    "%t. Healing is a thing I do for others now.",
    "%t. The wound closes. The memory does not.",
    "Stay alive. It is inconvenient otherwise, %t.",
    "%t. I give what was never given to me.",
    "Mend, and be grateful you can, %t.",
    "%t. That is borrowed time, correctly applied.",
    "Nothing about this is for you. It is for the fight, %t.",
}

-- Lesser Heal -------------------------------------------------------------

H["SPELL:Lesser Heal"] = {
    "%t. There! Right as rain.",
    "%t. Ha! All patched up.",
    "%t. Splendid. Try to keep it.",
    "Lovely. Off you go, %t.",
    "/em closes the wound with a cheerful flourish",
    "%t. Ha! Good as new.",
    "%t. There! Barely a scratch now.",
    "%t. Marvellous. Do be careful.",
    "%t. Ha! Sorted.",
    "%t. Splendid work, if I say so.",
    "There you are, %t!",
    "%t. Ha! Nothing to it.",
    "Wonderful. Back you go, %t.",
    "%t. That's better!",
    "%t. Ha! Tidy little mend.",
    "%t. Delightful. All fixed.",
    "%t. There! Presentable again.",
    "%t. Ha! Lovely.",
    "Splendid. Off with you, %t.",
    "Do try not to need another, %t!",
    "Ha! Sorted you out, %t.",
    "%t. Marvellous. Carry on.",
    "%t. There. Much better.",
    "%t. Ha! Easy.",
    "%t. Splendid! Next patient.",
}
S["SPELL:Lesser Heal"] = {
    "%t. Treated. Return to position.",
    "%t. Wound closed.",
    "That should stabilise you, %t.",
    "%t. Applied. Continue.",
    "/em closes the wound efficiently and moves on",
    "Enough to keep you upright, %t.",
    "%t. Healing confirmed.",
    "%t. That is all I can spare. Use it.",
    "%t. Stabilised. Move.",
    "%t. Correctly applied.",
    "You are functional. Continue, %t.",
    "Treated, %t.",
    "Do not take another like that, %t.",
    "%t. Efficient. Next.",
    "%t. Wound managed.",
    "%t. Return to the line.",
    "%t. That will hold.",
    "%t. Applied. Watch yourself.",
    "%t. Sufficient for now.",
    "%t. Treated and ready.",
    "%t. That is triage, not comfort.",
    "%t. Recovered enough. Proceed.",
    "%t. Closed. Move up.",
    "%t. Nothing wasted.",
    "%t. Handled. Continue.",
}
W["SPELL:Lesser Heal"] = {
    "%t. There. Closed.",
    "%t. Fine. Patched again.",
    "%t. One more wound in a long day of them.",
    "%t. It will hold. Probably.",
    "/em closes the wound without ceremony",
    "%t. There. Try to keep it shut.",
    "%t. Fine. Better than before.",
    "%t. Another patch. Another minute.",
    "%t. There. Nothing special.",
    "%t. It works. It always works.",
    "%t. Fine. Move along.",
    "%t. I have closed thousands of these.",
    "%t. There. Done.",
    "%t. It hardly takes thought now.",
    "%t. Fine. Stitched.",
    "%t. One more mend.",
    "There. Off you go, %t.",
    "%t. It is enough. Barely.",
    "%t. Fine. Next.",
    "%t. Nothing to it any more.",
    "%t. There. That will do.",
    "%t. Another small repair.",
    "%t. Fine. Whole again. Roughly.",
    "%t. It holds until it doesn't.",
    "%t. There. Continue.",
}
G["SPELL:Lesser Heal"] = {
    "Stop bleeding. That is an order, %t.",
    "Flesh obeys me better than it obeys you, %t.",
    "%t. A small mercy. They are the only ones I have.",
    "%t. Held together by will and a little Light.",
    "/em forces the wound shut with cold hands",
    "%t. Not whole. Whole is beyond either of us.",
    "%t. I am better at ending than mending. Be grateful.",
    "Take it before I reconsider, %t.",
    "%t. The wound closes. The memory does not.",
    "Do not waste this on dying twice, %t.",
    "Enough to keep you upright. No more, %t.",
    "%t. Skin over the gap. That is all healing is.",
    "You get the Light. I got the grave, %t.",
    "%t. Better. Now stay out of the way.",
    "I keep you alive because I need you alive, %t.",
    "%t. That is the last of my patience and my power.",
    "Stand. You are repaired, %t.",
    "%t. Nothing about this is tenderness.",
    "%t. The Shadow allows me this much.",
    "%t. Closed. Do not open it again.",
    "You live because it is useful to me, %t.",
    "That will hold if you are careful. Be careful, %t.",
    "%t. I have closed worse on myself.",
    "%t. Mended. Now earn it.",
    "%t. The flesh answers. It always answers.",
}

-- Fade --------------------------------------------------------------------

H["SPELL:Fade"] = {
    "%t. Ha! Where did I go?",
    "%t. Nothing here! Move along.",
    "%t. Splendid. Invisible-ish.",
    "%t. Ha! Look elsewhere, everyone.",
    "/em steps back and becomes remarkably uninteresting",
    "%t. Wonderful. Nobody sees the corpse.",
    "%t. Ha! Gone.",
    "Do carry on without me, %t!",
    "%t. Splendid trick, this.",
    "%t. Ha! Not me. Never me.",
    "%t. Marvellous. Off their list.",
    "%t. Ha! Was I ever here?",
    "%t. Delightfully forgettable.",
    "%t. There! Somebody else's problem.",
    "%t. Ha! Try the fellow behind me.",
    "%t. Wonderful. Peace at last.",
    "%t. Ha! Poof.",
    "%t. Splendid. Very sneaky.",
    "%t. Nothing to see, friends!",
    "%t. Ha! Attention elsewhere, please.",
    "%t. Marvellous little spell.",
    "Ha! Lost me, did you, %t?",
    "%t. Splendid. Onward, quietly.",
    "Do look somewhere else, %t!",
    "%t. Ha! Gone like that.",
}
S["SPELL:Fade"] = {
    "%t. Let their eyes pass over me.",
    "%t. I am no longer worth looking at.",
    "%t. Look to the one in front. Not to me.",
    "Turn your eyes elsewhere, %t.",
    "/em steps back and lowers his presence deliberately",
    "%t. I withdraw from their notice.",
    "%t. Their attention returns where it belongs.",
    "%t. Quietly. Out of sight.",
    "%t. I make myself unremarkable.",
    "Look to the one with the shield, %t.",
    "%t. I remove myself from their reckoning.",
    "%t. That is the disciplined response.",
    "%t. Stepping back. Hold them there.",
    "%t. Nothing here worth watching.",
    "%t. Eyes off me. Back to the front.",
    "%t. I fall out of their notice.",
    "%t. They are looking somewhere else now.",
    "%t. Unseen is a position, like any other.",
    "%t. I step into the quiet behind the fight.",
    "%t. Let the front line do its work.",
    "%t. I am not the one they want.",
    "%t. Out of their sight. As intended.",
    "%t. Do not be seen. That is the whole of it.",
    "%t. Withdrawn. Continue.",
    "%t. I am the least interesting thing here now.",
}
W["SPELL:Fade"] = {
    "Look elsewhere. Please, %t.",
    "%t. Fine. Forget me.",
    "%t. There. Somebody else's turn.",
    "%t. I would rather not be noticed.",
    "/em quietly stops being worth looking at",
    "%t. Fine. Gone.",
    "%t. There. Off their list.",
    "%t. One less thing to deal with.",
    "%t. It works. Small mercy.",
    "%t. Fine. Nobody sees me.",
    "%t. There. Quiet.",
    "%t. I have had enough attention for one day.",
    "%t. Fine. Elsewhere.",
    "%t. The dead are easy to overlook.",
    "%t. There. Better.",
    "Leave me out of it, %t.",
    "%t. Fine. Invisible enough.",
    "%t. One more retreat.",
    "%t. There. Unnoticed.",
    "%t. It never lasts long.",
    "%t. Fine. Ignore me.",
    "%t. Attention is exhausting.",
    "%t. There. Off I go.",
    "%t. Nobody looks at me anyway.",
    "%t. Fine. Let them look elsewhere.",
}
G["SPELL:Fade"] = {
    "Look elsewhere. There is nothing here, %t.",
    "%t. The dead are easy to overlook.",
    "%t. I was never here.",
    "%t. Forget me. Most do.",
    "/em steps into a shadow that was not there a moment ago",
    "%t. Between one shadow and the next.",
    "%t. Attention is a burden. I set it down.",
    "You will not find me until I choose, %t.",
    "%t. The dark hides its own.",
    "%t. I am difficult to look at now.",
    "Nothing here worth your eyes, %t.",
    "%t. The Shadow closes over me.",
    "You forgot me the moment I stepped back, %t.",
    "I am still here. You simply cannot hold it, %t.",
    "Watch someone else. It is safer, %t.",
    "Gone from your mind entirely, %t.",
    "%t. The dark takes me in and gives nothing back.",
    "You will not see me coming, %t.",
    "%t. I move unnoticed. That is how this ends.",
    "%t. Nothing to see. Look away.",
    "I am a gap in your attention now, %t.",
    "%t. The Shadow keeps me.",
    "%t. Forget the corpse. It is only a corpse.",
    "You will remember me later. Too late, %t.",
    "%t. Unseen. That is the most dangerous thing I can be.",
}
