-- RPVox -- Paladin class pack
--
-- Voice: a Blood Knight. He does not pray and he was never granted anything --
-- he takes the Light by force and resents needing it at all. Arrogant,
-- theologically furious, contemptuous of everyone who kneels. Underneath it,
-- the quiet knowledge that what he is holding was stolen and is screaming.
--
-- Single voice, no moods yet. Mood packs can be scoped with class = "PALADIN".

RPVox_CLASSES.PALADIN = {
    name = "Paladin",
    spells = {
        { spell = "Crusader Strike",        icon = "Interface\\Icons\\Spell_Holy_CrusaderStrike",      chance = 10 },
        { spell = "Judgement",              icon = "Interface\\Icons\\Spell_Holy_RighteousFury",       chance = 10 },
        { spell = "Seal of Righteousness",  icon = "Interface\\Icons\\Ability_ThunderBolt",            chance = 10 },
        { spell = "Seal of Command",        icon = "Interface\\Icons\\Ability_Warrior_InnerRage",      chance = 10 },
        { spell = "Seal of Blood",          icon = "Interface\\Icons\\Spell_Holy_SealOfBlood",         chance = 10 },
        { spell = "Consecration",           icon = "Interface\\Icons\\Spell_Holy_InnerFire",           chance = 10 },
        { spell = "Exorcism",               icon = "Interface\\Icons\\Spell_Holy_Excorcism_02",        chance = 10 },
        { spell = "Holy Wrath",             icon = "Interface\\Icons\\Spell_Holy_Excorcism",           chance = 10 },
        { spell = "Hammer of Justice",      icon = "Interface\\Icons\\Spell_Holy_SealOfMight",         chance = 10 },
        { spell = "Hammer of Wrath",        icon = "Interface\\Icons\\Ability_ThunderClap",            chance = 10 },
        { spell = "Avenging Wrath",         icon = "Interface\\Icons\\Spell_Holy_AvengingWrath",       chance = 10 },
        { spell = "Holy Shield",            icon = "Interface\\Icons\\Spell_Holy_BlessingOfProtection", chance = 10 },
        { spell = "Avenger's Shield",       icon = "Interface\\Icons\\Spell_Holy_AvengersShield",      chance = 10 },
        { spell = "Righteous Fury",         icon = "Interface\\Icons\\Spell_Holy_SealOfFury",          chance = 10 },
        { spell = "Holy Light",             icon = "Interface\\Icons\\Spell_Holy_HolyBolt",            chance = 10 },
        { spell = "Flash of Light",         icon = "Interface\\Icons\\Spell_Holy_FlashHeal",           chance = 10 },
        { spell = "Lay on Hands",           icon = "Interface\\Icons\\Spell_Holy_LayOnHands",          chance = 10 },
        { spell = "Cleanse",                icon = "Interface\\Icons\\Spell_Holy_Renew",               chance = 10 },
        { spell = "Redemption",             icon = "Interface\\Icons\\Spell_Holy_Resurrection",        chance = 10 },
        { spell = "Divine Shield",          icon = "Interface\\Icons\\Spell_Holy_DivineIntervention",  chance = 10 },
        { spell = "Divine Protection",      icon = "Interface\\Icons\\Spell_Holy_Restoration",         chance = 10 },
        { spell = "Blessing of Protection", icon = "Interface\\Icons\\Spell_Holy_SealOfProtection",    chance = 10 },
        { spell = "Blessing of Freedom",    icon = "Interface\\Icons\\Spell_Holy_SealOfValor",         chance = 10 },
        { spell = "Blessing of Might",      icon = "Interface\\Icons\\Spell_Holy_FistOfJustice",       chance = 10 },
        { spell = "Blessing of Kings",      icon = "Interface\\Icons\\Spell_Magic_MageArmor",          chance = 10 },
        { spell = "Devotion Aura",          icon = "Interface\\Icons\\Spell_Holy_DevotionAura",        chance = 10 },
        { spell = "Retribution Aura",       icon = "Interface\\Icons\\Spell_Holy_AuraOfLight",         chance = 10 },
    },
    lines = {

        -- Abilities -----------------------------------------------------

        ["SPELL:Crusader Strike"] = {
            "%t. Plain work. I am capable of plain work.",
            "/em swings without a prayer, without a word, without hesitation",
            "%t. No blessing on this one. Just the arm.",
            "%t. I do not need it to be holy to be effective.",
            "%t. There. Struck. No liturgy required.",
            "/em hits like a man who resents needing a hammer",
            "%t. My arm is mine. Only the rest is borrowed.",
            "%t. Simple. Direct. Honest, for once.",
        },

        ["SPELL:Judgement"] = {
            "%t. Judged. By me. Not by anything above me.",
            "/em passes sentence with a weapon rather than a word",
            "%t. There is no court. There is only what I decide.",
            "%t. I do not ask permission to condemn.",
            "%t. Sentence, and execution, in the same motion.",
            "/em delivers judgement without once looking upward",
            "%t. The Light does not judge. I do. It merely obeys.",
            "%t. You have been weighed by somebody who does not care.",
            "%t. Guilty. Everyone is. Get on with it.",
            "/em brings something white and unwilling down onto a man",
        },

        ["SPELL:Seal of Righteousness"] = {
            "/em seals his weapon with something that visibly resists him",
            "%t. Righteous. That is the word they use.",
            "/em binds light to steel the way one binds a prisoner",
            "%t. Hold still. This part is not for you.",
            "%t. It comes when it is called. It has no choice.",
            "/em forces a blessing onto a blade that flickers under it",
        },

        ["SPELL:Seal of Command"] = {
            "%t. Command. Note the word. Not request.",
            "/em issues an order to something that has no capacity to refuse",
            "%t. I do not ask. I have never asked.",
            "%t. It obeys me. That is the entire arrangement.",
            "/em seals his weapon with the tone of a man giving orders to staff",
        },

        ["SPELL:Seal of Blood"] = {
            "%t. Yes. It costs me. Everything costs me.",
            "/em pays for power in his own blood and does not blink",
            "%t. I will bleed for this. Willingly.",
            "%t. My people paid more for less.",
            "/em opens his own hand to seal a weapon with it",
            "%t. Blood is honest. The Light is not.",
        },

        ["SPELL:Consecration"] = {
            "%t. This ground is mine now. Stand on it and burn.",
            "/em claims a circle of earth by force of will alone",
            "%t. Consecrated. By me. Without ceremony.",
            "%t. Holy ground, and I made it holy myself.",
            "/em drives light into the soil like a stake",
            "%t. Nothing about this was blessed. It was taken.",
        },

        ["SPELL:Exorcism"] = {
            "%t. Out. Whatever you are, out.",
            "/em burns something unclean with something equally unwilling",
            "%t. This is what it is actually for.",
            "%t. I have no quarrel with you. I have a function.",
            "/em drives the Light into something that screams in two voices",
        },

        ["SPELL:Holy Wrath"] = {
            "%t. Wrath. That much I supply myself.",
            "/em releases something that has been straining to be released",
            "%t. All of it, outward, at once.",
            "%t. This is the only prayer I know.",
            "/em lets go of the leash for exactly one second",
        },

        ["SPELL:Hammer of Justice"] = {
            "%t. Down. On your knees. Everyone kneels eventually.",
            "/em puts a man on the ground and does not offer a hand",
            "%t. Justice is a hammer. It was always a hammer.",
            "%t. Stay there. It suits you.",
            "/em pins a soldier in place with a gesture that costs him nothing",
            "%t. I have knelt. I did not enjoy it. Your turn.",
        },

        ["SPELL:Hammer of Wrath"] = {
            "%t. You are finished. This is only the paperwork.",
            "/em throws something white and heavy at a man already falling",
            "%t. Do not crawl. It is undignified for both of us.",
            "%t. The end, delivered from a distance.",
        },

        ["SPELL:Avenging Wrath"] = {
            "/em burns so brightly that it is clearly hurting him",
            "%t. All of it. Now. Everything I am holding.",
            "%t. This is what it looks like when I stop being careful.",
            "%t. Yes, it is screaming. Yes, I am using it anyway.",
            "/em opens himself entirely and something enormous pours through",
            "%t. Look at me. This is what my people had to become.",
        },

        ["SPELL:Holy Shield"] = {
            "/em raises a shield that answers back",
            "%t. Come on then. Break yourself on it.",
            "%t. Everything you spend, you spend for nothing.",
            "/em sets his feet and dares the field to move him",
        },

        ["SPELL:Avenger's Shield"] = {
            "%t. And you. And you as well.",
            "/em throws a shield that chooses its own targets",
            "%t. It goes where it likes. I merely aim it.",
            "%t. Three of you. It was not a difficult decision.",
        },

        ["SPELL:Righteous Fury"] = {
            "/em makes himself impossible to ignore",
            "%t. Me. Look at me. Nobody else matters.",
            "%t. I am the loudest thing on this field.",
            "/em draws every eye by sheer force of arrogance",
        },

        ["SPELL:Holy Light"] = {
            "/em forces something to heal that would rather not",
            "Hold still. This is not gentle.",
            "You are welcome. Do not thank the Light. Thank me.",
            "/em pours brightness into a wound with visible effort",
            "It works. Whether it wants to or not.",
            "There. Mended. Do not waste it.",
        },

        ["SPELL:Flash of Light"] = {
            "/em snaps off a healing without breaking stride",
            "Quickly. That is all I have time for.",
            "Up. Now.",
            "/em drags somebody back from the edge one-handed",
            "Do not make me do that twice.",
        },

        ["SPELL:Lay on Hands"] = {
            "/em gives away everything he has and stays standing out of spite",
            "Take it. All of it. Get up.",
            "This costs me more than you know.",
            "/em empties himself into somebody else and says nothing about it",
            "I will not do this again today. Be worth it.",
            "There. Now we are both in trouble.",
        },

        ["SPELL:Cleanse"] = {
            "/em burns something out of a friend without asking first",
            "Hold still. This will sting.",
            "Whatever that was, it is gone.",
            "/em scours a curse away with something that does not enjoy the work",
            "Cleaner. Not clean. Cleaner.",
        },

        ["SPELL:Redemption"] = {
            "/em drags somebody back who had already stopped",
            "No. Get up. You do not get to leave.",
            "I did not permit that.",
            "/em forces life back into a body with obvious anger",
            "Up. There is still work.",
            "Do not thank me. Thank whatever I took this from.",
        },

        ["SPELL:Divine Shield"] = {
            "/em becomes untouchable and looks bored about it",
            "%t. No. I do not think so.",
            "%t. Try. Go on. Try.",
            "/em wraps himself in something absolute",
            "%t. Nothing you have can reach me.",
        },

        ["SPELL:Divine Protection"] = {
            "/em hardens the air around himself with a small gesture",
            "%t. Not yet.",
            "%t. I decide when I am hurt.",
            "/em shrugs off a blow that should have landed",
        },

        ["SPELL:Blessing of Protection"] = {
            "/em wraps a companion in something absolute and steps in front anyway",
            "Nothing touches you. Move.",
            "Get out. I will hold this.",
            "/em spends a blessing on somebody else without hesitating",
        },

        ["SPELL:Blessing of Freedom"] = {
            "/em breaks something invisible off a friend's legs",
            "Go. Nothing holds you now.",
            "Run. That is the whole of the blessing.",
            "/em cuts somebody loose from a thing that had hold of them",
        },

        ["SPELL:Blessing of Might"] = {
            "/em lays a hand on a shoulder and something transfers",
            "Take it. Hit harder.",
            "There. Now you are worth having beside me.",
            "/em blesses somebody with the manner of a man handing over a tool",
        },

        ["SPELL:Blessing of Kings"] = {
            "/em bestows something with more ceremony than he usually permits",
            "Kings. Yes. We had those, once.",
            "Everything about you, improved. You are welcome.",
            "/em grants a blessing named for a thing his people lost",
        },

        ["SPELL:Devotion Aura"] = {
            "/em stands still and something spreads out from him whether he wills it or not",
            "Stay near me. That is the only instruction.",
            "/em radiates protection with an expression of faint distaste",
            "Devotion. There is a word I did not choose.",
        },

        ["SPELL:Retribution Aura"] = {
            "/em burns quietly, and everything near him agrees to burn too",
            "%t. Touch any of us. See what happens.",
            "%t. Retribution is automatic. I do not have to think about it.",
            "/em stands in the middle of his people, radiating consequence",
        },

        -- Reactions -----------------------------------------------------

        ["REACT:LOWHEALTH"] = {
            "%t. This is not how it goes. This is not how it goes.",
            "%t. I am bleeding. Light does not stop that. I have checked.",
            "/em looks at his own blood with genuine offence",
            "%t. Do not mistake this for weakness. It is arithmetic.",
            "%t. I have been broken before. I was rebuilt worse.",
            "%t. I did not survive the fall of my city for this.",
            "/em plants his feet and refuses to give ground he cannot hold",
            "%t. The Light is not helping. It never helps. It only obeys.",
            "%t. I will not kneel. Not to you. Not to anything.",
            "%t. Everything I have, I took. I can take more.",
            "/em drags in a breath through armour that has been opened",
            "%t. My people watched their sun go out. You are nothing.",
            "%t. Stop looking at me like that.",
            "%t. I have held worse than this together.",
            "/em forces something bright into a wound and hates the sound it makes",
            "%t. I am not permitted to fall. I have not permitted it.",
            "%t. Very well. Everything, then.",
            "%t. Do you know what I gave up to be able to do this?",
            "/em straightens under the weight of his own armour by will alone",
            "%t. Faith is for people who were given something.",
            "%t. I am still standing. Note that. Remember it.",
            "%t. This body has been dying for years. It can wait longer.",
            "/em spits blood onto ground he has already consecrated",
            "%t. There is nothing above me to pray to.",
            "%t. Good. Now I am angry, and that is useful.",
            "%t. I take what I need. I will take this too.",
            "/em raises his shield with an arm that should not still work",
            "%t. Not here. Not to something like you.",
            "%t. I have bled for less and won.",
            "%t. Come on then. Finish it or fail.",
        },

        ["REACT:DEATH"] = {
            "%t. So it lets go at the end. Of course it does.",
            "/em falls in full armour, which makes a great deal of noise",
            "%t. I took it and it was never mine.",
            "%t. Tell them I did not kneel.",
            "%t. Do not bury me facing the sun.",
            "/em reaches for something bright and finds it already gone",
            "%t. My city fell. Now so have I. It is symmetrical.",
            "%t. I regret none of it. Very little of it.",
            "%t. Somebody take my blade. Do not let it rust.",
            "/em looks up at nothing, furious to the last",
            "%t. I was owed more time than this.",
            "%t. Was it screaming, all those years? I never asked.",
            "%t. Light. You could have. You simply did not.",
            "/em goes down hard, still holding the shield up",
            "%t. Do not pray over me. I would find it insulting.",
            "%t. Silvermoon. I would have liked to see it whole.",
            "%t. Everything I held is going out at once.",
            "/em releases something that flees him gratefully",
            "%t. There. It is free of me now.",
            "%t. I am not sorry. Write that down.",
            "%t. It was never a gift. It was a hostage.",
            "/em dies with his jaw set and his eyes open",
            "%t. Tell my order I did not disgrace it.",
            "%t. Cold. That is new.",
            "%t. Finish it, then. I will not ask twice.",
        },

        ["REACT:RESURRECT"] = {
            "/em stands, and something bright reluctantly returns to him",
            "Back. It did not want to. It rarely does.",
            "That was not death. That was a delay.",
            "/em checks his armour before he checks himself",
            "Nobody speaks of that.",
            "I have been dead. It was quiet. I did not care for the quiet.",
            "/em flexes a hand and watches light gather in it without enthusiasm",
            "It obeys. Still. Good.",
            "Right. Where was I.",
            "/em straightens his tabard with more care than the situation warrants",
            "One does not stay down. Not from where I come from.",
            "My people came back from worse. Considerably worse.",
            "/em looks at the sky as though daring it to comment",
            "No prayer. No gratitude. Just up.",
            "That will not happen again.",
            "/em takes up his shield and finds it heavier than before",
            "I am owed a great deal for that.",
            "Fine. Fine. Working.",
            "/em breathes out slowly and puts the fear somewhere it will not show",
            "Nothing is finished.",
        },

        ["REACT:KILLINGBLOW"] = {
            "%t. Judged and answered.",
            "/em stands over a body and does not offer any words for it",
            "%t. There. Sentence carried out.",
            "%t. I did not enjoy that. I do not need to.",
            "/em cleans his weapon without looking down",
            "%t. That is what the Light is for. Whatever they tell you.",
            "%t. Nobody is coming for your soul. I checked.",
            "%t. You had the chance to be elsewhere.",
            "/em plants his weapon and lets the moment pass",
            "%t. One fewer thing between me and morning.",
            "%t. Do not look for meaning in it. There is none.",
            "%t. My order does not pray over the dead. It moves on.",
            "%t. Rest. That is the closest to a blessing I have.",
            "/em steps over a corpse in armour that does not permit hurrying",
            "%t. That was righteous. I have decided it was.",
            "%t. He believed something. It did not matter.",
            "%t. Finished. Next.",
            "/em wipes his blade on the ground rather than on the body",
            "%t. I take no pleasure. I take the field.",
            "%t. Consecrated ground. He is welcome to it.",
        },

        ["REACT:COMBATSTART"] = {
            "%t. Kneel or do not. It ends the same.",
            "/em lowers his visor without any particular urgency",
            "%t. I am not here to convert you.",
            "%t. There will be no sermon. There is never a sermon.",
            "%t. You have picked a fight with something I stole.",
            "/em draws, and the air around the blade objects",
            "%t. I do not fight for anyone. I fight because I am able.",
            "%t. Come on. Let us find out what you believe.",
            "%t. My people were given nothing. We took this.",
            "/em sets his shield and becomes immovable",
            "%t. Every one of you thinks you are on the right side.",
            "%t. Judgement is not coming. Judgement is here.",
            "%t. I have no interest in your reasons.",
            "%t. Try. Genuinely. I would enjoy the surprise.",
            "/em rolls his shoulders under armour that has been repaired many times",
            "%t. Nothing about this will be holy.",
            "%t. Stand still and it will be quicker.",
            "%t. Right. Let us be about it.",
            "/em calls up light that flinches before it obeys",
            "%t. This is going to hurt one of us. Statistically, you.",
        },

        ["REACT:COMBATEND"] = {
            "/em lowers his shield and lets the light go out",
            "Done.",
            "It goes quiet when it is finished. So do I.",
            "/em checks his armour for cracks with practised fingers",
            "That was work. Nothing more.",
            "Nobody needs a prayer said over them. Move.",
            "/em stands still, breathing, until the brightness fades entirely",
            "There. It is free of me until the next time.",
            "I want to put this armour down for an hour.",
            "/em wipes his blade clean and sheathes it properly",
            "No hymn. No thanks. Simply over.",
            "My order taught me to feel nothing after. It worked.",
            "/em flexes a hand that is still faintly glowing and closes it",
            "Enough of that for one day.",
            "Everything holds. Just.",
            "/em looks at the ground he consecrated and lets it go",
            "It is only ground again.",
            "Right. Onward.",
            "/em sits heavily, which he would not do if anyone were watching",
            "Quiet. Finally.",
        },

        ["REACT:INTERRUPTED"] = {
            "%t. You do not get to stop me.",
            "%t. That was mine. I had hold of it.",
            "/em loses his grip on something that immediately tries to escape",
            "%t. Do you know how hard that is to hold?",
            "%t. It slipped. Because of you.",
            "%t. Nothing interrupts me. Nothing.",
            "/em closes his fist on empty air and grinds his teeth",
            "%t. Very well. The blunt way, then.",
            "%t. You have made this take longer and hurt more.",
            "%t. I do not have to cast to end you.",
            "/em drops what he was building and reaches for a weapon instead",
            "%t. That was rude, and it was clever, and I will remember both.",
            "%t. Again. And do not touch my hands.",
            "%t. It fights me enough without your help.",
            "/em resets his stance with visible fury and no wasted motion",
            "%t. One more. Try one more.",
            "%t. I am not a priest. You cannot silence me.",
            "%t. Fine. Steel, then.",
            "/em stops trying to be precise about any of it",
            "%t. Enough.",
        },

        ["REACT:LEVELUP"] = {
            "/em holds more than he could yesterday, and it strains less",
            "More. Good. I want more.",
            "It resists less each time. That is not comfort.",
            "/em flexes a hand and watches light gather without a struggle",
            "Stronger. That is the only measure.",
            "My order would approve. I do not care.",
            "/em straightens under armour that suddenly weighs less",
            "Another step away from what I was.",
            "I am getting very good at this.",
            "/em looks at his own hand as though it belonged to somebody harder",
            "Good. There is a long way to go and a great deal owed.",
            "It obeys more readily now. I notice that.",
            "/em says nothing and simply stands taller",
            "Capacity. That is all any of it is.",
            "Better. Not finished.",
        },

        ["REACT:FALLING"] = {
            "This armour was not designed for this.",
            "/em falls extremely quickly, being made mostly of metal",
            "Oh, this is going to be loud.",
            "Plate. Plate and gravity. A poor combination.",
            "/em drops like something dropped rather than something falling",
            "I am not built to do this.",
            "The ground. Yes. Obviously.",
            "/em braces in a way that will not help at all",
            "Nothing about this is dignified.",
            "Light. Not for help. Just noting it.",
            "/em hits hard enough to dent something",
            "That will need a smith.",
            "Fine. Fine. Ow.",
            "/em falls silently, refusing to make a sound about it",
            "I have survived worse landings.",
        },

        ["REACT:DROWNING"] = {
            "Armour. It is always the armour.",
            "/em sinks fast, weighed down by everything that protects him",
            "This is the one thing plate cannot answer.",
            "Air. Now.",
            "/em struggles with the straps of something that is killing him",
            "Get it off. Get it off.",
            "Up. Up. Come on.",
            "/em claws toward a surface that is much too far away",
            "Not like this. Not in the dark.",
            "I cannot burn my way out of water.",
            "/em fights and sinks and fights again",
            "Cold. Very cold.",
            "Somebody.",
            "/em breaks the surface for half a breath and goes under",
            "This is a stupid way for anything to end.",
        },

        ["REACT:DURABILITY"] = {
            "/em examines a dent that has become a crack",
            "This plate has been remade three times. It is tired.",
            "Everything I own has been broken and mended.",
            "/em runs a thumb along a split in a pauldron",
            "So has my city. So have I.",
            "It will hold. It has held through worse.",
            "/em ties a strap where a buckle used to be",
            "I need a smith. A good one. A patient one.",
            "Armour is faith you can actually measure.",
            "/em looks at his own kit with something close to affection",
            "This has kept me alive for years. It deserves better than me.",
            "Cracked. Everything is cracked.",
            "/em tests a joint and finds it grinding",
            "One more fight in it. Perhaps.",
            "Repairs. Before anything else.",
        },

        -- Idle ----------------------------------------------------------

        ["IDLE:EAT"] = {
            "/em eats in armour, because taking it off takes too long",
            "Fuel. Nothing more.",
            "/em says no grace whatsoever before eating",
            "No blessing. I do not thank anything for food.",
            "My people ate better. Everything was better.",
            "/em eats quickly and without any evident pleasure",
            "It is a body. It requires maintenance.",
        },

        ["IDLE:DRINK"] = {
            "/em drinks water and thinks about wine from a city that no longer pours it",
            "This is not what we drank at home.",
            "/em drinks standing, in full plate, as always",
            "To the ones who did not come back.",
            "Nothing tastes right since. Nothing at all.",
            "/em raises a flask very slightly, to nobody",
            "One does not sit down in armour if one intends to get up.",
        },

        ["IDLE:MOUNT"] = {
            "/em mounts up in one heavy, practised motion",
            "Come. There is ground to cover.",
            "/em rides upright, because he was drilled to ride upright",
            "A knight walks nowhere he can ride.",
            "Faster. I dislike being late to anything.",
            "/em pats a warhorse with a gauntlet, which neither of them enjoys",
        },

        ["IDLE:QUESTACCEPT"] = {
            "Very well. It will be done.",
            "/em accepts a task without asking whether it is righteous",
            "I do not need to approve of it. I need to finish it.",
            "Consider it handled.",
            "/em listens, nods once, and asks nothing further",
            "You do not have to explain. I have heard worse reasons.",
            "Fine. But I do it my way.",
            "/em takes an order the way a soldier takes an order",
            "There is no such thing as a small duty.",
            "It will be done properly or not at all.",
        },

        ["IDLE:FISHING"] = {
            "/em fishes in full armour, which looks as absurd as it is",
            "This is the only thing I do that has no purpose.",
            "/em sits at the water and lets the light go out entirely",
            "Nothing here needs judging. It is restful.",
            "I could put the armour down. I will not, but I could.",
            "/em watches the water and, for once, holds nothing at all",
            "Quiet. I had forgotten quiet.",
        },

        ["IDLE:DISCOVERY"] = {
            "/em looks out at somewhere new and does not immediately assess it for cover",
            "It is beautiful. That still happens sometimes.",
            "/em stands a long moment, and something in his face loosens",
            "Nothing here has burned. Nothing here has fallen.",
            "I would have liked to show somebody this.",
            "/em takes off a gauntlet, briefly, to touch something",
            "Good. Some of the world is still intact.",
        },
    },
}
