-- RPVox -- Shaman class pack
--
-- Voice: an old orc woman who does not command the elements so much as
-- negotiate with them, and they are frequently in a mood. Warm, dry, tired,
-- and on first-name terms with fire. Speaks to the wind more often than to
-- people, and gets better answers.
--
-- Single voice, no moods yet. Mood packs can be scoped with class = "SHAMAN".

RPVox_CLASSES.SHAMAN = {
    name = "Shaman",
    spells = {
        { spell = "Lightning Bolt",       icon = "Interface\\Icons\\Spell_Nature_Lightning",           chance = 10 },
        { spell = "Chain Lightning",      icon = "Interface\\Icons\\Spell_Nature_ChainLightning",      chance = 10 },
        { spell = "Earth Shock",          icon = "Interface\\Icons\\Spell_Nature_EarthShock",          chance = 10 },
        { spell = "Flame Shock",          icon = "Interface\\Icons\\Spell_Fire_FlameShock",            chance = 10 },
        { spell = "Frost Shock",          icon = "Interface\\Icons\\Spell_Frost_FrostShock",           chance = 10 },
        { spell = "Stormstrike",          icon = "Interface\\Icons\\Ability_Shaman_Stormstrike",       chance = 10 },
        { spell = "Lightning Shield",     icon = "Interface\\Icons\\Spell_Nature_LightningShield",     chance = 10 },
        { spell = "Rockbiter Weapon",     icon = "Interface\\Icons\\Spell_Nature_RockBiter",           chance = 10 },
        { spell = "Flametongue Weapon",   icon = "Interface\\Icons\\Spell_Fire_FlameTounge",           chance = 10 },
        { spell = "Windfury Weapon",      icon = "Interface\\Icons\\Spell_Nature_Cyclone",             chance = 10 },
        { spell = "Healing Wave",         icon = "Interface\\Icons\\Spell_Nature_MagicImmunity",       chance = 10 },
        { spell = "Lesser Healing Wave",  icon = "Interface\\Icons\\Spell_Nature_HealingWaveLesser",   chance = 10 },
        { spell = "Chain Heal",           icon = "Interface\\Icons\\Spell_Nature_HealingWaveGreater",  chance = 10 },
        { spell = "Ancestral Spirit",     icon = "Interface\\Icons\\Spell_Nature_Regenerate",          chance = 10 },
        { spell = "Purge",                icon = "Interface\\Icons\\Spell_Nature_Purge",               chance = 10 },
        { spell = "Ghost Wolf",           icon = "Interface\\Icons\\Spell_Nature_SpiritWolf",          chance = 10 },
        { spell = "Water Breathing",      icon = "Interface\\Icons\\Spell_Shadow_DemonBreath",         chance = 10 },
        { spell = "Far Sight",            icon = "Interface\\Icons\\Spell_Nature_FarSight",            chance = 10 },
        { spell = "Bloodlust",            icon = "Interface\\Icons\\Spell_Nature_BloodLust",           chance = 10 },
        { spell = "Searing Totem",        icon = "Interface\\Icons\\Spell_Fire_SearingTotem",          chance = 10 },
        { spell = "Magma Totem",          icon = "Interface\\Icons\\Spell_Fire_SelfDestruct",          chance = 10 },
        { spell = "Fire Nova Totem",      icon = "Interface\\Icons\\Spell_Fire_SealOfFire",            chance = 10 },
        { spell = "Stoneclaw Totem",      icon = "Interface\\Icons\\Spell_Nature_StoneClawTotem",      chance = 10 },
        { spell = "Earthbind Totem",      icon = "Interface\\Icons\\Spell_Nature_StrengthOfEarthTotem02", chance = 10 },
        { spell = "Tremor Totem",         icon = "Interface\\Icons\\Spell_Nature_TremorTotem",         chance = 10 },
        { spell = "Windfury Totem",       icon = "Interface\\Icons\\Spell_Nature_Windfury",            chance = 10 },
        { spell = "Mana Spring Totem",    icon = "Interface\\Icons\\Spell_Nature_ManaRegenTotem",      chance = 10 },
        { spell = "Healing Stream Totem", icon = "Interface\\Icons\\INV_Spear_04",                     chance = 10 },
    },
    lines = {

        -- Abilities -----------------------------------------------------

        ["MELEE"] = {
            "%t. Old woman. Heavy hands. Do the arithmetic.",
            "/em swings something blunt with sixty years of practice behind it",
            "%t. The elements are busy. This one is mine.",
            "%t. I did not always have totems.",
            "%t. Down you go.",
            "/em hits hard and steps back to let the ground do the rest",
            "%t. My arms still work. Note that.",
            "%t. Sometimes you just hit the thing.",
            "%t. Come here, then.",
            "/em plants her feet and does not give any ground at all",
        },
        ["SPELL:Lightning Bolt"] = {
            "%t. The sky agreed. It does not always.",
            "/em asks the air for something and gets it on the third try",
            "%t. That was not me. I only pointed.",
            "%t. The storm is in a giving mood today.",
            "%t. Do not thank me. Thank the weather.",
            "/em holds up one hand and something enormous answers",
            "%t. I asked politely. It went badly for you.",
            "%t. There is a great deal of anger up there and very little of it is mine.",
            "%t. Quick, that one. Quick is a kindness.",
            "/em speaks a word upward and the answer comes down",
        },

        ["SPELL:Chain Lightning"] = {
            "%t. And your friends. It does not stop where I tell it.",
            "/em lets something loose that finds its own way about",
            "%t. Do not stand near each other. Nobody ever listens.",
            "%t. It goes where it likes. I merely started it.",
            "/em throws lightning and steps back to watch it decide",
            "%t. That is what happens when you crowd a storm.",
        },

        ["SPELL:Earth Shock"] = {
            "%t. The ground has an opinion about you.",
            "/em strikes the earth and lets it pass the message on",
            "%t. Quiet now. The stone says quiet.",
            "%t. That is a very old thing hitting you.",
            "/em asks the ground for one sharp favour",
            "%t. Stone does not argue. It simply arrives.",
        },

        ["SPELL:Flame Shock"] = {
            "%t. Fire will not let go once it has hold.",
            "/em sets something burning and does not stay to watch",
            "%t. It likes you. That is unfortunate for you.",
            "%t. I told it not to linger. It never listens.",
            "/em speaks briefly to a flame that ignores her instructions",
            "%t. It will keep working after I stop.",
        },

        ["SPELL:Frost Shock"] = {
            "%t. Slow down. The water insists.",
            "/em lays cold on somebody the way one lays a hand on a shoulder",
            "%t. Stay a while. We are not finished.",
            "%t. Ice is only water that has stopped being reasonable.",
            "/em cools the air until somebody's legs stop cooperating",
        },

        ["SPELL:Stormstrike"] = {
            "%t. Both hands, and the sky behind them.",
            "/em hits twice with something crackling between the blows",
            "%t. This is the part I do myself.",
            "%t. Old woman. Heavy hands. Do the arithmetic.",
            "/em brings weapons down with the storm arriving a heartbeat later",
            "%t. The wind helps. I do most of it.",
        },

        ["SPELL:Lightning Shield"] = {
            "/em wraps herself in three small tempers that circle slowly",
            "%t. Touch me and find out.",
            "/em asks the storm to sit close for a while",
            "%t. They bite. They are not mine and they bite.",
            "%t. I would keep my distance, personally.",
        },

        ["SPELL:Rockbiter Weapon"] = {
            "/em rubs stone dust along an edge and murmurs to it",
            "There. Heavier. Meaner.",
            "/em asks the earth to sit in her weapon a while",
            "Stone in the steel. It knows what to do.",
            "Hold on tight, old thing.",
        },

        ["SPELL:Flametongue Weapon"] = {
            "/em coaxes fire into an edge, which takes some persuading",
            "Yes, yes. In you go.",
            "/em argues briefly with a flame and wins",
            "It complains about being confined. It always complains.",
            "Burn where I put you. Not before.",
        },

        ["SPELL:Windfury Weapon"] = {
            "/em asks the wind for speed and gets rather more than she asked for",
            "Steady. Steady. Good.",
            "/em binds a gale into a weapon that shudders under it",
            "The wind is excitable. That is the whole point of it.",
            "Now we go quickly.",
        },

        ["SPELL:Healing Wave"] = {
            "/em pours water into a wound with the patience of a very old woman",
            "Hold still. This takes as long as it takes.",
            "The water knows what to do. It has done this longer than either of us.",
            "/em cups her hands and something clean rises out of them",
            "There. Better. Sit down anyway.",
            "You are not the first thing I have mended today.",
        },

        ["SPELL:Lesser Healing Wave"] = {
            "/em slaps a quick healing on somebody and moves on",
            "Quick one. That is all you get.",
            "Up. Up. No, do not thank me.",
            "/em patches a wound the way one patches a tent in the rain",
            "That will hold. Probably.",
        },

        ["SPELL:Chain Heal"] = {
            "/em sends water out and lets it find who needs it",
            "It will find you. It always finds you.",
            "/em heals three people without appearing to aim at any of them",
            "Share it. There is enough.",
            "Water goes downhill. So does mercy.",
        },

        ["SPELL:Ancestral Spirit"] = {
            "/em speaks to somebody who is not present and is answered",
            "Not yet. Send them back.",
            "They are not finished. I have asked. Politely.",
            "/em kneels beside a body and argues with the ancestors",
            "Up. Your grandmother says up.",
            "I have called in a favour for you. Be worth it.",
        },

        ["SPELL:Purge"] = {
            "%t. Whatever that is, it is coming off.",
            "/em scrapes something unwelcome off a man like ice from a windscreen",
            "%t. Borrowed magic. Give it back.",
            "%t. That was not yours to be wearing.",
        },

        ["SPELL:Ghost Wolf"] = {
            "/em drops to four legs and remembers she prefers it",
            "Faster this way. Quieter too.",
            "/em becomes something grey and long-legged",
            "The wolf does not worry about any of this.",
            "Better. Much better.",
        },

        ["SPELL:Water Breathing"] = {
            "/em has a short word with the water about lungs",
            "It has agreed not to drown you. For now.",
            "/em blesses somebody's breathing with visible effort",
            "Do not test it. It is a favour, not a promise.",
        },

        ["SPELL:Far Sight"] = {
            "/em closes her eyes and looks somewhere she is not",
            "Hold on. I am elsewhere for a moment.",
            "/em goes very still and something behind her eyes travels",
            "The wind carries pictures if you ask it right.",
            "Ah. That is what is over there.",
        },

        ["SPELL:Bloodlust"] = {
            "/em beats a rhythm on the ground that everybody's blood picks up",
            "Faster. All of you. Now.",
            "/em calls something up out of the earth that gets into everyone's legs",
            "This is old. Older than the Horde. Move.",
            "Go. Go. Do not think about it, go.",
        },

        ["SPELL:Searing Totem"] = {
            "/em plants something small and bad-tempered in the dirt",
            "%t. It does the fiddly work. I do the rest.",
            "/em sets a totem down and pats it once, encouragingly",
            "%t. It is not clever. It is persistent.",
            "%t. Go on. Off you go.",
        },

        ["SPELL:Magma Totem"] = {
            "%t. Mind your feet. I did warn you.",
            "/em drives a totem into ground that immediately regrets it",
            "%t. Everything close to that is going to be uncomfortable.",
            "%t. The fire is out and it is not fussy about who.",
        },

        ["SPELL:Fire Nova Totem"] = {
            "%t. Stand back. All of you, stand back.",
            "/em sets something down that is very obviously counting",
            "%t. Three. Two. You should have moved.",
            "/em plants a totem and walks away from it briskly",
        },

        ["SPELL:Stoneclaw Totem"] = {
            "/em pushes a lump of stubborn stone into the ground",
            "Hit that instead. It does not mind.",
            "%t. Take it out on the rock. It has no feelings.",
            "/em sets down something that will be hit a great deal",
        },

        ["SPELL:Earthbind Totem"] = {
            "%t. The ground has hold of you now.",
            "/em plants something that makes everybody's boots heavy",
            "%t. Walk if you like. Slowly, though.",
            "%t. Nobody is running anywhere.",
        },

        ["SPELL:Tremor Totem"] = {
            "/em drives down a totem that shakes fear out of people",
            "None of that. Not while I am here.",
            "/em plants something that rattles the nonsense loose",
            "Whatever is in your head, it is leaving.",
        },

        ["SPELL:Windfury Totem"] = {
            "/em sets down a totem and the air around it starts hurrying",
            "There. Everybody quicker.",
            "/em plants the wind in the ground, which it dislikes",
            "Go on. Swing faster.",
        },

        ["SPELL:Mana Spring Totem"] = {
            "/em opens a small spring in dry ground",
            "Drink. It will keep coming.",
            "/em plants water where there was none and looks pleased about it",
            "Nobody goes empty while I am standing.",
        },

        ["SPELL:Healing Stream Totem"] = {
            "/em sets down something that quietly mends everyone near it",
            "Small and steady. That is how most healing works.",
            "/em plants a totem and lets it get on with it",
            "It will not save you. It will keep you.",
        },

        -- Reactions -----------------------------------------------------

        ["REACT:LOWHEALTH"] = {
            "%t. Ah. That is a lot of blood for an old woman.",
            "%t. I have been hit by better and buried them.",
            "/em presses a hand to her ribs and swears in orcish",
            "%t. The water is busy. It will get to me.",
            "%t. Do not fuss. I have had worse in the Barrens.",
            "%t. Bones do not knit as fast as they did.",
            "/em spits and looks entirely unimpressed with her own condition",
            "%t. I am too old for this and too stubborn to stop.",
            "%t. The elements are being slow today. Typical.",
            "%t. Fire. Fire, I need you now. Yes. Now.",
            "/em straightens her back with an audible complaint from it",
            "%t. I have outlived two Horde. I will outlive you.",
            "%t. That will bruise. Everything bruises now.",
            "%t. Come on then. I have not finished being difficult.",
            "/em takes a breath that hurts and does not let it show",
            "%t. My grandmother fought at Hillsbrad. I do not fold.",
            "%t. Wind. Wind, a hand, please.",
            "%t. It has been a long life. It is not over.",
            "/em leans on her weapon and turns it into a stance",
            "%t. Do not look so pleased. I bleed often.",
            "%t. Ancestors. Not yet. I have things to do.",
            "%t. This body has failed me before. It comes back.",
            "/em wipes blood off her face with the back of a wrist",
            "%t. I am slower than I was and meaner than I was.",
            "%t. Right. No more asking nicely.",
            "%t. Every one of my scars has a name. You do not get one.",
            "/em plants her feet and refuses to be moved off them",
            "%t. The ground is holding me up. Ask it to stop, if you can.",
            "%t. Enough. I want my supper.",
            "%t. Come on. Finish it or step back.",
        },

        ["REACT:DEATH"] = {
            "%t. Ah. So that is that.",
            "/em goes down heavily and does not complain about it",
            "%t. Tell them I went arguing.",
            "%t. Put me in the ground. Properly. Facing out.",
            "%t. Ancestors. I am coming. Do not fuss.",
            "/em reaches toward the earth and it comes up to meet her",
            "%t. It has been a good long while. Longer than most.",
            "%t. My totems go to somebody young and rude.",
            "%t. The wind will carry it. Somebody will hear.",
            "/em lets go of a weapon she has carried for forty years",
            "%t. I was never afraid of this part.",
            "%t. Do not weep. I have had more than my share.",
            "%t. The fire will not miss me. It misses nobody.",
            "/em says a name in orcish and the ground takes it",
            "%t. There is nothing owed. That is a rare thing.",
            "%t. Somebody feed my wolf.",
            "%t. Cold. Well. That happens.",
            "/em closes her eyes with something like satisfaction",
            "%t. I go into the earth. The earth was always going to win.",
            "%t. Tell the young ones I said listen more.",
            "%t. Enough now. Enough.",
            "/em dies the way she lived, without hurrying",
            "%t. I would have liked to see the spring.",
            "%t. It is quiet. The elements have gone quiet.",
            "%t. Right. Go on then.",
        },

        ["REACT:RESURRECT"] = {
            "/em sits up out of the dirt with a great deal of grumbling",
            "The ancestors sent me back. They said I was talking too much.",
            "Well. That was rude of somebody.",
            "/em shakes soil out of her hair and does not care where it lands",
            "Everything aches. Everything ached before, mind.",
            "I saw them. They are all fine. They asked after you.",
            "/em rolls a shoulder and listens to it click",
            "Back, and in a temper.",
            "The earth spat me out. It usually does. I am too loud.",
            "/em checks her totems before she checks herself",
            "All present. Good.",
            "Right. Where was I. Somebody was being annoying.",
            "/em stands with the deliberate slowness of someone very old",
            "Old bones. Old bones and no patience.",
            "I have died before. I keep not staying dead.",
            "/em spits, stretches, and picks up her weapon",
            "That is twice this year. It is getting silly.",
            "Do not fuss. Do not fuss.",
            "/em pats the ground once, in thanks, and gets on with it",
            "Up. There is work.",
        },

        ["REACT:KILLINGBLOW"] = {
            "%t. There. Go back to the earth.",
            "/em stands over a body and says something quiet in orcish",
            "%t. It is done. Do not linger.",
            "%t. The ground will take you. It takes everyone.",
            "/em closes a dead man's eyes without ceremony",
            "%t. No shame in it. You fought.",
            "%t. Somebody will burn a fire for you. Not me.",
            "%t. That is one more for the earth.",
            "/em plants her weapon and rests both hands on it a moment",
            "%t. I take no joy in this. I take no shame either.",
            "%t. Rest. You have earned rest.",
            "%t. Your ancestors will meet you. Mine will not comment.",
            "%t. Down you go.",
            "/em steps back so the blood does not reach her boots",
            "%t. Finished. Next.",
            "%t. You were somebody's child. Everybody is.",
            "%t. The elements do not care who wins. They only witness.",
            "/em murmurs something to the ground where the body fell",
            "%t. Go quietly. I will not follow you for a while.",
            "%t. It is over. Good.",
        },

        ["REACT:COMBATSTART"] = {
            "%t. Right. Let us see who wants what.",
            "/em rolls her shoulders and something in the air begins to gather",
            "%t. I am too old to be doing this and here I am.",
            "%t. You could walk away. You will not, but you could.",
            "%t. Fire. Wake up. We are needed.",
            "/em plants a totem before she has even drawn a weapon",
            "%t. I have fought better than you and buried them all.",
            "%t. Do not make me shout. My voice is not what it was.",
            "%t. Come on then, if you are coming.",
            "%t. The elements are awake and in a poor temper.",
            "/em sets her feet the way she was taught sixty years ago",
            "%t. I did not want this. I am very good at it anyway.",
            "%t. Stand still. It goes faster.",
            "%t. Somebody is going to be sorry and it will not be me.",
            "/em speaks a word upward and the clouds notice",
            "%t. You are standing on ground that knows me.",
            "%t. Last chance. I always give one.",
            "%t. Right. Everybody hold on.",
            "/em cracks her knuckles, which takes a while",
            "%t. Let us get this done before supper.",
        },

        ["REACT:COMBATEND"] = {
            "/em collects her totems one by one, unhurried",
            "There. Done.",
            "Thank you. All of you. Yes, you as well.",
            "/em pats the ground once before standing up",
            "That was more work than it looked.",
            "The fire is sulking. It always sulks afterwards.",
            "/em sits down heavily on a rock and stays there",
            "Old bones. Old bones and a long day.",
            "Everyone still upright? Good.",
            "/em checks her people over before she checks herself",
            "Right. Who is bleeding. Honestly, now.",
            "I want tea and I want to not be shouted at.",
            "/em cleans her weapon slowly and thoroughly",
            "The wind has gone quiet. That is how you know.",
            "Enough for one afternoon.",
            "/em looks up at a sky that has stopped being interested",
            "They are settling. Let them settle.",
            "Good. Come on, then. Somewhere with a fire.",
            "/em stretches and every part of her objects",
            "Peace. For a while.",
        },

        ["REACT:INTERRUPTED"] = {
            "%t. I was talking to somebody.",
            "%t. That took a moment to arrange.",
            "/em loses hold of something that grumbles and goes away",
            "%t. Now I have to ask again. They hate being asked twice.",
            "%t. Rude. To me and to the sky.",
            "%t. Right. Faster and worse, then.",
            "/em shakes out her hands and starts the conversation over",
            "%t. The elements do not queue. You have cost me.",
            "%t. Do not do that again.",
            "%t. Fine. I have hands. I have always had hands.",
            "/em gives up on asking and reaches for a weapon instead",
            "%t. You have annoyed the wind. That was unwise.",
            "%t. Again. And this time keep your hands to yourself.",
            "%t. That was going to be beautiful.",
            "/em breathes out slowly and begins again from the start",
            "%t. Clever. Do not be clever twice.",
            "%t. I am old and I do not have time for repeats.",
            "%t. Very well. The quick way.",
            "/em stops asking the elements politely",
            "%t. Enough of that.",
        },

        ["REACT:LEVELUP"] = {
            "/em notices the elements answered faster that time",
            "Ah. They are listening better.",
            "That is a lifetime of being polite paying off.",
            "/em holds up a hand and something answers before she asks",
            "Good. Good. Still learning, at my age.",
            "The wind knows my name a little better today.",
            "/em nods once at nothing in particular",
            "Nobody is ever finished. That is the point.",
            "Stronger. Slower, but stronger.",
            "/em smiles, which makes her whole face rearrange",
            "My teacher would have grunted. That was high praise.",
            "One more thing I can do. There is always one more.",
            "/em pats the ground, pleased with it and with herself",
            "They trust me a little further. That is all this is.",
            "Right. On we go.",
        },

        ["REACT:FALLING"] = {
            "Oh, this is going to hurt.",
            "/em falls, complaining loudly the entire way",
            "Air. Air, a hand. Air? No. Fine.",
            "This is why I ride.",
            "/em plummets, arms out, entirely undignified",
            "Ancestors, not like this. Not off a rock.",
            "The ground and I are old friends. This is not friendly.",
            "/em braces the way she has braced many times",
            "Old bones. Old bones. Oh no.",
            "I asked the wind. The wind is busy.",
            "/em hits, rolls, and lies there swearing",
            "Every single time.",
            "That was my own stupid fault.",
            "/em falls silently, having decided shouting will not help",
            "Right. Down we go.",
        },

        ["REACT:DROWNING"] = {
            "The water knows me. It is being difficult anyway.",
            "/em struggles upward, furious rather than frightened",
            "We have talked about this. We have talked about this.",
            "Air. Please. As a favour.",
            "/em kicks hard and loses a totem to the dark",
            "That was my good totem.",
            "Up. Up. Which way is up.",
            "/em fights water that has decided not to listen today",
            "I have asked nicely twice.",
            "Not like this. Not by an element I know personally.",
            "/em breaks the surface, gets half a breath, goes under",
            "Cold. Very cold. Very rude.",
            "Somebody. Anybody. Anything.",
            "/em claws upward with the last of it",
            "This is a stupid way for an old woman to go.",
        },

        ["REACT:DURABILITY"] = {
            "/em looks at a strap that has finally had enough",
            "This kit is older than most of the people I fight.",
            "Everything wears out. Me included.",
            "/em ties a knot in leather that has been knotted before",
            "It has done good work. It is allowed to be tired.",
            "I should mend this. I have said that for a year.",
            "/em turns a broken buckle over in her fingers",
            "My teacher gave me this. It has outlasted her.",
            "Held together with string and stubbornness.",
            "/em examines a split seam and sighs at it",
            "Right. A smith, then. And an argument about the price.",
            "It will hold. It always holds. Until it does not.",
            "/em pats a worn-out piece of armour like an old dog",
            "We have been through a great deal, you and I.",
            "One more fight. Then repairs. I promise. I always promise.",
        },

        -- Idle ----------------------------------------------------------

        ["IDLE:EAT"] = {
            "/em eats slowly and thanks the fire for the cooking",
            "Something died for this. Say so, at least.",
            "/em puts a small piece aside on the ground before eating any",
            "That bit is for the ancestors. They eat first.",
            "It is not good. It is hot. That will do.",
            "/em eats with her fingers and no apology whatsoever",
            "I have eaten worse in places I will not describe.",
            "Sit. Eat. Nobody is hurrying us.",
        },

        ["IDLE:DRINK"] = {
            "/em pours a little on the ground before drinking",
            "First mouthful is not mine. It never is.",
            "/em drinks water and has a brief silent word with it",
            "Thank you. You have been busy today.",
            "Clean water. There is nothing better and everyone forgets it.",
            "/em drinks deeply and wipes her mouth on her wrist",
            "In the Barrens we would have fought over this.",
        },

        ["IDLE:MOUNT"] = {
            "/em greets her mount properly before getting on",
            "Come on, you. We have ground to cross.",
            "/em swings up with more effort than she used to need",
            "Getting on is harder every year. Getting off is worse.",
            "Steady. Neither of us is young.",
            "/em rides with the ease of somebody who learned before she could walk",
        },

        ["IDLE:MINING"] = {
            "/em asks the stone before she takes any of it",
            "Sorry. I will only take what I need.",
            "/em works the rock steadily, talking to it under her breath",
            "This has been here longer than anything alive. Show some manners.",
            "There. Thank you.",
            "/em brushes dust off a seam almost tenderly",
            "The earth gives. It does not have to.",
        },

        ["IDLE:FISHING"] = {
            "/em sits at the water's edge and has a long, silent conversation",
            "Well? Anything? No? Fine. We will sit.",
            "/em fishes without much hope and no impatience at all",
            "The water tells me things when it is in the mood.",
            "This is the only quiet I get.",
            "/em watches the surface and lets her shoulders come down",
            "Nobody is shouting. Nobody is bleeding. Good.",
        },

        ["IDLE:DISCOVERY"] = {
            "/em stops and takes in somewhere she has never stood",
            "New ground. It does not know me yet.",
            "/em crouches and puts a palm flat on unfamiliar earth",
            "Hello. I am not staying. I only wanted to say so.",
            "The wind is different here. Listen.",
            "/em stands a long moment, letting the place get used to her",
            "Somewhere new, at my age. That is a gift.",
        },
    },
}
