-- RPVox -- mood pack: SERIOUS (Priest)
--
-- Lines are stored plain; the addon prefixes each with [serious] when seeding.
-- Voice: the priest at work. Formal, measured, clerical. No jokes, no self-pity.
-- This is the man he was before Lordaeron, still operating.

RPVox_MOOD_LINES = RPVox_MOOD_LINES or {}

RPVox_MOOD_LINES.SERIOUS = {
    name  = "serious",
    class = "PRIEST",

    ["REACT:LOWHEALTH"] = {
        "%t. I am wounded. Adjust accordingly.",
        "%t. Losing ground. Not losing the fight.",
        "%t. Report: badly hurt, still functional.",
        "%t. I require a moment.",
        "%t. The body is failing. The work is not.",
        "Hold position. I will manage, %t.",
        "%t. This is within tolerance. Barely.",
        "%t. Focus. Breathe. Continue.",
        "/em steadies himself and resumes the cadence of a prayer",
        "%t. Wounded, not finished.",
        "Attend to yourselves. I will hold, %t.",
        "%t. The damage is severe. Proceed regardless.",
        "%t. I have taken worse and continued.",
        "Do not break formation for me, %t.",
        "%t. Discipline first. Pain second.",
        "%t. Still standing. That is sufficient.",
        "%t. Mark my position.",
        "%t. A wound is information, nothing more.",
        "%t. Continue the plan.",
        "%t. I will not fall here.",
        "%t. Concentration holds. Everything else is negotiable.",
        "%t. This is survivable.",
        "%t. Steady. The line matters more than I do.",
        "%t. Assess. Adapt. Continue.",
        "%t. I have reserves. Not many.",
        "Do not falter on my account, %t.",
        "%t. The Light is thin here. I will manage without.",
        "%t. Injured. Continuing.",
        "Hold. I am not done, %t.",
        "/em presses a hand to the wound and keeps casting",
        "%t. One thing at a time.",
        "%t. There is work left. That settles it.",
        "%t. I do not require assistance yet.",
        "Note the wound. Move on, %t.",
        "%t. The fight is not lost.",
        "%t. I am reaching my limit. I am not there.",
        "%t. Composure. Always composure.",
        "%t. This body has been asked for more before.",
        "Keep your positions, %t.",
        "%t. The situation is deteriorating. Not irrecoverably.",
        "%t. I will hold as long as required.",
        "%t. Discipline is what remains when strength does not.",
        "%t. Wounded. Report acknowledged. Continue.",
        "Stay focused, %t.",
        "%t. I am still of use.",
        "Do not mistake damage for defeat, %t.",
        "%t. This is what training is for.",
        "%t. I have measured this. I can continue.",
        "%t. The end is not here yet.",
        "/em recites something under his breath, steadying",
        "Hold the line. I am holding mine, %t.",
        "%t. A moment. Then we continue.",
        "%t. Severe, but not final.",
        "%t. I will finish what I began.",
        "%t. Nothing has changed. Only my margin.",
        "%t. Proceed as planned.",
        "%t. The work continues while I do.",
        "Keep your discipline. I will keep mine, %t.",
        "%t. Wounds are expected. Panic is not.",
        "%t. Still able. Still willing.",
        "%t. The Shadow steadies what the flesh cannot.",
        "%t. This will not decide the outcome.",
        "%t. I remain in the fight.",
        "%t. One breath at a time. Even without breath.",
        "Do not look at me. Watch the flank, %t.",
        "%t. Bearing up.",
        "%t. The pain is noted and set aside.",
        "%t. I have not yielded. I will not.",
        "Continue. I am behind you, %t.",
        "%t. This is manageable.",
        "Compose yourself, %t. I have.",
        "%t. The body is a tool. It is chipped, not broken.",
        "Report when you can. I am busy, %t.",
        "%t. There is still a plan. Follow it.",
        "%t. I will endure this.",
        "%t. Concentration is all that is required now.",
        "%t. Severe damage. Position held.",
        "/em straightens with visible effort",
        "%t. Enough. Back to work.",
        "%t. The margin is thin. It is still a margin.",
        "%t. Steady hands. That is what matters.",
        "%t. I have accounted for this.",
        "%t. We continue.",
        "Do not waste healing on me yet, %t.",
        "%t. Bleeding is not dying.",
        "%t. The fight has my full attention.",
        "Hold. Hold. Hold, %t.",
        "%t. This is the hard part. It passes.",
        "%t. I know exactly how much I have left.",
        "%t. Nothing changes. Continue.",
        "%t. Injury acknowledged. Proceeding.",
        "%t. The line holds while I stand in it.",
        "%t. Focus on the target, not on me.",
        "%t. I have been here before. It ended well enough.",
        "%t. Discipline. Now more than ever.",
        "%t. Still capable.",
        "%t. The situation is grave. It is not lost.",
        "Steady, all of you, %t.",
        "%t. I will see this through.",
        "%t. Continue the work.",
    },

    ["REACT:DEATH"] = {
        "%t. I have fallen. Continue without me.",
        "Hold the line, %t.",
        "%t. Finish what we started.",
        "/em falls silently, hands still folded",
        "Do not retrieve the body. Win first, %t.",
        "%t. The work continues. See that it does.",
        "%t. I am down. Adjust.",
        "%t. Report it plainly. No embellishment.",
        "Take the position. That was the objective, %t.",
        "%t. This changes the plan, not the goal.",
        "Do not mourn. Not yet, %t.",
        "%t. I regret only the unfinished work.",
        "%t. The Dark Lady's business, not mine.",
        "%t. Carry on. That is an order.",
        "My part is done. Yours is not, %t.",
        "Fall back if you must. Do not scatter, %t.",
        "%t. I go where I have been before.",
        "Note the time and the cause, %t.",
        "Steady, all of you, %t.",
        "%t. This was a calculated risk.",
        "%t. Someone take the flank.",
        "%t. I accept this outcome.",
        "%t. The objective stands.",
        "Do not follow me down, %t.",
        "%t. See that it was not wasted.",
        "%t. There is no more I can do from here.",
        "Hold. Hold without me, %t.",
        "%t. Remember the name for the report.",
        "%t. My concentration failed before my will did.",
        "%t. Finish it properly.",
        "%t. A clean death. That is all one asks.",
        "%t. The line must hold.",
        "%t. Tell them I was in position.",
        "%t. I have no last requests.",
        "%t. Continue the advance.",
        "%t. This is not the end of the matter.",
        "Attend to the living, %t.",
        "%t. The dark is familiar. Do not worry.",
        "Take what I carried. Use it, %t.",
        "%t. I fell facing the enemy.",
        "Do your duty. I did mine, %t.",
        "%t. Nothing here is unexpected.",
        "%t. There is no shame in this.",
        "%t. Regroup. Immediately.",
        "%t. See it through.",
        "%t. The plan survives me.",
        "%t. I will return. Do not wait.",
        "%t. Cover the retreat if there is one.",
        "%t. My work is recorded. That is enough.",
        "/em closes his eyes with something like discipline",
        "Keep your formation, %t.",
        "%t. This was always possible.",
        "Do not let it turn, %t.",
        "%t. The mission first. Always.",
        "%t. I go quietly.",
        "%t. Report to the Apothecarium.",
        "Say nothing to the recruits, %t.",
        "%t. This is a setback. Nothing more.",
        "Stand your ground, %t.",
        "%t. I have done what was required.",
        "Do not lose the position over a corpse, %t.",
        "%t. The Forsaken do not stay down. Neither will I.",
        "%t. Continue.",
        "%t. There is more at stake than me.",
        "%t. Finish the fight.",
        "%t. It was well fought on both sides.",
        "%t. I fall. The work does not.",
        "Attend to the wounded first, %t.",
        "%t. This will be brief.",
        "Keep the discipline, %t.",
        "%t did what was necessary. So did I.",
        "%t. No last words are needed.",
        "%t. The dark is patient. So am I.",
        "%t. See that the others get out.",
        "%t. I have been ready for this since Lordaeron.",
        "Take the ground, %t.",
        "Hold what we have, %t.",
        "%t. There is no confusion here. Only an ending.",
        "Do not falter now, %t.",
        "%t. I have measured this risk and accepted it.",
        "%t. Carry on properly.",
        "%t. The Shadow will return me. Wait for it.",
        "%t. Steady. This is only a pause.",
        "Do not let my fall cost you yours, %t.",
        "%t. I am finished for the moment.",
        "%t. See to the objective.",
        "%t. A soldier's end. Acceptable.",
        "%t. Nothing left to say.",
        "%t. Mark the position.",
        "The rest is yours, %t.",
        "Hold fast, %t.",
        "%t. I did not waver.",
        "%t. This was not carelessness. It was arithmetic.",
        "Do the work, %t.",
        "%t. Continue as planned.",
        "%t. There will be time to account for this later.",
        "My hands are still. Yours are not, %t.",
        "%t. Finish it.",
        "%t. That is all.",
        "%t. The objective outlives me. See to it.",
    },

    ["REACT:RESURRECT"] = {
        "I am back. Report.",
        "Status.",
        "Where do you need me, %t?",
        "/em rises and immediately checks the field",
        "Resume positions.",
        "How long was I down?",
        "Back in the line.",
        "Give me the situation.",
        "Ready. Continue.",
        "That cost us time. Let us make it up.",
        "I am functional. Proceed.",
        "The objective. Where does it stand?",
        "Back on my feet. Back to work.",
        "Casualties?",
        "Nothing broken that matters.",
        "Understood. Continuing.",
        "Return to formation.",
        "I have lost nothing but minutes.",
        "Assess and advance.",
        "The Dark Lady returns what she needs.",
        "Thank you. Now, the fight, %t.",
        "Restored. Proceed.",
        "I am fit for duty.",
        "Let us not repeat that.",
        "Report as you go, %t.",
        "Ready when you are.",
        "I have my bearings.",
        "The plan stands?",
        "Back. Continue the advance.",
        "/em straightens his robes and takes up position",
        "No time lost that cannot be recovered.",
        "I am whole enough.",
        "Point me at the objective.",
        "Where is %t?",
        "Standing. Working.",
        "Give me a moment to steady, then continue.",
        "That was a lapse. It will not recur.",
        "Back at my post.",
        "Situation unchanged? Good.",
        "Continue as before.",
        "The work resumes.",
        "I am ready.",
        "Nothing to discuss. Move.",
        "Recovered. Proceeding.",
        "What did I miss?",
        "Very well. Back to it.",
        "The line held. Good.",
        "I am accounted for.",
        "Resume.",
        "Fit and in position.",
        "Do not lose momentum on my account.",
        "Back where I belong.",
        "Understood. Advancing.",
        "Reassembled and ready.",
        "Give me the count.",
        "I have work to finish.",
        "Steady. We continue.",
        "Nothing has changed but the delay.",
        "Back in the fight.",
        "Report when convenient.",
        "The objective still stands.",
        "I am restored. Barely, but restored.",
        "Take your positions.",
        "Ready to proceed.",
        "That was survivable. Evidently.",
        "Back to discipline.",
        "The Shadow returns me to duty.",
        "I stand ready.",
        "Continue where we left off.",
        "Nothing further. Move.",
        "Present and functional.",
        "Let us finish this properly.",
        "Position?",
        "Very well. Onward.",
        "Rested, in a manner of speaking.",
        "The work is unchanged.",
        "Standing by.",
        "I am able. Proceed.",
        "Return to the plan.",
        "Understood. In position.",
        "Back, and no worse.",
        "There is still time.",
        "Continue the operation.",
        "I am fit to continue.",
        "Report and advance.",
        "Recovered. What is required?",
        "Back to the line.",
        "Give the order.",
        "I have returned. Do not dwell on it.",
        "Ready and steady.",
        "The matter is unfinished. So am I.",
        "Resume the advance.",
        "In position. Continue.",
        "That delay is accounted for.",
        "I am here. Proceed.",
        "Nothing to report. Carry on.",
        "Whole enough to work.",
        "Standing again. Good.",
        "Back in the order of battle.",
        "Continue.",
    },

    ["REACT:KILLINGBLOW"] = {
        "%t. Target down.",
        "%t. That one is finished.",
        "%t. Confirmed.",
        "%t. Next.",
        "%t is down.",
        "/em lowers his hand and looks for the next threat",
        "%t. One less.",
        "%t. Cleanly done.",
        "Rest. It is over for you, %t.",
        "%t. Objective progressing.",
        "%t. That was necessary.",
        "Move up, %t.",
        "%t. The threat is ended.",
        "Down. Watch the flank, %t.",
        "%t. Finished. Reposition.",
        "%t. Efficient enough.",
        "%t. Report: one enemy neutralised.",
        "%t. Continue the advance.",
        "%t. That is settled.",
        "Do not linger over the body, %t.",
        "%t. Another dealt with.",
        "%t. Clear.",
        "%t. Confirm the kill and move.",
        "%t. The fight narrows.",
        "%t. One down. Maintain formation.",
        "%t. Enemy down. Keep watch.",
        "%t. There is nothing more from that one.",
        "%t. Handled.",
        "%t. Proceed.",
        "The Light take you. Or the dark. Whichever comes, %t.",
        "%t. Ended cleanly.",
        "%t. That is one fewer problem.",
        "Down. Continue, %t.",
        "%t. Objective advanced.",
        "%t. No further threat from that quarter.",
        "%t. Neutralised.",
        "Move on. Quickly, %t.",
        "%t. The matter is closed.",
        "%t. That will do.",
        "%t. Nothing wasted.",
        "%t. One more accounted for.",
        "%t. Steady. Next target.",
        "Down and confirmed, %t.",
        "Keep the pressure on, %t.",
        "%t. That was correctly done.",
        "%t. Clear here. Where next?",
        "%t. Enemy neutralised. Advancing.",
        "%t. The count improves.",
        "Rest, %t. It is finished.",
        "%t. Nothing personal was involved.",
        "%t. Dealt with.",
        "%t. Threat removed.",
        "%t. Onward.",
        "%t. The line advances.",
        "%t. Handled properly.",
        "%t. That is how it is done.",
        "%t. No mercy required. None given.",
        "%t. Report it and move.",
        "%t. Efficient. Continue.",
        "%t. One target eliminated.",
        "%t. It is over for them.",
        "%t. Steady progress.",
        "%t. The field narrows.",
        "Down. Reform, %t.",
        "%t. That concludes that.",
        "%t. Nothing further needed.",
        "%t. Advance.",
        "%t. The dead are not my concern now.",
        "%t. Cleanly ended.",
        "Move. There are others, %t.",
        "%t. Objective clear here.",
        "%t. Confirmed down.",
        "%t. Good. Continue.",
        "%t. That threat is closed.",
        "%t. No further action required.",
        "Keep formation. Keep moving, %t.",
        "%t. Neatly finished.",
        "%t. One less blade against us.",
        "%t. Understood. Next.",
        "%t. The work continues.",
        "Down. Hold position, %t.",
        "%t. Ended.",
        "%t. Proceed to the next.",
        "%t. That was required. Nothing more.",
        "%t. Clear and advancing.",
        "%t. Duty discharged.",
        "%t. The enemy is one fewer.",
        "%t. Steady on. Next.",
        "%t. Finished properly.",
        "%t. Confirm and continue.",
        "%t. That is settled cleanly.",
        "Down. Watch behind, %t.",
        "%t. No further threat.",
        "Move up and hold, %t.",
        "%t. Correctly handled.",
        "%t. One target down. Continue.",
        "%t. The advance continues.",
        "%t. It is done.",
        "%t. Threat ended. Maintain the advance.",
        "%t. Confirmed down. Eyes forward.",
    },

    ["REACT:COMBATSTART"] = {
        "%t. Positions.",
        "%t. Engaging.",
        "%t. Contact.",
        "%t. Form up.",
        "Hostiles. Take your places, %t.",
        "/em raises both hands and begins the working",
        "%t. Steady. Here they come.",
        "Mark your targets, %t.",
        "%t. This is what we prepared for.",
        "Hold the line, %t.",
        "%t. Engage on my mark.",
        "Discipline, all of you, %t.",
        "%t. Enemy contact.",
        "Watch the flanks, %t.",
        "Ready, %t.",
        "Do not break formation, %t.",
        "%t. You have chosen this.",
        "Take them carefully, %t.",
        "%t. The Shadow attends. Begin.",
        "%t. Focus.",
        "%t. Weapons ready.",
        "%t. Advance when ready.",
        "Stay together, %t.",
        "%t. This will be brief if we do it correctly.",
        "Assess before you strike, %t.",
        "%t. No wasted effort.",
        "%t. I am in position.",
        "%t. Begin.",
        "%t. Steady now.",
        "Hold until I say, %t.",
        "%t. Enemy in range.",
        "Keep your discipline, %t.",
        "%t. This is not a skirmish. Treat it seriously.",
        "%t. Confirm targets.",
        "Move as one, %t.",
        "%t. The work begins.",
        "Ready yourselves, %t.",
        "%t. I will hold the rear.",
        "Count them before you commit, %t.",
        "%t. No heroics.",
        "Take the ground carefully, %t.",
        "%t. Engage.",
        "Watch each other, %t.",
        "%t. This ends one way. Ensure it is ours.",
        "%t. Steady. Together.",
        "%t. Contact left.",
        "Do this properly, %t.",
        "%t. Precision, not haste.",
        "%t. I have the flank.",
        "Prepare yourselves, %t.",
        "%t. There is no room for error here.",
        "%t. Focus on the objective.",
        "%t. Advance.",
        "Hold your positions until the moment, %t.",
        "%t. This is the work. Do it well.",
        "Ready. Steady, %t.",
        "%t. Enemy engaged.",
        "Mind your footing, %t.",
        "Take them in order, %t.",
        "%t. No unnecessary risks.",
        "%t. Begin the advance.",
        "%t. I am ready.",
        "%t. Mark and hold.",
        "%t. Discipline wins this.",
        "%t. Contact confirmed.",
        "Keep to the plan, %t.",
        "%t. We fight properly or not at all.",
        "%t. Engage carefully.",
        "%t. Steady hands.",
        "Watch the line, %t.",
        "%t. Now. Together.",
        "%t. This requires attention.",
        "%t. No mistakes.",
        "%t. Hostile forces. Prepare.",
        "Take position and hold, %t.",
        "%t. The plan stands. Execute it.",
        "Ready the working, %t.",
        "%t. Contact. Respond.",
        "%t. In position.",
        "%t. Advance steadily.",
        "%t. This will be decided by discipline.",
        "Hold formation, %t.",
        "%t. Enemy sighted. Engage.",
        "Do not overextend, %t.",
        "Take it seriously, %t.",
        "%t. The Dark Lady's work begins.",
        "Ready. Begin, %t.",
        "%t. Steady the line.",
        "%t. We start now.",
        "Keep your eyes forward, %t.",
        "%t. Precision from the start.",
        "%t. Contact. All positions.",
        "Move, %t.",
        "%t. This is a serious matter.",
        "Prepare and hold, %t.",
        "Attend to your own line, %t.",
        "%t. Begin the work.",
        "%t. Engaging now.",
        "Hold. Then strike, %t.",
        "%t. Everyone to their assigned position.",
    },

    ["REACT:COMBATEND"] = {
        "Clear.",
        "Field secure.",
        "Report.",
        "Casualties?",
        "Reform.",
        "/em surveys the field and begins counting",
        "That is concluded.",
        "Stand down. Stay alert.",
        "Check the wounded.",
        "Position held.",
        "Objective complete.",
        "Regroup.",
        "Good discipline. All of you, %t.",
        "The engagement is over.",
        "Account for everyone.",
        "Secure the area.",
        "That went as planned.",
        "Tend to the injured first.",
        "Weapons down. Eyes up.",
        "No further contact.",
        "We hold the ground.",
        "Steady. It may not be finished.",
        "Report when you are able, %t.",
        "Take stock.",
        "The line held.",
        "That is done properly.",
        "Rest briefly. Then move.",
        "All clear here.",
        "Maintain watch.",
        "Efficiently handled.",
        "Nothing further.",
        "Reassemble.",
        "The objective stands secured.",
        "Recover what is useful.",
        "Do not scatter.",
        "Losses?",
        "That concludes the engagement.",
        "Hold this position.",
        "Well executed.",
        "Prepare to move.",
        "The threat is ended.",
        "Attend to yourselves.",
        "Watch the approaches.",
        "That was necessary work.",
        "Status of the wounded?",
        "Stand ready. We continue shortly.",
        "Field is ours.",
        "Nothing more to be done here.",
        "Sound off.",
        "That was correctly handled.",
        "Take a moment. Only a moment.",
        "Reform the line.",
        "The area is secure.",
        "Discipline held. Good.",
        "Report and rest.",
        "We move in five.",
        "No pursuit.",
        "The engagement is closed.",
        "Everyone accounted for?",
        "Steady. Stay ready.",
        "That is one objective met.",
        "Clean up and move on.",
        "Hold here.",
        "Good work. Stay sharp.",
        "The dead can wait. Check the living.",
        "Nothing followed us. Good.",
        "Secure and continue.",
        "That went acceptably.",
        "Await orders.",
        "The position is held.",
        "Assess damage.",
        "Prepare for the next.",
        "Nothing more required here.",
        "Concluded.",
        "Stand easy. Briefly.",
        "Check your gear.",
        "That is settled.",
        "We continue when ready.",
        "Field clear. Maintain formation.",
        "Report to me when you have counted.",
        "That was properly done.",
        "Recover and reform.",
        "Silence. Listen for more.",
        "Nothing further approaching.",
        "The work here is finished.",
        "Regroup and rest.",
        "Hold the ground we took.",
        "Acceptable outcome.",
        "Everyone upright? Good.",
        "Move out when ready.",
        "That is concluded cleanly.",
        "Stay in formation.",
        "The matter is closed.",
        "Prepare to advance.",
        "Good. Now the next task.",
        "Secure. Continue.",
        "Steady. We are not finished for the day.",
        "That will do. Move.",
        "Hold position until I give the word.",
        "Log the engagement. We move at my order.",
    },

    ["REACT:INTERRUPTED"] = {
        "%t. The working is broken. Give me a moment.",
        "%t. Cover me. I will begin again.",
        "%t. Interrupted. Adjusting.",
        "%t. Noted. Continuing by other means.",
        "%t. That was well timed.",
        "/em takes a breath and starts the words again",
        "%t. Silence me and I will use my hands.",
        "%t. Delay only.",
        "%t. Understood. Alternative approach.",
        "%t. I require a moment of quiet.",
        "%t. That will not work twice.",
        "%t. Adjusting. Hold the line.",
        "%t. The words are broken. The intent is not.",
        "Someone deal with %t.",
        "%t. Recovering. Continue without me.",
        "That was competent of you, %t.",
        "%t. Interrupted. Not stopped.",
        "Give me space to work, %t.",
        "%t. The Shadow does not require permission.",
        "%t. Very well. Directly, then.",
        "Note that tactic. It will be used again, %t.",
        "%t. Cover the flank while I recover.",
        "%t. That cost us a moment. Nothing more.",
        "%t. Regaining focus.",
        "%t. Concentration broken. Reforming it.",
        "%t. A competent interruption. Rare.",
        "%t. Continue. I will catch up.",
        "%t. That changes nothing of substance.",
        "%t. Adjust and continue.",
        "%t. Interrupt me again and I will change my approach.",
        "%t. Understood. Proceeding differently.",
        "Hold them off. One moment, %t.",
        "%t. The casting failed. The plan has not.",
        "%t. Recovering concentration.",
        "%t. That was the correct move on their part.",
        "%t. Very well. We do this the slower way.",
        "Do not let them do that again, %t.",
        "%t. Broken. Beginning again.",
        "%t. I need three seconds.",
        "%t. Noted and adapting.",
        "Watch for the interrupt. It is deliberate, %t.",
        "%t. They know what they are doing.",
        "%t. Continue the pressure while I recover.",
        "%t. That was skill, not luck.",
        "%t. Adjusting my approach.",
        "%t. The line must hold while I reset.",
        "%t. Interrupted. Compensating.",
        "Give me room, %t.",
        "%t. That was effective. It will not remain so.",
        "%t. Recovering. Maintain position.",
        "%t. Focus lost. Focus regained.",
        "%t. We adapt. That is all.",
        "Take note of that timing, %t.",
        "%t. A moment. Then I resume.",
        "%t. Nothing lost but tempo.",
        "That was well judged, %t.",
        "%t. Beginning again.",
        "%t. Silence is temporary.",
        "%t. Adjusting to their tactics.",
        "%t. The working is delayed, not cancelled.",
        "Hold. I am reforming it, %t.",
        "%t. That interruption was expected.",
        "%t. Continue. I am nearly back.",
        "%t. Countered. Adapting.",
        "%t. One moment of quiet is all I need.",
        "%t. That was proper technique.",
        "%t. Recovering now.",
        "Do not let that repeat, %t.",
        "%t. Interrupted cleanly. Credit where due.",
        "%t. Resuming shortly.",
        "%t. The intent survives the interruption.",
        "%t. Very well. Plan two.",
        "%t. Concentration is a discipline. I have it back.",
        "Hold them, %t.",
        "%t. That bought them seconds. No more.",
        "%t. Adjusting. Stand ready.",
        "%t. Understood. Continuing.",
        "%t. The Shadow finds another route.",
        "Give me the space and it is finished, %t.",
        "%t. That was their best moment.",
        "%t. Reforming the working.",
        "%t. Nothing decisive. Continue.",
        "%t. I have accounted for this.",
        "Note it and move on, %t.",
        "%t. Broken cleanly. Beginning again.",
        "Interrupt all you like. I have time, %t.",
        "%t. Adapting.",
        "%t. That is one tactic identified.",
        "%t. Recovering. Watch the flank.",
        "%t. The delay is acceptable.",
        "%t. Silence me and the plan proceeds anyway.",
        "%t. One moment.",
        "%t. Effective, briefly.",
        "%t. Continuing by other means.",
        "%t. That will not decide this.",
        "%t. Reset and resume.",
        "%t. Understood. Adjusting now.",
        "%t. The work resumes.",
        "%t. Beginning again. Hold position.",
        "%t. Cover the gap. I resume in a moment.",
    },
}
