-- RPVox -- Warrior-Barbarian class pack
--
-- Voice: song-lyric puns. Every line bends a well-known rock, hip hop or
-- R&B hook into the spell being cast. Kept in the addon rather than in saved
-- variables so it survives reinstalls and can live in version control.

RPVox_CLASSES = RPVox_CLASSES or {}

RPVox_CLASSES.WARRIOR_BARBARIAN = {
    name = "Warrior-Barbarian",
    spells = {
        { spell = "Charge",                    icon = "Interface\\Icons\\Ability_Warrior_Charge",              chance = 10 },
        { spell = "Intercept",                 icon = "Interface\\Icons\\Ability_Rogue_Sprint",                chance = 10 },
        { spell = "Heroic Strike",             icon = "Interface\\Icons\\Ability_Rogue_Ambush",                chance = 10 },
        { spell = "Cleave",                    icon = "Interface\\Icons\\Ability_Warrior_Cleave",              chance = 10 },
        { spell = "Slam",                      icon = "Interface\\Icons\\Ability_Warrior_DecisiveStrike",      chance = 10 },
        { spell = "Execute",                   icon = "Interface\\Icons\\INV_Sword_48",                        chance = 10 },
        { spell = "Overpower",                 icon = "Interface\\Icons\\Ability_MeleeDamage",                 chance = 10 },
        { spell = "Revenge",                   icon = "Interface\\Icons\\Ability_Warrior_Revenge",             chance = 10 },
        { spell = "Rend",                      icon = "Interface\\Icons\\Ability_Gouge",                       chance = 10 },
        { spell = "Hamstring",                 icon = "Interface\\Icons\\Ability_ShockWave",                   chance = 10 },
        { spell = "Thunder Clap",              icon = "Interface\\Icons\\Spell_Nature_ThunderClap",            chance = 10 },
        { spell = "Whirlwind",                 icon = "Interface\\Icons\\Ability_Whirlwind",                   chance = 10 },
        { spell = "Sunder Armor",              icon = "Interface\\Icons\\Ability_Warrior_Sunder",              chance = 10 },
        { spell = "Devastate",                 icon = "Interface\\Icons\\INV_Sword_11",                        chance = 10 },
        { spell = "Mortal Strike",             icon = "Interface\\Icons\\Ability_Warrior_SavageBlow",          chance = 10 },
        { spell = "Bloodthirst",               icon = "Interface\\Icons\\Spell_Nature_BloodLust",              chance = 10 },
        { spell = "Shield Slam",               icon = "Interface\\Icons\\Ability_Warrior_ShieldBash",          chance = 10 },
        { spell = "Rampage",                   icon = "Interface\\Icons\\Ability_Warrior_Rampage",             chance = 10 },
        { spell = "Concussion Blow",           icon = "Interface\\Icons\\Ability_ThunderBolt",                 chance = 10 },
        { spell = "Sweeping Strikes",          icon = "Interface\\Icons\\Ability_Rogue_SliceDice",             chance = 10 },
        { spell = "Victory Rush",              icon = "Interface\\Icons\\Ability_Warrior_DevastatingBlow",     chance = 10 },
        { spell = "Battle Stance",             icon = "Interface\\Icons\\Ability_Warrior_OffensiveStance",     chance = 10 },
        { spell = "Defensive Stance",          icon = "Interface\\Icons\\Ability_Warrior_DefensiveStance",     chance = 10 },
        { spell = "Berserker Stance",          icon = "Interface\\Icons\\Ability_Racial_Avatar",               chance = 10 },
        { spell = "Battle Shout",              icon = "Interface\\Icons\\Ability_Warrior_BattleShout",         chance = 10 },
        { spell = "Commanding Shout",          icon = "Interface\\Icons\\Ability_Warrior_RallyingCry",         chance = 10 },
        { spell = "Demoralizing Shout",        icon = "Interface\\Icons\\Ability_Warrior_WarCry",              chance = 10 },
        { spell = "Intimidating Shout",        icon = "Interface\\Icons\\Ability_GolemThunderClap",            chance = 10 },
        { spell = "Challenging Shout",         icon = "Interface\\Icons\\Ability_BullRush",                    chance = 10 },
        { spell = "Taunt",                     icon = "Interface\\Icons\\Spell_Nature_Reincarnation",          chance = 10 },
        { spell = "Mocking Blow",              icon = "Interface\\Icons\\Ability_Warrior_PunishingBlow",       chance = 10 },
        { spell = "Piercing Howl",             icon = "Interface\\Icons\\Ability_GolemThunderClap",            chance = 10 },
        { spell = "Disarm",                    icon = "Interface\\Icons\\Ability_Warrior_Disarm",              chance = 10 },
        { spell = "Pummel",                    icon = "Interface\\Icons\\INV_Gauntlets_04",                    chance = 10 },
        { spell = "Shield Bash",               icon = "Interface\\Icons\\Ability_Warrior_ShieldBash",          chance = 10 },
        { spell = "Spell Reflection",          icon = "Interface\\Icons\\Ability_Warrior_ShieldReflection",    chance = 10 },
        { spell = "Bloodrage",                 icon = "Interface\\Icons\\Ability_Racial_BloodRage",            chance = 10 },
        { spell = "Berserker Rage",            icon = "Interface\\Icons\\Spell_Nature_AncestralGuardian",      chance = 10 },
        { spell = "Death Wish",                icon = "Interface\\Icons\\Spell_Shadow_DeathPact",              chance = 10 },
        { spell = "Recklessness",              icon = "Interface\\Icons\\Ability_CriticalStrike",              chance = 10 },
        { spell = "Retaliation",               icon = "Interface\\Icons\\Ability_Warrior_Challange",           chance = 10 },
        { spell = "Shield Wall",               icon = "Interface\\Icons\\Ability_Warrior_ShieldWall",          chance = 10 },
        { spell = "Shield Block",              icon = "Interface\\Icons\\Ability_Defend",                      chance = 10 },
        { spell = "Last Stand",                icon = "Interface\\Icons\\Spell_Holy_AshesToAshes",             chance = 10 },
        { spell = "Enraged Regeneration",      icon = "Interface\\Icons\\Ability_Warrior_FocusedRage",         chance = 10 },
        { spell = "Intervene",                 icon = "Interface\\Icons\\Ability_Warrior_VictoryRush",         chance = 10 },
        { spell = "Throw",                     icon = "Interface\\Icons\\Ability_Throw",                       chance = 10 },
        { spell = "Shoot",                     icon = "Interface\\Icons\\Ability_Marksmanship",                chance = 10 },
        { spell = "Blood Fury",                icon = "Interface\\Icons\\Racial_Orc_BerserkerStrength",        chance = 10 },
        { spell = "Berserking",                icon = "Interface\\Icons\\Racial_Troll_Berserk",                chance = 10 },
        { spell = "War Stomp",                 icon = "Interface\\Icons\\Ability_WarStomp",                    chance = 10 },
        { spell = "Stoneform",                 icon = "Interface\\Icons\\Spell_Shadow_UnholyStrength",         chance = 10 },
        { spell = "Will of the Forsaken",      icon = "Interface\\Icons\\Spell_Shadow_RaiseDead",              chance = 10 },
        { spell = "Arcane Torrent",            icon = "Interface\\Icons\\Spell_Shadow_Teleport",               chance = 10 },
    },
    lines = {

        ["MELEE"] = {
            "Simple vork. Honest vork.",
            "%s hits da ting. Da ting says ow.",
            "SMASH!",
            "No spells. Only ahms.",
            "Vy talk ven you can do dis?",
            "Da axe goes in. Dat is da vhole job.",
            "I am very good at one ting.",
            "Again. And again.",
            "My ahms do da tinking.",
            "You are softer dan da last one, %t.",
            "Dis is vat I vas made for.",
            "AGAIN!",
            "Hit. Hit. Hit again.",
            "Bonk.",
            "Nuting fancy. Everyting effective.",
        },

        ["REACT:LOWHEALTH"] = {
            "It's naht a tumah. It is a svord. It is definitely a svord.",
            "I am leaking.",
            "%s is still standing. Barely.",
            "HEALAH!",
            "Dat is a lot of my blood on da outside.",
            "I have had vorse. I tink. I forget.",
            "Still angry. Still going.",
            "Dis is fine. Dis is naht fine.",
            "Ow. Ow. Ow.",
            "Vy is everyting red.",
            "SOMEBODY DO SOMETING!",
            "Naht dead yet, %t.",
            "My legs feel strange.",
            "More anger. Anger is also medicine. Probably.",
            "Keep hitting. Hitting fixes it.",
        },

        ["REACT:DEATH"] = {
            "I'll be bahk.",
            "Oh.",
            "Dat is naht good.",
            "%s is sleeping now.",
            "I did naht see dat one coming.",
            "I should have used da shield.",
            "I did naht like da shield anyway.",
            "Vort it.",
            "Tell my axe I loved it.",
            "Who is hitting da floor? Oh. It is me.",
            "I vas vinning. I tink.",
            "CROM!",
            "Dis is embarrassing.",
            "Do naht loot me.",
            "Good fight. Bad ending.",
        },

        ["REACT:RESURRECT"] = {
            "I said I vould be bahk.",
            "I am bahk. Who did I miss?",
            "%s lives again.",
            "Good. More hitting.",
            "Tank you, magic person.",
            "Vere vas I. Yes. Angry.",
            "Dat vas a long nap.",
            "Nuting hurts. Everyting hurts.",
            "UP! FIGHT!",
            "I dreamed about hitting tings.",
            "Do naht tell anyone I fell ovah.",
            "Again. Let us go again.",
        },

        ["REACT:KILLINGBLOW"] = {
            "Hasta la vista, %t.",
            "You are terminated, %t.",
            "%s vins again.",
            "NEXT!",
            "Dat is vat happens.",
            "You should have been biggah, %t.",
            "Did everyone see dat?",
            "Dat is... many. I have done dis many times.",
            "Goodbye, %t.",
            "My axe is happy.",
            "Too easy.",
            "Who is next? Anyone? Please?",
            "I vill remembah you. No I vill naht.",
            "HA!",
            "One less ting.",
        },

        ["REACT:COMBATSTART"] = {
            "Vat is best in life? Dis. Dis is best.",
            "Finally.",
            "%s has been vaiting for dis.",
            "HERE VE GO!",
            "I have been so bored, %t.",
            "You look breakable.",
            "No talking. Fighting.",
            "I do naht know vy ve fight. I do naht care.",
            "Come on den, %t.",
            "Dis is my favourite part of da day.",
            "IT'S TIME!",
            "Good. Good.",
        },

        ["REACT:COMBATEND"] = {
            "Is dat all?",
            "More. I vant more.",
            "Dat vas fun.",
            "Are dere oders? Find oders.",
            "%s is still angry.",
            "Good vork today.",
            "Now vat. I only know one ting.",
            "My axe is sticky.",
            "Who vants food?",
            "Bored already.",
            "I did naht get to use all my buttons.",
            "Again? Please?",
        },

        ["REACT:INTERRUPTED"] = {
            "HEY! I VAS DOING DAT!",
            "Rude.",
            "%t made me stop. I do naht like %t.",
            "Dat vas my big sving.",
            "Now I am angrier. Good for me. Bad for you.",
            "Do naht do dat again, %t.",
            "I vas vinding up.",
            "You vill pay for dat.",
            "I vill do it again. Votch.",
            "Dat is cheating, %t.",
            "GRRR!",
            "My sving. My beautiful sving.",
        },

        ["REACT:LEVELUP"] = {
            "I am biggah.",
            "More muscle.",
            "%s grew.",
            "New tings to learn. New tings to hit.",
            "Strongah dan yesterday.",
            "I feel very good about myself.",
            "Biggah man. Same brain.",
            "More health to lose.",
            "UP GOES DA NUMBER!",
            "Good. Good.",
        },

        ["REACT:FALLING"] = {
            "AAAAAA!",
            "Da ground is coming.",
            "I did naht mean to do dis.",
            "%s is flying. Badly.",
            "Vy is down so fast?",
            "Dis is naht hitting. Dis is being hit.",
            "Who put da hole dere?",
            "I hate falling.",
            "Oof.",
            "Ow. Ow. Ground.",
        },

        ["REACT:DROWNING"] = {
            "Vater is bad.",
            "I cannot hit vater.",
            "%s is too heavy for dis.",
            "AIR!",
            "Da armour vas a mistake.",
            "Vich vay is up?",
            "I do naht like swimming.",
            "Glub.",
            "Dis is naht a good death.",
            "Help. Help.",
        },

        ["REACT:DURABILITY"] = {
            "My armour is broken.",
            "%s needs da hammah man.",
            "Pieces are falling off me.",
            "Dat vas expensive metal.",
            "I can see trough my own chestplate.",
            "Dis is vy I get hit so much.",
            "Repairs. Now.",
            "Clank. Dat is naht a good clank.",
            "I look like rubbish.",
            "Still fights, doh.",
        },

        ["IDLE:EAT"] = {
            "Meat.",
            "A big man needs big food.",
            "Chew. Chew. Chew.",
            "Dis is da second best ting.",
            "More, please.",
            "I do naht ask vat it is.",
        },

        ["IDLE:DRINK"] = {
            "Milk is for babies. Ven you grow up you drink from a biggah cup.",
            "Glug.",
            "Tirsty man.",
            "Dis is chust vater. Disappointing.",
            "Drink. Den hit tings.",
            "Aaah.",
        },

        ["IDLE:HEALTHSTONE"] = {
            "Hole closed. Good.",
            "A magic rock made me bettah.",
            "Bettah now.",
            "I do naht know how it vorks.",
            "More health. Bahk to vork.",
        },

        ["IDLE:MANAPOTION"] = {
            "Vy do I have dis.",
            "Da blue one does nuting for me.",
            "I drank it anyway.",
            "Dat vas naht for me. Too late.",
            "Tastes bad. Did nuting.",
        },

        ["IDLE:FISHING"] = {
            "Dis is very slow.",
            "Fish cannot be hit. Sadly.",
            "I am being patient. It is hard.",
            "Nuting is happening.",
            "Can I hit da vater?",
            "Still nuting.",
        },

        ["IDLE:MINING"] = {
            "Hit rock. Get metal. Simple.",
            "Dis is basically fighting.",
            "Da rock does naht fight bahk. Boring, but fine.",
            "My favourite job.",
            "SMASH DA ROCK!",
        },

        ["IDLE:HERBALISM"] = {
            "Small plant. Gentle hands.",
            "I am being very careful.",
            "Dis is naht hitting, but it is nice.",
            "Pretty. I like pretty.",
            "Oops. Broke it.",
        },

        ["IDLE:SKINNING"] = {
            "Sorry, animal.",
            "Da knife is small. I am naht good at small.",
            "Dis part is messy.",
            "I do naht enjoy dis.",
            "Da fur is varm, doh.",
        },

        ["IDLE:MOUNT"] = {
            "Big animal. Goes fast.",
            "Valking is slow. Dis is naht.",
            "Hello, horse. Ve go now.",
            "I am heavy. Sorry, horse.",
            "Fastah to da fighting.",
            "Good animal.",
            "Up ve go.",
        },

        ["IDLE:QUESTACCEPT"] = {
            "I vill hit it. Vatevah it is.",
            "Who do I hit?",
            "Yes. I did naht listen, but yes.",
            "Point at it. I do da rest.",
            "Sounds good. Vat vas it?",
            "Give me a direction.",
            "Consider it done.",
        },

        ["IDLE:QUEST"] = {
            "Done. It is finished.",
            "Vere is my gold?",
            "Dat vas easy.",
            "I did da ting.",
            "Pay da big man.",
            "Vat is next?",
        },

        ["IDLE:DISCOVERY"] = {
            "New place. New tings.",
            "Oooh.",
            "I have naht broken anyting here yet.",
            "Big. Very big.",
            "I like it here.",
            "Vat lives here? Can I fight it?",
        },

        ["IDLE:CRAFT:Alchemy"] = {
            "Mix da liquids. Carefully.",
            "I am naht good at dis.",
            "It vent green. Is dat right?",
            "Tiny bottles. Big hands.",
        },

        ["IDLE:CRAFT:Blacksmithing"] = {
            "Hitting metal vit a hammah. My favourite hobby.",
            "BANG! BANG!",
            "Dis is smashing, but useful.",
            "Now dat is a good svord.",
        },

        ["IDLE:CRAFT:Cooking"] = {
            "Fire plus meat equals food.",
            "I burned it. Still eating it.",
            "Cooking is easy. You chust heat it.",
            "Smells good. Mostly.",
        },

        ["IDLE:CRAFT:Enchanting"] = {
            "Magic on my axe. Good.",
            "I do naht understand. It glows, doh.",
            "A sparkly svord hits hardah? Fine.",
            "Magic is acceptable ven it is on my veapon.",
        },

        ["IDLE:CRAFT:Engineering"] = {
            "Dis vill explode. Dat is da point.",
            "Tiny parts. Big fingers.",
            "It blew up. As expected.",
            "I like da ones dat go bang.",
        },

        ["IDLE:CRAFT:First Aid"] = {
            "Cloth on hole. Done.",
            "I am naht a doctor. I am a cloth man.",
            "Vrap it tight. Very tight.",
            "Dat should hold. Probably.",
        },

        ["IDLE:CRAFT:Jewelcrafting"] = {
            "Small shiny rock.",
            "My hands are too big for dis.",
            "Pretty. I do naht know vy.",
            "Do naht smash da gem. Do naht smash da gem.",
        },

        ["IDLE:CRAFT:Leatherworking"] = {
            "Skin becomes armour. A good cycle.",
            "Sewing. Vit dese hands.",
            "Tank you again, animal.",
            "Tough leather for a tough man.",
        },

        ["IDLE:CRAFT:Tailoring"] = {
            "Tiny needle. Enormous man.",
            "I am making clothes. Do naht laugh.",
            "Ow. Da needle got me.",
            "It is naht pretty, but it is clothes.",
        },

        ["IDLE:CRAFT:Smelting"] = {
            "Rock goes in. Metal comes out.",
            "Big fire.",
            "I do naht know vy it vorks. It vorks.",
            "Hot. Very hot. Good.",
        },

        ["SPELL:Charge"] = {
            "GET TO DA CHOPPA!",
            "Dere is no choppa. Dere is only me, %t.",
            "I am coming ovah dere. Do naht go anywhere.",
            "%s does naht valk. %s arrives.",
            "You vant to talk? Ve can talk. I vill be closer.",
            "RUN!",
            "Distance is a problem I solve vit legs.",
            "I saw you from ovah dere, %t. Now I am here.",
            "No varning. Dat is da vhole idea.",
            "I did naht look both vays.",
            "Hello, %t. Surprise.",
            "Ground, meet feet. Feet, meet %t.",
        },

        ["SPELL:Intercept"] = {
            "You cannot run from me. I have already run.",
            "COME HERE!",
            "%s is fastah dan you tought.",
            "Going somewhere, %t?",
            "Dat vas a long vay. I did it anyway.",
            "Surprise. It is da big one.",
            "I do naht chase. I arrive.",
            "You had a head start. It did naht help.",
            "BOOM. Now I am here.",
            "Running avay only makes it interesting.",
            "Nowhere is far enough, %t.",
            "I am very fast for a heavy man.",
        },

        ["SPELL:Heroic Strike"] = {
            "Let off some steam, %t.",
            "Same sving. More of it.",
            "HIT HARDAH. DAT IS DA PLAN.",
            "%s saves da anger for dis one.",
            "Vy hit small ven you can hit big.",
            "Dat vas a good one. I felt it in my shouldahs.",
            "Heroic. It is in da name.",
            "I have one idea and it is excellent.",
            "You are going to remembah dat, %t.",
            "More force. Alvays more force.",
            "Dat is da vhole strategy. It vorks.",
            "OOF. Sorry. Naht sorry.",
        },

        ["SPELL:Cleave"] = {
            "Two of you. One sving. Efficient.",
            "Nobody is left out.",
            "BOTH OF YOU!",
            "%s does naht play favourites.",
            "You stood next to each oder. Dat vas da mistake.",
            "I am generous vit my violence.",
            "One ahm. Two problems. Solved.",
            "Group discount.",
            "Stand closer togeder. It helps me.",
            "Sideways. Dat is da trick.",
            "Sharing is important.",
            "Buy one, get one, %t.",
        },

        ["SPELL:Slam"] = {
            "Vait for it, %t.",
            "Dis one is slow. It is vort da vait.",
            "I take my time. You vill see vy.",
            "%s vinds up.",
            "Patience. Den da ceiling comes down.",
            "DOWN IT GOES!",
            "You can see it coming. It happens anyway.",
            "Slow is fine ven it is loud.",
            "Dat vas from da shouldahs.",
            "Big sving for a big problem.",
            "Some tings should naht be rushed.",
            "Dere. Dat is vat I vas vaiting for.",
        },

        ["SPELL:Execute"] = {
            "Consider dat finished, %t.",
            "Remembah ven I said I vould kill you last? I lied.",
            "You are terminated, %t.",
            "Hasta la vista, %t.",
            "NOW YOU ARE FINISHED!",
            "%s has been saving dis.",
            "All da anger. All at once.",
            "You vere almost dead. I do naht like almost.",
            "Nuting personal, %t. Everyting final.",
            "Dat is da last one you get.",
            "Low health makes me very happy.",
            "Goodnight, %t.",
        },

        ["SPELL:Overpower"] = {
            "You missed. Dat vas your one mistake.",
            "HA! Nuting but air, %t.",
            "Now it is my turn.",
            "%s noticed dat. %s notices everyting. Sometimes.",
            "You cannot block dis one. Sorry.",
            "Good dodge. Bad outcome.",
            "I SAW DAT!",
            "Try again, %t. I vill vait.",
            "Dat is vat dodging gets you.",
            "An opening. I take openings.",
            "You are off balance. I am naht.",
            "Tank you for missing.",
        },

        ["SPELL:Revenge"] = {
            "You hit me. Now I hit you. Dis is fair.",
            "DAT VAS A MISTAKE!",
            "%s does naht forget. Vell. %s forgets most tings. Naht dis.",
            "Block, den answer. Good system.",
            "Ow. Now you ow.",
            "I vas vaiting for you to do dat, %t.",
            "Revenge is a simple vord. I like simple vords.",
            "You should naht have touched me.",
            "My shield said no. My ahm says more.",
            "Tank you for hitting me, %t.",
            "Dis is da polite response.",
            "Everyting comes bahk around.",
        },

        ["SPELL:Rend"] = {
            "If it bleeds, I can kill it.",
            "Stick around, %t.",
            "Dat vill naht close on its own.",
            "%s makes da hole. Da hole does da rest.",
            "You are leaking, %t.",
            "BLEED!",
            "Slow hurt is still hurt.",
            "I am a patient man. Occasionally.",
            "Check bahk in a few seconds. Still bleeding.",
            "Red is coming out. Dat is da point.",
            "Drip. Drip.",
            "I do naht have to do anyting now. It vorks alone.",
        },

        ["SPELL:Hamstring"] = {
            "Stick around, %t.",
            "Legs. No more running.",
            "STAY!",
            "%s does naht enjoy chasing people.",
            "I vent low. It is naht honourable. It vorks.",
            "Vere are you going, %t? Nowhere.",
            "You valk now.",
            "Dat is a tendon. I tink. I do naht know da vords.",
            "Running is for latah. Dere is no latah.",
            "Limp for me, %t.",
            "I fixed your running problem.",
            "Slow legs. Slow %t.",
        },

        ["SPELL:Thunder Clap"] = {
            "Let off some steam. All of you.",
            "BOOM!",
            "I clap. It is naht applause.",
            "%s makes tunder vit his hands.",
            "Everyone slows down. You are velcome.",
            "Da ground is angry too now.",
            "EVERYBODY FEEL DAT!",
            "Dat is my favourite noise.",
            "All of you at once. It is only fair.",
            "My ears are ringing. Vort it.",
            "Shake. Shake.",
            "One clap, many problems.",
        },

        ["SPELL:Whirlwind"] = {
            "Come vit me if you vant to live. Everyone else, stay exactly dere.",
            "ROUND AND ROUND!",
            "I am a large circle of problems.",
            "%s spins very vell for his size.",
            "Do naht stand near me. Or do.",
            "Dizzy, but happy.",
            "I do naht know who I hit. All of dem.",
            "Dis is da best feeling dere is.",
            "VHEEE!",
            "Ahms out. Svord out. Go.",
            "Everyone in da circle. Dat is da rule.",
            "Again. Let us do it again.",
        },

        ["SPELL:Sunder Armor"] = {
            "Knock knock, %t. Dat is your armour leaving.",
            "One. Two. Tree. More. Many.",
            "Five times. I can count to five.",
            "%s is patient. %s stacks it up.",
            "Armour is annoying. I make less of it.",
            "You are getting softer, %t.",
            "DAT IS ANODER ONE!",
            "Metal first. Den you.",
            "Dis part is boring. My friends insist.",
            "Dent. Anoder dent.",
            "Soon dere vill be nuting left to knock off.",
            "Shiny shell. Naht for long.",
        },

        ["SPELL:Devastate"] = {
            "Two jobs, one sving. Dis is progress.",
            "I hit you and your armour at da same time.",
            "%s learned a new move. %s is proud.",
            "Vy do one ting ven you can do two.",
            "BREAK IT!",
            "Shield in one hand. Violence in da oder.",
            "More dents. Also more pain.",
            "Dis is da clever sunder.",
            "Your armour is bad now. So are you, %t.",
            "I like dis one bettah dan da old one.",
            "Again. And again. And again.",
            "Devastate. A big vord for a big hit.",
        },

        ["SPELL:Mortal Strike"] = {
            "Now da healing does naht vork so vell.",
            "Your healah cannot help you, %t.",
            "%s aims for da important part.",
            "Deep. Very deep.",
            "DIS ONE IS MINE!",
            "Mortal. Dat means dead soon.",
            "Dat vill naht close.",
            "Dis is da mean one. I like da mean one.",
            "Nuting gets fixed aftah dat, %t.",
            "Best sving I have.",
            "Ow for you. Good for me.",
            "Bad news for vhoever is keeping you alive.",
        },

        ["SPELL:Bloodthirst"] = {
            "If it bleeds, I get strongah.",
            "I am here for da blood, %t. Naht da conversation.",
            "MORE!",
            "%s drinks da fight.",
            "Your blood is now my health. Dat is da deal.",
            "I do naht need a healah. I need more of you.",
            "Fast hit. No vaiting.",
            "Tirsty. Alvays tirsty.",
            "Hit, den feel bettah. Good system.",
            "Red is my favourite colour.",
            "Dis one feeds me.",
            "Do naht run out, %t.",
        },

        ["SPELL:Shield Slam"] = {
            "A shield is chust a square hammah.",
            "Who says shields are for hiding?",
            "BONK!",
            "%s hits vit da flat ting.",
            "Face, meet shield. Shield vins.",
            "Dis is vy I carry it.",
            "I use everyting as a veapon. Even da naht-veapons.",
            "You did naht expect da shield, %t.",
            "Heavy. Flat. Fast. Perfect.",
            "CLANG!",
            "Best possible use for it.",
            "Blocking is a side job.",
        },

        ["SPELL:Rampage"] = {
            "It builds. It keeps building.",
            "EVERYBODY GET ANGRY!",
            "%s is on a rampage. Da name is accurate.",
            "More anger means more hitting. Simple.",
            "Crit. Anoder one. Stack it up.",
            "Anger is a resource. I have plenty.",
            "My friends get angry too. Dat is nice.",
            "I do naht slow down.",
            "MAXIMUM!",
            "Nobody stops dis now.",
            "Up and up and up.",
            "Dis is vat I am for.",
        },

        ["SPELL:Concussion Blow"] = {
            "Head. I hit da head.",
            "Go to sleep, %t.",
            "%s hit da tinking part.",
            "BONK!",
            "No more toughts for you, %t.",
            "You are standing but naht really.",
            "I do naht know vat a concussion is. I know vat a blow is.",
            "Birds. You are seeing birds.",
            "Quiet now, %t.",
            "Da head is da softest part.",
            "Five seconds of peace for everyone.",
            "LIGHTS OUT!",
        },

        ["SPELL:Sweeping Strikes"] = {
            "One sving. Two people. Dat is mathematics.",
            "Every hit counts twice now.",
            "FREE HITS!",
            "%s gets bonus violence.",
            "I hit %t and somebody else. Naht sure who.",
            "Dis is a very good deal.",
            "Double. Everyting is double.",
            "I feel clever. It is a strange feeling.",
            "Sweeping. Like a broom, but vit a svord.",
            "More people means more value.",
            "Please stand in groups. It helps.",
            "Da next ten are special.",
        },

        ["SPELL:Victory Rush"] = {
            "Vinning is good for da health.",
            "I killed someting. Now I feel vonderful.",
            "%s vins. %s gets strongah. Dat is how bodies vork.",
            "NEXT!",
            "No healah needed. Only more of you, %t.",
            "Fresh. I am fresh again.",
            "Victory tastes like health.",
            "Dat one died so I could have a snack.",
            "Best feeling dere is. Let us do it again.",
            "Who is next? Anyone?",
            "Killing is medicine. I am fairly sure.",
            "I feel bettah already.",
        },

        ["SPELL:Battle Stance"] = {
            "Normal standing. It is fine.",
            "Dis is da middle one.",
            "%s stands like dis now.",
            "Naht too angry. Naht too safe.",
            "Boring stance. Useful stance.",
            "I change how I stand and it matters somehow.",
            "Feet go here. Dat is da vhole ting.",
            "Balanced. Unlike everyting else about me.",
            "I lose my anger doing dis. Rude.",
            "Ready. Normal ready.",
            "Standing is hardah dan it looks.",
            "Battle Stance. Because battle.",
        },

        ["SPELL:Defensive Stance"] = {
            "Dis is naht my vay.",
            "Stand still. Take da hit. It is boring.",
            "%s must be careful now. %s hates dis.",
            "Less smashing, more surviving. Bad trade.",
            "My friends insist.",
            "Dis is da sad stance.",
            "I am a vall now. Valls are boring.",
            "FINE!",
            "Hitting me vorks less vell. Still rude.",
            "I vill be patient. For one minute.",
            "Somebody has to do it.",
            "Take less. Give less. Vy.",
        },

        ["SPELL:Berserker Stance"] = {
            "Now. Now ve do it my vay.",
            "NO GUARD! ONLY SMASHING!",
            "%s does naht care about defence.",
            "Hit more. Get hit more. Vort it.",
            "Dis is da good one.",
            "I feel alive. Also very exposed.",
            "Safety is for latah.",
            "Danger is fine. Danger is good.",
            "Dis is how I vas born to stand.",
            "Best stance. No argument.",
            "Crit more. Who cares about armour.",
            "Finally.",
        },

        ["SPELL:Battle Shout"] = {
            "I am naht shouting. Dis is my normal voice.",
            "AAAAAAA!",
            "%s yells. Yelling is a buff.",
            "I do naht know vy dis vorks. It vorks.",
            "Everybody gets strongah. You are velcome.",
            "Shouting is my magic.",
            "Are you strongah? Yes. Because I made a noise.",
            "Remind me in two minutes. I vill forget.",
            "Noise. Free strength. Good system.",
            "My troat hurts. My friends are strong.",
            "CROM!",
            "Who needs a shout? Everybody needs a shout.",
        },

        ["SPELL:Commanding Shout"] = {
            "You are all biggah now. You are velcome.",
            "More blood in my friends.",
            "%s only knows two shouts. Dis is one of dem.",
            "MORE MEAT ON EVERYBODY!",
            "Dis shout makes you big, naht strong. Different shout.",
            "Hardah to kill now. All of you.",
            "Commanding. Dat means bossy. I am bossy.",
            "Yelling for health. It makes sense to me.",
            "Extra health for everyone.",
            "Big shout for big friends.",
            "I have exactly two ideas and dis is one.",
            "Dere. Now go and be difficult to kill.",
        },

        ["SPELL:Demoralizing Shout"] = {
            "You lack discipline, %t.",
            "I said a mean ting. Now you hit softer.",
            "%s hurt your feelings, %t.",
            "YOU ARE ALL BAD AT FIGHTING!",
            "Vords hurt. Dat is da entire spell.",
            "You are veak now because I said so.",
            "I am naht good at insults. It still vorks.",
            "Nobody believes in temselves anymore.",
            "Go home, %t. You are bad at dis.",
            "Dat is bullying. It is also tactics.",
            "You fight like a farmer, %t. A bad farmer.",
            "Everyone feel vorse. Immediately.",
        },

        ["SPELL:Intimidating Shout"] = {
            "GET TO DA CHOPPA!",
            "RUN!",
            "%s is very scary.",
            "Boo.",
            "Vy is everyone leaving? Oh. Me.",
            "Come bahk latah. Naht now. Latah.",
            "Dat vas my scary voice.",
            "Dey run in all directions. It is funny every time.",
            "AAAAAAAAAA!",
            "Sometimes I frighten myself.",
            "Go. Go on. Tink about it and return.",
            "You are all scared now. Correctly.",
        },

        ["SPELL:Challenging Shout"] = {
            "All of you. Come here.",
            "EVERYBODY FIGHT ME!",
            "%s vants all of da attention.",
            "Forget my friends. I am more interesting.",
            "I am da biggest problem in dis room.",
            "Dis is a bad idea. I am doing it.",
            "My friends are boring. Hit me instead.",
            "Line up. Dere is enough of me for everyone.",
            "COME ON DEN!",
            "A challenge. I do naht know vat I vin.",
            "Look at me. Only me.",
            "Every single one of you.",
        },

        ["SPELL:Taunt"] = {
            "You are looking at da vrong person, %t. I am right here.",
            "Hey. Look at me. I am da big one.",
            "%s is more annoying dan dey are.",
            "OVAH HERE!",
            "Stop looking at my friend.",
            "You vant to hit me. You do. Trust me.",
            "My friend is squishy. I am naht.",
            "Dat is right. Come to da big man.",
            "I am rude on purpose.",
            "It vorks every time. I am very annoying.",
            "OI!",
            "No. Me. Hit me, %t.",
        },

        ["SPELL:Mocking Blow"] = {
            "I hit you and I laughed. Both count.",
            "Your haircut is bad, %t.",
            "%s mocks you. Dat means laughing.",
            "Two tings at once. I am clever today.",
            "Bonk. Also, an insult.",
            "COME AND GET ME!",
            "Now you are angry. Good.",
            "I do naht know good insults. It still vorks.",
            "Dat vas mocking. I tink.",
            "A hit plus rudeness equals attention.",
            "Look at me. I did dat on purpose.",
            "You are going to vant to hit me now.",
        },

        ["SPELL:Piercing Howl"] = {
            "Chill out, %t.",
            "AWOOOO!",
            "%s howls like an angry dog.",
            "Everybody valks now.",
            "My voice hurts your legs somehow.",
            "Nobody runs avay from me.",
            "EVERYONE SLOW DOWN!",
            "Dat vas loud and also useful.",
            "I do naht understand vy it vorks.",
            "Loud noise. Slow legs. Magic.",
            "A howl is naht a vord. It is a noise.",
            "Take your time. You have no choice.",
        },

        ["SPELL:Disarm"] = {
            "I need your axe, your boots and your horse.",
            "Now you have no stick.",
            "%s took your toy avay.",
            "Vere is your svord, %t? On da ground.",
            "PICK IT UP DEN!",
            "Fight me vit your hands. Go on.",
            "You look silly now, %t.",
            "Dat vas easy. Too easy.",
            "I do naht need a veapon either. But I have one.",
            "Drop it. Good.",
            "Dis is my favourite mean trick.",
            "Empty hands. How does dat feel, %t?",
        },

        ["SPELL:Pummel"] = {
            "Shut up, %t.",
            "No spells. Only hitting.",
            "%s punches da vords out.",
            "STOP TALKING!",
            "I do naht like magic. So I hit it.",
            "Vat vere you saying, %t? Nuting now.",
            "Fist to da mouth. Very effective.",
            "Magic is cheating. Dis is fair.",
            "Casting time is ovah.",
            "I interrupt you. Vit my hand.",
            "Dat vas rude of you to cast.",
            "No more of dat.",
        },

        ["SPELL:Shield Bash"] = {
            "Da shield says be quiet.",
            "CLANG!",
            "%s uses da flat ting on your face.",
            "No vords. Only metal.",
            "Stop casting, %t.",
            "I hit you vit da boring side.",
            "Magic, interrupted by a large object.",
            "You vere saying someting, %t?",
            "Shield Bash. Simple name. Simple job.",
            "Dat is vat a shield is for. Also blocking.",
            "SHUT IT!",
            "Quiet.",
        },

        ["SPELL:Spell Reflection"] = {
            "Your spell. Your problem now, %t.",
            "No tank you. You can have it bahk.",
            "%s is naht smart. %s has a smart shield.",
            "HA!",
            "Dat must hurt, %t. It vas yours.",
            "I do naht know how dis vorks. It is funny.",
            "You hit yourself. I vatched.",
            "Return to sender. I heard someone say dat once.",
            "A shield is also a mirror. Apparently.",
            "Nice spell, %t. Enjoy it.",
            "BOUNCE!",
            "Everyting comes bahk around.",
        },

        ["SPELL:Bloodrage"] = {
            "Hurt myself. Get angry. Good trade.",
            "%s hits %s to get started.",
            "Ow. Vort it.",
            "I need anger. I take it from me.",
            "Dis is fine. Dis is normal.",
            "MORE!",
            "Blood makes rage. Rage makes everyting else.",
            "I do naht tink dis is healthy.",
            "Free anger. It only costs blood.",
            "Da healah vill be fine vit dis.",
            "Who needs health? I need anger.",
            "Owww. Right. Ready.",
        },

        ["SPELL:Berserker Rage"] = {
            "Let off some steam.",
            "RAAAAGE!",
            "%s is too angry to be afraid.",
            "Fear? Vat is fear. I forgot.",
            "Nobody can scare me now.",
            "I cannot feel anyting. Excellent.",
            "Try to frighten me. Go on.",
            "Anger is bettah dan tinking.",
            "My brain is off. Perfect.",
            "Dis is my natural state.",
            "CANNOT BE STOPPED!",
            "Cannot be scared. Can only continue.",
        },

        ["SPELL:Death Wish"] = {
            "DO IT. DO IT NOW!",
            "Maybe I die. Vort it.",
            "%s does naht care anymore.",
            "Dis is a bad idea. I love it.",
            "Death Vish. Da name is honest.",
            "More damage. Also more damage to me.",
            "I have made peace vit dis.",
            "Healah. Sorry in advance.",
            "Big risk. Big result.",
            "I do naht plan ahead.",
            "If I die, I die angry.",
            "Vort it. It is alvays vort it.",
        },

        ["SPELL:Recklessness"] = {
            "No tinking. Only hitting.",
            "VOTCH DIS!",
            "%s has no plan and no regrets.",
            "Every hit is a big hit now.",
            "Defence is for latah.",
            "Dese are da best fifteen seconds.",
            "I take double. I give much more.",
            "Reckless. Dat means no care.",
            "I am naht being careful, on purpose.",
            "Nuting can go vrong. Probably.",
            "CRIT! AGAIN!",
            "Maximum everyting.",
        },

        ["SPELL:Retaliation"] = {
            "Hit me. See vat happens.",
            "Everybody hit me at once. Please.",
            "%s hits bahk automatically now.",
            "I do naht even have to try.",
            "COME ON!",
            "You sving, I sving. Free for me.",
            "Touching me is now a mistake.",
            "I am spiky. Like an angry plant.",
            "More enemies means more free hits.",
            "Keep going. I like it.",
            "Dis is best ven dere are many of you.",
            "Retaliation. It means hitting bahk.",
        },

        ["SPELL:Shield Wall"] = {
            "I'll be bahk. I am staying here, but emotionally, I'll be bahk.",
            "Nuting hurts me now. It is still boring.",
            "%s is a vall. Valls are sad.",
            "Hit me all you vant, %t. I barely notice.",
            "Dis is naht smashing. I do naht enjoy it.",
            "I vill hide. For ten seconds.",
            "Everyting bounces off. Fine. Good.",
            "I only do dis ven frightened. I am naht frightened.",
            "BEHIND DA METAL!",
            "Can I go bahk to hitting now? No? Fine.",
            "Big metal. Behind it.",
            "Ten seconds of nuting. Den everyting.",
        },

        ["SPELL:Shield Block"] = {
            "Block first. Den answer.",
            "A shield is for hiding. I do naht like hiding.",
            "%s holds da shield up. Briefly.",
            "Nuting gets trough for a moment.",
            "Up goes da shield. Down comes da axe. Soon.",
            "Two blocks. Dat is all I get.",
            "COME ON DEN!",
            "Metal between me and you.",
            "Blocking is boring but useful.",
            "I am ready for you, %t.",
            "Dis is so I can hit bahk latah.",
            "Right. Now revenge.",
        },

        ["SPELL:Last Stand"] = {
            "I'll be bahk. I nevah left.",
            "Naht dead yet. More blood, please.",
            "%s gets biggah ven nearly dead.",
            "More health from nowhere. Do naht ask.",
            "Dis is borrowed health. I vill pay latah. Maybe.",
            "Healah, hurry. I bought you time.",
            "I AM NAHT DYING TODAY!",
            "Twenty seconds of being enormous.",
            "Vere did dis health come from? Who cares.",
            "Last Stand. Dat means I stand. Last.",
            "Still here. Still going.",
            "Dis is da emergency button.",
        },

        ["SPELL:Enraged Regeneration"] = {
            "It's naht a tumah. It is chust anger.",
            "Anger makes da vounds close.",
            "%s heals by being furious.",
            "I do naht need a healah. I have feelings.",
            "Spend da anger. Get da health. Good deal.",
            "Dis is my own magic. It is rage.",
            "Bleeding less now. Still angry.",
            "Medicine for a big man.",
            "BETTAH!",
            "Rage is a bandage.",
            "Who needs a priest.",
            "I fix myself.",
        },

        ["SPELL:Intervene"] = {
            "Come vit me if you vant to live.",
            "GET BEHIND ME!",
            "%s takes dat one for you.",
            "Naht my friend. Me.",
            "A big body is for blocking.",
            "I run to my friend and become a vall.",
            "Dis is a nice ting dat I do.",
            "You are safe now. Probably.",
            "Move. I am going dere.",
            "Hit me instead.",
            "Friends are important. So is smashing.",
            "Dat is vat I am for.",
        },

        ["SPELL:Throw"] = {
            "I trow da axe. Da axe does naht come bahk. Poor design.",
            "%s trows someting at %t.",
            "Too far to hit. So I trow.",
            "Vhoosh. Den ow, for you.",
            "Dis is naht as good as being close.",
            "COME CLOSER!",
            "Trowing is boring but it reaches.",
            "I have many sharp tings.",
            "Go avay, little axe. Hit %t.",
            "I am bettah at close vork.",
            "Dat vill do until I get dere.",
            "Naht my finest skill.",
        },

        ["SPELL:Shoot"] = {
            "Dis is naht a veapon for a man like me.",
            "%s uses da far veapon. %s is sad.",
            "Point. Shoot. No fun.",
            "A bow is for people who are frightened.",
            "I vant to be closer, %t.",
            "COME HERE SO I CAN PUT DIS DOWN!",
            "Hunters make dis look easy.",
            "It counts as hitting. Barely.",
            "I miss my axe.",
            "Fine. Fine. Shooting.",
            "Vorst part of da job.",
            "Pew. Dat is da noise, I tink.",
        },

        ["SPELL:Blood Fury"] = {
            "Da ancestors say hit hardah.",
            "%s has da angry blood.",
            "RAAAA!",
            "More strength from somewhere inside me.",
            "I do naht know vere it comes from.",
            "Red mist. I love da red mist.",
            "Healing vorks less now. Who cares.",
            "Blood Fury. Good name. Accurate name.",
            "My grandfather vould be proud.",
            "Biggah ahms. Even biggah ahms.",
            "Fifteen seconds of extra everyting.",
            "Dis is da good stuff.",
        },

        ["SPELL:Berserking"] = {
            "Fastah. Everyting fastah.",
            "%s svings quickly now.",
            "More hits in da same time. Mathematics.",
            "VOOO!",
            "Da more hurt I am, da fastah I go. Strange.",
            "My ahms are a blur.",
            "Dis is a very good racial.",
            "Speed is damage. I know dis one.",
            "Cannot stop now.",
            "Berserking. Anoder vord for angry.",
            "FAST!",
            "Troll speed. Excellent.",
        },

        ["SPELL:War Stomp"] = {
            "Big foot. Big result.",
            "%s stamps. Everybody falls ovah.",
            "NOBODY MOVE!",
            "Hooves are good for dis.",
            "Da ground says ow. So do you, %t.",
            "I am very heavy. It is an advantage.",
            "Everyone near me is dizzy now.",
            "Dat is a tauren ting. A good ting.",
            "My legs are also veapons.",
            "Tud.",
            "Stand still, all of you.",
            "STOMP!",
        },

        ["SPELL:Stoneform"] = {
            "I am rock now.",
            "%s turns to stone. Good stone.",
            "Poison does nuting to a rock.",
            "Hardah skin. Dwarf business.",
            "No more bleeding. I am a mineral.",
            "GRANITE!",
            "Bad tings fall off me now.",
            "Stone. Form. Two simple vords.",
            "I am built like a vall. Now literally.",
            "Nuting sticks to rock.",
            "Dis is useful and it looks good.",
            "Try dat again, %t.",
        },

        ["SPELL:Will of the Forsaken"] = {
            "Nobody tells me vat to do.",
            "GET OUT OF MY HEAD!",
            "%s has his own brain. Small, but his own.",
            "I am already dead. Fear does nuting.",
            "My mind is mine. Such as it is.",
            "No charm. No sleep. No fear.",
            "I decide vere I run. Me.",
            "You cannot frighten a corpse.",
            "Dat did naht vork on me, %t.",
            "Forsaken vill. Very strong vill.",
            "I tink my own toughts. Both of dem.",
            "Break free. Simple.",
        },

        ["SPELL:Arcane Torrent"] = {
            "Dat vas magic and I did it.",
            "%s does da elf ting.",
            "QUIET!",
            "Stop casting. All of you.",
            "I am an elf. Elves do sparkles.",
            "I do naht understand my own racial.",
            "It came from my hands. Strange.",
            "No more vords from you, %t.",
            "Blood elf magic. Still mostly hitting doh.",
            "I press da button. Tings go quiet.",
            "Sparkle. Also silence.",
            "Nobody talk.",
        },
    },
}
