-- RPVox -- mood pack: WEARY (Priest)
--
-- Lines are stored plain; the addon prefixes each with [weary] when seeding.
-- Voice: tired past caring. Not sad, not angry -- worn smooth. He does this
-- because it is what happens next, and it has been happening for a long time.

RPVox_MOOD_LINES = RPVox_MOOD_LINES or {}

RPVox_MOOD_LINES.WEARY = {
    name  = "weary",
    class = "PRIEST",

    ["REACT:LOWHEALTH"] = {
        "%t. Again. Of course.",
        "%t. I am too tired for this.",
        "%t. Fine. Take it. Take all of it.",
        "/em sags, then straightens out of habit",
        "%t. How many times must this body be opened.",
        "%t. I have run out of concern.",
        "%t. Another wound. There is a queue.",
        "Do what you like. I am not stopping you, %t.",
        "%t. This is the part I have done a thousand times.",
        "%t. Bleeding again. It hardly registers.",
        "%t. I would flinch if I had the energy.",
        "%t. Wake me when it is over.",
        "%t. Not this. Not today.",
        "%t. So much effort to stay upright.",
        "%t. Every wound is the same wound eventually.",
        "%t. I am tired of holding this together.",
        "/em breathes out slowly and keeps going",
        "%t. It never stops. That is the whole of it.",
        "%t. One more hole. Fine.",
        "%t. I have nothing left to be frightened with.",
        "Go on. Finish or don't, %t.",
        "%t. The stitching gives out eventually. Everything does.",
        "%t. How long have I been standing here.",
        "%t. Pain used to mean something.",
        "%t. I cannot remember not being hurt.",
        "Let it come, %t.",
        "%t. Still here. Unfortunately.",
        "%t. That should worry me. It doesn't.",
        "%t. I am running on the last of it.",
        "%t. This is very old, this feeling.",
        "%t. Another day. Another wound.",
        "%t. I stopped counting these years ago.",
        "%t. Enough. Please. Enough.",
        "/em leans on nothing in particular",
        "%t. It aches. It always aches.",
        "Do not trouble yourself. I will manage, %t.",
        "%t. There is no drama left in this.",
        "%t. The body complains. I ignore it.",
        "%t. Slower every time.",
        "%t. I am worn through.",
        "%t. Same wound, different century.",
        "%t. It will close. Badly. As always.",
        "%t. Nothing new here.",
        "%t. I have been this hurt for years.",
        "%t. Just get it over with.",
        "%t. Standing costs more than it used to.",
        "%t. So tired of bleeding.",
        "%t. Fine. Fine. Fine.",
        "%t. I have no fight left, only habit.",
        "%t. Everything is heavy.",
        "Hurt me if it helps you, %t.",
        "%t. It hardly seems worth the fuss.",
        "%t. I am held together by routine.",
        "%t. That was almost enough.",
        "%t. Some day one of these will finish it.",
        "%t. Not much of me left to ruin.",
        "/em wipes at the blood without interest",
        "%t. The whispers are tired too.",
        "%t. How tedious pain has become.",
        "%t. Another mark on a ruined thing.",
        "%t. I keep going because stopping takes effort.",
        "%t. Nothing hurts the way it used to.",
        "%t. This body has given all it has.",
        "%t. One more. Always one more.",
        "%t. I have been dying slowly for a very long time.",
        "Finish it, then, %t.",
        "Whatever you like, %t.",
        "%t. I cannot muster the alarm.",
        "%t. It stopped mattering some time ago.",
        "%t. Still standing. Do not ask how.",
        "%t. So old, this ache.",
        "Take what is left. It is not much, %t.",
        "%t. I would rest if resting worked.",
        "%t. Nothing changes.",
        "%t. Another wound to ignore.",
        "%t. The pain is background now.",
        "%t. I have forgotten what whole felt like.",
        "%t. Fine. Bleed then.",
        "%t. This is not even the worst of the week.",
        "%t. Slower. Everything is slower.",
        "%t. I am too old for this and I do not age.",
        "Let it run out, %t.",
        "%t. Nothing about this is new.",
        "%t. Weary. Wounded. Working.",
        "%t. I will not fall. I simply lack the energy to.",
        "%t. How many more of these.",
        "%t. It hardly bleeds any more. Poor circulation.",
        "Keep going if it pleases you, %t.",
        "%t. There is very little of me here.",
        "/em stands very still until the moment passes",
        "%t. I am running down.",
        "%t. Every part of this is familiar.",
        "%t. So be it.",
        "%t. One more scar on a scarred thing.",
        "%t. The end will be a relief. Not today though.",
        "%t. I have done this too many times.",
        "%t. Nothing left to protect.",
        "%t. Fine. I am used to it.",
        "%t. It goes on. It always goes on.",
        "%t. I endure. That is all I do now.",
    },

    ["REACT:DEATH"] = {
        "%t. Ah. Rest, then.",
        "%t. Finally.",
        "%t. That is a small mercy.",
        "/em lets go without resistance",
        "%t. Nothing to be done.",
        "%t. Well. That is that.",
        "%t. I was expecting it.",
        "Down again. Same as ever, %t.",
        "Do not bother resurrecting me quickly, %t.",
        "%t. The dark is quieter than this.",
        "%t. I have done this so many times.",
        "%t. Nothing lost that I was using.",
        "%t. Good. A pause.",
        "%t. Was that all? It usually is.",
        "%t. So this is Tuesday.",
        "Let me be for a while, %t.",
        "%t. It is not even a surprise.",
        "%t. Another one. Add it to the pile.",
        "%t. I hardly noticed.",
        "%t. The same ending as always.",
        "%t. Fine. I needed the rest.",
        "%t. Nothing has changed.",
        "%t. I am too tired to resent this.",
        "Down. Again. Predictably, %t.",
        "%t. That took less than I expected.",
        "%t. Not the worst thing today.",
        "%t. Very well.",
        "%t. I have nothing to say about it.",
        "%t. Same as the last one.",
        "%t. There. Done.",
        "/em slumps, unbothered",
        "%t. It ends. It always ends.",
        "%t. Wake me if it matters.",
        "%t. So I fall. Nothing new.",
        "%t. I had stopped trying anyway.",
        "%t. That is enough for one day.",
        "%t. Nothing worth remembering.",
        "Take the body somewhere quiet, %t.",
        "%t. Another death in a long line of them.",
        "Do not make a fuss, %t.",
        "%t. I would rather not get up.",
        "%t. Well. It happens.",
        "%t. I was tired anyway.",
        "%t. There is no dread left in it.",
        "%t. Same dark. Same silence.",
        "%t. Fine. I yield to the arithmetic.",
        "%t. I have been falling for years.",
        "%t. Nothing here I have not seen.",
        "Down, and quiet at last, %t.",
        "%t. It stopped being frightening long ago.",
        "%t. So it goes.",
        "%t. That was inevitable.",
        "%t. I am too worn to protest.",
        "%t. Nothing to it.",
        "%t. Not even a good death.",
        "Let the ground have me for a while, %t.",
        "%t. There is a certain relief in it.",
        "%t. Again? Very well.",
        "%t. The same as always.",
        "%t. I will get up later. Reluctantly.",
        "%t. Nothing changed by that.",
        "%t. Death is the only rest I get.",
        "%t. Enough.",
        "%t. Predictable.",
        "%t. So tired. So very tired.",
        "%t. That will do.",
        "%t. I stopped fighting it a while ago.",
        "%t. Same result. Different field.",
        "%t. Fine. Down I go.",
        "Do not hurry on my account, %t.",
        "%t. A small quiet. Then back to it.",
        "%t. It hardly matters.",
        "/em is still, and does not look troubled",
        "%t. Nothing to mourn.",
        "%t. One more ending, poorly attended.",
        "%t. Not the first. Not the last.",
        "%t. I will be back. I always am. Regrettably.",
        "Take your time, %t.",
        "%t. Nothing lost, nothing gained.",
        "%t. Old news.",
        "%t. The dark again. Familiar.",
        "%t. So that is done.",
        "%t. There is no fear in it any more.",
        "%t. Very well then.",
        "%t. That is the way of it.",
        "Down, and glad of the quiet, %t.",
        "%t. Another day ending badly.",
        "%t. I hardly felt the difference.",
        "%t. Nothing here worth noting.",
        "%t. Fine. Rest at last.",
        "%t. It comes for everyone. Repeatedly, in my case.",
        "%t. That was overdue.",
        "%t. So be it.",
        "%t. I have no complaints left.",
        "Down. Quiet. Good, %t.",
        "%t. It ends the same way every time.",
        "%t. Nothing to add.",
        "Let me lie here a moment, %t.",
        "%t. Enough for one day.",
        "Let me lie still a while longer, %t.",
    },

    ["REACT:RESURRECT"] = {
        "Must I?",
        "Up again. Always up again.",
        "/em rises slowly, without enthusiasm",
        "I was comfortable.",
        "Back. Unfortunately.",
        "The grave never keeps me long enough.",
        "Fine. I am standing.",
        "Nothing has improved.",
        "So. Again.",
        "One more life I did not ask for.",
        "Awake. Regrettably.",
        "Do we have to.",
        "The world is exactly as tiresome as I left it.",
        "I would rather have stayed.",
        "Everything still hurts. Naturally.",
        "Back on my feet. Give me a moment.",
        "That was not enough rest.",
        "Same body. Same complaints.",
        "Standing. Barely.",
        "The dark did not want me. It never does.",
        "Very well. Where were we.",
        "This gets no easier.",
        "Another go, then.",
        "I am running out of enthusiasm.",
        "Up. Because that is what happens.",
        "/em rolls a stiff shoulder and sighs",
        "Nothing waits down there either.",
        "Back among the noise.",
        "Fine. Continue.",
        "I did not miss any of this.",
        "Every return is heavier.",
        "The same aches, patiently waiting.",
        "So much for rest.",
        "I am upright. Do not expect more.",
        "It never sticks.",
        "Awake and unimpressed.",
        "Whoever did that: thank you, I suppose.",
        "Back to the long business of continuing.",
        "Nothing changed while I was gone.",
        "Right. On with it.",
        "One more time around.",
        "I have done this too often.",
        "Standing again. Marvellous.",
        "The body obeys. Slowly. Resentfully.",
        "Back to it, then.",
        "How tiresome, being necessary.",
        "There is no rest on either side.",
        "Fine. I am here.",
        "Give me a moment to remember why.",
        "Up, and no better for it.",
        "Everything is where I left it. Unfortunately.",
        "Another day begins. Badly.",
        "I am returned. Nobody rejoice.",
        "Same world. Same weight.",
        "So we continue.",
        "Nothing to celebrate.",
        "Back. Wearily.",
        "I would sleep if it worked.",
        "That was barely a pause.",
        "Right. What now.",
        "Fine. Standing.",
        "The whispers start again first.",
        "Nothing improved by dying.",
        "I keep coming back. It keeps being this.",
        "Up we go. Slowly.",
        "/em stands and stares at nothing for a moment",
        "Well. Here we are again.",
        "I was almost peaceful.",
        "Back to work, I suppose.",
        "Never long enough.",
        "Fine. Point me somewhere.",
        "It never lasts.",
        "One more resurrection to add to the tally.",
        "So. Still going.",
        "The dirt was quieter.",
        "Right. Continuing.",
        "Nothing awaits me but more of this.",
        "I am up. That is the whole report.",
        "Same as it ever was.",
        "Standing. For now.",
        "Give the corpse a minute.",
        "Another beginning. How tedious.",
        "Back. Slower each time.",
        "There is always more to do.",
        "Fine. Onward, I suppose.",
        "It goes on and on and on.",
        "Awake. Working. Tired.",
        "Nothing new to report.",
        "Up because there is no alternative.",
        "The world did not stop. It never does.",
        "So. Once more.",
        "I am here. Do not expect enthusiasm.",
        "Back in the ruin of the day.",
        "Everything continues. Including me.",
        "Right. Move.",
        "That will have to be rest enough.",
        "Standing again, for whatever it is worth.",
        "Nothing has changed. It never does.",
        "Fine. Let us continue.",
        "Back. Slower and less willing each time.",
    },

    ["REACT:KILLINGBLOW"] = {
        "%t. There. Done.",
        "%t. Another one.",
        "Rest. You are luckier than me, %t.",
        "/em turns away before the body settles",
        "%t. That is finished.",
        "%t. It hardly seems worth it now.",
        "%t. One more. There is always one more.",
        "Go on then. Rest, %t.",
        "%t. Nothing satisfying in that.",
        "You may stay dead. I envy you, %t.",
        "%t. That is the fifth today. Or the fiftieth.",
        "%t. It ends. Everything ends. Except me.",
        "%t. Fine. Next.",
        "%t. I take no pleasure in it any more.",
        "You are done. Lucky, %t.",
        "%t. Another name I will not remember.",
        "That is enough of you, %t.",
        "Down. Same as the rest, %t.",
        "%t. So it goes.",
        "Rest, %t. Genuinely.",
        "%t. Nothing to say over the body.",
        "%t. It is only ever this.",
        "You get the quiet. I get the walking, %t.",
        "%t. Another ending in a long series.",
        "%t. There. Nothing personal.",
        "%t. I have stopped counting.",
        "%t. Finished. On to the next.",
        "%t. That was tedious for both of us.",
        "Down you go, %t.",
        "Sleep. It is more than I get, %t.",
        "/em steps over the body without looking",
        "%t. One less thing moving.",
        "%t. Nothing changes. Another falls.",
        "%t. Enough.",
        "%t. That was necessary. Nothing more.",
        "You are free of it now, %t.",
        "%t. Same as always.",
        "%t. Another for the pile.",
        "Do not look at me like that, %t.",
        "%t. Fine. That is settled.",
        "%t. It is done. It is always done.",
        "You will not have to do this again, %t.",
        "%t. So much effort for so little.",
        "That is the end of you, %t.",
        "%t. I would apologise if I had the energy.",
        "Rest well. I mean that, %t.",
        "%t. Another quiet body.",
        "Nothing left of you to argue with, %t.",
        "%t. It never gets easier. It gets duller.",
        "%t. There. Move on.",
        "%t. One more corpse in a long career of them.",
        "You are finished. Consider it a kindness, %t.",
        "%t. That was no trouble. That is the trouble.",
        "Down. And on we go, %t.",
        "%t. So many of these.",
        "%t. The dirt gets everyone. Eventually.",
        "%t. Nothing worth remarking on.",
        "%t. Fine. Onwards.",
        "%t. That is one less voice.",
        "%t. Another thing that stopped.",
        "Rest. You have earned an ending, %t.",
        "%t. I do not enjoy it. I simply do it.",
        "%t. That is that.",
        "%t. One more. Same as the last.",
        "You are quiet now. Good, %t.",
        "%t. Nothing to celebrate here.",
        "Down, and no better for it, %t.",
        "%t. It is only ever the same result.",
        "%t. Another finished thing.",
        "/em says nothing at all over the body",
        "%t. There. Now the next.",
        "So it ends for you, %t.",
        "%t. I have done this so often it is dull.",
        "You had a life. It is over, %t.",
        "%t. Nothing more required.",
        "%t. Fine. That is done.",
        "%t. One less problem, ten thousand more.",
        "%t. The end comes cheap out here.",
        "Rest. Truly, %t.",
        "%t. Another day, another body.",
        "%t. It is finished. So am I, nearly.",
        "Down. Move on, %t.",
        "%t. That is enough of that.",
        "You are the lucky one, %t.",
        "%t. So many. So very many.",
        "%t. Nothing left to fight.",
        "%t. It ends as it always ends.",
        "%t. Another one settled.",
        "There. Peace for you at least, %t.",
        "%t. One more entry on a long ledger.",
        "%t. That is done and I am tired.",
        "Go quietly. Everyone does eventually, %t.",
        "%t. Fine. Finished.",
        "%t. Nothing here worth the effort it took.",
        "Down. On we go, %t.",
        "Rest, and do not envy me, %t.",
        "%t. That is all it ever is.",
        "%t. Enough. Next.",
        "Down. There is always another behind it, %t.",
        "You rest. I keep walking, %t.",
    },

    ["REACT:COMBATSTART"] = {
        "%t. Must we.",
        "%t. Oh, not again.",
        "/em raises his hands with visible reluctance",
        "%t. Very well. If we must.",
        "Do we really have to do this, %t.",
        "%t. Fine.",
        "%t. Another one of these.",
        "I have not the energy for you, %t.",
        "%t. Must everything be a fight.",
        "%t. So. This again.",
        "Come on then. Quickly, %t.",
        "%t. I would rather not.",
        "%t. Here we go. Once more.",
        "%t. Can this not wait.",
        "%t. Another interruption.",
        "If you insist, %t.",
        "%t. Very well. Get it over with.",
        "%t. I am too tired for a long one.",
        "%t. Please be quick about it.",
        "%t. This is the fourth today.",
        "%t. Sigh. Come on then.",
        "Do try to make it brief, %t.",
        "%t. Fine. Approach.",
        "%t. The same as always.",
        "%t. I had almost sat down.",
        "%t. Not now. But apparently now.",
        "%t. Right. Again.",
        "%t. Another body that wants a fight.",
        "%t. So be it. Again.",
        "Let us get this over with, %t.",
        "/em sighs and begins the working",
        "You could walk away. You will not, %t.",
        "%t. Every day. Every single day.",
        "%t. Very well. Come here.",
        "%t. I have done this so many times.",
        "Do we begin, then, %t.",
        "Fine. Whatever you like, %t.",
        "%t. Another one who wants something.",
        "%t. Must be Tuesday.",
        "%t. This will be dull.",
        "Come on. Slowly. I do not mind, %t.",
        "%t. One more scrap. Fine.",
        "%t. So it starts again.",
        "%t. I am so tired of this.",
        "%t. Right. Get on with it.",
        "%t. Not the first today. Not the last.",
        "%t. Very well. Violence.",
        "If you must, you must, %t.",
        "%t. Here we are again.",
        "Do your worst. Or don't, %t.",
        "%t. Another tedious afternoon.",
        "Come on then, %t.",
        "%t. This never stops.",
        "%t. Fine. Again. Again.",
        "%t. I would like one quiet hour.",
        "%t. It never ends, this.",
        "%t. Very well. Begin.",
        "%t. Another fight I did not ask for.",
        "%t. So. Once more, then.",
        "%t. Right. Let us be quick.",
        "%t. I have no enthusiasm left for this.",
        "Do get on with it, %t.",
        "%t. Another. Of course.",
        "%t. Fine. Come at me.",
        "%t. How very tiresome.",
        "%t. Same as yesterday. Same as tomorrow.",
        "%t. I will do this because it is what happens.",
        "%t. Very well. Where were we.",
        "%t. It hardly seems worth drawing breath. Which I do not.",
        "Come on. Let us not drag it out, %t.",
        "%t. Another one. Marvellous.",
        "%t. So we fight. Again.",
        "%t. Fine. If it must be.",
        "%t. I am too worn for a proper effort.",
        "%t. Right. Standard business.",
        "%t. One more of these.",
        "Do not expect much of a show, %t.",
        "%t. Very well. On we go.",
        "%t. Another day, another idiot.",
        "%t. This again. Always this.",
        "%t. Fine. Let us begin.",
        "%t. I have nothing left but habit.",
        "Come on. Quickly, please, %t.",
        "%t. Another interruption to a long dull day.",
        "%t. So. Fighting. Again.",
        "%t. Right then. Go on.",
        "%t. It never lets up.",
        "%t. Very well. Have at it.",
        "%t. Another. And another. And another.",
        "%t. Fine. I am here. Begin.",
        "Do we have to shout as well, %t.",
        "%t. I will be brief. I lack the stamina otherwise.",
        "%t. Same thing, different field.",
        "%t. Right. Again, then.",
        "%t. Another scuffle. How thrilling.",
        "%t. Fine. Come along.",
        "Let us get this behind us, %t.",
        "%t. So it goes. Again.",
        "%t. Very well. Once more.",
        "%t. Another one wanting something from me.",
    },

    ["REACT:COMBATEND"] = {
        "Finally.",
        "Is that it?",
        "Good. Quiet.",
        "/em lowers his hands and stands there a while",
        "Enough for today.",
        "That took longer than it needed to.",
        "Right. On to the next tedium.",
        "Thank the dark, silence.",
        "Well. That is over.",
        "One less thing.",
        "I need a moment. I will not get one.",
        "Done. Again.",
        "Another one behind us.",
        "It never stays quiet long.",
        "Good. Nothing left to hit.",
        "That is enough violence for a while.",
        "So it ends. As they all do.",
        "Now the walking. Always the walking.",
        "Silence. Briefly.",
        "Fine. What next.",
        "I am too old for these afternoons.",
        "That accomplished very little.",
        "Over. Thank the Shadow.",
        "Another one survived. Barely worth noting.",
        "Rest? No. There is more.",
        "Nothing changed. Nothing ever does.",
        "Right. Onward, I suppose.",
        "Good. Quiet at last.",
        "That was as tiresome as expected.",
        "Bodies to walk around now.",
        "One more done.",
        "The quiet never lasts.",
        "So that is that.",
        "Enough. Please, enough.",
        "Nothing left standing. Good.",
        "I would sit if sitting helped.",
        "Another fight ended. Another beginning shortly.",
        "That is over. Something else will start.",
        "Fine. Moving on.",
        "So much noise for so little.",
        "/em stands among the bodies, unmoved",
        "Well. Back to the tedium.",
        "Nothing follows. Small mercy.",
        "Done. Next.",
        "That is the third today.",
        "Silence. I had forgotten it.",
        "Right. Continue.",
        "Nothing worth the effort it cost.",
        "Over at last.",
        "I am tired in a way sleep does not touch.",
        "Another one finished.",
        "Good. On we go.",
        "That was not worth waking for.",
        "Quiet. Enjoy it while it holds.",
        "So it ends. Again.",
        "Fine. Onward.",
        "Nothing gained. Nothing much lost.",
        "That is done. Something else waits.",
        "One more behind me.",
        "The day continues. Regrettably.",
        "Enough for one afternoon.",
        "Right. What is next on the list.",
        "Nothing left to do here.",
        "Over. Finally over.",
        "I am running very low.",
        "Another survived. Hooray, I suppose.",
        "Quiet again. It always feels borrowed.",
        "Fine. Let us move.",
        "That took what little I had.",
        "So. Done.",
        "Nothing more required of me. For now.",
        "Right. On.",
        "It ends the way they all end.",
        "Good. Nothing moving.",
        "Another fight, another nothing.",
        "Enough. Let us go.",
        "That is finished. So am I.",
        "The silence is the only wage.",
        "Fine. Continue.",
        "One more of those behind us.",
        "Nothing to report. As usual.",
        "Over, and I am no better for it.",
        "Right. Walking again.",
        "That is that. Until the next.",
        "Quiet. Briefly. As ever.",
        "Enough of that for one day.",
        "So we continue.",
        "Nothing new here.",
        "Done. Tired. Moving.",
        "Another. Behind us. Fine.",
        "Right. There is always more.",
        "It is over. Something else will not be.",
        "Good. A moment of nothing.",
        "That will have to do.",
        "Fine. What now.",
        "Ended. As they do.",
        "One more finished. Onward.",
        "Enough. Move on.",
        "Over. Until the next one.",
        "I will take the quiet while it lasts.",
    },

    ["REACT:INTERRUPTED"] = {
        "%t. Of course.",
        "%t. Naturally.",
        "/em stops, sighs, and starts again",
        "%t. Fine. Again from the beginning.",
        "Must you, %t.",
        "%t. Predictable.",
        "%t. Very well. Once more.",
        "%t. That is about right for today.",
        "%t. I had almost finished.",
        "%t. Everything is like this.",
        "%t. Yes. Obviously.",
        "%t. Right. Again, then.",
        "%t. Why not. Nothing else has gone well.",
        "%t. Fine. I will start over.",
        "Of course you did, %t.",
        "%t. That is the sort of day it has been.",
        "%t. So be it.",
        "%t. I have not the patience for this.",
        "Very well. Take your moment, %t.",
        "%t. Nothing ever goes cleanly.",
        "%t. Fine. The slow way.",
        "%t. As expected.",
        "%t. Right. Where was I.",
        "%t. Naturally that would happen.",
        "%t. I will simply do it again. Wearily.",
        "%t. That figures.",
        "%t. Very well.",
        "%t. It is always something.",
        "%t. Fine. Interrupt away.",
        "%t. One more thing going wrong.",
        "Do you feel better, %t?",
        "%t. So it goes.",
        "%t. Right. Again.",
        "%t. That is the third time today.",
        "%t. Nothing works the first time.",
        "%t. Fine. From the top.",
        "%t. I expected as much.",
        "%t. How very typical.",
        "%t. Very well. Begin again.",
        "%t. That was inevitable.",
        "/em pinches the bridge of his nose and resumes",
        "%t. Naturally.",
        "%t. It hardly matters.",
        "%t. Fine. Continue interrupting.",
        "%t. Everything takes twice as long.",
        "%t. Right. Starting over.",
        "%t. Nothing goes smoothly. Ever.",
        "%t. So. Again.",
        "%t. Very well. Again, slowly.",
        "%t. That is fair, I suppose.",
        "%t. One more delay.",
        "%t. Fine. I have nothing but time.",
        "%t. Of course. Why not.",
        "%t. It is that sort of afternoon.",
        "%t. Right. Yet again.",
        "Naturally you would do that, %t.",
        "%t. So tedious.",
        "Fine. As you like, %t.",
        "%t. That will add a minute. Wonderful.",
        "%t. Everything is an effort.",
        "%t. Very well. Once more, with feeling I do not have.",
        "%t. It happens. Constantly.",
        "%t. Right. Where were we.",
        "%t. Nothing surprising there.",
        "Fine. Do it again if you must, %t.",
        "%t. I have stopped expecting otherwise.",
        "%t. So it goes. Again.",
        "%t. That is about the size of it.",
        "%t. Very well. Resuming.",
        "%t. Another interruption to a long day.",
        "%t. Fine. I will manage.",
        "%t. Of course that happened.",
        "%t. It always does.",
        "%t. Right. Beginning again.",
        "%t. Nothing is ever simple.",
        "%t. So be it. Again.",
        "%t. Very well. I have the patience of the dead.",
        "%t. That is one more delay.",
        "Fine. Whatever you like, %t.",
        "%t. Naturally. Why would it work.",
        "%t. Right. Once more.",
        "%t. It hardly registers now.",
        "%t. So. Delayed again.",
        "%t. Fine. Start over.",
        "%t. Everything twice. Always twice.",
        "%t. Very well. Continue.",
        "%t. That is the pattern of the day.",
        "%t. One more thing to redo.",
        "%t. Right. From the beginning, then.",
        "%t. Nothing new about that.",
        "%t. Fine. Again and again and again.",
        "%t. Of course. Certainly. Naturally.",
        "%t. So we go around once more.",
        "%t. Very well. I am used to it.",
        "%t. That will do nothing but tire us both.",
        "%t. Right. Resuming, wearily.",
        "%t. Fine. As always.",
        "%t. It never goes right the first time.",
        "%t. Fine. Nothing works the first time anyway.",
        "%t. I will begin again. As always.",
    },
}
