-- RPVox -- class packs
--
-- Each pack gives a class its own ability list and its own voice. Creating a
-- profile from a pack seeds every trigger from `lines`, falling back to the
-- generic set in RPVoxLines.lua for anything the pack does not cover.
--
--   spells = { { spell = "<exact spell name>", icon = "...", chance = n }, ... }
--   lines  = { ["REACT:DEATH"] = { "..." }, ["SPELL:Charge"] = { "..." }, ... }

RPVox_CLASSES = {}

-- Priest ------------------------------------------------------------------
-- Lines live in RPVoxLines.lua (the Forsaken shadow priest voice).

RPVox_CLASSES.PRIEST = {
    name = "Priest",
    spells = {
        { spell = "Shoot",              icon = "Interface\\Icons\\INV_Wand_01",                 chance = 10 },
        { spell = "Smite",              icon = "Interface\\Icons\\Spell_Holy_HolySmite",        chance = 10 },
        { spell = "Mind Blast",         icon = "Interface\\Icons\\Spell_Shadow_UnholyFrenzy",   chance = 10 },
        { spell = "Shadow Word: Pain",  icon = "Interface\\Icons\\Spell_Shadow_ShadowWordPain", chance = 10 },
        { spell = "Power Word: Shield", icon = "Interface\\Icons\\Spell_Holy_PowerWordShield",  chance = 10 },
        { spell = "Renew",              icon = "Interface\\Icons\\Spell_Holy_Renew",            chance = 10 },
        { spell = "Lesser Heal",        icon = "Interface\\Icons\\Spell_Holy_LesserHeal",       chance = 10 },
        { spell = "Mind Flay",          icon = "Interface\\Icons\\Spell_Shadow_SiphonMana",     chance = 10 },
        { spell = "Psychic Scream",     icon = "Interface\\Icons\\Spell_Shadow_PsychicScream",  chance = 10 },
        { spell = "Fade",               icon = "Interface\\Icons\\Spell_Magic_LesserInvisibilty", chance = 10 },
        -- The rest of the kit ------------------------------------------
        { spell = "Heal",                 icon = "Interface\\Icons\\Spell_Holy_Heal",                chance = 10 },
        { spell = "Greater Heal",         icon = "Interface\\Icons\\Spell_Holy_GreaterHeal",         chance = 10 },
        { spell = "Flash Heal",           icon = "Interface\\Icons\\Spell_Holy_FlashHeal",           chance = 10 },
        { spell = "Prayer of Healing",    icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing02",   chance = 10 },
        { spell = "Binding Heal",         icon = "Interface\\Icons\\Spell_Holy_BindingHeal",         chance = 10 },
        { spell = "Prayer of Mending",    icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing",     chance = 10 },
        { spell = "Circle of Healing",    icon = "Interface\\Icons\\Spell_Holy_CircleOfRenewal",     chance = 10 },
        { spell = "Power Word: Fortitude",icon = "Interface\\Icons\\Spell_Holy_WordFortitude",       chance = 10 },
        { spell = "Prayer of Fortitude",  icon = "Interface\\Icons\\Spell_Holy_PrayerOfFortitude",   chance = 10 },
        { spell = "Divine Spirit",        icon = "Interface\\Icons\\Spell_Holy_DivineSpirit",        chance = 10 },
        { spell = "Prayer of Spirit",     icon = "Interface\\Icons\\Spell_Holy_PrayerofSpirit",      chance = 10 },
        { spell = "Shadow Protection",    icon = "Interface\\Icons\\Spell_Shadow_AntiShadow",        chance = 10 },
        { spell = "Inner Fire",           icon = "Interface\\Icons\\Spell_Holy_InnerFire",           chance = 10 },
        { spell = "Levitate",             icon = "Interface\\Icons\\Spell_Magic_FeatherFall",        chance = 10 },
        { spell = "Resurrection",         icon = "Interface\\Icons\\Spell_Holy_Resurrection",        chance = 10 },
        { spell = "Dispel Magic",         icon = "Interface\\Icons\\Spell_Holy_DispelMagic",         chance = 10 },
        { spell = "Mass Dispel",          icon = "Interface\\Icons\\Spell_Arcane_MassDispel",        chance = 10 },
        { spell = "Abolish Disease",      icon = "Interface\\Icons\\Spell_Nature_NullifyDisease",    chance = 10 },
        { spell = "Cure Disease",         icon = "Interface\\Icons\\Spell_Holy_NullifyDisease",      chance = 10 },
        { spell = "Shackle Undead",       icon = "Interface\\Icons\\Spell_Nature_Slow",              chance = 10 },
        { spell = "Mind Soothe",          icon = "Interface\\Icons\\Spell_Holy_MindSooth",           chance = 10 },
        { spell = "Mind Control",         icon = "Interface\\Icons\\Spell_Shadow_ShadowWordDominate",chance = 10 },
        { spell = "Holy Fire",            icon = "Interface\\Icons\\Spell_Holy_SearingLight",        chance = 10 },
        { spell = "Holy Nova",            icon = "Interface\\Icons\\Spell_Holy_HolyNova",            chance = 10 },
        { spell = "Shadow Word: Death",   icon = "Interface\\Icons\\Spell_Shadow_DemonicFortitude",  chance = 10 },
        { spell = "Vampiric Embrace",     icon = "Interface\\Icons\\Spell_Shadow_UnsummonBuilding",  chance = 10 },
        { spell = "Vampiric Touch",       icon = "Interface\\Icons\\Spell_Holy_Stoicism",            chance = 10 },
        { spell = "Shadowform",           icon = "Interface\\Icons\\Spell_Shadow_Shadowform",        chance = 10 },
        { spell = "Silence",              icon = "Interface\\Icons\\Spell_Shadow_ImpPhaseShift",     chance = 10 },
        { spell = "Shadowfiend",          icon = "Interface\\Icons\\Spell_Shadow_Shadowfiend",       chance = 10 },
        { spell = "Devouring Plague",     icon = "Interface\\Icons\\Spell_Shadow_BlackPlague",       chance = 10 },
        { spell = "Touch of Weakness",    icon = "Interface\\Icons\\Spell_Shadow_DeadofNight",       chance = 10 },
    },
    lines = {
        ["SPELL:Mind Flay"] = {
            "Slowly. I am in no hurry at all, %t.",
            "Your thoughts, unravelling. Thread by thread, %t.",
            "This takes concentration, %t. Do not distract me.",
            "%t. The dark drinks deep.",
            "%t. I am in your thoughts. I am staying.",
            "%t. Every second of this is deliberate.",
            "Scream if it helps. It will not, %t.",
            "Rot, from the mind outward, %t.",
            "A long, cold hand around your reason, %t.",
            "%t. This is the patient kind of cruelty.",
        },
        ["SPELL:Shadow Word: Pain"] = {
            "Let it fester, %t.",
            "Suffer, %t, as I have suffered.",
            "Your nerves still work? Good, %t.",
            "Feel it spread, %t.",
            "A slow rot for you, %t.",
            "%t. Pain is such an honest teacher.",
            "%t. Let the rot do its work.",
            "%t. This takes time. It always does.",
            "/em points two fingers and lets the rot take hold",
            "/em whispers something in a language that predates Lordaeron",
            "%t. Such a fragile thing, flesh.",
            "%t. Oh, does it hurt? How wonderful.",
            "You still fear death, %t. Amusing.",
            "Enjoy your last warm breath, %t.",
            "Your body betrays you already, %t.",
            "%t. Living things are so loud when they break.",
        },
        ["SPELL:Psychic Scream"] = {
            "RUN, %t.",
            "/em screams with a voice that is not entirely his own",
            "Run, %t. Everyone does.",
            "Hear what I hear. Now flee from it, %t.",
            "%t. The whispers, all at once. Enjoy.",
            "%t. A taste of my waking hours.",
            "Now you know what the dark sounds like, %t.",
            "%t. Scatter, little things.",
            "%t. Fear is honest. Wear it.",
            "%t. That is the noise I live with.",
        },
        ["SPELL:Fade"] = {
            "Look elsewhere. There is nothing here, %t.",
            "%t. The dead are easy to overlook.",
            "%t. I was never here.",
            "%t. Forget me. Most do.",
            "%t. Between one shadow and the next.",
            "%t. Attention is a burden. I set it down.",
            "/em seems briefly difficult to look at",
            "/em steps into a shadow that was not there a moment ago",
        },
    },
}

-- Mage --------------------------------------------------------------------
-- Voice: an arcanist. Precise, superior, faintly bored by everyone else's
-- reasoning. Treats combat as applied theory and death as a data point.

RPVox_CLASSES.MAGE = {
    name = "Mage",
    spells = {
        { spell = "Frostbolt",        icon = "Interface\\Icons\\Spell_Frost_FrostBolt02",     chance = 10 },
        { spell = "Fireball",         icon = "Interface\\Icons\\Spell_Fire_FlameBolt",        chance = 10 },
        { spell = "Arcane Missiles",  icon = "Interface\\Icons\\Spell_Nature_StarFall",       chance = 10 },
        { spell = "Fire Blast",       icon = "Interface\\Icons\\Spell_Fire_Fireball",         chance = 10 },
        { spell = "Pyroblast",        icon = "Interface\\Icons\\Spell_Fire_Fireball02",       chance = 10 },
        { spell = "Blizzard",         icon = "Interface\\Icons\\Spell_Frost_IceStorm",        chance = 10 },
        { spell = "Frost Nova",       icon = "Interface\\Icons\\Spell_Frost_FrostNova",       chance = 10 },
        { spell = "Blink",            icon = "Interface\\Icons\\Spell_Arcane_Blink",          chance = 10 },
        { spell = "Polymorph",        icon = "Interface\\Icons\\Spell_Nature_Polymorph",      chance = 10 },
        { spell = "Counterspell",     icon = "Interface\\Icons\\Spell_Frost_IceShock",        chance = 10 },
        { spell = "Ice Block",        icon = "Interface\\Icons\\Spell_Frost_Frost",           chance = 10 },
        { spell = "Evocation",        icon = "Interface\\Icons\\Spell_Nature_Purge",          chance = 10 },
        { spell = "Arcane Intellect", icon = "Interface\\Icons\\Spell_Holy_MagicalSentry",    chance = 10 },
        { spell = "Conjure Water",    icon = "Interface\\Icons\\INV_Drink_04",                chance = 10 },
        { spell = "Conjure Food",     icon = "Interface\\Icons\\INV_Misc_Food_39",            chance = 10 },
        { spell = "Shoot",            icon = "Interface\\Icons\\INV_Wand_01",                 chance = 10 },
    },
    lines = {
        -- Abilities -----------------------------------------------------
        ["SPELL:Frostbolt"] = {
            "%t. Cold is simply the absence of argument.",
            "%t. Slow down. I insist.",
            "%t. Elementary application.",
            "Note the deceleration, %t.",
            "/em traces a sigil and the air frosts over",
            "%t. Freezing point reached.",
            "%t. Predictable trajectory. Predictable result.",
            "You are moving too quickly to think, %t.",
            "%t. Ice does not negotiate.",
            "Another degree colder, %t.",
            "%t. Precision over spectacle.",
            "%t. That should slow the discussion.",
        },
        ["SPELL:Fireball"] = {
            "%t. Combustion. Reliable.",
            "%t. Heat is the simplest argument.",
            "/em rolls flame between two fingers before releasing it",
            "Observe the conversion of mana into consequence, %t.",
            "Burn, %t.",
            "%t. The classical solution.",
            "%t. That should be sufficiently warm.",
            "%t. Fire asks nothing and takes everything.",
            "Applied thermodynamics, %t.",
            "%t. A tidy little sun.",
            "%t. Straightforward. Effective.",
            "%t. Nothing elegant. Merely correct.",
        },
        ["SPELL:Arcane Missiles"] = {
            "%t. Sequenced. Unavoidable.",
            "%t. Arithmetic, delivered.",
            "/em holds the channel steady, counting under his breath",
            "%t. One. Two. Three. Four.",
            "%t. The arcane does not miss.",
            "%t. No dodging pure mathematics.",
            "%t. Precision in series.",
            "%t. Each one is a decimal place.",
            "You cannot outrun the equation, %t.",
            "Delivered, %t. All of them.",
            "%t. The purest form of the art.",
            "%t. Elegant. Repetitive. Fatal.",
        },
        ["SPELL:Fire Blast"] = {
            "%t. Instantly, then.",
            "%t. No incantation required.",
            "%t. Quick and hot.",
            "%t. That is what haste is for.",
            "/em snaps his fingers",
            "%t. Punctuation.",
            "%t. A small correction.",
            "%t. Immediate. Unarguable.",
        },
        ["SPELL:Pyroblast"] = {
            "%t. This one took a moment. Enjoy it.",
            "Observe what patience produces, %t.",
            "/em holds the working aloft until it is unbearable to look at",
            "%t. The long cast is always the interesting one.",
            "%t. That was worth the wait.",
            "Consider this a formal statement, %t.",
            "%t. Nothing subtle. Nothing survives.",
            "%t. The culmination of several seconds of theory.",
            "I do hope you were watching, %t.",
            "%t. That will leave a crater and a lesson.",
        },
        ["SPELL:Blizzard"] = {
            "%t. Weather, on request.",
            "All of you. Simultaneously, %t.",
            "/em raises both hands and the sky answers",
            "%t. A localised catastrophe.",
            "%t. Everyone receives a portion.",
            "%t. The forecast is unfavourable.",
            "%t. Area denial. Textbook.",
            "Stand there if you like, %t.",
        },
        ["SPELL:Frost Nova"] = {
            "Stay, %t.",
            "%t. Rooted. Now we can talk.",
            "/em stamps once and the ground goes white",
            "%t. Distance is a tactical resource.",
            "You will wait there, %t.",
            "%t. Immobilised. Predictably.",
            "%t. That is quite far enough.",
            "Do not follow. It ends badly, %t.",
        },
        ["SPELL:Blink"] = {
            "%t. Elsewhere.",
            "%t. Spatial reasoning.",
            "/em is abruptly somewhere else",
            "You were expecting me to remain, %t?",
            "%t. Distance, corrected.",
            "%t. The shortest path is not always continuous.",
            "%t. Repositioning.",
            "%t. Physics is a suggestion.",
        },
        ["SPELL:Polymorph"] = {
            "You will be more agreeable as a sheep, %t.",
            "%t. An improvement, honestly.",
            "/em sketches a shape in the air and the target simplifies",
            "Do not struggle. It only prolongs the wool, %t.",
            "%t. A temporary demotion.",
            "%t. There. Much quieter.",
            "You were more trouble with hands, %t.",
            "Consider it a sabbatical, %t.",
            "%t. The transformation is entirely reversible. Probably.",
            "%t. Baa.",
        },
        ["SPELL:Counterspell"] = {
            "%t. No.",
            "%t. That will not be happening.",
            "/em cuts the air and the working collapses",
            "Silence. It suits you, %t.",
            "Your casting was sloppy anyway, %t.",
            "%t. Denied.",
            "%t. I have read that spell. It is derivative.",
            "%t. Not while I am present.",
        },
        ["SPELL:Ice Block"] = {
            "%t. Excuse me a moment.",
            "/em vanishes inside a shell of ice",
            "%t. Reassessing from inside a very cold box.",
            "%t. Temporarily unavailable.",
            "%t. This is a tactical retreat with better insulation.",
            "Do carry on without me. Briefly, %t.",
            "%t. Nothing reaches me in here.",
            "%t. A moment of perfect, freezing clarity.",
        },
        ["SPELL:Evocation"] = {
            "%t. One moment. Refuelling.",
            "/em stands still, drawing the ambient arcane inward",
            "Do keep them occupied, %t.",
            "%t. Restoring the reservoir.",
            "%t. This is the least dignified part of the profession.",
            "%t. Mana does not conjure itself. Well. Nearly.",
            "%t. A brief intermission.",
            "%t. Guard me or lose me.",
        },
        ["SPELL:Arcane Intellect"] = {
            "There. You will think marginally faster, %t.",
            "%t. A modest improvement to a modest mind.",
            "/em taps a colleague on the forehead",
            "Do try to use it, %t.",
            "%t. Cleverness, applied externally.",
            "You are welcome, %t.",
            "%t. That should help. Marginally.",
            "%t. Intellect, on loan.",
        },
        ["SPELL:Conjure Water"] = {
            "%t. Water from nothing. Still impressive, I think.",
            "/em produces water out of the air, unimpressed with himself",
            "%t. Hydration, provided.",
            "Do not ask where it comes from, %t.",
            "%t. A trick, but a useful one.",
            "%t. There. Drink.",
            "%t. The most requested spell in my repertoire. Depressingly.",
            "%t. Free of charge. This time.",
        },
        ["SPELL:Shoot"] = {
            "%t. Regrettable, but necessary.",
            "%t. Out of mana. Into indignity.",
            "/em fires the wand with a look of profound disappointment",
            "%t. Years of study, reduced to this.",
            "%t. A stick. I am reduced to a stick.",
            "%t. Conserving. Do not comment.",
            "%t. This is not the art. This is arithmetic with splinters.",
            "%t. It counts as damage. Barely.",
            "Do not tell the Kirin Tor about this, %t.",
            "Even this is more than you have earned, %t.",
            "%t. Mana is finite. My contempt is not.",
            "%t. Adequate. Nothing more.",
        },
        ["SPELL:Conjure Food"] = {
            "%t. Sustenance. Of a sort.",
            "/em conjures a meal and looks faintly embarrassed",
            "%t. Yes, yes. Food. Marvellous.",
            "%t. Years of study, and this is what people ask for.",
            "%t. It is edible. That is the entire claim.",
            "%t. There. A banquet.",
            "Do not expect seasoning, %t.",
            "%t. The arcane provides. Blandly.",
        },

        ["IDLE:QUESTACCEPT"] = {
            "Very well. A practical application.",
            "/em accepts the task with visible reservations",
            "I will require expenses.",
            "This is well beneath my training. I accept anyway.",
            "Fine. Where is it, and what does it know?",
            "Consider it solved. The travel is the tedious part.",
            "You could have hired anyone. You were right not to.",
            "Noted. I will attend to it between readings.",
        },

        -- Reactions -----------------------------------------------------
        ["REACT:LOWHEALTH"] = {
            "%t. This is going poorly.",
            "%t. Cloth. The eternal problem with cloth.",
            "/em backs away, calculating",
            "%t. I require distance immediately.",
            "%t. That was closer than the theory allows.",
            "%t. Recalculating.",
            "%t. I am not built for this proximity.",
            "%t. Somebody intercept. Please.",
            "%t. The margin has become uncomfortable.",
            "%t. This is why I stand behind somebody larger.",
            "%t. Structural integrity: poor.",
            "%t. I have miscalculated.",
            "Do not let it touch me again, %t.",
            "%t. Blink is looking increasingly attractive.",
            "%t. That should not have connected.",
            "%t. I am a delicate instrument.",
            "%t. Withdrawing. Obviously.",
            "%t. The odds are deteriorating.",
            "%t. Someone do something useful.",
            "/em checks his own condition with alarm",
            "%t. This is precisely the scenario I dislike.",
            "%t. Too close. Far too close.",
            "%t. I would like a wall between us.",
            "Note to self: more armour. There is no more armour, %t.",
            "%t. Critical. Genuinely critical.",
            "%t. I have made an error in positioning.",
            "%t. That is a great deal of my blood.",
            "%t. Distance. Distance. Distance.",
            "%t. The experiment is failing.",
            "%t. I cannot absorb this. Nobody can.",
        },
        ["REACT:DEATH"] = {
            "%t. Ah. Miscalculated.",
            "%t. That is embarrassing.",
            "/em collapses in a heap of expensive robes",
            "%t. The variables were unfavourable.",
            "%t. I shall revise my model.",
            "%t. A regrettable outcome.",
            "%t. Someone will write this up incorrectly.",
            "%t. Cloth. It was always going to be cloth.",
            "Do not touch my components, %t.",
            "%t. I had a counter for that. It required time.",
            "%t. Well. That settles the hypothesis.",
            "%t. Killed by something with a stick. Undignified.",
            "%t. The theory was sound. The execution was not.",
            "Note the cause of death precisely, %t.",
            "%t. I want a rematch under controlled conditions.",
            "%t. That should not have been survivable. It was not.",
            "%t. A failure of positioning, not of theory.",
            "%t. Someone fetch my notes.",
            "%t. Fascinating, actually. Briefly.",
            "%t. I have died more elegantly before.",
            "%t. Tell the Kirin Tor it was quick.",
            "%t. Insufficient distance. Always insufficient distance.",
            "/em goes still, one hand still shaping a spell",
            "The arcane does not save you from arithmetic, %t.",
            "%t. That was an error I will not repeat.",
            "%t. I require a resurrection and an apology.",
            "%t. Reduced to a data point.",
            "%t. So much for the elegant solution.",
            "Do not step on the reagents, %t.",
            "%t. I shall be back and considerably more prepared.",
        },
        ["REACT:RESURRECT"] = {
            "Thank you. Now, where are my components?",
            "Restored. Let us not discuss it.",
            "/em rises and immediately checks his robes",
            "That was inefficient. Continuing.",
            "Back. Do not comment.",
            "The model has been updated.",
            "Right. New tactics.",
            "I have learned something. Reluctantly.",
            "Reconstituted.",
            "Where is my water? I will conjure more.",
            "That will not happen again.",
            "Standing. Slightly humiliated.",
            "Give me a moment to re-establish my wards.",
            "Back, and considerably more cautious.",
            "The arcane is patient with its practitioners.",
            "Rebuilt from a very good set of notes.",
            "I intend to stand much further away this time.",
            "Functional. Barely dignified.",
            "Do not look at me like that.",
            "Right. Position, then power.",
            "/em brushes himself off with wounded pride",
            "I have revised the plan entirely.",
            "Returned. Let us pretend otherwise.",
            "That gap in the record is now closed.",
            "Back to work. Further back, specifically.",
            "One resurrection, gratefully received.",
            "My hands work. That is all I require.",
            "The experiment resumes.",
            "Thank you. Genuinely. Now, distance.",
            "Upright and recalculating.",
        },
        ["REACT:KILLINGBLOW"] = {
            "%t. As predicted.",
            "%t. Q.E.D.",
            "/em dusts his hands with mild satisfaction",
            "The maths were never in your favour, %t.",
            "%t. Resolved.",
            "%t. That is the expected result.",
            "%t. One variable removed.",
            "%t. Cleanly done.",
            "You should have studied, %t.",
            "%t. Another confirmation of the theory.",
            "%t. Reduced to component parts.",
            "The arcane is not interested in your effort, %t.",
            "%t. That concludes the demonstration.",
            "%t. Predictable from the opening.",
            "%t. Filed under: resolved.",
            "You were an interesting case. Briefly, %t.",
            "%t. Precisely as calculated.",
            "%t. There. Tidy.",
            "%t. The elegant solution, applied.",
            "%t. Nothing personal. Merely inevitable.",
            "%t. One less complication.",
            "%t. That is what preparation looks like.",
            "%t. The result was never in doubt.",
            "%t. Efficiently resolved.",
            "You brought a sword to a theorem, %t.",
            "Concluded, %t.",
            "%t. Another entry for the record.",
            "%t. The demonstration is complete.",
            "%t. Simple, in the end.",
            "%t. Next problem.",
        },
        ["REACT:COMBATSTART"] = {
            "%t. Very well. Let us be quick.",
            "You have interrupted my reading, %t.",
            "/em begins shaping something complicated",
            "%t. Positions, please.",
            "%t. This will be instructive.",
            "%t. I would advise against this.",
            "Do keep your distance. For your sake, %t.",
            "%t. Another practical demonstration, then.",
            "You have chosen the wrong opponent, %t.",
            "Let us establish the parameters, %t.",
            "%t. I am extremely well prepared.",
            "%t. This will not take long.",
            "Do try to make it interesting, %t.",
            "%t. The arcane is already moving.",
            "You are standing in a very poor position, %t.",
            "%t. Very well. Applied theory.",
            "%t. I have several unpleasant options.",
            "Consider this your only warning, %t.",
            "%t. Somebody hold them. I need six seconds.",
            "%t. Beginning.",
            "You will regret closing the distance, %t.",
            "I have read about people like you, %t.",
            "Let us see how you handle the cold, %t.",
            "%t. An opportunity for research.",
            "Do not touch anything, %t.",
            "Ready. Obviously, %t.",
            "%t. This is going to be one-sided.",
            "%t. Very well. Come and be studied.",
            "%t. The demonstration begins.",
            "Stand still. It is easier for both of us, %t.",
        },
        ["REACT:COMBATEND"] = {
            "As expected.",
            "Concluded.",
            "/em straightens his sleeves",
            "That was hardly worth the mana.",
            "Results recorded.",
            "Tidy enough.",
            "Nothing left to solve here.",
            "I shall need to sit down and drink something.",
            "The demonstration is over.",
            "Efficient. Barely.",
            "Do not touch the residue.",
            "Someone should catalogue this.",
            "Mana expenditure: acceptable.",
            "That is that.",
            "Back to the reading, then.",
            "A satisfactory outcome.",
            "Nothing further to calculate.",
            "I require water. Naturally I will make it.",
            "Concluded without incident. Mostly.",
            "Filed and forgotten.",
            "The field is clear.",
            "A predictable resolution.",
            "Right. Recovering mana.",
            "Someone remind me why I leave the tower.",
            "Adequate work, all round.",
            "Nothing here worth a paper.",
            "That went according to theory.",
            "Order restored.",
            "Let us move before something else arrives.",
            "Done. Efficiently, I think.",
        },
        ["REACT:INTERRUPTED"] = {
            "%t. Rude.",
            "%t. That was six seconds of work.",
            "/em glares over the ruined working",
            "You have no idea what you just interrupted, %t.",
            "%t. Very well. The short version.",
            "%t. That was deliberate. I noticed.",
            "Do you know how long that takes, %t?",
            "%t. Interrupted. Adjusting.",
            "%t. Somebody deal with that one.",
            "You have delayed the inevitable by four seconds, %t.",
            "%t. A crude tactic. Effective, admittedly.",
            "%t. That will not work twice.",
            "My concentration is not yours to break, %t.",
            "%t. Fine. Instant casts, then.",
            "You have made this take longer. Congratulations, %t.",
            "%t. Noted. Adapting.",
            "That was competent of you. Once, %t.",
            "%t. Silence me and I improvise.",
            "%t. The theory survives the interruption.",
            "%t. Cover me. I am beginning again.",
            "%t. That cost me a very good spell.",
            "Do that again and I will use the unpleasant one, %t.",
            "%t. Recalculating. Loudly.",
            "You have my complete attention now, %t.",
            "%t. How very tiresome.",
            "%t. The working is broken. The intent is not.",
            "%t. Fine. We do this inelegantly.",
            "That is one interruption. You get no more, %t.",
            "%t. Adjusting the approach.",
            "%t. Beginning again. Watch closely.",
        },
    },
}

-- Warrior -----------------------------------------------------------------
-- Voice: a scarred veteran. Blunt, tactical, gallows humour, no mysticism.

RPVox_CLASSES.WARRIOR = {
    name = "Warrior",
    spells = {
        { spell = "Charge",             icon = "Interface\\Icons\\Ability_Warrior_Charge",        chance = 10 },
        { spell = "Heroic Strike",      icon = "Interface\\Icons\\Ability_Rogue_Ambush",          chance = 10 },
        { spell = "Rend",               icon = "Interface\\Icons\\Ability_Gouge",                 chance = 10 },
        { spell = "Thunder Clap",       icon = "Interface\\Icons\\Spell_Nature_ThunderClap",      chance = 10 },
        { spell = "Battle Shout",       icon = "Interface\\Icons\\Ability_Warrior_BattleShout",   chance = 10 },
        { spell = "Demoralizing Shout", icon = "Interface\\Icons\\Ability_Warrior_WarCry",        chance = 10 },
        { spell = "Intimidating Shout", icon = "Interface\\Icons\\Ability_GolemThunderClap",      chance = 10 },
        { spell = "Execute",            icon = "Interface\\Icons\\INV_Sword_48",                  chance = 10 },
        { spell = "Taunt",              icon = "Interface\\Icons\\Spell_Nature_Reincarnation",    chance = 10 },
        { spell = "Sunder Armor",       icon = "Interface\\Icons\\Ability_Warrior_Sunder",        chance = 10 },
        { spell = "Shield Slam",        icon = "Interface\\Icons\\Ability_Warrior_ShieldSlam",    chance = 10 },
        { spell = "Mortal Strike",      icon = "Interface\\Icons\\Ability_Warrior_SavageBlow",    chance = 10 },
    },
    lines = {
        -- Abilities -----------------------------------------------------
        ["SPELL:Charge"] = {
            "%t. OUT OF MY WAY!",
            "%t. Closing!",
            "You're mine, %t.",
            "%t. No more running.",
            "%t. Here I come.",
            "Brace, if you've time, %t.",
            "%t. Straight through the middle!",
            "%t. Too slow!",
            "%t. Distance never saved anyone.",
            "%t. Meet me halfway, then.",
            "%t. Coming through!",
            "Stand and take it, %t!",
        },
        ["SPELL:Heroic Strike"] = {
            "Take that, %t!",
            "Hard enough for you, %t?",
            "%t. Straight through the guard.",
            "%t. That's how it's done.",
            "Feel the weight of it, %t.",
            "%t. One good swing beats ten clever ones.",
            "%t. Simple. Effective.",
            "Down the middle, %t.",
        },
        ["SPELL:Rend"] = {
            "Bleed for a while, %t.",
            "%t. That won't close on its own.",
            "Let the wound do the work, %t.",
            "%t. Slow and messy. My favourite.",
            "You'll feel that for the rest of it, %t.",
            "%t. Opened up nicely.",
            "Count your blood while you can, %t.",
            "Patience. You're already losing, %t.",
        },
        ["SPELL:Thunder Clap"] = {
            "All of you. Now, %t.",
            "Ground shakes. So do you, %t.",
            "%t. Everyone gets one.",
            "Slow down, the lot of you, %t.",
            "Feel that in your teeth, %t?",
            "%t. No favourites here.",
            "%t. That's for the whole crowd.",
        },
        ["SPELL:Battle Shout"] = {
            "%t. ON ME!",
            "Stand together, %t!",
            "%t. Backs straight. Shields up.",
            "%t. With me, and we hold!",
            "%t. Hearts high! Blades higher!",
            "%t. Nobody breaks today.",
            "Let them hear us coming, %t.",
            "%t. Steady. We've seen worse.",
            "Fight like you mean it, %t!",
            "%t. For everyone still standing!",
        },
        ["SPELL:Demoralizing Shout"] = {
            "You've already lost. Look at you, %t.",
            "%t. Nobody's coming to help.",
            "Hear that? That's your nerve going, %t.",
            "%t. Doubt is heavier than armour.",
            "You're smaller than you were, %t.",
            "Go on. Reconsider, %t.",
            "That's the sound of the fight leaving you, %t.",
        },
        ["SPELL:Intimidating Shout"] = {
            "RUN, THEN, %t!",
            "GET OUT OF MY SIGHT, %t!",
            "Cowards. All of you, %t.",
            "%t. That's right. Scatter.",
            "%t. Fear does my work for me.",
            "Go! And tell the rest, %t!",
            "%t. I said MOVE!",
        },
        ["SPELL:Execute"] = {
            "%t. It's over. Lie down.",
            "%t. This is the last one.",
            "No more standing for you, %t.",
            "%t. Finished.",
            "Should have run when you could, %t.",
            "%t. End of the line.",
            "I'll make it quick. Quicker than you deserve, %t.",
            "Down. For good, %t.",
        },
        ["SPELL:Taunt"] = {
            "%t. Over here, ugly!",
            "Look at ME, %t.",
            "%t. Forget them. I'm the problem.",
            "Come on then, I'm right here, %t.",
            "Face me, not them, %t.",
            "Am I not worth your time, %t?",
            "%t. Eyes on me!",
            "You want someone to hit? Try this, %t.",
        },
        ["SPELL:Sunder Armor"] = {
            "%t. Chip away. That's the trick.",
            "%t. Another plate gone.",
            "%t. Armour's only good until it isn't.",
            "%t. Piece by piece.",
            "%t. Nothing holds forever.",
            "Softening you up, %t.",
        },
        ["SPELL:Shield Slam"] = {
            "%t. Shield's a weapon too.",
            "Didn't see that coming, did you, %t.",
            "%t. Nose first.",
            "%t. Hard edge, hard lesson.",
            "%t. That's what it's for.",
            "Take the whole thing, %t.",
        },
        ["SPELL:Mortal Strike"] = {
            "%t. That one won't heal right.",
            "%t. Deep. Very deep.",
            "%t. No stitching that.",
            "%t. The wound that stays a wound.",
            "Bleed and stay bleeding, %t.",
            "%t. That's the one that matters.",
        },

        -- Reactions -----------------------------------------------------
        ["REACT:LOWHEALTH"] = {
            "%t. Still standing.",
            "%t. That one hurt. Good.",
            "%t. I've bled worse into worse dirt.",
            "%t. Armour's holding. Barely.",
            "%t. Not done. Not close to done.",
            "Come on then, finish it, %t.",
            "%t. A scratch. A deep, worrying scratch.",
            "%t. My shield arm's going.",
            "%t. Bandage later. Fight now.",
            "You'll tire before I fall, %t.",
            "%t. This is where I get stubborn.",
            "%t. Blood in my eyes. Fine.",
            "%t. Been here before. Walked out before.",
            "Stay upright, you idiot, %t.",
            "%t. Grip's slipping. Grip harder.",
            "%t. Ribs. Definitely ribs.",
            "%t. One arm's enough.",
            "Hold the ground. Just hold it, %t.",
            "%t. I don't fall easy.",
            "Keep swinging. Always keep swinging, %t.",
            "%t. That's a lot of my blood down there.",
            "You've hurt me. Now finish it or run, %t.",
            "Legs, don't you dare, %t.",
            "%t. Nearly through the plate.",
            "%t. Old wounds and new ones.",
            "Fight's not over till I say, %t.",
            "%t. I've been carried off fields before. Not today.",
            "%t. Every soldier's been here.",
            "%t. Steady, steady.",
            "%t. Pain's just information.",
            "%t. Still breathing. Mostly.",
            "%t. Should've brought a bigger shield.",
            "Come on, one more push, %t.",
            "You want this ground? Take it off my body, %t.",
            "%t. Half dead is still half alive.",
            "The plate's ruined. So are you, %t.",
            "%t. I heal ugly. Always have.",
            "%t. That'll scar. Good.",
            "%t. Don't tell the healers. They fuss.",
            "%t. The line holds while I do.",
            "%t. I've had worse from friendlier hands.",
            "%t. Wobbling. Not falling.",
            "%t. My grandfather died standing. Family habit.",
            "%t. Not much left in the arms.",
            "%t. Blood loss is a state of mind.",
            "%t. Just a little further.",
            "Cut deeper next time. Save us both trouble, %t.",
            "%t. I can still lift this.",
            "Down to the last of it, %t.",
            "Hold. HOLD, %t.",
            "You are running out of chances, %t.",
            "%t. My knees are voting to stop.",
            "%t. Fine. The hard way.",
            "%t. This is the part where I get angry.",
            "%t. There's still fight in the old dog.",
            "%t. Nothing vital. Probably.",
            "Keep your feet. Keep your feet, %t.",
            "%t. Bleeding's just slower fighting.",
            "Was that your best, %t?",
            "%t. One more round in me.",
            "%t. Everything hurts. Everything works.",
            "%t. Don't like the sound of that rib.",
            "Try harder. I'm still here, %t.",
            "%t. I've walked home worse than this.",
            "%t. The armour did its job. Mostly.",
            "%t. Not the worst day I've had.",
            "%t. Two good hands, one good arm.",
            "%t. Slower now. Not weaker.",
            "Give me a moment. Then give me a weapon, %t.",
            "You're close. That's all you are, %t.",
            "%t. The dirt can wait.",
            "%t. This is nothing. This is nothing.",
            "%t. Been dying since my first campaign.",
            "%t. Cracked. Not broken.",
            "%t. One good hit left. Make it count.",
            "%t. I'll sleep when it's finished.",
            "%t. Vision's going grey at the edges.",
            "Enough of me left to kill you, %t.",
            "%t. Stubbornness beats healing every time.",
            "Get up. You always get up, %t.",
            "%t. The pain can wait its turn.",
            "%t. Not while I can hold a blade.",
            "%t. Fine. Bleed together, then.",
            "%t. Nearly finished. Nearly.",
            "%t. Weight of the shield's doubled.",
            "%t. Fought worse on less.",
            "%t. Never lost a fight standing up.",
            "%t. One breath. One more swing.",
            "You'll have to take me apart, %t.",
            "%t. Stitch it later.",
            "%t. Still enough blood for one more.",
            "%t. The wound's honest. I respect that.",
            "Hurt me again. See what happens, %t.",
            "%t. I don't have the wind for speeches.",
            "%t. This body's carried me through worse.",
            "Set your feet. Set your feet, %t.",
            "%t. That could have been fatal. Wasn't.",
            "Half a soldier still beats you, %t.",
            "%t. End of my strength, not my will.",
            "Hold the line. Even alone, %t.",
        },
        ["REACT:DEATH"] = {
            "%t. Not... finished...",
            "%t. Should have hit harder.",
            "%t. Tell them I stood.",
            "%t. Damn.",
            "%t. I've had worse. Not much worse.",
            "%t. That's the one.",
            "Get up. Get up. ...No, %t.",
            "%t. Fought well. Both of us.",
            "Keep my shield, %t.",
            "%t. Bleeding out. Typical.",
            "%t. Don't drag me. I'll walk.",
            "%t. Is that all it took?",
            "I'll remember your face, %t.",
            "%t. Should have worn the heavier plate.",
            "%t. One more swing. That's all I needed.",
            "%t. Blood in the mouth. Familiar.",
            "%t. A soldier's end. Fine.",
            "%t. Ground's cold.",
            "%t. No last words. Never had any.",
            "%t. The line breaks. So do I.",
            "%t. I've fallen before. I get up.",
            "%t. Finish it, then.",
            "%t. Someone take the flank.",
            "%t. Poor form. Effective, though.",
            "%t. That'll leave a mark.",
            "Rest? Never liked it, %t.",
            "Hold the line without me, %t.",
            "%t. Tell my brother it was quick.",
            "%t. I don't yield. I just stop.",
            "Down. Not out. Just... down, %t.",
            "%t. Fell fighting. Good enough.",
            "%t. My arms won't answer.",
            "%t. Should have blocked that.",
            "%t. Dying's the easy part.",
            "%t. Never ran. Remember that.",
            "%t. Where's my axe.",
            "Cut me down properly next time, %t.",
            "%t. Slow. Everything's slow.",
            "%t. So this is the last hill.",
            "%t. Save the eulogy. Sharpen my blade.",
            "%t. Wounds catch up eventually.",
            "%t. The armour held. I didn't.",
            "%t. Good hit. Credit where it's due.",
            "%t. I'll be back on the field.",
            "%t. Send word to the regiment.",
            "%t. Enough steel in me for a smithy.",
            "%t. It stops hurting. That's the bad sign.",
            "%t. I've bled on better ground.",
            "%t. A soldier dies standing. Give me a moment.",
            "%t. My legs. Where are my legs.",
            "%t. Not a bad way out.",
            "%t. Should have drunk less last night.",
            "Take the field. Take it, %t.",
            "%t. That was the killing blow. Well found.",
            "%t. My grip's gone.",
            "%t. They'll sing something. Probably wrong.",
            "%t. Battle's over for me.",
            "Get the wounded out first, %t.",
            "%t. I hate losing.",
            "Steel and dirt. Fitting, %t.",
            "%t. Curse it all.",
            "Give me a weapon. Any weapon, %t.",
            "%t. So heavy.",
            "%t. I'll walk it off. ...I won't.",
            "%t. One good arm left. Not enough.",
            "%t. Beaten. Say it plainly.",
            "%t. The horn sounds. Not for me.",
            "%t. Sword's still in my hand. Good.",
            "%t. Bury me facing the enemy.",
            "%t. Bones break. So be it.",
            "%t. Should have led with the shield.",
            "%t. I have earned the rest.",
            "Down goes another old soldier, %t.",
            "%t. Fought too long. Always do.",
            "%t. Cold. Very cold.",
            "%t. Not much of a death.",
            "Hah. Got you at least once, %t.",
            "%t. That's the end of the watch.",
            "%t. Nothing left in me.",
            "Get off. Let me fall properly, %t.",
            "%t. They'll need someone on that gate.",
            "%t. My father died like this.",
            "%t. A clean death. Rare.",
            "%t. The battle goes on. Good.",
            "%t. It's dark and I'm angry about it.",
            "Give my rations to the recruits, %t.",
            "%t. Better men than me went first.",
            "%t. Damn good fight, though.",
            "See you on the other side, %t.",
            "%t. The pain stops. Shame.",
            "%t. I stood the whole time. Note that.",
            "Steel out. Lights out, %t.",
            "Do it faster next time, %t.",
            "%t. So much for the plan.",
            "%t. The shield wall failed.",
            "%t. Just a scratch. A very large scratch.",
            "Rest, they said. Never listened, %t.",
            "Down in the dirt where I started, %t.",
            "%t. Again. And I'll rise again.",
            "%t. Tell them the line held as long as I did.",
        },
        ["REACT:RESURRECT"] = {
            "Where's my weapon.",
            "Right. Back to it.",
            "Who won?",
            "Everything aches. Everything works.",
            "Up. Again.",
            "Don't fuss. I'm fine.",
            "That's twice today.",
            "Owe someone a drink for that.",
            "Back on my feet where I belong.",
            "Did we hold?",
            "Stiff. Nothing broken that matters.",
            "Give me a moment and a blade.",
            "Bad dreams. Worse waking.",
            "Still in one piece. Roughly.",
            "Point me at them.",
            "That's enough lying down.",
            "Death's overrated.",
            "The armour's ruined. Again.",
            "How long was I out?",
            "Back to work.",
            "Somebody owes me a rematch.",
            "Feels like a bad hangover with knives.",
            "On your feet, soldier. That's me.",
            "Thanks. Don't make a thing of it.",
            "Second wind. Or third.",
            "Where were we?",
            "Bones set, temper's worse.",
            "Never trust a quiet battlefield.",
            "Fine. Round two.",
            "I've been carried before. Hate it.",
            "Nothing a fight won't cure.",
            "Legs work. Good enough.",
            "That's the last time I take that flank.",
            "Standing. Barely. Standing.",
            "Get me back in the line.",
            "Someone find my shield.",
            "Wake up, old man. Work to do.",
            "The regiment's still short a body. Mine.",
            "Well, that was embarrassing.",
            "Not the first time. Not the last.",
            "Back among the noise.",
            "I've got unfinished business.",
            "Alive. Annoyed.",
            "Cracked ribs and a grudge.",
            "Right then. Where's the enemy.",
            "Do not tell the recruits about this.",
            "Death did not take. It rarely does.",
            "Give me one minute. Then I fight.",
            "My head's ringing like a smithy.",
            "Battered, not beaten.",
            "The field's still there. So am I.",
            "Whoever patched me: good work.",
            "Back to the grind.",
            "Should have stayed down. Never do.",
            "Same fight. Angrier soldier.",
            "The wound's fresh. So's the anger.",
            "Nothing that a shield won't fix.",
            "Let's finish what dropped me.",
            "Old soldiers do not stay down.",
            "One more scar for the collection.",
            "Enough rest for a lifetime.",
            "The dirt didn't want me.",
            "Steel in hand, feet under me.",
            "I've come back from worse dirt.",
            "That's the trouble with dying. It sticks with you.",
            "Fit to fight. Roughly.",
            "Right. Who's next.",
            "Take the front. I'm behind you.",
            "Standing takes practice. I've had plenty.",
            "Never could sleep through a battle.",
            "Every time I get comfortable, something kills me.",
            "Good as new. Nothing like new.",
            "Back where I fell. Fitting.",
            "The wound will keep. The fight won't.",
            "My armour's seen better decades.",
            "Someone hand me something heavy.",
            "Enough of that nonsense.",
            "Alive, upright, and irritated.",
            "The pain came back first. It always does.",
            "Same body, more holes.",
            "Get the line reformed.",
            "I have died in worse places.",
            "Move. Before the legs think twice.",
            "Fine. Where's the fight.",
            "Nothing broken that I'll admit to.",
            "That's what the plate is for.",
            "Back from the mud again.",
            "Do not look so surprised.",
            "The war didn't stop for me. Good.",
            "Shield up. Feet set. Continue.",
            "One more life spent poorly.",
            "Awake and looking for someone.",
            "The healers earned their pay.",
            "Standing hurts. Sitting hurts worse.",
            "Let's not do that again this week.",
            "Rise, soldier. That's an order to myself.",
            "The dead can wait. I've work.",
            "Sharpen it. We go again.",
            "Back on the line.",
            "Still here. Still angry.",
        },
        ["REACT:KILLINGBLOW"] = {
            "Down you go, %t.",
            "%t. Next.",
            "%t. Should have run.",
            "%t. That's one.",
            "Rest, soldier, %t.",
            "%t. Fought poorly. Died the same.",
            "%t. Nothing personal.",
            "%t. Clean enough.",
            "You picked the wrong line, %t.",
            "Stay down this time, %t.",
            "%t. Well fought. Not well enough.",
            "%t. That's how it ends.",
            "%t. One less blade against us.",
            "Say hello to the rest, %t.",
            "You had the numbers. Not the nerve, %t.",
            "Off the field, %t.",
            "%t. Add it to the count.",
            "%t. Poor form at the end there.",
            "You'll not stand again, %t.",
            "%t. Simple as that.",
            "Should have kept your guard up, %t.",
            "%t. Finished. Move on.",
            "%t. Another for the ledger.",
            "Take the rest. You earned it, %t.",
            "That's the fight out of you, %t.",
            "Some die loud. You didn't, %t.",
            "%t. The dirt takes everyone.",
            "You wanted a soldier's death. There, %t.",
            "%t. That's what happens.",
            "%t. Better men fell to worse.",
            "%t. Nothing to say? Good.",
            "%t. Neat work.",
            "%t. Bury him properly.",
            "%t. One down. Plenty left.",
            "You lasted longer than most, %t.",
            "The line holds. You don't, %t.",
            "%t. So much for that.",
            "%t. Should have brought friends.",
            "You did bring friends. Where are they now, %t?",
            "Down. Done, %t.",
            "%t. War's simple, in the end.",
            "%t. That's the whole of it.",
            "%t. Nothing clever about it.",
            "%t. Good armour. Bad footwork.",
            "You'll not be missed by me, %t.",
            "Rest easy. Or don't, %t.",
            "%t. It's over. Truly over.",
            "Enough out of you, %t.",
            "%t. That was the last mistake.",
            "Fold up, %t.",
            "Down goes another, %t.",
            "You fought. It wasn't enough, %t.",
            "%t. Now stay in the dirt.",
            "%t. Done and dusted.",
            "The ground's yours now, %t.",
            "%t. That's the job.",
            "%t. Not a wasted swing.",
            "You'll make a fine warning, %t.",
            "Off you go, %t.",
            "%t. Silence. Better already.",
            "%t. One more for the pile.",
            "%t. Should have surrendered.",
            "%t. War doesn't negotiate.",
            "The end of your watch, %t.",
            "Never saw it coming, did you, %t.",
            "%t. That's the price.",
            "Move aside. Someone braver's next, %t.",
            "You had your chance, %t.",
            "%t. Finished cleanly. Rare enough.",
            "%t. Nothing personal. Just the line.",
            "Down, and I'm still standing, %t.",
            "Give me a real fight next time, %t.",
            "Your friends saw that, %t.",
            "%t. One less on the other side.",
            "Cut down where you stood. Respect, %t.",
            "%t. That'll do.",
            "You stood your ground. It wasn't enough ground, %t.",
            "The war continues without you, %t.",
            "Sleep it off. Forever, %t.",
            "%t. Another name I won't learn.",
            "%t. That's the end of that argument.",
            "Steel wins arguments, %t.",
            "%t. Should have stayed home.",
            "%t. Nothing left to fight.",
            "Down like the rest, %t.",
            "You were the easy one, %t.",
            "%t. That was quick. Too quick.",
            "%t. Enough of that.",
            "%t. The field claims another.",
            "You lost. Simple, %t.",
            "%t. Now there is one fewer.",
            "I'll remember the fight. Not you, %t.",
            "%t. Well struck, if I say so.",
            "%t. That's a body, not a soldier.",
            "%t. Nothing more to prove.",
            "Take the loss with you, %t.",
            "Off the board, %t.",
            "Down, and quiet at last, %t.",
            "%t. That's how the line is held.",
            "%t. One more, then. Who's next.",
        },
        ["REACT:COMBATSTART"] = {
            "%t. Shields up!",
            "%t. Here we go.",
            "%t. About time.",
            "%t. Right. Work.",
            "%t. Form up!",
            "Let's be quick about it, %t.",
            "You picked this, %t.",
            "%t. Blades out.",
            "%t. I was enjoying the quiet.",
            "%t. On me!",
            "%t. Steady, now.",
            "Come on then, %t.",
            "%t. That's close enough.",
            "%t. Bad decision, friend.",
            "Fine. Have it your way, %t.",
            "%t. Line up and die tidy.",
            "%t. This won't take long.",
            "Ready when you are, %t.",
            "%t. Another day, another brawl.",
            "Try me, %t.",
            "Hope you've eaten. Long fight, %t.",
            "Set your feet, %t.",
            "You want the ground? Earn it, %t.",
            "%t. Weapons free.",
            "Let's see what you've got, %t.",
            "%t. No talking. Fighting.",
            "%t. First blood, then.",
            "%t. Trouble found me. It usually does.",
            "Don't make me chase you, %t.",
            "Come get your lesson, %t.",
            "You'll regret standing there, %t.",
            "Fight's on, %t!",
            "%t. Draw. Now.",
            "%t. I've been itching for this.",
            "Right where I want you, %t.",
            "%t. Everyone stay sharp.",
            "%t. Charge or be charged.",
            "%t. Nothing fancy. Just steel.",
            "Get it over with, %t.",
            "You look confident. That'll pass, %t.",
            "%t. Time to work.",
            "Stand where I can reach you, %t.",
            "%t. This is my ground.",
            "%t. Enough talk.",
            "Watch the flanks, %t!",
            "%t. Better men have tried.",
            "Let's find out, %t.",
            "Move and you die tired, %t.",
            "%t. So be it.",
            "Come on, then, all of you, %t.",
            "%t. Nobody backs up.",
            "Take a breath. Your last quiet one, %t.",
            "Get behind me, %t.",
            "%t. I'll take the front.",
            "Odds are poor. For you, %t.",
            "Show me a proper fight, %t.",
            "%t. The talking's done.",
            "You'll do, %t.",
            "%t. Steady the line!",
            "%t. Not the first. Not the last.",
            "%t. Point taken. Now bleed.",
            "%t. Fists or blades, I don't mind.",
            "You'll break before I do, %t.",
            "%t. One of us walks away.",
            "%t. This is what I'm for.",
            "Try to make it interesting, %t.",
            "Look me in the eye, %t.",
            "%t. Now we're honest with each other.",
            "Bring it here, %t.",
            "%t. Nowhere to run to.",
            "%t. It's a good day for it.",
            "Let's keep this simple, %t.",
            "Stand and fight, %t!",
            "Don't say I didn't warn you, %t.",
            "You're in my way, %t.",
            "%t. Well. Nobody lives forever.",
            "%t. In we go.",
            "Cut them down, %t!",
            "That's a mistake you're making, %t.",
            "Hold the ground, %t!",
            "%t. I don't need luck.",
            "%t. Enough standing about.",
            "%t. Here it comes.",
            "%t. Blades high!",
            "You've had your warning, %t.",
            "%t. Nothing personal. Yet.",
            "%t. The line starts here.",
            "Right, ugly. You first, %t.",
            "%t. This is what I trained for.",
            "%t. Nobody breaks formation!",
            "%t. Someone's dying today.",
            "Come on. Test me, %t.",
            "%t. That's it. Closer.",
            "Fight or flee. Decide, %t.",
            "%t. I've no patience left.",
            "Get in and get it done, %t.",
            "%t. Bad odds. Good day.",
            "%t. Squaring up, are we?",
            "%t. Enough. Begin.",
            "%t. Feet set. Shield up. Go.",
        },
        ["REACT:COMBATEND"] = {
            "Clear!",
            "Line held.",
            "That'll do.",
            "Anyone hurt?",
            "Check the wounded.",
            "Over already?",
            "Good work. Now clean up.",
            "Still standing. All that matters.",
            "Regroup.",
            "Nothing left to hit.",
            "That was hardly a workout.",
            "Catch your breath.",
            "Sound off if you're breathing.",
            "Well fought.",
            "Sharpen up. There'll be more.",
            "The field's ours.",
            "Weapons down. For now.",
            "Everyone accounted for?",
            "Quiet again. Hate it.",
            "Get the bodies out of the way.",
            "Not bad. Not good either.",
            "Break's over in five.",
            "Blade needs a whetstone.",
            "That cost us less than I feared.",
            "Move out.",
            "We held. That's the whole job.",
            "Take the water while you can.",
            "Another fight, another dent.",
            "Armour's ruined. Worth it.",
            "Silence. Enjoy it.",
            "Count the wounded, not the dead.",
            "That's enough for one afternoon.",
            "Nothing broken. This time.",
            "Rest, but stay ready.",
            "The quiet never lasts.",
            "Job's done.",
            "Somebody get a fire going.",
            "We'll do it again tomorrow.",
            "Not one step back. Good.",
            "Stow it and move.",
            "That was the easy part.",
            "Watch the treeline anyway.",
            "Fight's over. Stay sharp.",
            "Right. What's next.",
            "I've had harder mornings.",
            "Good. Now the boring part.",
            "Everyone still upright? Good.",
            "Blood dries. Move on.",
            "Nothing to it.",
            "Pack up. We march.",
            "Another one survived.",
            "Bandage what needs it.",
            "That's the line held again.",
            "Done. Next.",
            "Nobody died standing still.",
            "Steady work, all of you.",
            "Quiet. Suspiciously quiet.",
            "Take the win.",
            "Don't get comfortable.",
            "That's how it's supposed to go.",
            "Fine soldiering.",
            "Clean your blades.",
            "One more day on the ledger.",
            "The dead can wait. The living can't.",
            "Rest while the resting's good.",
            "Not a bad scrap.",
            "Same again tomorrow, no doubt.",
            "Enough. Water and bandages.",
            "Sit down before you fall down.",
            "We're still here. That's the victory.",
            "Nothing more to do.",
            "That went about as expected.",
            "Field's quiet. Keep watch.",
            "Get some food in you.",
            "The war goes on. It always does.",
            "That's the last of them.",
            "Right. Back to marching.",
            "Fight's finished. Grumbling starts.",
            "Held the ground. Kept the men.",
            "Nothing worth reporting.",
            "Clean sweep.",
            "Well. That's over.",
            "Weapons check.",
            "We've earned a sit down.",
            "The noise stops. Good.",
            "Not a scratch worth mentioning.",
            "Fall back and regroup.",
            "That's the third today.",
            "Battle's done. So am I.",
            "Keep your armour on.",
            "The quiet before the next one.",
            "That's enough steel for now.",
            "Good. Nobody left standing but us.",
            "Job finished. Move along.",
            "Rest easy. Briefly.",
            "Now the walking starts.",
            "All clear here.",
            "Another fight behind us.",
            "Stand down. Slowly.",
            "Boots on. We're not done marching.",
        },
        ["REACT:INTERRUPTED"] = {
            "%t. Oi!",
            "Do that again, %t.",
            "%t. Rude.",
            "%t. That's cheating.",
            "You'll pay for that, %t.",
            "%t. Nice try.",
            "%t. Hands off.",
            "%t. Cheap shot.",
            "%t. I was busy!",
            "That earned you something nasty, %t.",
            "%t. Fine. The hard way.",
            "You've made this personal, %t.",
            "Wasted your trick, %t.",
            "%t. Was that meant to stop me?",
            "%t. Bought yourself a second. Well done.",
            "%t. Now I'm annoyed.",
            "Try that when I'm looking, %t.",
            "%t. Clever. Once.",
            "You'll not get another, %t.",
            "%t. That's twice.",
            "Steel doesn't need permission, %t.",
            "%t. Interrupt this, then.",
            "%t. Coward's move.",
            "You only made it worse, %t.",
            "%t. Enough of that.",
            "%t. Right. No more manners.",
            "%t. I don't need the fancy stuff anyway.",
            "%t. Hands. Blades. Same result.",
            "You have my full attention now, %t.",
            "%t. Bad idea.",
            "That'll cost you teeth, %t.",
            "Do you feel clever, %t?",
            "%t. Postponed. Not stopped.",
            "I'll finish it after you're down, %t.",
            "Keep your hands to yourself, %t.",
            "%t. Cute.",
            "You're only delaying the obvious, %t.",
            "That's the last one you get, %t.",
            "Now you've irritated a large man, %t.",
            "%t. Fine. Straight to the point, then.",
            "%t. Nothing lost but patience.",
            "%t. Well swung. Now die.",
            "Timing. I'll give you that, %t.",
            "%t. It doesn't work twice.",
            "Try it again. Please, %t.",
            "You've bought a beating, %t.",
            "%t. I don't stop. I pause.",
            "That was your one chance, %t.",
            "%t. Nothing changes.",
            "%t. Was that the plan? All of it?",
            "You are making this take longer, %t.",
            "%t. Wrong man to interrupt.",
            "%t. That's going in the report.",
            "%t. I'll remember that.",
            "You just made me angry, not slower, %t.",
            "%t. Enough games.",
            "%t. Interrupted. Not stopped.",
            "You'll want to run now, %t.",
            "%t. Good hands. Bad judgement.",
            "That is not how you win, %t.",
            "%t. Again? Really?",
            "%t. Fine. We do it plainly.",
            "%t. Cheap and clever. Neither helps.",
            "You're wasting both our time, %t.",
            "%t. That'll be the last time.",
            "%t. Poor manners.",
            "Should have hit harder while you were there, %t.",
            "Delay all you like, %t.",
            "You cannot stop a swing, %t.",
            "So you have a trick. I have a sword, %t.",
            "%t. Now stand still.",
            "You'll regret being fast, %t.",
            "%t. Enough. Come here.",
            "That was your best moment. It's over, %t.",
            "Try to keep up, %t.",
            "%t. One second, well wasted.",
            "You have annoyed the wrong soldier, %t.",
            "%t. That does not work on me.",
            "Save your strength, %t.",
            "Interruptions won't save you, %t.",
            "%t. Nothing but noise.",
            "You've made it worse for yourself, %t.",
            "%t. That was rude and pointless.",
            "%t. Right. Blade it is.",
            "You knocked the words out. Not the intent, %t.",
            "Try silence. It suits you, %t.",
            "%t. The fight goes on regardless.",
            "%t. I've been hit harder by weather.",
            "%t. Nice hands. Shame about the rest.",
            "%t. It only postpones the pain.",
            "You picked a slow way to lose, %t.",
            "That's enough from you, %t.",
            "You'll not do that twice, %t.",
            "%t. Fine. Old fashioned, then.",
            "You've spent your luck, %t.",
            "%t. Not clever enough.",
            "%t. Every trick has one use.",
            "%t. Well. Now I try harder.",
            "%t. That changes nothing.",
            "Stand still and take it, %t.",
        },
    },
}
