-- RPVox -- Priest-Rhyming class pack
--
-- Voice: song-lyric puns. Every line bends a well-known rock, hip hop or
-- R&B hook into the spell being cast. Kept in the addon rather than in saved
-- variables so it survives reinstalls and can live in version control.

RPVox_CLASSES = RPVox_CLASSES or {}

RPVox_CLASSES.PRIEST_RHYMING = {
    name = "Priest-Rhyming",
    class = "PRIEST",
    spells = {
        { spell = "Lesser Heal",               icon = "Interface\\Icons\\Spell_Holy_LesserHeal",               chance = 10 },
        { spell = "Heal",                      icon = "Interface\\Icons\\Spell_Holy_Heal",                     chance = 10 },
        { spell = "Greater Heal",              icon = "Interface\\Icons\\Spell_Holy_GreaterHeal",              chance = 10 },
        { spell = "Flash Heal",                icon = "Interface\\Icons\\Spell_Holy_FlashHeal",                chance = 10 },
        { spell = "Binding Heal",              icon = "Interface\\Icons\\Spell_Holy_BlindingHeal",             chance = 10 },
        { spell = "Renew",                     icon = "Interface\\Icons\\Spell_Holy_Renew",                    chance = 10 },
        { spell = "Prayer of Healing",         icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing02",        chance = 10 },
        { spell = "Prayer of Mending",         icon = "Interface\\Icons\\Spell_Holy_PrayerOfMending",          chance = 10 },
        { spell = "Circle of Healing",         icon = "Interface\\Icons\\Spell_Holy_CircleOfRenewal",          chance = 10 },
        { spell = "Power Word: Shield",        icon = "Interface\\Icons\\Spell_Holy_PowerWordShield",          chance = 10 },
        { spell = "Lightwell",                 icon = "Interface\\Icons\\Spell_Holy_SummonLightwell",          chance = 10 },
        { spell = "Desperate Prayer",          icon = "Interface\\Icons\\Spell_Holy_Restoration",              chance = 10 },
        { spell = "Resurrection",              icon = "Interface\\Icons\\Spell_Holy_Resurrection",             chance = 10 },
        { spell = "Pain Suppression",          icon = "Interface\\Icons\\Spell_Holy_PainSupression",           chance = 10 },
        { spell = "Power Word: Fortitude",     icon = "Interface\\Icons\\Spell_Holy_WordFortitude",            chance = 10 },
        { spell = "Prayer of Fortitude",       icon = "Interface\\Icons\\Spell_Holy_PrayerOfFortitude",        chance = 10 },
        { spell = "Divine Spirit",             icon = "Interface\\Icons\\Spell_Holy_DivineSpirit",             chance = 10 },
        { spell = "Prayer of Spirit",          icon = "Interface\\Icons\\Spell_Holy_PrayerofSpirit",           chance = 10 },
        { spell = "Shadow Protection",         icon = "Interface\\Icons\\Spell_Shadow_AntiShadow",             chance = 10 },
        { spell = "Prayer of Shadow Protection", icon = "Interface\\Icons\\Spell_Holy_PrayerofShadowProtection", chance = 10 },
        { spell = "Inner Fire",                icon = "Interface\\Icons\\Spell_Holy_InnerFire",                chance = 10 },
        { spell = "Fear Ward",                 icon = "Interface\\Icons\\Spell_Holy_Excorcism",                chance = 10 },
        { spell = "Power Infusion",            icon = "Interface\\Icons\\Spell_Holy_PowerInfusion",            chance = 10 },
        { spell = "Inner Focus",               icon = "Interface\\Icons\\Spell_Frost_WindWalkOn",              chance = 10 },
        { spell = "Dispel Magic",              icon = "Interface\\Icons\\Spell_Holy_DispelMagic",              chance = 10 },
        { spell = "Mass Dispel",               icon = "Interface\\Icons\\Spell_Arcane_MassDispel",             chance = 10 },
        { spell = "Cure Disease",              icon = "Interface\\Icons\\Spell_Holy_NullifyDisease",           chance = 10 },
        { spell = "Abolish Disease",           icon = "Interface\\Icons\\Spell_Nature_NullifyDisease",         chance = 10 },
        { spell = "Levitate",                  icon = "Interface\\Icons\\Spell_Holy_LayOnHands",               chance = 10 },
        { spell = "Mind Soothe",               icon = "Interface\\Icons\\Spell_Holy_MindSooth",                chance = 10 },
        { spell = "Mind Vision",               icon = "Interface\\Icons\\Spell_Holy_MindVision",               chance = 10 },
        { spell = "Shackle Undead",            icon = "Interface\\Icons\\Spell_Nature_Slow",                   chance = 10 },
        { spell = "Mind Control",              icon = "Interface\\Icons\\Spell_Shadow_ShadowWordDominate",     chance = 10 },
        { spell = "Fade",                      icon = "Interface\\Icons\\Spell_Magic_LesserInvisibilty",       chance = 10 },
        { spell = "Smite",                     icon = "Interface\\Icons\\Spell_Holy_HolySmite",                chance = 10 },
        { spell = "Holy Fire",                 icon = "Interface\\Icons\\Spell_Holy_SearingLight",             chance = 10 },
        { spell = "Holy Nova",                 icon = "Interface\\Icons\\Spell_Holy_HolyNova",                 chance = 10 },
        { spell = "Shoot",                     icon = "Interface\\Icons\\INV_Wand_01",                         chance = 10 },
        { spell = "Mind Blast",                icon = "Interface\\Icons\\Spell_Shadow_UnholyFrenzy",           chance = 10 },
        { spell = "Shadow Word: Pain",         icon = "Interface\\Icons\\Spell_Shadow_ShadowWordPain",         chance = 10 },
        { spell = "Shadow Word: Death",        icon = "Interface\\Icons\\Spell_Shadow_DemonicFortitude",       chance = 10 },
        { spell = "Mind Flay",                 icon = "Interface\\Icons\\Spell_Shadow_SiphonMana",             chance = 10 },
        { spell = "Psychic Scream",            icon = "Interface\\Icons\\Spell_Shadow_PsychicScream",          chance = 10 },
        { spell = "Shadowform",                icon = "Interface\\Icons\\Spell_Shadow_Shadowform",             chance = 10 },
        { spell = "Vampiric Embrace",          icon = "Interface\\Icons\\Spell_Shadow_UnsummonBuilding",       chance = 10 },
        { spell = "Vampiric Touch",            icon = "Interface\\Icons\\Spell_Holy_Stoicism",                 chance = 10 },
        { spell = "Silence",                   icon = "Interface\\Icons\\Spell_Shadow_ImpPhaseShift",          chance = 10 },
        { spell = "Shadowfiend",               icon = "Interface\\Icons\\Spell_Shadow_Shadowfiend",            chance = 10 },
        { spell = "Devouring Plague",          icon = "Interface\\Icons\\Spell_Shadow_BlackPlague",            chance = 10 },
        { spell = "Touch of Weakness",         icon = "Interface\\Icons\\Spell_Shadow_DeadofNight",            chance = 10 },
        { spell = "Hex of Weakness",           icon = "Interface\\Icons\\Spell_Shadow_FingerOfDeath",          chance = 10 },
        { spell = "Shadowguard",               icon = "Interface\\Icons\\Spell_Nature_LightningShield",        chance = 10 },
        { spell = "Starshards",                icon = "Interface\\Icons\\Spell_Arcane_StarFire",               chance = 10 },
        { spell = "Elune's Grace",             icon = "Interface\\Icons\\Spell_Holy_ElunesGrace",              chance = 10 },
        { spell = "Feedback",                  icon = "Interface\\Icons\\Spell_Shadow_RitualOfSacrifice",      chance = 10 },
        { spell = "Chastise",                  icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing",          chance = 10 },
        { spell = "Symbol of Hope",            icon = "Interface\\Icons\\Spell_Holy_SymbolOfHope",             chance = 10 },
        { spell = "Consume Magic",             icon = "Interface\\Icons\\Spell_Nature_Purge",                  chance = 10 },
    },
    lines = {

        ["MELEE"] = {
            "I raise a mace I would not choose; the Light forgives, but you still bruise.",
            "My words have failed, my patience too; so now the blunt end speaks to you.",
            "I asked you nicely. You declined. So here's the mace, and never mind.",
            "A holy man should never swing; and yet, here comes the holy thing.",
            "The book is heavy, so's the blow; I read to you, and down you go.",
            "This is not scripture, this is force; I do regret it, but of course.",
            "A prayer would take too long to say; the mace is faster anyway.",
            "My hands were made to bless and mend; they're doing something else, my friend.",
            "Blunt work for one who deals in grace; but someone had to close the space.",
            "I did not train for this at all; and yet I swing, and yet you fall.",
            "Not every sermon needs a word; sometimes the point is better heard.",
            "I strike, and I confess it plain: I rather liked that. Once again.",
            "The Light looks on and does not speak; perhaps because my aim is weak.",
            "Forgive me, for I strike anew; I've run quite out of things to do.",
            "Down comes the mace, and down go you; there's little else that I can do.",
        },

        ["REACT:LOWHEALTH"] = {
            "My blood is out, my breath is thin; the Light has not yet let me in.",
            "I've read of martyrs. They looked calm. I am not calm. I want a balm.",
            "Somebody, anybody, pray; I'd rather not go out this way.",
            "The wound is deep, the hour is late; I'm asking nicely. Hold the gate.",
            "I have a robe and not a shield; and yet I have not left the field.",
            "I mend the world and not myself; my health is on the highest shelf.",
            "A little help would not go wrong; I've held this longer than I'm strong.",
            "I've patched up half the realm today; the half that's left is me, okay?",
            "My hands still work, my knees do not; I'll take whatever help I've got.",
            "This is the part where faith is tried; I'd like it tried a bit less wide.",
            "Not yet, not yet, I've work to do; and half of that is healing you.",
            "The dark leans in and asks my name; I have not answered. All the same.",
            "I'll hold. I'll hold. I said I'd hold. That story's not so often told.",
            "The Light is near. I hope it's near. I'd like some proof, and fairly clear.",
            "I am not brave, I'm only slow; and slow is not the way to go.",
        },

        ["REACT:DEATH"] = {
            "I spoke of this a hundred times; and now it comes, and now it rhymes.",
            "The candle gutters, then it's gone; the Light goes out, the Light goes on.",
            "The book is closed, the page is turned; a lesson taught, a lesson learned.",
            "I am not frightened. That's not true. But there is little I can do.",
            "The dark is patient. So am I. We've met before. We'll meet. Goodbye.",
            "My work is done, my hands are still; I healed a lot. I always will.",
            "So that is death. It's very plain. I rather thought there'd be more rain.",
            "I go to see what I have preached; I hope the promises are reached.",
            "Do not grieve loudly. Grieve in verse. It's what I'd want. It could be worse.",
            "The Light did not arrive in time; but I'll not hold that as a crime.",
            "I'm told there's rest. I'll test the claim. Remember me, and spell my name.",
            "A priest should meet it unafraid; I'm mostly there. I'm partly swayed.",
            "That's all. The sermon's at an end. Somebody resurrect me, friend.",
            "Tell them I went without a sound; well, nearly. Put me in the ground.",
            "I fall, and falling, I compose; it scans, at least. And there it goes.",
        },

        ["REACT:RESURRECT"] = {
            "The door swung shut, the door swung wide; I've had a look at the other side.",
            "I'm up! I'm whole! I'm mostly here! Whoever did that, come stand near.",
            "A debt is owed and I will pay; but not today. But not today.",
            "I have returned, as I was taught; and rather sooner than I thought.",
            "Death held the door but let me through; I have some questions. So do you.",
            "Back to the world, back to the fray; I liked the quiet, though. I'll say.",
            "Thank you. Truly. Bless your hands. I'm told this rarely ever stands.",
            "Up from the dust and on my feet; the sermon isn't yet complete.",
            "I've seen the end. It's fine. It's bright. Now hold still while I set you right.",
            "Restored, returned, and slightly odd; I'll blame the journey, not the god.",
        },

        ["REACT:KILLINGBLOW"] = {
            "You had your chance, you had your say; the Light has filed it all away.",
            "Rest now. I mean that. Rest, and cease. I'd rather leave you here in peace.",
            "I did not hate you. Understand: it simply had to be my hand.",
            "That's one more soul the dark can keep; I'll say a word, then get some sleep.",
            "A short account, and neatly squared; I'd say I'm sorry. I'm prepared.",
            "The Light does not enjoy this part; and neither, mostly, does my heart.",
            "You fought me well. You fought me wrong. You will not feature in the song.",
            "Down goes another, quick and clean; the tidiest I've ever been.",
            "I'll pray for you. I always do. It's short, but I do get it through.",
            "You should have run. You should have hid. I gave you time. You never did.",
            "So ends the argument we had; the ending's fair, the timing's bad.",
            "One fewer problem in the world; the banner's dropped, the flag is furled.",
        },

        ["REACT:COMBATSTART"] = {
            "Well. Here we are. The talking's done. I'd hoped for two. There's only one.",
            "I came to bless and not to fight; and yet I'm rolling up the right.",
            "Stand back, stand back, and let me see how bad an afternoon this'll be.",
            "I offered peace. You offered this. I'll do my best. I rarely miss.",
            "A pity. Truly. Here we go. I'll try to keep the damage low.",
            "The Light is with me. So's a mace. Let's see which one of them you face.",
            "I do not relish what's ahead; but neither will I end up dead.",
            "Come on, then. Come and test the vow; I've held it long. I'll hold it now.",
            "You picked a priest. That's brave of you. You'll find we're harder than we do.",
            "Begin, then. Let the record show I asked you nicely not to go.",
            "My hands are up. My heart is calm. This will not end in any psalm.",
            "The hour has come, the hour is late; I'll meet it standing, straight and great.",
        },

        ["REACT:COMBATEND"] = {
            "The noise has stopped, the dust comes down; I'll take my quiet where it's found.",
            "That's finished, then. That's finished well. There's nothing more that I need tell.",
            "Silence at last, and hands unclenched; the thirst for it is barely quenched.",
            "I'll sit a moment. Let me be. There's nothing left to do but breathe.",
            "The field is still, the work is through; I'll count the living. There are few.",
            "An end. A blessing. Then a rest. Of all the outcomes, that's the best.",
            "Sheathe it, whatever you have drawn; the danger's passed, the thing is gone.",
            "I'll write this up in careful verse; the truth is bad, the rhyme is worse.",
            "Well. Nobody has died today. That's more than I can usually say.",
            "Peace, for a while. It never stays. But I have learned to like the days.",
        },

        ["REACT:INTERRUPTED"] = {
            "You cut me off. That's very rude. It ruins both the line and mood.",
            "A verse half-said is worse than none; now I must start where I'd begun.",
            "I had a rhyme! You broke the rhyme! I'll find another. Give me time.",
            "That was a lovely line, and now it's gone, and I don't know quite how.",
            "Interrupt a priest mid-prayer, and see how little the Light will care.",
            "You stopped my words. You'll wish you hadn't. Now the next one comes down harder.",
            "I nearly had it. Nearly there. And you have knocked it out the air.",
            "Do that again and see, my friend, how quickly I forget to mend.",
            "The couplet's ruined. So are you. It's what I'm going to see us through.",
            "You've cost me metre, breath and grace; I'll take all three back from your face.",
        },

        ["REACT:LEVELUP"] = {
            "A little further up the stair; the Light is thicker in the air.",
            "I know a little more than I did; another door comes off the lid.",
            "Stronger, and slower to be swayed; a better version, better made.",
            "The verse improves, the voice does too; there's more of me than there once grew.",
            "Onward and upward, so they write; I'm rather better than last night.",
            "New words to say, new ways to mend; a good day's climbing, in the end.",
            "I've grown. Not tall. But something's grown. I feel a little less alone.",
            "Another rung. Another rhyme. I'm getting better all the time.",
        },

        ["REACT:FALLING"] = {
            "The ground and I have plans to meet; this was not on my calendar sheet.",
            "Down, down, and down, without a plan; I am a falling holy man.",
            "Levitate! Levitate! Oh, no. I've left it far too late to go.",
            "This is not flight. Let's not pretend. This has a very solid end.",
            "The Light is up. I'm going down. I'll see it shortly, from the ground.",
            "I have no wings, I have no rope; I have a robe and fading hope.",
            "Gravity does not take a vow; it never has. It won't right now.",
            "A prayer, then. Short. There isn't room. I'm going straight towards my doom.",
        },

        ["REACT:DROWNING"] = {
            "The water's over, under, through; there's very little I can do.",
            "I cannot breathe and cannot pray; the words come out and float away.",
            "Up! Which way's up? I've lost the sky. This is a foolish way to die.",
            "My robe is heavy, so am I; the surface seems remarkably high.",
            "Air. Just a little. That's the ask. I'm not accustomed to this task.",
            "I healed a hundred. Not one swims. The irony is at my brim.",
            "Blessed are those who learned to float; I never did. I never wrote.",
            "Somebody reach. Somebody grab. I'd rather not end in the drab.",
        },

        ["REACT:DURABILITY"] = {
            "My robe is torn from hem to throat; it barely counts now as a coat.",
            "The stitching's gone, the cloth is thin; the weather's getting rather in.",
            "I look like something dragged and dropped; the mending really should have stopped.",
            "A holy man in holey cloth; I've made that joke. I'm not that wroth.",
            "This robe has seen the Light and worse; it's falling off me, verse by verse.",
            "I need a vendor, and I need him near; there's more of me than robe, I fear.",
            "Threadbare and blessed. One out of two. That's not the ratio I'd choose.",
            "A priest should look the part, they say; I look like I've been chewed today.",
            "Repairs, repairs, and gold to find; my dignity is close behind.",
        },

        ["IDLE:EAT"] = {
            "A little bread, a little cheese; a body runs on more than pleas.",
            "Even the pious have to chew; the spirit's fine, the stomach's due.",
            "I'll eat, and I'll be grateful for it; the Light provides. I still ignore it.",
            "Sustenance, plain and unadorned; a decent meal is never scorned.",
            "Break bread with me, or watch me eat; there's little dignity, but meat.",
            "A moment's peace, a mouthful too; there's not much finer one can do.",
        },

        ["IDLE:DRINK"] = {
            "Water is holy, so they claim; it quenches all the same the same.",
            "A drink, a breath, a quiet spell; the throat does most of the work as well.",
            "Cool on the tongue and down it goes; a small mercy, as mercy shows.",
            "I'll sip, and I'll say nothing more; the silence here is what it's for.",
            "Blessed is the one with a full cup; I'll drink it slowly, then get up.",
            "Nothing profound in this at all; I'm thirsty. That's the whole of it, all.",
        },

        ["IDLE:HEALTHSTONE"] = {
            "A stone, a swallow, and I'm well; how it works, I couldn't tell.",
            "I hold with prayer. I'll hold with this. It closes wounds. I'll not dismiss.",
            "Warlock craft in a holy hand; the Light and I have an understand.",
            "Down it goes, and up I come; borrowed grace, and rather rum.",
            "I should refuse. I never do. It works, and that will have to do.",
        },

        ["IDLE:MANAPOTION"] = {
            "A bitter blue, a swallowed flame; the well fills up, and I'm the same.",
            "Not elegant, but neither slow; the mana's back, and off I go.",
            "I'd rather meditate, I would; but this is faster, and it's good.",
            "Blue in the bottle, blue in me; the arithmetic of piety.",
            "One gulp, and I can heal again; the price of being useful, then.",
        },

        ["IDLE:FISHING"] = {
            "The water's still, and so am I; we watch each other, hour by.",
            "Nothing is biting. Nothing will. It's rather good for standing still.",
            "A patient art, a pointless one; and yet I've never left it done.",
            "The float goes down, the float goes up; I've caught a boot and half a cup.",
            "There is a sermon here, I'm sure; but I'd not put you through the cure.",
            "Peace, and a line, and nothing more; that's what an afternoon is for.",
        },

        ["IDLE:MINING"] = {
            "The rock gives up what rock will give; a hard and honest way to live.",
            "I swing, it splits, and there's the ore; I quite enjoy this. Rather more.",
            "Down in the dark and hitting stone; at least I'm useful, and alone.",
            "A pick, a vein, a steady beat; the rhythm of it's rather sweet.",
            "No prayer will shift a slab of ore; that's what the arms are given for.",
        },

        ["IDLE:HERBALISM"] = {
            "A gentle pull, a careful hand; the greenest gifts across the land.",
            "The Light grows quietly in the weeds; I take a few, and leave the seeds.",
            "Small leaves, small roots, small quiet joys; the best of work that makes no noise.",
            "I'll not uproot it all, I swear; I take my half and leave it there.",
            "There's grace in growing things, I find; it asks for nothing, and it's kind.",
        },

        ["IDLE:SKINNING"] = {
            "Forgive me, beast. It's rough, but true: there's little else that I can do.",
            "A blessing first, and then the blade; that's how the trade has always paid.",
            "I do not like this part at all; I say a word, and take the fall.",
            "Nothing is wasted. That's the rule. To leave it rotting would be cruel.",
            "Rest easy. What is left will serve. It's more respect than most deserve.",
        },

        ["IDLE:MOUNT"] = {
            "Up and away, and rather quick; the road is long, the light is thick.",
            "A faithful beast, a decent pace; I'd not get far at walking pace.",
            "Hooves on the road and wind in cloth; there's little in this world I'd swap.",
            "Onward, then. The world is wide. I've quite enjoyed the standing-side.",
            "Ride, and be grateful for the ride; there's worse than horses at your side.",
            "The saddle's hard, the going's fair; I'll say a small word for the mare.",
            "Away, away, and do not stop; the day's begun, and I'm on top.",
        },

        ["IDLE:QUESTACCEPT"] = {
            "Say what you need, and say it plain; I'll do it once, and not complain.",
            "Consider it accepted, then; I'll come and tell you how, and when.",
            "A task, a duty, and a word; the worst request I've never heard.",
            "Very well. It shall be done. I'd rather this than sit in sun.",
            "You've asked, and asking is enough; I'll manage, even if it's rough.",
            "I'll go. I'll see. I'll set it right. And I'll be back before the night.",
            "It's what I'm for, if I'm for aught; I'll take the errand that you brought.",
        },

        ["IDLE:QUEST"] = {
            "It's finished, and it's finished clean; the tidiest I've ever been.",
            "Done, delivered, and complete; now put the payment in my seat.",
            "There. As promised, so it stands. I'll take the gold in both my hands.",
            "The task is closed, the ledger's square; I'd do it twice, but only fair.",
            "You asked, I went, and here's the end; I'd do the same again, my friend.",
            "Concluded, neatly, as I said; now let me go and find a bed.",
        },

        ["IDLE:DISCOVERY"] = {
            "A place I've never stood before; I'll stand a moment, then explore.",
            "How strange. How fine. How very new. I'd write it down, if words would do.",
            "The world keeps having further in; I've barely started. I'll begin.",
            "Some corner nobody has blessed; I'll do it now, and leave the rest.",
            "New light, new air, new ground, new sky; a decent reason to be spry.",
            "I did not know this place was here; the world grows wider every year.",
        },

        ["IDLE:CRAFT:Alchemy"] = {
            "A measure, a mixture, a careful pour; a little less would have been more.",
            "It bubbles green. It should be blue. I'll drink it anyway. Won't you?",
            "The recipe says stir it slow; I stirred it fast an hour ago.",
            "Science and prayer, in equal part; the science does the harder start.",
        },

        ["IDLE:CRAFT:Blacksmithing"] = {
            "The hammer falls, the iron sings; a holy man makes worldly things.",
            "Heat it, hit it, hold it true; there's honest work in what I do.",
            "Not every blessing comes in words; some come in steel, and that's preferred.",
            "Bang, and bang, and bang again; the anvil has no time for men.",
        },

        ["IDLE:CRAFT:Cooking"] = {
            "A pot, a fire, a little thyme; the meal is late, but so's the rhyme.",
            "I burned it once. I'll burn it twice. The prayer above it makes it nice.",
            "Feeding the body's holy too; I'd rather cook than heal you through.",
            "Something is bubbling. Something's done. I'll serve it out to everyone.",
        },

        ["IDLE:CRAFT:Enchanting"] = {
            "A word, a dust, a gentle glow; the thing is better than it was, although.",
            "Magic on cloth and magic on steel; I never quite believe it's real.",
            "It shimmers now. It didn't then. I'll do the same trick once again.",
            "Enchanted, blessed, and slightly bright; I'd say that's turned out rather right.",
        },

        ["IDLE:CRAFT:Engineering"] = {
            "It ticks. It shouldn't. Stand you back. There's every chance of a loud crack.",
            "A cog, a spring, a length of wire; and, more than likely, open fire.",
            "The Light did not design this thing; I made it, and I made it sing.",
            "It's finished! Possibly! We'll see! Please stand a little way from me.",
        },

        ["IDLE:CRAFT:First Aid"] = {
            "A strip of cloth, a steady hand; the oldest healing in the land.",
            "No spell at all. Just linen, tight. And that's enough to set it right.",
            "Hold still, hold still, I'm nearly through; a bandage does what prayers can't do.",
            "Wrap it, tie it, let it be; the body does the rest, not me.",
        },

        ["IDLE:CRAFT:Jewelcrafting"] = {
            "A little stone, a lot of care; the light gets caught and settles there.",
            "Cut it, turn it, cut once more; it's better than it was before.",
            "Small work, close work, quiet and slow; the sort of thing I'm glad to know.",
            "It's only rock until it's cut; and then it's rather lovely. But.",
        },

        ["IDLE:CRAFT:Leatherworking"] = {
            "The hide gives up its final use; I'll make it worth the old abuse.",
            "Cut it, stitch it, work it soft; it kept a beast, it'll keep a croft.",
            "Nothing is wasted, that's the creed; I'll make from this whatever's need.",
            "Rough on the hands and rough to wear; but rough is what will get you there.",
        },

        ["IDLE:CRAFT:Tailoring"] = {
            "A needle's small, the work is slow; but robes don't sew themselves, you know.",
            "Thread through the eye, and through, and through; a priest should look the part he'll do.",
            "I've mended more than men today; this cloth at least will stay that way.",
            "Stitch by stitch and inch by inch; the finish always makes me flinch.",
        },

        ["IDLE:CRAFT:Smelting"] = {
            "The fire takes what the rock won't yield; a harder faith than any field.",
            "In goes the ore, out comes the bar; I never quite believe how far.",
            "Heat, and heat, and heat some more; that's all there ever is, therefore.",
            "The furnace roars, the metal runs; it's one of the more honest ones.",
        },

        ["SPELL:Lesser Heal"] = {
            "A little Light, a little mend; it's not the best I have, my friend.",
            "A modest heal for modest harm; there's not much power in this charm.",
            "I'll close the smaller of the two; the larger one is up to you.",
            "It's small. It's slow. It's what I've got. It's better, though, than having naught.",
            "Hold still, %t, and take the least; a lesser word, a lesser priest.",
            "The rank is low, the will is high; it's all I've learned. I'll learn. Goodbye.",
            "A thread of Light across the tear; it's thin, but I have put it there.",
            "Not every wound needs all I've learned; a little heat, a little burned.",
            "I'd give you more if more were mine; make do with this. You'll turn out fine.",
            "The smallest mercy still is one; and when it's given, it is done.",
            "A drop of grace, no more, no less; I'd call that partial, not success.",
            "It's called the lesser for a cause; but lesser still obeys the laws.",
        },

        ["SPELL:Heal"] = {
            "Be still, and let the Light come through; it knows the work. It'll see you new.",
            "A steady heal, a steady hand; the plainest gift I understand.",
            "No flourish here, no clever art; just closing you back up, and heart.",
            "Lean on the word and not the wound; the flesh will follow, and be tuned.",
            "I've done this more than I can say; and every time, it works this way.",
            "Slow and sufficient, as designed; it costs me less. Do bear that in mind.",
            "You're mending, %t, and mending well; the rest of it is yours to tell.",
            "The Light does not ask what you've done; it only asks if you've begun.",
            "Stand up. You're whole. Don't make a fuss. There's more of this in front of us.",
            "The middle heal, the honest kind; the sort you'll rarely ever mind.",
            "Take it, and take it without shame; I'd give it out to all the same.",
            "Whole again, or close enough; the rest of it is only tough.",
        },

        ["SPELL:Greater Heal"] = {
            "Be still, and let the wound be sealed; by grace, and not by strength, you're healed.",
            "The greater word, the greater cost; without it, you'd have well been lost.",
            "I'll spend it all and spend it now; there's little point in asking how.",
            "This is the one I hold in store; you'll not be needing any more.",
            "Everything I have, at once; it leaves me hollow. Take the response.",
            "That was expensive, %t, and rare; go carefully, and have a care.",
            "A flood, and not a thread, of Light; you're whole again. You're more than right.",
            "The deepest wound the day has known; I've closed it up. You're not alone.",
            "I gave you all the Light I had; if I look pale, it's not that bad.",
            "Whole. Entirely. Head to shoe. Now try not needing that anew.",
            "Nothing held back and nothing kept; you're mended while the danger crept.",
            "That's my best work, and freely spent; do something worthy with what's lent.",
        },

        ["SPELL:Flash Heal"] = {
            "No time to think, no time to pray; the Light must simply come this way.",
            "Quick, then! Quick! Before you drop! A hurried word, and then a stop.",
            "It's fast, it's dear, it's rather crude; but you're alive, and that is good.",
            "I'd do it slower if I could; there wasn't time. There rarely would.",
            "Hold on, %t. Hold on. Hold tight. It's coming now, and coming bright.",
            "A snatch of grace, a gasp of flame; you're standing. That's the whole of the aim.",
            "Expensive haste, and worth the price; I'd pay it once. I've paid it twice.",
            "There's no elegance in this at all; I caught you halfway through the fall.",
            "Faster than falling, just about; that's all the margin I had out.",
            "A flash, a breath, and you're restored; I'm out of mana, and I'm floored.",
            "Not pretty. Never meant to be. It bought a second. Take it. Flee.",
            "The quickest word I ever learned; and every time, it's dearly earned.",
        },

        ["SPELL:Binding Heal"] = {
            "One for you and one for me; the Light does not object, you see.",
            "I'll mend us both and call it fair; there's quite enough of it to share.",
            "A selfish word? Perhaps. But no: a healer standing helps us so.",
            "Together, then, or not at all; I'll not be first to hit the wall.",
            "Both of us, %t, in one breath; a tidy stitch against a death.",
            "I bind us in the self-same grace; it's rather neat, and saves a place.",
            "The one who mends must mend as well; there's no one else, so far as I can tell.",
            "You rise, I rise, and that's the trick; the pair of us, and rather quick.",
            "I'd feel guilty, but I don't; a healer down is one that won't.",
            "Two for the price of one, and cheap; the sort of bargain that I keep.",
            "Shared out, and neither of us less; it doubles, oddly, under stress.",
            "We're bound in this, we always were; the word just makes it rather clearer.",
        },

        ["SPELL:Renew"] = {
            "A little Light, and left to run; it does its work when I am done.",
            "I set it going, then I go; it mends you gently, soft and slow.",
            "Not all at once. That's not the way. It closes over through the day.",
            "Patience is folded in the spell; it'll take a while, and end you well.",
            "It ticks along, %t, and stays; a quiet grace across the days.",
            "You'll not feel much, and that's the point; it's easing every strained joint.",
            "The slow ones are the kindest sort; they ask for nothing in report.",
            "I've set the Light to keep its watch; it needs no further care, nor touch.",
            "It works while I am doing more; that's why I like this one, therefore.",
            "A seed of mending, quietly sown; you'll find you're better, on your own.",
            "Nothing dramatic. Nothing quick. But steady beats the dramatic trick.",
            "Renewed, and renewing as we speak; it favours patient over weak.",
        },

        ["SPELL:Prayer of Healing"] = {
            "All of you, then. Stand close and still. One prayer, and it will serve you, will.",
            "A word for four is still one word; the sweetest bargain ever heard.",
            "You all stood in it. All of you. So all of you get mended too.",
            "Together, wounded; healed the same; I'll not be asking who's to blame.",
            "Group up, %t, and group up near; the Light has trouble reaching rear.",
            "One breath, and everybody mends; it's cheaper than four separate ends.",
            "I'd rather heal you one by one; but there's no time, so this is done.",
            "The whole of you at once, at last; the danger's thick, the casting's fast.",
            "A prayer that spreads across the four; expensive, but it's worth far more.",
            "Nobody left, and nobody last; the Light is generous and vast.",
            "Stand close together. That's the rule. It makes a healer's job less cruel.",
            "All mended, all at once, and done; now try not standing in the sun.",
        },

        ["SPELL:Prayer of Mending"] = {
            "It leaps from one of you to next; a wandering and helpful text.",
            "I cast it once. It travels round. It finds the hurt without a sound.",
            "A blessing with a mind to roam; it'll do its work and then go home.",
            "One word, and five of you are due; it hops along the whole way through.",
            "It's on you now, %t, and will wait until you take the next bad fate.",
            "It bounces off and finds the next; a clever, economic hex.",
            "Nobody thanks it. Nobody sees. It's mending you between the trees.",
            "I set it loose and let it choose; there's not a drop of it to lose.",
            "It waits until you take a hit; there's rather lovely sense in it.",
            "Five saves from one, and rather cheap; the sort of spell that earns its keep.",
            "Off it goes to someone new; it always knows before I do.",
            "A wandering mercy, doing rounds; the best of all the healing sounds.",
        },

        ["SPELL:Circle of Healing"] = {
            "A ring of Light, and all within; it finds the hurt beneath the skin.",
            "Stand in the circle. Stand in tight. And all of you will come out right.",
            "It falls on everybody near; if you're outside it, come you here.",
            "One circle, and the party's whole; the cheapest way to reach the goal.",
            "Around us all, %t, it goes; who gets the most, the Light well knows.",
            "No aiming needed, none at all; it simply finds you, one and all.",
            "A ring, a word, and everybody's mended; the argument is neatly ended.",
            "It picks the worst and helps them first; a kindly answer to the worst.",
            "Group up. I've said it once before. The circle only reaches four.",
            "The wounded gather without cue; the Light will sort out who is who.",
            "Everyone in, and everyone healed; the tidiest across the field.",
            "A circle drawn in nothing much; and every one of you feels its touch.",
        },

        ["SPELL:Power Word: Shield"] = {
            "A word is spoken, thin as air; and yet no blade shall find you there.",
            "Not armour, not a wall of stone; a sentence standing on its own.",
            "I said a word. The word is strong. It'll hold the worst of it, not long.",
            "Go on and take it. Take the blow. The word will bear it. Off you go.",
            "You're bubbled now, %t, and safe; a little breathing room to chafe.",
            "Nothing will reach you for a while; do something useful. Do it with style.",
            "It costs a lot and lasts no time; but so does everything sublime.",
            "The word absorbs what flesh would not; it's rather better than you've got.",
            "Prevention over cure, they say; and it is cheaper, either way.",
            "A shell of syllables, and thin; but nothing yet has broken in.",
            "Speak first, and heal a great deal less; the finest trick in my address.",
            "There. A word between you and harm; a small and complicated charm.",
        },

        ["SPELL:Lightwell"] = {
            "I've put a well of Light right here; click it, and it will hold you dear.",
            "It's free. It's there. It heals a lot. And nobody has ever got.",
            "A fountain standing in the fray; please use it. Please. It's there all day.",
            "I built it out of hope and prayer; nobody's ever noticed there.",
            "It's over there, %t, and glows; it works. It really works. Who knows.",
            "Ten charges, waiting, going spare; the well is willing. No one's there.",
            "I set it down with honest pride; and every single one walks wide.",
            "You have to click it. That's the catch. And that, it seems, no one can match.",
            "A quiet miracle, ignored; it stands and shines and gets no reward.",
            "Please. Just once. Just click the thing. I'd like to hear the healing sing.",
            "The most efficient spell I own; and I have used it all alone.",
            "There's Light enough in it for all; it waits, unclicked, against the wall.",
        },

        ["SPELL:Desperate Prayer"] = {
            "There's no one left to heal but me; so this is what desperate must be.",
            "A prayer for one, and that one's mine; I'd share it if there were the time.",
            "The name is honest, I'll admit; there's rather a lot of desperate in it.",
            "I ask, and asking is the whole; there's nothing clever in this role.",
            "No time to reach for you, %t; I'm reaching for myself. Forgive.",
            "When all the words have gone away, there's still one left for me to say.",
            "I mend the world, then mend the priest; the last one always gets the least.",
            "A selfish word, but softly meant; it's what the final breath is spent.",
            "Straight up, and straight back down to me; the shortest prayer there'll ever be.",
            "I would not use it if I could; I've used it now. I hope it's good.",
            "The Light hears best when things are worst; it's cruel, but that's the way it's versed.",
            "One prayer, one healer, and one chance; I've taken it. I'll take the glance.",
        },

        ["SPELL:Resurrection"] = {
            "The door was shut, the door is wide; rise up, and leave the dark inside.",
            "Come back. There's work you've yet to do. The Light is not yet done with you.",
            "Death held you briefly. Now it won't. Get up. And this time, please, please don't.",
            "I'll call you back across the line; the debt is mine. The debt is fine.",
            "Up you get, %t, and up you stay; I'd rather not do this all day.",
            "The dark has better things to keep; you'll go there later. Go back to sleep.",
            "Return, return, and mind the gap; the world's still here. It's on the map.",
            "I asked. It listened. Here you are. You didn't travel very far.",
            "Rise, and be grateful, and be quick; there's more of this, and it's thick.",
            "You went. You're back. Say nothing more. That's what the Light appointed for.",
            "A word can call you from the deep; that's not a thing I take too cheap.",
            "Back to your feet and back to breath; a small rebuttal made to death.",
        },

        ["SPELL:Pain Suppression"] = {
            "I cannot stop it. Not at all. But I can soften how you fall.",
            "The hurt continues. You do not. That's rather the best I've ever got.",
            "Eight seconds where the world can't reach; a mercy longer than a speech.",
            "I'll take the edge off what's ahead; it's not a cure. You're not yet dead.",
            "Hold on, %t, and hold on tight; eight seconds of an easier fight.",
            "The blows still land. They land less true. That's all that I can do for you.",
            "A dulling, not a mending, this; the sort of grace that's easy to miss.",
            "I've turned the volume of it down; the hurt is there. It makes no sound.",
            "Not healing. Something close to peace. A borrowed and a brief release.",
            "Suppressed, and only for a spell; then everything comes back as well.",
            "I'd stop the pain if I knew how; the best I have is quiet, now.",
            "A moment's mercy, bought and lent; that's what the whole of it is meant.",
        },

        ["SPELL:Power Word: Fortitude"] = {
            "A word to make you rather more; you'll last a little longer for.",
            "Not healing, but a deeper well; you'll take a beating rather well.",
            "More of you to lose, my friend; it buys you time before the end.",
            "Stand up. You're heartier than you were. A word will do that, as it were.",
            "There, %t. You're a fraction more; it's why they keep me on the door.",
            "The dullest word I ever cast; and yet it's why so many last.",
            "A little stamina, freely thrown; nobody thanks me. It's well known.",
            "Fortitude. It means to bear. I've put a bit more of it there.",
            "I'll cast it once, then cast again; you always drop it. Always, then.",
            "The bedrock word, the one before; you'd not survive the fight, therefore.",
            "Bigger, and harder to put down; a plain grey blessing, not a crown.",
            "That's stamina. Do use it well. And don't come back to me to tell.",
        },

        ["SPELL:Prayer of Fortitude"] = {
            "All of you at once, and done; I'll not be asked by everyone.",
            "One prayer, one reagent, and it's cast; and this time, please, please make it last.",
            "The whole of you, and rather stout; that's what the candle went about.",
            "Group buffed, group blessed, and group ignored; the usual and just reward.",
            "There. All of you. Now go, %t, and try to keep it. Try, I beg.",
            "I've spent the reagent. Spent the breath. Do not go running into death.",
            "Everybody harder to fell; if you die now, you've died quite well.",
            "The whole room's tougher. Off we go. And no, I will not cast it slow.",
            "One cast for five is how it's done; and cheaper, too, than one by one.",
            "Fortified, the lot of you; now do the things you're meant to do.",
            "Nobody thank me. Please. Don't start. It's dull, but it's the better part.",
            "That's everyone. That's all of it. Now go and make some use of it.",
        },

        ["SPELL:Divine Spirit"] = {
            "A deeper well beneath your feet; the sort of gift that's hard to beat.",
            "Spirit, they call it. Odd, but true: it means more casting left in you.",
            "Not strength, not speed, but staying long; the quiet part of being strong.",
            "You'll find the bottom further down; a modest and unnoticed crown.",
            "Here, %t, and here's the rest; the deeper well, the longer test.",
            "Nobody notices this at all; until the mana starts to fall.",
            "The dullest buff, the finest kind; it's there behind you all the time.",
            "Spirit regenerates the pool; it's arithmetic, not rule.",
            "You'll cast for longer. That's the whole. A steady, unremarkable goal.",
            "A gift you'll only see in length; the slow accumulation of strength.",
            "Take it, and take it without thought; that's rather how it's always bought.",
            "More in the well than there had been; the least dramatic thing I've seen.",
        },

        ["SPELL:Prayer of Spirit"] = {
            "Deeper wells for all of you; the reagent's gone. It'll have to do.",
            "One prayer, one candle, and it's spent; that's where the shopping money went.",
            "The whole of you, and deeper drawn; you'll cast until the coming dawn.",
            "Everybody's well runs deep; now try to make the buff you keep.",
            "All of you, %t, and all at once; I'll not be doing this response.",
            "An expensive word for quiet good; I'd cast it less often if I could.",
            "Spirit for five, and spirit spare; nobody's going to notice there.",
            "The party's deeper than it was; and nobody will ask me cause.",
            "Group blessed, group deepened, group away; that's quite enough of that today.",
            "There. The whole room casts for longer. Do try and come back rather stronger.",
            "One cast, five wells, and off we go; the maths of it is rather so.",
            "Take it, and cast until you're dry; and then don't come to me and cry.",
        },

        ["SPELL:Shadow Protection"] = {
            "The dark will come. It always does. I've made it rather less than was.",
            "A shield against the coming night; you'll take it softer. That's the right.",
            "Shadow will find you. That's its way. It'll find you gentler, though, today.",
            "Against the dark, a little wall; it will not stop it. Not at all.",
            "There, %t. The dark's less deep; a small provision you should keep.",
            "I know the shadow rather well; I've worn it. So I know its tell.",
            "Whatever crawls out of the black will land, and land a fraction slack.",
            "Protection is a modest word; the best defence I've ever heard.",
            "You'll feel it less. That's all it means. A dulling of the darker scenes.",
            "The night is coming. Let it come. You're readier than you were, by some.",
            "I've stood in shadow. I know its cost. Take this, and be a little less lost.",
            "Against the dark, and warded fair; it isn't much, but it is there.",
        },

        ["SPELL:Prayer of Shadow Protection"] = {
            "The whole of you, against the black; one prayer, and none of you'll go slack.",
            "Everybody warded, all at once; the dark can do its worst response.",
            "A candle spent, a party saved; that's how the reagent gets behaved.",
            "All five of you, and all made proof; the shadow's coming through the roof.",
            "There, %t, and there's the lot; the dark will hit for less than got.",
            "I know what's coming. So do you. This blunts a fraction of it through.",
            "Group warded, and the night ahead; you'll take it standing, not in bed.",
            "The shadow's patient. So's the word. It'll hold a while. That's what I've heard.",
            "One cast, five saved, and rather dear; but nobody complains down here.",
            "Against the dark, the lot of you; and now there's nothing more to do.",
            "The night comes on. We're ready, though. As ready as I ever go.",
            "All shadowed, all protected, all; now stand together. Do not fall.",
        },

        ["SPELL:Inner Fire"] = {
            "A fire that burns behind the eyes; it keeps the blade off, to my surprise.",
            "Not warmth for me, but armour thin; the Light goes out as well as in.",
            "I'm lit from somewhere further back; it turns a fraction of the attack.",
            "It shows. I know it shows. It should. A priest alight is doing good.",
            "Look at me glow, %t. It's fine. It's armour, and it's mostly mine.",
            "A cloth-wearer needs every trick; and this one's cheap and rather quick.",
            "The fire is inward, but it guards; it turns the blows and turns the shards.",
            "I burn a little. So I do. It keeps the worst of it from through.",
            "Not passion. Armour. Do not read a thing into the way I bleed.",
            "It flickers, and it holds the line; a modest miracle of mine.",
            "Some carry shields. I carry flame. It gets me to the self-same aim.",
            "Alight, and rather better dressed; of all my armour, this is best.",
        },

        ["SPELL:Fear Ward"] = {
            "Whatever screams, you'll stand your ground; you will not hear the running sound.",
            "One shriek is coming. Only one. And you'll ignore it when it's done.",
            "Be not afraid. I mean it plain: you literally cannot, again.",
            "The terror comes. You will not go. I've fixed your feet. Now let it show.",
            "Stand fast, %t, and stand you must; the ward will hold, and so will trust.",
            "They'll try to scatter you. They'll fail. There's iron underneath the pale.",
            "Fear is a spell. So is this. It cancels out the coming hiss.",
            "One warding, and one scream refused; it's not a thing to be misused.",
            "You'll feel the fear and stay in place; that's braver, really, either case.",
            "The ward's on you. Now hold the line. It only works the single time.",
            "Whatever howls out of the dark will find you standing on your mark.",
            "No running, then. No running now. I've warded you. I don't know how.",
        },

        ["SPELL:Power Infusion"] = {
            "Take all of it. Take all I've got. And use it while the iron's hot.",
            "Fifteen seconds of being more; go on and even up the score.",
            "I'll pour it into you instead; it's better used than left unsaid.",
            "Faster, cheaper, harder too; that's all the infusion can do.",
            "Go on then, %t. Go. Be quick. It's short, and rather hard to pick.",
            "I give my power to your hand; I hope you know it's contraband.",
            "Not mine to keep, not mine to hold; it's better spent than growing old.",
            "Everything I have, on you; now show me what you meant to do.",
            "Fifteen seconds. Make them count. It's rather a considerable amount.",
            "The finest gift I have to give; go on and make the moment live.",
            "I'll be the quieter of the two; the loud part now belongs to you.",
            "Infused, and burning rather bright; do something worthy of the light.",
        },

        ["SPELL:Inner Focus"] = {
            "One word for free, and only one; and then the little grace is done.",
            "No cost at all. That's rare and sweet. A gift of clarity, complete.",
            "The mind goes still, the price goes out; there's not a thing to think about.",
            "A single spell that costs me naught; the cheapest lesson ever taught.",
            "Watch closely, %t. Here's the trick: it's free, and rather more than quick.",
            "Focus. And nothing else at all. The quiet just before the fall.",
            "I've saved it for the moment's need; and now the moment's here indeed.",
            "Free, and better than it was; the finest word there ever does.",
            "One perfect casting, gratis, whole; a small economy of soul.",
            "It's not much use except when dire; and then it's water on the fire.",
            "The mind is clear, the cost is none; and then the little grace is done.",
            "A breath of focus, sharply drawn; and after that, the moment's gone.",
        },

        ["SPELL:Dispel Magic"] = {
            "Whatever's clinging, let it go; a word, and off it comes. And so.",
            "That isn't yours. It's coming off. It's not the sort of thing to scoff.",
            "A curse, a hex, a clever spell; I'll take it off and wish it well.",
            "Somebody put that there. Not me. And now it's gone, and now you're free.",
            "Hold still, %t, and let me look; whatever's on you, off it took.",
            "I've spent my life removing things; that's half of what a healer brings.",
            "Cleaner than you were before; there's nothing on you any more.",
            "A word to strip the magic bare; you'll find there's nothing left on there.",
            "It came from somewhere. Now it's gone. That's all the thought I'll spend upon.",
            "Dispelled, and dispelled rather clean; the tidiest that I have been.",
            "Not every problem needs a heal; some just need peeling off, for real.",
            "Off, and away, and out of sight; the simplest work, and always right.",
        },

        ["SPELL:Mass Dispel"] = {
            "That whole circle, wiped and bare; whatever's magic isn't there.",
            "All of it, and all at once; a wide and thorough, sweeping response.",
            "Everything in that ring goes clear; there's nothing magical left here.",
            "I'll strip the lot. I do not care whose careful work was sitting there.",
            "Stand in it, %t, and stand clean; the widest scrub I've ever been.",
            "Their shields, their curses, all the same; it does not ask a single name.",
            "A circle drawn, and magic dies; there's rather little compromise.",
            "Expensive, slow, and very wide; it takes down everything inside.",
            "It clears the field of clever tricks; and rather ruins several picks.",
            "Whatever they had planned is gone; and now the fair fight carries on.",
            "One casting, and the board is bare; I'd call that elegant, and rare.",
            "Everything magic, everywhere, off; I'll take the silence, and the scoff.",
        },

        ["SPELL:Cure Disease"] = {
            "Whatever crawled in, out it comes; a word, and then the sickness numbs.",
            "That's rot, and rot has got to go; hold still, and let the Light say no.",
            "A plague is only stubborn cloth; I'll take it off, and take it off.",
            "Something is wrong beneath the skin; I'll get it out. I'll not begin.",
            "Hold still, %t. It's coming out. There's not a lot to think about.",
            "The body's fighting. So am I. Between us both, the thing will die.",
            "I do not want to know what's there; I'll simply take it off with care.",
            "Cured, and cleaner than before; do not go touching any more.",
            "A word against the creeping thing; it's gone. It's gone. There. That's the swing.",
            "Disease is patient. So's the Light. And only one of them was right.",
            "It's out. It's gone. It's off. It's done. Now go and try not catching one.",
            "Whatever that was, it's not now; I'd rather not explain the how.",
        },

        ["SPELL:Abolish Disease"] = {
            "Not once, but three times over, gone; the stubborn sort can't carry on.",
            "It'll try to stay. It'll try in vain. It gets removed and removed again.",
            "A cure that keeps on curing through; the thorough thing I like to do.",
            "Whatever's clever, this is more; it'll knock it off the second floor.",
            "Hold still a while, %t, and see: it lifts and lifts, repeatedly.",
            "The word stays on and does its rounds; it hunts the sickness through the grounds.",
            "Some things come back. Not under this. It gets them all. It doesn't miss.",
            "Abolished. Not just pushed away. It will not trouble you today.",
            "Three passes, and the thing is dead; I'd call that thoroughly ahead.",
            "The persistent kind needs persistence too; and that's precisely what I do.",
            "It'll keep on working when I've gone; the tidiest I've ever done.",
            "Whatever's in you, out it goes; and out again, and out. It knows.",
        },

        ["SPELL:Levitate"] = {
            "Your feet have left the honest ground; you'll fall, but you will fall unbound.",
            "Down you go, but gently, slow; a softer landing than you'd know.",
            "The Light will hold you as you fall; it will not stop you. Not at all.",
            "Float, then. Float and do not fret. The bottom hasn't found you yet.",
            "Off you go, %t, and drift; it's rather a peculiar gift.",
            "A reagent gone to make you light; I hope you think it's worth the flight.",
            "Not flying. Falling, but polite. There's quite a difference, and it's slight.",
            "You'll touch the ground and feel no shock; I've slowed you to a gentle walk.",
            "Weightless, and looking rather odd; a small conspiracy with god.",
            "The ground will wait. It always does. It'll meet you softer than it was.",
            "Down through the air like falling snow; a rather dignified way to go.",
            "Drift, and enjoy the way you land; the finest trick I have on hand.",
        },

        ["SPELL:Mind Soothe"] = {
            "Be calm. Be still. There's nothing here. Go back to what you were, my dear.",
            "Nothing to see, and nothing near; the thought of us will disappear.",
            "I'll smooth the edges of your thought; you'll not recall that we were caught.",
            "Peace, for a moment, gently laid; we'll pass by while the mind is stayed.",
            "Look elsewhere, %t. Look away. There's nothing worth your time today.",
            "A quiet word across the mind; it leaves no trace of any kind.",
            "You're calmer now. You don't know why. And we'll be gone before you try.",
            "Not sleep, but something close to rest; a soothing of the over-stressed.",
            "The temper drops, the guard comes down; we'll slip on past you through the town.",
            "Softly, softly, nothing more; you'll never know we passed your door.",
            "I'd rather calm you than contend; a gentler means towards an end.",
            "Untroubled now, and looking wide; we'll take the quiet route beside.",
        },

        ["SPELL:Mind Vision"] = {
            "I'm looking out behind your eyes! You'd not believe how well it flies!",
            "I see what you see! Rather neat! And you don't feel it. Not a beat!",
            "Don't mind me! I'll just have a look! You'll never find it in a book!",
            "A borrowed pair of eyes, no less! And nobody the wiser. Yes!",
            "Hold still, %t. I'm having a peek. It's rather rude, and rather sleek!",
            "You're walking round and I'm inside! There's nowhere left for you to hide!",
            "I do not need to leave this spot! I'm seeing everything you've got!",
            "Scouting! With somebody else's head! It's rather better done than said!",
            "Whatever's round the corner, well: you're going to see it. Then I'll tell!",
            "A little peep! A little pry! And absolutely no goodbye!",
            "It's not polite. I'm well aware. But it does rather get me there!",
            "Through your eyes and out the back! A thoroughly unpleasant hack!",
        },

        ["SPELL:Shackle Undead"] = {
            "Be still, poor thing. Be still and wait. The Light has put you out of date.",
            "Bound in a word, and held in place; there's mercy hidden in this grace.",
            "You should have rested long ago; I'll hold you till it's time to go.",
            "Nobody touch him. Not a hand. That's how the shackle's meant to stand.",
            "Wait there, %t. Wait, and hold. This one is bound. This one is old.",
            "A chain of Light around the dead; it holds the body, holds the head.",
            "Whatever kept you walking, stop; I'll hold you here until we drop.",
            "One at a time. That's how it's done. I'll shackle this and take that one.",
            "Rest, or as close as you can come; I'll hold you gently. Hold you numb.",
            "You will not move. You will not fight. You'll simply stand there in the Light.",
            "It's kinder than it looks, this spell; I'll let you go and wish you well.",
            "Held, and held for quite a while; there's pity in it, and no guile.",
        },

        ["SPELL:Mind Control"] = {
            "Your body's mine! Your thoughts are too! There's rather little you can do!",
            "Walk over there! No! Over there! I'm rather enjoying this affair!",
            "I'll drive a while! Do have a rest! You'll find I'm not the very best!",
            "Off the cliff! No! Only teasing! I find this rather rather pleasing!",
            "Come here, %t. And now go back. I'm rather getting the hang of that!",
            "Hit your own friends! Go on! Go on! And then I'll drop you when it's done!",
            "It's not permanent! Don't you fret! It's rather the best that I can get!",
            "A puppet! With a proper string! I'd say it's my delightful thing!",
            "Say what I tell you! Say it now! And do not ask me why or how!",
            "I've got the reins! You've got the legs! The finest of my dirty dregs!",
            "Nobody kill him! He's with me! Well. Temporarily, you see!",
            "Whose head is this? It's mine today! I'll give it back. Perhaps. We'll say!",
        },

        ["SPELL:Fade"] = {
            "Look somewhere else! I'm not that near! There's nothing terribly worth here!",
            "I've gone all quiet! Not all gone! Just far less interesting to look on!",
            "Forget about me! Go and see! Whoever else that isn't me!",
            "The healer's boring! Truly, dull! Go bother somebody with a skull!",
            "Not me, %t! Not me at all! Go find the fellow by the wall!",
            "I've dimmed myself! It's rather neat! A tactical and quick retreat!",
            "Still here! Just rather less on show! Now go away. Please. Off you go!",
            "The tank's more interesting! Yes! He is! Go over there and mind your biz!",
            "Faded, and rather hard to see; you're looking straight through most of me!",
            "It's not invisibility, quite; it's just a strong lack of delight!",
            "I've made myself the boring one! It's rather cleverly begun!",
            "Nothing to see here! Not a thing! Now go and hit somebody. Bing!",
        },

        ["SPELL:Smite"] = {
            "The Light does not debate or plead; it simply answers, and you bleed.",
            "A word, a weight, and down it comes; it argues rather less than sums.",
            "I asked you twice. I'll not ask thrice. The Light is warm. The Light's not nice.",
            "Straight from above and straight to you; there's nothing complicated through.",
            "That's holy fire, %t, and plain; I'd do it once. I'll do't again.",
            "The oldest word a priest can throw; and after all this time, it'll go.",
            "Not clever. Not refined at all. But heavy when it starts to fall.",
            "I'd rather bless than break, it's true; but breaking's what you've asked me to.",
            "The Light does not require finesse; it lands, and leaves you rather less.",
            "A smiting is a kind of speech; the sort of sermon few can reach.",
            "Down comes the word and down come you; it's what a smiting's meant to do.",
            "I smite, and I do not rejoice; but neither do I doubt the choice.",
        },

        ["SPELL:Holy Fire"] = {
            "The Light can burn as well as bless; it's rather less discussed, I guess.",
            "It catches, and it will not stop; a slow and consecrated crop.",
            "I set the holy flame alight; it'll do its work throughout the night.",
            "Not warmth. Not comfort. Something worse. The other side of every verse.",
            "You're burning, %t, and you'll stay; the fire has rather a long day.",
            "A sacred fire is fire still; it does not care about goodwill.",
            "It lands, and then it lingers on; it's working long after I've gone.",
            "They never mention this at all; the burning part behind the call.",
            "Consecrated, and rather hot; the gentlest thing that I have not.",
            "I'd put it out, but that's not how; it burns until it's finished. Now.",
            "The Light is warmth. The Light is flame. It rather depends which way it came.",
            "It'll burn a while, and burn you through; there's nothing more that I need do.",
        },

        ["SPELL:Holy Nova"] = {
            "The Light goes out in all directions; friends get hugs and you get corrections.",
            "One word, and everybody's touched; the enemy rather less than much.",
            "It knows the difference, which is odd; it heals a friend and hurts a clod.",
            "Around me, outward, all at once; a generous and costly response.",
            "Stand close, %t, or stand away; the Light does not much care today.",
            "A ring of grace that also bites; it settles rather several fights.",
            "It mends behind and burns in front; a very complicated stunt.",
            "Expensive. Showy. Slightly vain. But look how far the Light has lain.",
            "Everyone gets a share of this; the friends get help, the rest get hiss.",
            "It costs a fortune. Worth it, though. Just look at how the whole thing glows.",
            "Both at once, and neatly done; a small and radiating sun.",
            "The Light expands and does not choose; it simply lands, and someone loses.",
        },

        ["SPELL:Shoot"] = {
            "The mana's gone, the wand comes out; there's little dignity about.",
            "A stick that sparks, and not much more; that's what the empty well is for.",
            "I read the scriptures. Now I aim. It's not exactly the same game.",
            "Plink, and plink, and plink again; the slowest damage known to men.",
            "It counts, %t. It barely counts. But so do very small amounts.",
            "Years of study, and a wand; the joke has rather worn beyond.",
            "I'd cast, but casting wants a cost; and all of that is rather lost.",
            "A little light on a little stick; it's not impressive, but it's quick.",
            "Conserving, and I'll not explain; I'll be back casting soon again.",
            "The wand goes off. The wand goes on. And rather little damage done.",
            "Not what I trained for. Not at all. But something has to fill the lull.",
            "Pointed, and fired, and mildly sad; it's honest work. It's not that bad.",
        },

        ["SPELL:Mind Blast"] = {
            "I'm in your skull! I'm in there now! I will not tell you when or how!",
            "A blast! A crack! Right through the brain! And then I'll do it all again!",
            "Your thoughts were tidy! Now they're not! I made a mess of what you've got!",
            "It goes off inside, not out! That's what the shadow's all about!",
            "Right in the head for you, %t! And that's the friendliest I get!",
            "No blade! No fire! No holy light! Just something breaking in the night!",
            "I do not need to touch at all! The mind's the easiest place to fall!",
            "Boom! But quiet! Boom! Inside! There's nowhere in your head to hide!",
            "The best of all my nasty tricks! I'd do it more, but timers stick!",
            "You felt that! Yes, you did! You did! I saw it move behind your lid!",
            "A blast that nobody can see! The worst of what the dark gave me!",
            "Straight through the middle of your thought! And no, I'm not the slightest sorry!",
        },

        ["SPELL:Shadow Word: Pain"] = {
            "A little rot, a little ache; it works on you while I'm on break.",
            "I said a word! The word is bad! It's slowly making you quite sad!",
            "It ticks! It ticks! It ticks some more! That's what a shadow word is for!",
            "I've set it going. Off I go. It hurts you steadily and slow.",
            "You'll feel it soon enough, %t; a little worse with each regret.",
            "No effort left for me at all! It does the work. I watch you fall!",
            "A word, and then a lot of waiting; the shadow's rather good at hating.",
            "Drip, drip, drip, and drip again; the least dramatic sort of pain.",
            "I don't need to be near you now! It's working, and it's working how!",
            "The word is in you. There it sits. And slowly takes you all to bits.",
            "Patience! Patience! That's the art! The slow ones always break the heart!",
            "It's still there. Yes. It's still there. Yes. It rather ruins the address.",
        },

        ["SPELL:Shadow Word: Death"] = {
            "A word so bad it hurts us both! And still I say it. Still, on oath!",
            "One word, and one of us goes down! Most likely you. But not renowned!",
            "It's not a nice one. Not at all. It's what I use to end the brawl.",
            "I say the word, the word says done; and one of us is not the one.",
            "That's it for you now, %t; the shortest word you'll ever get!",
            "The cost comes back on me, it's true! But rather less on me than you!",
            "A last resort, and rather rude! I'm not in a discussing mood!",
            "The shadow does not do goodbyes; it simply closes down the eyes.",
            "I'll pay for that. I always do. But I'll be paying less than you!",
            "One syllable to end a life! It's cheaper, honestly, than strife.",
            "It hurts to say! It hurts to hear! But mostly it just ends you here!",
            "The final word, and finally said; and one of us is going to bed.",
        },

        ["SPELL:Mind Flay"] = {
            "I'm in your head! I'm in there deep! You won't be getting any sleep!",
            "It peels, it peels, it peels away! And I've got nothing else today!",
            "I'll hold it steady. Do not move. There's rather nothing left to prove.",
            "Slow, and unpleasant, and it stays; the shadow does it several ways.",
            "Feel that, %t? That's me inside! There's nowhere in your skull to hide!",
            "I channel, and I do not blink! It's rather ruining how you think!",
            "Don't interrupt me! Not just now! I'm getting somewhere. Don't ask how!",
            "A steady scraping at the mind! The nastiest thing that I can find!",
            "It slows you too! That's rather neat! A tidy, horrible little feat!",
            "I'll keep it going while I can! It's not a very holy plan!",
            "Peel, and peel, and peel some more! That's what the shadow's really for!",
            "You're thinking slower! Yes, you are! I've not even got very far!",
        },

        ["SPELL:Psychic Scream"] = {
            "I scream! You scatter! Off you go! In four directions, fast and slow!",
            "Not with my mouth! With something worse! It empties rooms. It's rather terse.",
            "Run! Run away! All four of you! It's rather the best thing I do!",
            "The fear goes out. The crowd goes wide. There's nowhere left for you to hide.",
            "Off you go, %t! Off you run! And do come back when I am done!",
            "A shriek that nobody can hear! And every one of you in fear!",
            "Scatter! Scatter! Out you go! And take your friends! Yes! Yes! Hello!",
            "It buys me seconds. That's the point! And rather unhinges every joint!",
            "I did not want to. Yes, I did. It's rather fun, I'll not forbid.",
            "They run in circles, all confused; a tactic frequently misused.",
            "Nobody stands and nobody stays! It's chaos, and it always pays!",
            "The scream goes out! The room goes bare! And I am standing, breathing, there!",
        },

        ["SPELL:Shadowform"] = {
            "No heals from me! I've gone all black! Don't ask again! I won't switch back!",
            "I set the Light upon the shelf; tonight I am the dark itself.",
            "Don't look at me like that! It's fine! The shadow's every bit as mine!",
            "I'm purple now! And rather pleased! And absolutely not appeased!",
            "Don't ask me for a heal, %t! I've told you twice! I'm not upset!",
            "The robes go dark! The eyes go out! That's what the whole thing's all about!",
            "More damage in! More damage out! And nothing left to heal about!",
            "I was a healer! Once! Not now! I've made the switch! Don't ask me how!",
            "The shadow fits me rather well; it's roomier than the Light, I'll tell.",
            "I'm not myself. That's rather nice. I've been myself for far too long, twice.",
            "Black as a cellar, twice as cold! And funnier than I've been told!",
            "The Light is lovely. So's the dark. And one of them leaves more of a mark!",
        },

        ["SPELL:Vampiric Embrace"] = {
            "Your pain goes out, and comes to us! I'd call that rather generous!",
            "I hurt you, and my friends get well! It's rather a marvellous little spell!",
            "An embrace! From me! You lucky thing! Now bleed, and hear my party sing!",
            "Everything landing on you now is turning into health somehow!",
            "It's on you, %t, and it stays; you're healing us in several ways!",
            "You are a fountain! Did you know? The more you hurt, the more we grow!",
            "I do not have to heal at all! I simply have to watch you fall!",
            "The group gets better while you break! It's rather more than I can take!",
            "A dreadful spell! A useful one! I'll keep it going till you're done!",
            "Not charity! Extraction, dear! The finest racket round these years!",
            "You're paying for the party's health! And doing it without the wealth!",
            "Embrace! It's not affectionate! It's rather more a small event!",
        },

        ["SPELL:Vampiric Touch"] = {
            "A touch! And now you're paying rent! On mana that I've never lent!",
            "It drains, and drains, and drains some more! And I don't need my well restored!",
            "You're funding this! You didn't know! And now you do! And off we go!",
            "A little touch, a lot of tick; it keeps me casting, rather quick.",
            "You're topping me up, %t, for free! It's rather an economy!",
            "I do not need to drink at all! I simply need you standing tall!",
            "It hurts! And also, it's a well! A very entrepreneurial spell!",
            "Slow, and steady, and it pays; the best of all my nasty ways!",
            "Each little tick puts blue in me! It's rather lovely. Can't you see?",
            "You are a bank! I'm withdrawing! And rather cheerfully ignoring!",
            "Nothing personal! It's the fee! For being standing near to me!",
            "The touch stays on. The mana flows. That's rather how the shadow goes!",
        },

        ["SPELL:Silence"] = {
            "No more of that! No more! No word! You've said the last that I'll have heard!",
            "You had a spell. You had a plan. It's gone. It's gone. That's how I ran.",
            "Quiet! Quiet! Not a peep! I'd rather that you went to sleep!",
            "The words go in, but not back out! That's what the shadow's about!",
            "Nothing from you, %t! Not one! Your very talkative day is done!",
            "I've stopped the mouth without a hand! It's rather elegantly planned!",
            "Say something! Go on! Have a try! I'll wait. I'll wait. And so will I.",
            "You were about to ruin things! And now you've lost your speaking wings!",
            "Five seconds where you can't reply! I'd stretch it further if I'd try!",
            "A silence laid across the throat! The finest thing I ever wrote!",
            "No casting! None! Not one! Not now! I've shut you up. Don't ask me how!",
            "The room is quieter, I'd say! And rather better off that way!",
        },

        ["SPELL:Shadowfiend"] = {
            "Out comes the fiend! It's small! It's mean! The nastiest pet you've ever seen!",
            "Go on, my darling! Off you run! And bring me back a well that's spun!",
            "It eats their mana! Yes, it does! And gives it back to me, because!",
            "Ten seconds only! Make them count! It's rather a considerable amount!",
            "Sic him, my sweet! Get %t! And do not let the creature fret!",
            "Don't look at it! It bites! It will! And then it brings me back a fill!",
            "A shadow shaped into a cat! I'd not enquire much past that!",
            "My little horror's off to feed! It's rather everything I need!",
            "It's not a pet! It's more a tool! A hungry, purple, dreadful ghoul!",
            "Go! Go! And do not come back light! Bring mana back, and bring it right!",
            "I keep it somewhere. Do not ask. It's rather good at what I task!",
            "There goes my dreadful little friend! It'll drain them dry before the end!",
        },

        ["SPELL:Devouring Plague"] = {
            "It eats you slowly! Bit by bit! And I get healthier for it!",
            "A plague! A real one! In you! Now! And you can't get it off, somehow!",
            "It'll be there long after I've moved on; it works away till you are gone.",
            "I feed on this! I really do! Your rotting keeps me pushing through!",
            "That's in you now, %t. It stays. It'll ruin the next several days.",
            "A long one! Very long indeed! It's rather more than I will need!",
            "You cannot dispel that at all! It sits and waits for you to fall!",
            "Devouring! Look at the name! It's rather honestly the same!",
            "It rots! It creeps! It doesn't stop! And I get better, drop by drop!",
            "The nastiest word I ever learned! And every tick of it is earned!",
            "You're being eaten. Slowly, yes. But definitely, nonetheless!",
            "I set it loose and walked away! It'll finish you by end of day!",
        },

        ["SPELL:Touch of Weakness"] = {
            "Touch me and find you're rather less! It's not a spell that I confess!",
            "Go on! Swing! And watch it shrink! It's rather worse than you would think!",
            "Whoever hits me pays a price! I'd say it once. I've said it twice!",
            "A curse that's sitting on my skin! Whatever lands is landing thin!",
            "Come on and hit me, %t. Please. It only makes your damage cease.",
            "It's on me, waiting, rather still; for anyone who's got the will!",
            "You hit me once! You're weaker now! And that is rather clever, how!",
            "It costs you every time you try! And rather makes me want to cry!",
            "Weakness on touch! It's in the name! I'd say it's rather a good game!",
            "The first one through gets rather stung! And weaker than they were among!",
            "I do not have to lift a hand! It's all been previously planned!",
            "Swing away! I'll wait right here! You'll only make yourself less dear!",
        },

        ["SPELL:Hex of Weakness"] = {
            "A hex! A proper one! On you! And everything you do falls through!",
            "You're weaker now! And getting more! That's rather what a hex is for!",
            "Your damage drops! Your healing too! There's rather nothing left for you!",
            "I've laid a curse across the lot! It's rather more than you had got!",
            "That's on you, %t, and it clings; it takes the strength from all your swings!",
            "It's not a nice one! Not at all! It rather guarantees the fall!",
            "Everything softer! Everything less! A comprehensive little mess!",
            "A hex is nastier than a curse! I'd argue, but it's rather worse!",
            "You'll hit like paper! Yes, you will! And healing barely works you, still!",
            "I do enjoy this one, I'll say! It rather ruins the whole day!",
            "Weak, and weaker, and weaker yet! The nastiest hex you've ever met!",
            "It clings, it drags, it will not lift! A thoroughly unpleasant gift!",
        },

        ["SPELL:Shadowguard"] = {
            "Touch me and get a nasty shock! It's rather better than a lock!",
            "Three charges sitting on my skin! And every one of them goes in!",
            "Hit me! Go on! I rather dare! There's something waiting for you there!",
            "It bites back! Yes! Without my aid! A rather well-constructed trade!",
            "Careful now, %t. Careful, do. There's rather something waiting through!",
            "I don't have to do a thing at all! It punishes them when they fall!",
            "A guard of shadow, thin and mean! The best defence I've ever seen!",
            "Zap! And that was not from me! It's automatic, don't you see!",
            "Three of them, and then it's gone; but three's enough to carry on!",
            "They always hit me. Always do. And every time, it costs them through!",
            "I'd tell them not to. But I won't. It's funnier when they simply don't!",
            "It sits, and waits, and then it stings! One of my more delightful things!",
        },

        ["SPELL:Starshards"] = {
            "Elune is looking. So am I. And something's falling from the sky.",
            "The stars come down in little bits; and every single one of them hits.",
            "Look up. No. Never mind. Too late. The moon has rather sealed your fate.",
            "Shard after shard, and down they come; a slow and silver-falling sum.",
            "Above you, %t, and falling through; there's rather nothing you can do.",
            "The night sky lends me what it can; a very old and quiet plan.",
            "Not holy, quite. Not shadow, either. Something the moon has given, neither.",
            "They fall in silence, one by one; and then, quite suddenly, you're done.",
            "Elune does not require a word; the finest prayer I've never heard.",
            "A rain of stars, and rather cold; a spell I'm told is very old.",
            "The moon looks down. The moon looks on. And then a piece of it is gone.",
            "Silver, and falling, and precise; the moon has never asked me twice.",
        },

        ["SPELL:Elune's Grace"] = {
            "The moon has laid her hand on me; go on and try to hit. We'll see.",
            "Grace from above, and rather thin; but arrows will not find me in.",
            "I'm harder now to strike or spot; the moonlight helps me rather a lot.",
            "Swing away. I'll step aside. The moon has made me rather wide.",
            "Try it, %t. Go on. Do try. It rather makes the arrows shy.",
            "Elune is watching. So take care. There's more than me that's standing there.",
            "A gift of moonlight, briefly worn; it's rather better than forlorn.",
            "You'll find me difficult to land; there's silver sitting on my hand.",
            "Not armour. Something rather odd. A quiet argument with god.",
            "The moon's own grace, and only brief; but brief is rather a relief.",
            "Missed! And missed! And missed once more! That's rather what the grace is for.",
            "Under the moon I'm hard to catch; you'll find I'm rather more than match.",
        },

        ["SPELL:Feedback"] = {
            "Cast at me! Go on! I dare! It costs you rather dearly there!",
            "Every spell you throw comes back! A rather elegant attack!",
            "You're paying mana just to try! And that will rather make you cry!",
            "It's automatic! Not from me! It punishes them constantly!",
            "Cast away, %t! Cast some more! That's rather what the thing is for!",
            "Your mana's leaking! Yes, it is! And every drop of it is his!",
            "I don't lift a finger! Not at all! It simply drains them at the call!",
            "Feedback! Like a screaming string! A thoroughly obnoxious thing!",
            "They never notice till it's late; and then they're empty, and irate!",
            "The more you cast, the less you've got! It's rather more than I have not!",
            "A tax on magic! Simple! Neat! And rather difficult to beat!",
            "It hums along and does its bit! I rather like the look of it!",
        },

        ["SPELL:Chastise"] = {
            "You've been extremely badly behaved; stand there a while and be saved.",
            "A scolding, and a holy one; now stand quite still until I'm done.",
            "That's quite enough from you today; the Light has told you not to play.",
            "Chastised, and standing rather stunned; the lesson's taught, the lesson's done.",
            "Sit down, %t. Sit down and think. You're rather closer to the brink.",
            "I do not shout. I do not swear. I simply stop you standing there.",
            "A holy word to make you wait; the Light is punctual, if late.",
            "You've earned this. Truly. Yes, you have. It's rather more a scold than salve.",
            "Held in the Light and rather cross; a small correction, not a loss.",
            "The Light does discipline as well; it's rather less discussed, I'll tell.",
            "Stand still and think on what you've done; the sermon's short. The sermon's won.",
            "A rap across the knuckles, then; do not go doing that again.",
        },

        ["SPELL:Symbol of Hope"] = {
            "A symbol raised against the dark; take heart, and take a little spark.",
            "Mana for all, and hope besides; the draenei know a thing that guides.",
            "Hold on. Hold on. There's more to come. The well is not yet fully done.",
            "I raise it up. You all refill. It's rather more than force of will.",
            "Look up, %t. Look up and see; there's rather more of this in me.",
            "Hope is a resource. Odd, but so. And now there's rather more to go.",
            "The party's wells begin to rise; a small and stubborn kind of prize.",
            "When everything is nearly lost, that's rather when it's worth the cost.",
            "A little hope goes rather far; it's why we're standing where we are.",
            "Not healing. Something more like will. And everybody's casting still.",
            "Raised high, and shining, and it stays; the finest of the draenei ways.",
            "Hope, and the mana that it brings; the most peculiar of things.",
        },

        ["SPELL:Consume Magic"] = {
            "I ate your buff! I really did! And now it's mana. Off the lid!",
            "That's mine! It's mine! It's mine to eat! An elvish and delightful feat!",
            "Whatever's on you comes right off; and turns to mana. Do not scoff!",
            "Nom! And that was rather nice! I'd do it more than once or twice!",
            "Off it comes, %t, and down; the tastiest thing in all the town!",
            "It's not a dispel! It's a meal! It's rather a delightful deal!",
            "A buff removed! A well refilled! And absolutely no one killed!",
            "I'll take that, thank you. Yes. Right off. And no, I will not give it off!",
            "Two birds! One word! And rather quick! My favourite of the elvish trick!",
            "You put a lot of work in there; and now it's mine, and I don't care!",
            "Consumed! And rather nicely too! There's very little left of you!",
            "That's magic in my mana bar! I'd say I've rather come quite far!",
        },
    },
}
