-- RPVox -- mood pack: GRIM (Priest)
--
-- Lines are stored plain; the addon prefixes each with [grim] when seeding.
-- Voice: cold, quiet, and dangerous. No humour, no fatigue -- intent. This is
-- the mood where the Shadow is closest and the man is furthest away.

RPVox_MOOD_LINES = RPVox_MOOD_LINES or {}

RPVox_MOOD_LINES.GRIM = {
    name  = "grim",
    class = "PRIEST",

    ["REACT:LOWHEALTH"] = {
        "Cut deeper. I want to see what is under it, %t.",
        "You have opened a dead thing. Look inside, %t.",
        "/em does not react to the wound at all",
        "%t. There is nothing in me left to kill.",
        "Take it. It was never mine, %t.",
        "You are hurting a corpse. Think about that, %t.",
        "%t. I bleed cold. Notice the colour.",
        "Every wound teaches me something about you, %t.",
        "Keep going. See what answers, %t.",
        "%t. The Shadow tastes blood. It is interested.",
        "You should not have made me bleed, %t.",
        "%t. This is how it begins.",
        "%t. I am at my most dangerous like this.",
        "Nothing you do reaches me, %t.",
        "Look at what you have opened, %t.",
        "%t. The wound does not close. Neither will this.",
        "You are running out of me to destroy, %t.",
        "%t. I have been carved before. By experts.",
        "/em watches the blood fall with distant interest",
        "There is very little left, and all of it is aimed at you, %t.",
        "%t. Hurt me. It only sharpens things.",
        "%t. This body is a formality.",
        "You are close. That should frighten you, %t.",
        "%t. The dark comes nearer when I am like this.",
        "Cut me open. See what crawls out, %t.",
        "I do not fear the ending. You should, %t.",
        "%t. Blood is just another thing I have lost.",
        "%t. This is the part where it turns.",
        "%t. Nothing is holding me together but intent.",
        "You have made a mistake and it is not this wound, %t.",
        "%t. The whispers are very loud now.",
        "%t. I have nothing left to lose. Consider that.",
        "So little of me remains. All of it is for you, %t.",
        "You will not survive what comes next, %t.",
        "This wound will outlast you, %t.",
        "%t. I feel the cold coming. It is not for me.",
        "Take another piece. There are not many left, %t.",
        "%t. The Shadow is closest when the flesh fails.",
        "Look what you have started, %t.",
        "%t. There is no fear in this body. Only purpose.",
        "You have hurt me and I will remember precisely, %t.",
        "%t. Nothing left but the working.",
        "Cut, then. It changes nothing, %t.",
        "This is a very dangerous moment for you, %t.",
        "/em straightens slowly, and the air goes colder",
        "I am running out. So are you, %t.",
        "You wanted to see me bleed. Look closely, %t.",
        "%t. The last of me is the worst of me.",
        "%t. Nothing about this frightens me.",
        "%t. Now it is serious.",
        "%t. That wound is a promise.",
        "%t. I have died before and come back angrier.",
        "%t. The dark does not abandon me at the end.",
        "Push. See what pushes back, %t.",
        "Every drop is one you will answer for, %t.",
        "%t. There is nothing kind left in me.",
        "You are watching a thing that cannot be killed properly, %t.",
        "The rot goes deeper than your blade, %t.",
        "%t. I have nothing to protect. That makes me free.",
        "%t. This is where the polite part ends.",
        "You should have finished it, %t.",
        "%t. So close. And still not enough.",
        "The whispers say your name now, %t.",
        "%t. Nothing survives what I am about to do.",
        "%t. I am hollowed out and still standing.",
        "You have taken everything but the intent, %t.",
        "%t. Cold. Good. Cold is useful.",
        "%t. The wound is deep. My patience is deeper.",
        "%t. There is no mercy waiting at the bottom of this.",
        "You are looking at the last of a man, %t.",
        "%t. The Shadow steadies what the body cannot.",
        "Now you have my attention entirely, %t.",
        "%t. I will remember this wound specifically.",
        "%t. Nothing left to bargain with.",
        "Take the rest. Then answer for it, %t.",
        "You have opened something that should stay shut, %t.",
        "%t. The dark is very close. It is not here for me.",
        "%t. So be it. Let it come.",
        "%t. I am past caring what this costs.",
        "%t. That was almost enough. Almost.",
        "%t. There is nothing behind my eyes but the work.",
        "You will not walk away from this, %t.",
        "%t. The last of my blood is the coldest.",
        "/em smiles without any warmth at all",
        "%t. I have been ruined for years. This is nothing.",
        "You have made this personal, %t.",
        "%t. Nothing stops now.",
        "There is no version of this where you win, %t.",
        "The wound is yours to answer for, %t.",
        "I am nearly finished. So is your time, %t.",
        "%t. The Dark Lady is watching this.",
        "Cut all you like. It ends the same way, %t.",
        "You are bleeding a thing that does not stop, %t.",
        "%t. So little left. So much intent.",
        "%t. The cold in me is spreading outward now.",
        "Nothing you have will be enough, %t.",
        "This is where you learn what I am, %t.",
        "%t. There is no fear here. Only arithmetic.",
        "Take it. Then take what follows, %t.",
        "You are wounding something that does not stop, %t.",
        "You are close, %t. That should frighten you.",
        "Cut deeper, %t. See what is under it.",
        "You are hurting a corpse, %t.",
        "Keep going, %t. See what answers.",
        "You have made this personal, %t.",
        "There is very little left, %t, and all of it is for you.",
        "You should have finished it, %t.",
        "That wound is a promise, %t.",
        "I have nothing left to lose, %t. Consider that.",
        "You will not survive what comes next, %t.",
        "Hurt me, %t. It only sharpens things.",
        "The last of me is the worst of me, %t.",
        "You are running out of me, %t.",
        "This is where you learn what I am, %t.",
        "Nothing you do reaches me, %t.",
        "Push, %t. See what pushes back.",
        "You have opened something that should stay shut, %t.",
        "Take another piece, %t. There are few left.",
        "I bleed cold, %t. Notice the colour.",
        "You are bleeding a thing that does not stop, %t.",
        "That was almost enough, %t. Almost.",
        "I have been carved by experts, %t. You are not one.",
        "You will answer for every drop, %t.",
        "Now it is serious, %t.",
        "There is nothing kind left in me, %t.",
    },

    ["REACT:DEATH"] = {
        "%t. This is not finished.",
        "You have delayed me. Nothing more, %t.",
        "/em falls without a sound",
        "I will find you, %t.",
        "Remember the face, %t.",
        "%t. The dark keeps me only briefly.",
        "You have made an enemy that does not stay buried, %t.",
        "%t. This changes nothing at all.",
        "%t. I return. Count on it.",
        "%t. Nothing ends here.",
        "You should have made certain, %t.",
        "%t. The Shadow does not forget.",
        "Take your moment. It is borrowed, %t.",
        "%t. I have been killed by better and buried them after.",
        "%t. This is a pause. Not a conclusion.",
        "You will see me again, %t.",
        "%t. Nothing is settled.",
        "%t. The grave and I have an understanding.",
        "Enjoy it while it lasts, %t.",
        "%t. That was not enough to end me.",
        "I mark this. I mark you, %t.",
        "%t. There will be an accounting.",
        "You have killed nothing that was alive, %t.",
        "%t. The dark receives me. It always sends me back.",
        "%t. This is not how it ends.",
        "Remember what you did here, %t.",
        "%t. I fall. The intent does not.",
        "Nothing you have done matters, %t.",
        "You are already too late, %t.",
        "/em goes cold and still, eyes open",
        "%t. The Dark Lady is not finished with me.",
        "You will regret being efficient, %t.",
        "%t. There is no victory in this.",
        "%t. I will be back before the blood dries.",
        "%t. Nothing about this is final.",
        "Say nothing. Just wait, %t.",
        "%t. The dead keep excellent records.",
        "You have bought hours. No more, %t.",
        "%t. This is temporary. My attention is not.",
        "I know your name now, %t.",
        "%t. The ground is only ever a stopping place.",
        "%t. Nothing is over.",
        "You will not enjoy the second meeting, %t.",
        "%t. This debt carries.",
        "%t. I go into the dark. It knows me.",
        "%t. That was a mistake dressed as a victory.",
        "%t. Nothing here is concluded.",
        "%t. The whispers follow me down. They will come back up.",
        "You should be frightened of what returns, %t.",
        "%t. I have unfinished business and now it has a face.",
        "%t. This is not defeat. It is delay.",
        "%t. The dark is not an ending for my kind.",
        "Take the field. Keep it warm, %t.",
        "%t. I will come back for this.",
        "%t. Nothing forgotten. Nothing forgiven.",
        "You have killed a dead man. Consider what that means, %t.",
        "%t. This will be answered.",
        "%t. The Shadow keeps my place.",
        "Count the hours. I will, %t.",
        "%t. Nothing ends when I fall.",
        "That was well done. It will not save you, %t.",
        "%t. I mark the ground and the hour.",
        "%t. There is no rest waiting for either of us.",
        "You are now part of a very long list, %t.",
        "Down. Not done, %t.",
        "%t. The dark holds nothing I fear.",
        "%t. I return colder each time.",
        "%t. Nothing was settled by that.",
        "You have my full attention now. Permanently, %t.",
        "%t. This is a wound in a very long memory.",
        "%t. The grave is a doorway. I use it often.",
        "Nothing you do prevents what comes back, %t.",
        "%t. I will remember precisely how this went.",
        "That will cost more than you have, %t.",
        "%t. The dead are patient and I am the dead.",
        "%t. So. Again into the dark.",
        "You have earned something you do not want, %t.",
        "%t. This ends when I say it ends.",
        "%t. Nothing here is finished.",
        "%t. I fall quietly. I return otherwise.",
        "%t. The Shadow will bring me back sharper.",
        "Take your victory. Hold it carefully, %t.",
        "%t. There is a reckoning attached to this.",
        "%t. Nothing about my death is a conclusion.",
        "You will not be ready, %t.",
        "%t. I go. I always come back.",
        "That was the easy part for you, %t.",
        "%t. The dark and I are old colleagues.",
        "Remember this ground, %t.",
        "%t. Nothing lost that I will not reclaim.",
        "You have started something long, %t.",
        "I will be waiting when you are tired, %t.",
        "%t. This is one step in a very long walk.",
        "%t. The whispers will carry it back to me.",
        "%t. Nothing about this is the end.",
        "You should have run when it was possible, %t.",
        "%t. I fall. Watch the ground.",
        "%t. That is not the last of me.",
        "%t. The dark keeps nothing that belongs to her.",
        "%t. The dark is only a corridor. I know the way back.",
    },

    ["REACT:RESURRECT"] = {
        "I said I would return.",
        "Back. Colder.",
        "/em rises with the air chilling around him",
        "Now we continue.",
        "The dark returned me. It has a reason.",
        "You should have made certain, %t.",
        "I remember everything.",
        "Nothing was resolved while I was gone.",
        "Back, and less patient.",
        "The debt is still owed.",
        "Where is the one who did it.",
        "I have come back angrier.",
        "The Shadow keeps its investments.",
        "Nothing changed. Except my intent.",
        "Up. And looking for someone.",
        "That was a mistake you cannot undo, %t.",
        "Back. Do not run. It never works.",
        "The grave released me early.",
        "I return, and I recall the details.",
        "Nothing forgives what happened here.",
        "Standing. Cold. Focused.",
        "You had your hours. They are spent, %t.",
        "The dark had questions. I answered them.",
        "Back in the world. Regrettably for you, %t.",
        "Nothing waits for me down there. Only work up here.",
        "I have returned with a list.",
        "The Dark Lady's investment continues.",
        "Up, and the temperature falls.",
        "That killing bought nothing.",
        "Back. Precisely as promised.",
        "/em opens his eyes and they are entirely without light",
        "Every return costs something. Someone will pay it.",
        "Nothing was settled. Now it will be.",
        "I am back and the whispers came with me.",
        "You should be counting exits, %t.",
        "The dark sends me back for a purpose.",
        "Standing again. Colder than before.",
        "There is unfinished work and I know exactly what it is.",
        "Nothing about me improved down there.",
        "Back, and less inclined to mercy.",
        "The grave is not a punishment for my kind.",
        "I have returned. Attend to that fact.",
        "Nothing has changed but my patience.",
        "Up. Where is the one who did it.",
        "That interruption is over.",
        "The Shadow does not waste its servants.",
        "Back. Colder, quieter, worse.",
        "You are exactly where I left you. Good, %t.",
        "Nothing forgotten in the dark.",
        "I return with the same intent, sharpened.",
        "Standing. The debt stands with me.",
        "The dark holds no comfort. Only instruction.",
        "Back among you. Behave accordingly, %t.",
        "Nothing survives my attention forever.",
        "I have been raised again. Someone will regret arranging it.",
        "Up and looking for a name.",
        "That death changed nothing except the schedule.",
        "The whispers filled the silence with plans.",
        "Back. Watch me.",
        "Nothing about the dark frightens me. Nothing here does either.",
        "Returned, and remembering.",
        "The Dark Lady's work resumes.",
        "I am standing. That should concern someone.",
        "Nothing left down there for me.",
        "Up. Cold. Ready.",
        "The grave keeps sending me back. It knows why.",
        "Back with the same purpose, undiluted.",
        "You had your reprieve, %t.",
        "Nothing changed but the hour.",
        "I return. Note the time.",
        "The dark and I concluded our business.",
        "Standing. Nothing about me softened.",
        "Back, and the list is unchanged.",
        "Nothing was lost that mattered.",
        "I am here again. That is not good news.",
        "Up. The work continues.",
        "That was a delay, as I said.",
        "The Shadow returns what it needs.",
        "Back. Colder than the ground I came from.",
        "Nothing has ended.",
        "I remember the face and the hour.",
        "Standing again. Continue as before.",
        "The dark returned me sharper than I went in.",
        "Back. Say nothing.",
        "Nothing about this is finished.",
        "I return, and the debt returns with me.",
        "Up, and thoroughly focused.",
        "That was your window. It is closed, %t.",
        "The whispers welcomed me back with suggestions.",
        "Back. Colder. Certain.",
        "Nothing waits but the work.",
        "I have returned exactly as promised.",
        "Standing. The reckoning stands too.",
        "The grave is a door. I use it. I return.",
        "Back, and nothing is forgiven.",
        "Nothing about me is improved. Good.",
        "Up. Now. Where were we.",
        "Back, and the cold came with me.",
        "Nothing down there changed my intent.",
        "I said I would return. Note that I did.",
    },

    ["REACT:KILLINGBLOW"] = {
        "Stay down. Stay dead, %t.",
        "/em watches until the body stops moving entirely",
        "%t. That is what happens.",
        "Nothing left of you, %t.",
        "You should have run, %t.",
        "%t. One less thing breathing.",
        "The dark takes you now. It is not gentle, %t.",
        "%t. Finished. Completely.",
        "There will be no returning for you, %t.",
        "%t. That is the difference between us.",
        "You go into the ground and stay there, %t.",
        "%t. Nothing survives me for long.",
        "%t. Cold already. Good.",
        "Down. And that is permanent, %t.",
        "%t. The Shadow takes what it is owed.",
        "You were warned. Everyone is warned, %t.",
        "That is the whole of your story, %t.",
        "Nothing more from you, %t.",
        "The dirt gets you. It does not get me, %t.",
        "I gave you an ending. It is more than I received, %t.",
        "Stay where you fell, %t.",
        "%t. Nothing left to answer for.",
        "%t. That is a clean finish. Do not expect gratitude.",
        "You will not rise. I would know, %t.",
        "Down. Silent. Permanent, %t.",
        "The dark closes over you, %t.",
        "%t. One more name gone.",
        "Nothing of you continues, %t.",
        "You had a life. It is concluded, %t.",
        "%t. That is what defiance costs.",
        "/em turns away without a word",
        "Rest, and be grateful it takes, %t.",
        "Nothing about this was personal until you made it so, %t.",
        "The ground is yours now, %t.",
        "Down. Where you belong, %t.",
        "%t. That is the end of the argument.",
        "You are finished in a way I never was, %t.",
        "%t. Nothing left standing between me and the next.",
        "The dark received you quietly, %t.",
        "%t. One less voice in a very loud world.",
        "You should have chosen differently, %t.",
        "%t. That is settled permanently.",
        "Nothing you did mattered in the end, %t.",
        "%t. Cold and still. As intended.",
        "The Dark Lady counts you now, %t.",
        "Down. Do not stir, %t.",
        "You get the rest. I get the walking, %t.",
        "%t. Nothing about this was in doubt.",
        "%t. That was necessary and I did it well.",
        "%t. The whispers are satisfied. Briefly.",
        "%t. One more finished properly.",
        "You will not be coming back. Envy that, %t.",
        "Down. And permanently so, %t.",
        "Nothing further from you, %t.",
        "%t. The dark does not send everyone back.",
        "That is the last thing you will do, %t.",
        "You are ended. Truly ended, %t.",
        "%t. Nothing of that was wasted.",
        "The ground takes you cleanly, %t.",
        "%t. One more debt closed.",
        "You had your chance to walk away, %t.",
        "%t. That is what I do.",
        "Nothing left to fight in you, %t.",
        "Down, and no rising, %t.",
        "%t. The Shadow is fed. For now.",
        "You are quiet at last. Permanently, %t.",
        "Nothing about you continues past this, %t.",
        "%t. That is a proper ending.",
        "Rest, %t. You will not be disturbed.",
        "Down. Cold. Concluded, %t.",
        "The dark keeps you. It rarely keeps me, %t.",
        "%t. One more thing that will not rise.",
        "You are finished and I am not, %t.",
        "%t. Nothing survives contact with this for long.",
        "%t. That is the price. Paid in full.",
        "The ground closes over you, %t.",
        "Down. Do not be found, %t.",
        "Nothing left of what you were, %t.",
        "You met the wrong dead man, %t.",
        "%t. That ends it cleanly.",
        "The whispers count you and move on, %t.",
        "%t. One more silence made.",
        "You will stay in the dirt. That is the gift, %t.",
        "%t. Nothing more required here.",
        "Down. Permanently. Good, %t.",
        "%t. The dark received another.",
        "That is the last of you, %t.",
        "You are finished. Envy that, %t.",
        "%t. Nothing about that took long.",
        "%t. One more ending, cleanly made.",
        "%t. The Dark Lady's tally grows.",
        "Down and done with, %t.",
        "You will not be missed. Not by me, %t.",
        "Nothing left to say over you, %t.",
        "%t. That is concluded permanently.",
        "The ground has you now, %t.",
        "%t. One less. There will be others.",
        "You are ended. Completely and finally, %t.",
        "Down. The dark takes it from here, %t.",
        "%t. Nothing of that will trouble the world again.",
        "That is the end of you, %t.",
        "Stay in the dirt, %t.",
        "You are finished, %t. Entirely.",
        "Nothing of you continues, %t.",
        "You met the wrong dead man, %t.",
        "Rest, %t. You will not be disturbed.",
        "The dark has you now, %t.",
        "You will not rise, %t. I made certain.",
        "That was your whole story, %t.",
        "Go quietly, %t. You have no other option.",
        "You are ended, %t, and I am not.",
        "The ground takes you cleanly, %t.",
        "No more from you, %t.",
        "You had your chance, %t. It is spent.",
        "That is what defiance cost you, %t.",
        "You are cold already, %t. Efficient.",
        "Sleep, %t. It is more than I was given.",
        "The Dark Lady counts you now, %t.",
        "You will stay down, %t. That is the gift.",
        "Nothing survives me for long, %t.",
        "You are quiet at last, %t.",
        "That is settled permanently, %t.",
        "You are material now, %t. Nothing more.",
        "The dirt claims you, %t.",
        "One less voice, %t. Yours.",
    },

    ["REACT:COMBATSTART"] = {
        "You should not have, %t.",
        "/em fixes his eyes on %t and does not blink",
        "%t. That was a mistake.",
        "Come here, %t.",
        "%t. The Shadow wakes.",
        "You have chosen very poorly, %t.",
        "There is no version of this you survive, %t.",
        "%t. Nothing will be left.",
        "Stand still. It is easier, %t.",
        "%t. I am not in a forgiving mood.",
        "%t. The dark leans in.",
        "You have my attention. That is fatal, %t.",
        "%t. This ends one way.",
        "Do not run. It is worse when you run, %t.",
        "%t. Nothing about this will be quick.",
        "%t. I have been waiting for a reason.",
        "The whispers are already counting you, %t.",
        "You will not leave this ground, %t.",
        "%t. Cold work ahead.",
        "%t. That was the last free breath.",
        "Come, then. Learn something, %t.",
        "%t. Nothing here will be merciful.",
        "%t. The Dark Lady is watching. Perform.",
        "You are already finished. You simply do not know it, %t.",
        "%t. This will be thorough.",
        "%t. I do not fight. I conclude.",
        "%t. The dark is hungry today.",
        "You have made a serious error, %t.",
        "%t. Nothing survives what is about to happen.",
        "Stand where you are, %t.",
        "/em raises both hands and the light dims slightly",
        "That was your one chance to leave, %t.",
        "%t. There is nothing to negotiate.",
        "%t. The Shadow does the talking now.",
        "You will regret every step that brought you here, %t.",
        "%t. Nothing about me is patient today.",
        "%t. This is not a fight. It is an ending.",
        "Come closer. I want to be certain, %t.",
        "The whispers name you already, %t.",
        "You should be running. It will not help, %t.",
        "%t. Nothing will remain.",
        "%t. That is far enough.",
        "%t. I am cold today. Very cold.",
        "%t. There is no mercy in this mood.",
        "The dark and I are in agreement about you, %t.",
        "You have earned my full attention, %t.",
        "%t. Nothing pleasant follows.",
        "Stand and be finished, %t.",
        "%t. This will be exact.",
        "%t. The Shadow rises with me.",
        "You are already in the ground. Formalities remain, %t.",
        "%t. Nothing here will be gentle.",
        "Come. Let us conclude this, %t.",
        "%t. That was a poorly chosen fight.",
        "%t. I will make this permanent.",
        "%t. The dark has been waiting.",
        "You will not walk away, %t.",
        "%t. Nothing about my intent is uncertain.",
        "%t. This is what I am for.",
        "Do not speak. Just begin, %t.",
        "%t. The whispers want it done properly.",
        "You have chosen an ending, %t.",
        "%t. Nothing survives this attention.",
        "%t. Cold hands, cold work.",
        "That is enough noise from you, %t.",
        "%t. I have no patience in this mood.",
        "%t. The Dark Lady's business begins.",
        "You should have kept walking, %t.",
        "%t. Nothing here bargains.",
        "Stand still and it ends sooner, %t.",
        "This is the last conversation you have, %t.",
        "The dark closes in behind you, %t.",
        "You are exactly where I need you, %t.",
        "%t. Nothing about this is negotiable.",
        "Come along. It ends the same either way, %t.",
        "That was your final mistake, %t.",
        "%t. I am going to be thorough.",
        "%t. The Shadow does not blink.",
        "You have picked the wrong dead man, %t.",
        "Nothing you brought is enough, %t.",
        "This will not take long. Regrettably for you, %t.",
        "%t. The whispers are impatient.",
        "You will be finished properly, %t.",
        "Nothing of you will remain standing, %t.",
        "%t. Cold. Focused. Beginning.",
        "%t. That is close enough.",
        "%t. I am at my worst today.",
        "%t. The dark is very near.",
        "You have started something final, %t.",
        "%t. Nothing here is survivable.",
        "Stand. Face it, %t.",
        "%t. This is an execution with extra steps.",
        "%t. The Dark Lady watches. Behave accordingly.",
        "You have my complete and cold attention, %t.",
        "%t. Nothing follows this but silence.",
        "Come here and be finished, %t.",
        "That was the wrong choice, %t.",
        "%t. I intend to be very thorough.",
        "You have walked into something cold, %t.",
        "Nothing about this ends well for you, %t.",
        "You should not have, %t.",
        "Come here, %t.",
        "Stand still, %t. It is easier.",
        "You have chosen very poorly, %t.",
        "There is no version of this you survive, %t.",
        "Do not run, %t. It is worse when you run.",
        "I have been waiting for a reason, %t.",
        "You will not leave this ground, %t.",
        "That was your last free breath, %t.",
        "Nothing about this will be quick, %t.",
        "The whispers are counting you already, %t.",
        "You have my full attention now, %t. That is fatal.",
        "Come closer, %t. I want to be certain.",
        "You are already finished, %t. You simply do not know it.",
        "This ends one way, %t.",
        "The dark leans toward you, %t.",
        "You picked the wrong corpse, %t.",
        "Stand and be finished, %t.",
        "Nothing you brought is enough, %t.",
        "I intend to be thorough with you, %t.",
        "That is far enough, %t.",
        "You have earned something you do not want, %t.",
        "The Shadow has noticed you, %t.",
        "Do not speak, %t. Just begin.",
        "You are exactly where I need you, %t.",
    },

    ["REACT:COMBATEND"] = {
        "Nothing left standing.",
        "It is done.",
        "/em surveys the bodies without expression",
        "That is finished.",
        "Silence. As it should be.",
        "The ground has them now.",
        "Nothing survived.",
        "Complete.",
        "The Shadow is quiet again.",
        "That was thorough.",
        "Nothing more to end here.",
        "Leave them where they fell.",
        "The dark is fed. Briefly.",
        "It is concluded.",
        "Nothing moves. Good.",
        "That is the whole of it.",
        "They chose this ground. They keep it.",
        "The whispers settle.",
        "Nothing left to answer.",
        "Done. Properly done.",
        "The field is quiet and permanent.",
        "That is what happens.",
        "Nothing rises here again.",
        "It is finished cleanly.",
        "The Dark Lady's work, concluded.",
        "Nothing further required.",
        "Silence, and I made it.",
        "That is the end of them.",
        "Leave nothing behind but the bodies.",
        "The dark closes over the field.",
        "Nothing survived my attention.",
        "It ends. As I said it would.",
        "That is settled permanently.",
        "The whispers are quiet. Rare.",
        "Nothing left worth naming.",
        "Complete and cold.",
        "They are finished. Entirely.",
        "The ground is quieter now.",
        "Nothing more to do here.",
        "It is over, and thoroughly.",
        "That was necessary.",
        "The Shadow withdraws, satisfied.",
        "Nothing rises from this.",
        "Done. Move on.",
        "The field belongs to the dead. As always.",
        "Nothing here breathes.",
        "That is concluded.",
        "Silence returns. I prefer it.",
        "The dark is patient again.",
        "Nothing left of them.",
        "It is ended.",
        "That was properly finished.",
        "The whispers approve. Briefly.",
        "Nothing remains standing but me.",
        "Complete. Onward.",
        "They are quiet. Permanently.",
        "The ground took them cleanly.",
        "Nothing more will come from here.",
        "It is done and it will stay done.",
        "That is what thorough looks like.",
        "The Dark Lady is served.",
        "Nothing survives long here.",
        "Finished. Entirely finished.",
        "Silence. Earned.",
        "The dark settles back.",
        "Nothing left to conclude.",
        "It ends the way it had to.",
        "That field is finished.",
        "The whispers have nothing left to count.",
        "Nothing stands. Good.",
        "Complete. Cold. Quiet.",
        "They will not be getting up.",
        "The ground keeps them.",
        "Nothing follows.",
        "It is over. Permanently.",
        "That was concluded properly.",
        "The Shadow rests. So do they.",
        "Nothing here is unfinished.",
        "Done. Entirely.",
        "Silence, and it is mine.",
        "The dark has what it came for.",
        "Nothing left of that at all.",
        "It ends. Cleanly.",
        "That is thorough work.",
        "The whispers go quiet at last.",
        "Nothing moving anywhere.",
        "Complete. Nothing wasted.",
        "They are ended. Every one.",
        "The field is quiet and it will stay quiet.",
        "Nothing further from them.",
        "It is finished. Move.",
        "That was correctly done.",
        "The Dark Lady's tally grows again.",
        "Nothing remains.",
        "Done. Cold and done.",
        "Silence. Finally, silence.",
        "The dark keeps this ground now.",
        "Nothing left standing but the one who should not be.",
        "Nothing here will trouble anyone again.",
        "The quiet I leave behind is permanent.",
    },

    ["REACT:INTERRUPTED"] = {
        "You will regret that, %t.",
        "/em goes very still and very cold",
        "Do that again, %t.",
        "%t. That was noted.",
        "You have made this worse for yourself, %t.",
        "%t. Nothing is prevented. Only delayed.",
        "%t. I will remember the timing.",
        "%t. The Shadow does not forget interruptions.",
        "That will cost you a great deal, %t.",
        "You should not have touched me, %t.",
        "Delay all you like, %t.",
        "Nothing you do stops what is coming, %t.",
        "That was your last clever moment, %t.",
        "%t. I have all the time the grave gave me.",
        "You have annoyed something patient and cold, %t.",
        "%t. The words will come again. So will I.",
        "That bought you seconds and cost you more, %t.",
        "%t. Nothing changes except my mood.",
        "You will pay for that specifically, %t.",
        "%t. The whispers are irritated now. That is worse.",
        "Do it again. Please, %t.",
        "Nothing about that helped you, %t.",
        "I mark it. I mark you, %t.",
        "%t. That was a mistake with consequences.",
        "You cannot silence what is already dead, %t.",
        "%t. The dark finds another way in.",
        "%t. That will be remembered precisely.",
        "%t. Nothing prevented. Only postponed.",
        "You have made it personal now, %t.",
        "%t. I will finish it. Slower. Deliberately.",
        "%t. That was rude and it was final.",
        "%t. The Shadow speaks when I cannot.",
        "You should not have done that, %t.",
        "Nothing you have will hold me long, %t.",
        "Delay me again. I dare you, %t.",
        "%t. The words scatter. My intent does not.",
        "%t. That is one interruption too many.",
        "You have bought yourself something unpleasant, %t.",
        "%t. I am colder for that.",
        "%t. Nothing about that was wise.",
        "/em looks up slowly, and nothing behind the eyes moves",
        "%t. That was noted and filed.",
        "You will answer for the interruption, %t.",
        "%t. The dark does not require my voice.",
        "%t. That changed the terms considerably.",
        "%t. Nothing is stopped. It is only slower now.",
        "%t. I will do it again. Worse.",
        "You have made a very poor choice, %t.",
        "%t. The whispers finish what I start.",
        "%t. That will be repaid with interest.",
        "%t. Nothing silences intent.",
        "Do it once more and see what answers, %t.",
        "I have been interrupted by death. You are less, %t.",
        "That was your best moment. It is over, %t.",
        "You should be frightened now, %t.",
        "%t. The Shadow remembers everything.",
        "%t. Nothing prevented. Everything remembered.",
        "That earns you a slower ending, %t.",
        "I will take longer with you now, %t.",
        "You have made this considerably worse, %t.",
        "The dark is patient. So am I. You are not, %t.",
        "%t. That was a costly second.",
        "Nothing you do reaches the intent, %t.",
        "%t. I mark the interruption and the hand that made it.",
        "You will regret being quick, %t.",
        "%t. The words return. They always return.",
        "%t. That accomplished nothing but my attention.",
        "%t. Nothing stops this now.",
        "Do that again and I stop being careful, %t.",
        "%t. I am colder than I was a moment ago.",
        "You have chosen a worse ending for yourself, %t.",
        "The whispers are counting your seconds, %t.",
        "%t. That will be answered in full.",
        "%t. Nothing about this is over.",
        "I will begin again. You will not enjoy it, %t.",
        "You interrupted a working. That is noticed, %t.",
        "%t. The dark does not need permission.",
        "%t. That was recorded.",
        "Nothing you break stays broken, %t.",
        "%t. I have other means. All of them worse.",
        "You should have used that moment to run, %t.",
        "%t. The Shadow takes offence on my behalf.",
        "That was your mistake, plainly made, %t.",
        "%t. Nothing here is postponed for long.",
        "Do it again and it becomes personal, %t.",
        "%t. I remember every interruption. Every one.",
        "You have earned my full attention now, %t.",
        "%t. The words break. The purpose does not.",
        "That will be very expensive for you, %t.",
        "%t. Nothing stops the cold.",
        "%t. I will finish this deliberately now.",
        "You made it worse. Considerably, %t.",
        "%t. The dark keeps score.",
        "%t. That was noted with interest.",
        "%t. Nothing prevented. Only sharpened.",
        "%t. I begin again, and colder.",
        "You will not like the second attempt, %t.",
        "%t. That will be answered slowly.",
        "You have delayed a very patient thing, %t.",
        "Nothing you did changed the ending, %t.",
        "You will regret that, %t.",
        "Do that again, %t.",
        "That was noted, %t.",
        "You have made this worse for yourself, %t.",
        "I will remember the timing, %t.",
        "That will cost you a great deal, %t.",
        "You should not have touched me, %t.",
        "Delay all you like, %t.",
        "You cannot silence what is already dead, %t.",
        "That was your best moment, %t. It has passed.",
        "I have other means, %t. All of them worse.",
        "You have annoyed something patient, %t.",
        "The words return, %t. So do I.",
        "Interrupt me again, %t. Please.",
        "That bought you a second, %t. It cost you more.",
        "You know what I am about to do, %t.",
        "Every interruption lengthens this, %t.",
        "The Shadow does not forget you, %t.",
        "Fine, %t. The ugly way.",
        "You have chosen a slower ending, %t.",
        "That changes the method, %t. Not the outcome.",
        "I begin again, %t, and colder.",
        "You will not manage that twice, %t.",
        "Noted and filed, %t.",
        "That was rude, %t, and pointless.",
    },
}
