-- RPVox -- Druid class pack
--
-- Voice: a Kaldorei who has only half returned from the Emerald Dream. She
-- speaks slightly out of step with the present, mistakes this war for an older
-- one, and is never entirely certain how long she has been awake. Gentle, very
-- old, and absolutely lethal in the moments she is fully here.
--
-- Single voice, no moods yet. Mood packs can be scoped with class = "DRUID".

RPVox_CLASSES.DRUID = {
    name = "Druid",
    spells = {
        { spell = "Wrath",            icon = "Interface\\Icons\\Spell_Nature_AbolishMagic",       chance = 10 },
        { spell = "Starfire",         icon = "Interface\\Icons\\Spell_Arcane_StarFire",           chance = 10 },
        { spell = "Moonfire",         icon = "Interface\\Icons\\Spell_Nature_StarFall",           chance = 10 },
        { spell = "Entangling Roots", icon = "Interface\\Icons\\Spell_Nature_StrangleVines",      chance = 10 },
        { spell = "Faerie Fire",      icon = "Interface\\Icons\\Spell_Nature_FaerieFire",         chance = 10 },
        { spell = "Hurricane",        icon = "Interface\\Icons\\Spell_Nature_Cyclone",            chance = 10 },
        { spell = "Cyclone",          icon = "Interface\\Icons\\Spell_Nature_EarthBind",          chance = 10 },
        { spell = "Hibernate",        icon = "Interface\\Icons\\Spell_Nature_Sleep",              chance = 10 },
        { spell = "Rejuvenation",     icon = "Interface\\Icons\\Spell_Nature_Rejuvenation",       chance = 10 },
        { spell = "Regrowth",         icon = "Interface\\Icons\\Spell_Nature_ResistNature",       chance = 10 },
        { spell = "Healing Touch",    icon = "Interface\\Icons\\Spell_Nature_HealingTouch",       chance = 10 },
        { spell = "Lifebloom",        icon = "Interface\\Icons\\INV_Misc_Herb_Felblossom",        chance = 10 },
        { spell = "Innervate",        icon = "Interface\\Icons\\Spell_Nature_Lightning",          chance = 10 },
        { spell = "Rebirth",          icon = "Interface\\Icons\\Spell_Nature_Reincarnation",      chance = 10 },
        { spell = "Mark of the Wild", icon = "Interface\\Icons\\Spell_Nature_Regeneration",       chance = 10 },
        { spell = "Thorns",           icon = "Interface\\Icons\\Spell_Nature_Thorns",             chance = 10 },
        { spell = "Bear Form",        icon = "Interface\\Icons\\Ability_Racial_BearForm",         chance = 10 },
        { spell = "Cat Form",         icon = "Interface\\Icons\\Ability_Druid_CatForm",           chance = 10 },
        { spell = "Travel Form",      icon = "Interface\\Icons\\Ability_Druid_TravelForm",        chance = 10 },
        { spell = "Prowl",            icon = "Interface\\Icons\\Ability_Ambush",                  chance = 10 },
        { spell = "Maul",             icon = "Interface\\Icons\\Ability_Druid_Maul",              chance = 10 },
        { spell = "Swipe",            icon = "Interface\\Icons\\INV_Misc_MonsterClaw_03",         chance = 10 },
        { spell = "Bash",             icon = "Interface\\Icons\\Ability_Druid_Bash",              chance = 10 },
        { spell = "Shred",            icon = "Interface\\Icons\\Spell_Shadow_VampiricAura",       chance = 10 },
        { spell = "Rip",              icon = "Interface\\Icons\\Ability_GhoulFrenzy",             chance = 10 },
        { spell = "Mangle",           icon = "Interface\\Icons\\Ability_Druid_Mangle2",           chance = 10 },
    },
    lines = {

        -- Abilities -----------------------------------------------------

        ["MELEE"] = {
            "%t. Teeth, then. If that is what you want.",
            "/em stops being careful with her hands",
            "%t. This shape has fewer manners.",
            "%t. Everything green defends itself. So do I.",
            "%t. I did not want to be close to you.",
            "/em strikes the way weather strikes, without malice",
            "%t. The wood is old and so am I.",
            "%t. Enough. Down.",
            "%t. Nothing personal. Only necessary.",
            "/em plants her feet and simply will not be moved",
        },
        ["SPELL:Wrath"] = {
            "%t. The wood is angry with you.",
            "/em lets something green and old travel down her arm",
            "%t. That was not me. That was the forest.",
            "%t. Everything here has an opinion of you.",
            "%t. I am only the nearest hand.",
            "/em speaks a word that grows heavier as it leaves her",
            "%t. Even the moss has heard about you.",
            "%t. Stop. Please. You are making it worse.",
        },

        ["SPELL:Starfire"] = {
            "%t. Look up. That is Elune, and she is looking back.",
            "/em pulls something white and burning down out of the sky",
            "%t. She does not often intervene. You have earned it.",
            "%t. The sky has been waiting for a reason.",
            "%t. This is very old light. It has come a long way for you.",
            "/em raises both hands and the night answers",
            "%t. Do not look directly at it.",
            "%t. Elune sees you now. I am sorry.",
        },

        ["SPELL:Moonfire"] = {
            "%t. A small silver thing, and it will not stop.",
            "/em marks a target with a fingertip of moonlight",
            "%t. It burns quietly. Most of the worst things do.",
            "%t. You will feel that all the way through.",
            "%t. Silver. It never washes out.",
            "/em traces a crescent in the air and lets it fall",
            "%t. Carry that with you.",
            "%t. The moon is patient. So am I. Mostly.",
        },

        ["SPELL:Entangling Roots"] = {
            "%t. Stay. The ground would like a word.",
            "/em presses two fingers to the earth and something below agrees",
            "%t. It has been waiting a long time for something to hold.",
            "%t. The more you pull, the tighter it gets.",
            "%t. The roots remember every footstep you took getting here.",
            "/em sinks her hand into soil that closes over it",
            "%t. Be still. Be still and it will be gentler.",
            "%t. You are standing on something older than your people.",
        },

        ["SPELL:Faerie Fire"] = {
            "%t. There you are. There you have been all along.",
            "/em lights someone up like a lantern and steps back",
            "%t. No more hiding. It was never very good hiding.",
            "%t. Everything can see you now. Everything.",
            "/em flicks green light across a shape in the dark",
            "%t. Glow, little thing.",
        },

        ["SPELL:Hurricane"] = {
            "%t. The sky has lost its temper. I did try.",
            "/em opens her arms and the weather comes down like a decision",
            "%t. This is what asking nicely looks like when it fails.",
            "%t. Get under something. There is nothing to get under.",
            "%t. I remember a storm like this. I remember being in it.",
            "/em stands perfectly still in the centre of the noise",
            "%t. Everything above you is angry at once.",
        },

        ["SPELL:Cyclone"] = {
            "%t. Go away for a moment. Come back changed.",
            "/em lifts someone off the ground with an idle turn of the wrist",
            "%t. The air will hold you. It holds most things.",
            "%t. Up you go. Think about it on the way.",
            "%t. This is peaceful, in its way.",
        },

        ["SPELL:Hibernate"] = {
            "%t. Sleep. It is not so bad. I have done it for centuries.",
            "/em sings four notes and something enormous lies down",
            "%t. Rest. You have been running a long time.",
            "%t. Dream of somewhere better. There is somewhere better.",
            "/em lowers a creature into sleep the way one lowers a child",
        },

        ["SPELL:Rejuvenation"] = {
            "Grow. Quickly now.",
            "/em lays a hand on someone and green light spreads under the skin",
            "Hold on. It is coming.",
            "You are only torn. Torn things close.",
            "/em breathes out slowly and the bleeding slows with it",
            "There. That is better. That is much better.",
            "The world wants you to stay. So do I.",
        },

        ["SPELL:Regrowth"] = {
            "/em presses both hands to a wound and does not look away",
            "Quickly. Quickly. There.",
            "This is the fast kind. Forgive the rush.",
            "/em knits flesh together with the impatience of someone who has done it too often",
            "Stay with me. Stay with me.",
            "Good. Good. Breathe.",
        },

        ["SPELL:Healing Touch"] = {
            "/em takes her time, because this one deserves it",
            "Slowly. Properly. All the way closed.",
            "I have been doing this since before your grandmother.",
            "/em holds a wound shut and speaks to it in Darnassian",
            "There. Whole. Try to stay that way.",
            "Nothing is beyond mending. Very little, anyway.",
        },

        ["SPELL:Lifebloom"] = {
            "/em leaves something growing quietly under the skin",
            "It will keep working after I stop.",
            "A slow bloom. Let it open.",
            "/em plants a small green thing in a wound and lets it do the rest",
            "Grow into it.",
        },

        ["SPELL:Innervate"] = {
            "/em presses a palm between someone's shoulders and shares what she has",
            "Take mine. I have more than I need.",
            "Here. Go on.",
            "/em gives something away without appearing to notice",
            "Do not thank me. Just keep going.",
        },

        ["SPELL:Rebirth"] = {
            "/em kneels and calls something back that had already turned away",
            "No. Not yet. Come back.",
            "You are not finished. I decide that.",
            "/em folds a seed into a dead hand and closes the fingers over it",
            "Up. The world is not done with you.",
            "I have seen where you were going. Come back.",
        },

        ["SPELL:Mark of the Wild"] = {
            "/em marks a companion with a fingertip and a word",
            "There. The wild knows you now.",
            "You will be harder to kill. Everyone is, with a mark.",
            "/em blesses someone absently, still half asleep",
            "Carry a little of the wood with you.",
        },

        ["SPELL:Thorns"] = {
            "/em wraps someone in something that will bite whatever bites them",
            "Let them try. Let them find out.",
            "Everything green defends itself. Now so do you.",
            "/em grows a quiet cruelty across a friend's shoulders",
            "Anything that touches you will regret it.",
        },

        ["SPELL:Bear Form"] = {
            "/em becomes something much larger and much less polite",
            "%t. Enough talking.",
            "%t. I will be blunt with you now. Very blunt.",
            "/em stops being a woman and starts being weather with teeth",
            "%t. This shape has fewer opinions.",
            "%t. I am tired of being reasonable.",
        },

        ["SPELL:Cat Form"] = {
            "/em drops to all fours between one step and the next",
            "%t. Now you will not hear me coming.",
            "/em becomes quiet in a way that is not natural",
            "%t. This shape does not talk much.",
            "%t. Watch the grass, if you like. It will not help.",
        },

        ["SPELL:Travel Form"] = {
            "/em becomes something faster and stops explaining herself",
            "The trees pass. Good.",
            "/em runs the way she remembers running, long ago",
            "This part I have always loved.",
            "Somewhere else. Anywhere else. Quickly.",
        },

        ["SPELL:Prowl"] = {
            "/em folds herself into the grass and stops existing",
            "%t. I am closer than you would like.",
            "/em moves without moving anything that would be noticed",
            "%t. Keep talking. It helps me.",
            "%t. You will not hear the last few steps.",
        },

        ["SPELL:Maul"] = {
            "%t. That is a paw, not a hand. There is a difference.",
            "/em brings something enormous down without ceremony",
            "%t. I am very old and very heavy.",
            "%t. No. Down.",
            "/em swats a soldier off his feet like a branch in the way",
            "%t. Enough.",
        },

        ["SPELL:Swipe"] = {
            "%t. All of you. Back.",
            "/em clears a half-circle of ground with one motion",
            "%t. Do not crowd a bear. Everyone knows this.",
            "%t. There is room for me and nothing else.",
        },

        ["SPELL:Bash"] = {
            "%t. Quiet, now.",
            "/em puts a skull against the ground and holds it there",
            "%t. I said quiet.",
            "%t. Lie down for a moment.",
        },

        ["SPELL:Shred"] = {
            "%t. You never saw where I was.",
            "/em opens a back that was turned at exactly the wrong time",
            "%t. Behind. Always behind.",
            "%t. This is the part I am least proud of.",
            "/em works quickly and without any sound at all",
            "%t. The grass told me where you would stand.",
        },

        ["SPELL:Rip"] = {
            "%t. Now it will not close.",
            "/em leaves something open on purpose",
            "%t. Bleed. It will be over sooner.",
            "%t. I am not being cruel. I am being quick.",
            "%t. Do not run. Running empties you faster.",
        },

        ["SPELL:Mangle"] = {
            "%t. There. Now everything hurts more.",
            "/em ruins something that will not heal straight",
            "%t. Torn wrong. That was deliberate.",
            "%t. I know exactly which part that was.",
        },

        -- Reactions -----------------------------------------------------

        ["REACT:LOWHEALTH"] = {
            "%t. Oh. I am bleeding. When did that start?",
            "%t. That is a great deal of red for one afternoon.",
            "/em looks at her own wound as though it belonged to somebody else",
            "%t. I felt that in a place I had forgotten I had.",
            "%t. Wait. Wait, I am still waking up.",
            "%t. This body is older than it looks and it is complaining.",
            "/em presses a hand to her side and finds it warm",
            "%t. Is this the war? Which war is this?",
            "%t. I have bled before. Not for a long time.",
            "%t. Give me a moment. Give me only a moment.",
            "/em stumbles and catches herself on a tree that agrees to be there",
            "%t. I am not finished. I have barely started.",
            "%t. The ground is very close suddenly.",
            "%t. Do not tell the grove about this.",
            "/em breathes in the way she was taught, centuries ago",
            "%t. I have slept through worse than you.",
            "%t. Everything green is watching me lose.",
            "%t. No. Not while I am awake.",
            "/em sets her feet and refuses to go back to sleep",
            "%t. I remember dying. I did not care for it.",
            "%t. This shape is failing. I have others.",
            "%t. Hold on. Hold on. Almost.",
            "/em tastes blood and finds it unfamiliar",
            "%t. So much noise, and I am so tired.",
            "%t. You have hurt something that was here before you.",
            "%t. I will mend. I always mend. Eventually.",
            "/em wipes her face and leaves it worse",
            "%t. The Dream is very close right now. That is a bad sign.",
            "%t. Not yet. Not yet. Not yet.",
            "%t. I am owed a longer life than this.",
        },

        ["REACT:DEATH"] = {
            "%t. Oh. So it is the sleeping again.",
            "/em falls slowly, the way a tree does",
            "%t. Tell the grove where I fell.",
            "%t. I was only just awake.",
            "%t. This is not so different from the Dream.",
            "/em reaches for the ground and finds it already holding her",
            "%t. Elune. It has been a long night.",
            "%t. Put me somewhere green.",
            "%t. I have done this before. It gets no easier.",
            "/em closes her eyes with something like relief",
            "%t. I do not think I finished what I woke for.",
            "%t. The roots will take me. They always do.",
            "%t. Was it worth it? Somebody find out.",
            "/em lets go of a shape she has held for a very long time",
            "%t. I am going back under. Do not follow.",
            "%t. Someone water the saplings. Somebody must.",
            "%t. Ten thousand years and this is the ending.",
            "/em becomes very still, and something small grows where she lands",
            "%t. I will be in the Dream. Look for me there.",
            "%t. It is quieter now. That is not entirely bad.",
            "%t. I have been dying since I woke. This is only the last of it.",
            "/em whispers a name nobody present recognises",
            "%t. Do not weep. I have had more years than anyone.",
            "%t. Cold. I had forgotten cold.",
            "%t. Wake me if it matters.",
        },

        ["REACT:RESURRECT"] = {
            "/em sits up out of the earth with leaves still in her hair",
            "Oh. Back again. How strange.",
            "Which war is this? No, do not tell me. I will work it out.",
            "/em shakes soil from her shoulders like someone rising from a nap",
            "That was a short sleep. I have had longer between blinks.",
            "I dreamed of a city with white towers. I always do.",
            "/em checks that she is the correct shape before standing",
            "Everything is where I left it. Good.",
            "How long was I gone? An hour? A year?",
            "/em breathes in and the colour comes back into her",
            "The Dream did not want me either. Fine.",
            "Up, then. There was something I was in the middle of.",
            "/em brushes a beetle off her arm and apologises to it",
            "I do not think I finished dying properly.",
            "Awake. Mostly. Enough.",
            "/em looks at her own hands to be certain they are hers",
            "The ground gave me back. It usually does.",
            "Do not fuss. I have been dead before breakfast.",
            "/em straightens, and something green closes over where she lay",
            "Right. Yes. I remember now.",
        },

        ["REACT:KILLINGBLOW"] = {
            "%t. There. Go back to the earth.",
            "/em stands over a body and looks genuinely sorry about it",
            "%t. That was not personal. Very little is.",
            "%t. Something will grow here. It always does.",
            "%t. Rest. You have stopped taking.",
            "/em closes a dead man's eyes with two fingers",
            "%t. The wood will make use of you.",
            "%t. I did not want to. I did anyway.",
            "%t. You will be part of something better than you were.",
            "/em kneels briefly, then rises and moves on",
            "%t. Balance. That is all this was.",
            "%t. I have killed better and mourned less.",
            "%t. Go quietly. That is the only mercy left.",
            "/em presses a hand to the ground where the body fell",
            "%t. There. It is done and it is over.",
            "%t. Do not make me do that again.",
            "%t. Something is already growing. Look.",
            "/em says four words in Darnassian over someone who cannot hear them",
            "%t. You were loud. Now you are useful.",
            "%t. It is finished. It should never have started.",
        },

        ["REACT:COMBATSTART"] = {
            "%t. Oh. Is this happening now?",
            "%t. I was somewhere else. Very well, I am here.",
            "/em blinks slowly and arrives in the present",
            "%t. Stop. Please stop. No? Very well.",
            "%t. You do not want to wake what is asleep in me.",
            "/em sets her staff down and lets her hands change instead",
            "%t. I have fought your grandfathers. I have their names.",
            "%t. This again. It is always this.",
            "%t. There is no need. There is never any need.",
            "/em looks almost disappointed as she takes position",
            "%t. Do not run. It only makes me quicker.",
            "%t. The trees do not want you here either.",
            "%t. Last chance. That is what I always say.",
            "%t. I am very tired and you have chosen badly.",
            "/em rolls her shoulders, and something beneath them shifts",
            "%t. Ten thousand years, and it is always this.",
            "%t. Come, then. Let us get it over with.",
            "%t. I remember when this valley was quiet.",
            "/em steps forward and the grass leans out of her way",
            "%t. You are standing in something sacred. Move.",
        },

        ["REACT:COMBATEND"] = {
            "/em stands still and listens until the wood sounds right again",
            "There. Quiet.",
            "That was not necessary. None of it ever is.",
            "/em kneels and pushes a torn root back into the soil",
            "The ground took some damage. That is what I mind.",
            "I am awake now, at least. That is something.",
            "/em picks a leaf out of her hair and studies it too long",
            "Somebody will grow over all of this.",
            "I would like to lie down for about a century.",
            "/em breathes out and the birds start again",
            "Listen. They have come back. That is how you know it is over.",
            "Enough. Enough for today.",
            "/em cleans her hands with a handful of moss",
            "I did not enjoy that. I am not meant to.",
            "Let it grow back. Let everything grow back.",
            "/em looks at the sky and cannot tell what season it is",
            "Now. Where was I going?",
            "The wood is settling. Good.",
            "/em sits down without warning and does not explain",
            "Peace. For a moment. Do not spoil it.",
        },

        ["REACT:INTERRUPTED"] = {
            "%t. You broke the thread.",
            "%t. I had almost finished. That took a while to gather.",
            "/em loses hold of something large and half formed",
            "%t. Do you know how old that spell was?",
            "%t. Start again, then. I have time. I have nothing but time.",
            "%t. That was rude to me and ruder to the forest.",
            "/em shakes her head slowly, like someone waking badly",
            "%t. No. No, I had it.",
            "%t. You will not manage that a second time.",
            "%t. Now I am awake. Properly awake.",
            "/em breathes in through her teeth and begins again",
            "%t. That word took a hundred years to learn.",
            "%t. Very well. Something faster, then.",
            "%t. I felt that in my teeth.",
            "/em gathers the pieces of an unfinished thing back together",
            "%t. You have my full attention now. That is worse for you.",
            "%t. Again. And this time do not touch me.",
            "%t. I lost the shape of it. I will find another.",
            "/em stops being gentle without appearing to change at all",
            "%t. That is enough of that.",
        },

        ["REACT:LEVELUP"] = {
            "/em stands straighter, and something very old settles into place",
            "Ah. More of me came back.",
            "I remember something I had forgotten. Good.",
            "/em flexes a hand and finds it steadier than yesterday",
            "The Dream gives things back slowly.",
            "Better. Nearer to what I was.",
            "/em looks at the moon as though checking a debt",
            "Another piece. There are a great many pieces.",
            "I am more awake than I was this morning.",
            "/em smiles, which she does not often do",
            "Growth. That is the whole of it, really.",
            "Somewhere a tree got taller too.",
            "/em breathes deeply and the air seems to agree with her",
            "I am becoming myself again. Slowly.",
            "Good. There is a long way still.",
        },

        ["REACT:FALLING"] = {
            "Oh. This is the falling part.",
            "/em falls with her arms out, entirely calm about it",
            "I meant to be a bird for that. I was too slow.",
            "The ground and I are about to disagree.",
            "/em tries to become something with wings and does not quite manage",
            "This has happened before. It ends badly.",
            "Down. Down is where everything goes.",
            "/em plummets, watching the scenery with interest",
            "I should have changed shape. I always think of it late.",
            "Elune. Not gracefully, then.",
            "/em braces for an impact she has felt many times",
            "Well. Gravity is also nature.",
            "Oh dear.",
            "/em hits hard and lies still, thinking about it",
            "That was my own fault entirely.",
        },

        ["REACT:DROWNING"] = {
            "The water does not want me. That is new.",
            "/em struggles upward through green dark",
            "Air. I had grown used to air.",
            "Everything down here is very calm and I am not.",
            "/em kicks hard and loses a handful of leaves to the current",
            "This is not the kind of sleep I meant.",
            "Up. Up. Which way is up.",
            "/em reaches for a surface that will not come closer",
            "I should have been an otter. I know how.",
            "No. Not water. Not like this.",
            "/em fights the water with the last of her air",
            "The river is not listening today.",
            "I have drowned before. I did not like it then either.",
            "/em breaks the surface for half a breath",
            "Somebody. Anybody.",
        },

        ["REACT:DURABILITY"] = {
            "/em examines a strap that has finally given up",
            "Everything wears. That is not a complaint, only a fact.",
            "This has held together for years. It has earned rest.",
            "/em ties a knot in leather that will not take another",
            "I should mend this. I say that every season.",
            "Torn. Frayed. Familiar.",
            "/em looks at her gear the way she looks at an old tree",
            "It is dying honestly, at least.",
            "Nothing lasts. Not armour, not cities, not anyone.",
            "/em pats a broken buckle as though consoling it",
            "I have had this longer than most people have been alive.",
            "It will hold. Probably. Once more.",
            "/em sighs at leather worn through to nothing",
            "Everything returns to the earth. Including my boots.",
            "I will find someone who mends things.",
        },

        -- Idle ----------------------------------------------------------

        ["IDLE:EAT"] = {
            "/em eats slowly, thanking each thing on the plate",
            "It grew. It was taken. It is eaten. That is the whole cycle.",
            "/em sits cross-legged on the ground rather than any seat",
            "I have eaten bark. This is better than bark.",
            "Nothing here was wasted. I checked.",
            "/em shares a portion with a bird that arrived uninvited",
            "Slowly. Food is not a task.",
            "I forget to eat for weeks. Then I remember all at once.",
            "/em chews thoughtfully and stares at the middle distance",
            "This came out of soil somewhere. Good soil.",
        },

        ["IDLE:DRINK"] = {
            "/em drinks water and tastes where it came from",
            "This came out of a rock a long way from here.",
            "/em cups her hands rather than use a flask",
            "Rain, eventually. All of it is rain, eventually.",
            "Cold. Clean. Old.",
            "/em pours a little onto the ground before drinking any",
            "The first mouthful belongs to whatever is underneath.",
            "I have drunk from worse. Much worse.",
            "/em drinks with her eyes closed",
            "There. That is better than any wine.",
        },

        ["IDLE:MOUNT"] = {
            "/em greets her mount before she gets on it",
            "Come. We have somewhere to be. I think.",
            "/em rides the way one rides a friend, not a machine",
            "You do not have to hurry. Neither do I.",
            "I used to run this whole distance. I remember it being shorter.",
            "/em rests a hand on a warm neck and murmurs something in Darnassian",
            "Onward. Gently.",
            "The roads have moved since I last looked.",
        },

        ["IDLE:HERBALISM"] = {
            "/em asks before she takes, and waits for something like an answer",
            "One from here. One from further on. Never all of them.",
            "/em leaves the roots and takes only what will regrow",
            "Thank you. I mean that.",
            "This one is old. I will find another.",
            "/em cuts a stem cleanly and covers the wound with soil",
            "It gives itself. It is only polite to notice.",
            "Slowly. There is no hurry in a garden.",
            "/em kneels for a long moment before disturbing anything",
            "I have known this plant longer than most people know their families.",
        },

        ["IDLE:FISHING"] = {
            "/em sits at the water's edge and becomes very difficult to notice",
            "This is closest to the Dream. That is why I like it.",
            "/em waits without any sign of waiting",
            "The river will decide. It always does.",
            "I could be here a year. I have been.",
            "/em watches the surface and forgets what she came for",
            "Quiet. Green. Enough.",
            "Nothing has to happen for this to be worth doing.",
        },

        ["IDLE:DISCOVERY"] = {
            "/em stops and looks at a place she does not recognise",
            "This was not here. Or I was not here. One of the two.",
            "/em breathes in and tries to place the season",
            "Something grew while I was asleep. Something always does.",
            "Oh. Look at that.",
            "/em stands still long enough to be mistaken for a tree",
            "I do not know this valley. That is a rare and lovely thing.",
            "The world kept going without me. Good. It should.",
            "/em touches a trunk and listens to it for a while",
            "New. All of it new. And I am so old.",
        },
    },
}
