-- RPVox -- mood lines for the Priest's offensive spells.
-- Loaded after the mood packs; these attach extra trigger sets to them.

RPVox_MOOD_LINES = RPVox_MOOD_LINES or {}
for _, m in ipairs({ "HAPPY", "SERIOUS", "WEARY", "GRIM" }) do
    RPVox_MOOD_LINES[m] = RPVox_MOOD_LINES[m] or { name = m:lower(), class = "PRIEST" }
end

local H = RPVox_MOOD_LINES.HAPPY
local S = RPVox_MOOD_LINES.SERIOUS
local W = RPVox_MOOD_LINES.WEARY
local G = RPVox_MOOD_LINES.GRIM

-- Shadow Word: Pain -------------------------------------------------------

H["SPELL:Shadow Word: Pain"] = {
    "%t. Ooh, this one's my favourite!",
    "%t. A little something to think about.",
    "Off you go, rotting merrily, %t.",
    "You'll love this. Well. No, %t.",
    "/em plants the curse with obvious relish",
    "%t. There! Isn't that interesting?",
    "%t. Tick, tick, tick.",
    "Enjoy the next few seconds, %t.",
    "That'll keep you busy, %t!",
    "%t. Lovely little rot, that.",
    "Do let me know how it feels, %t.",
    "%t. A gift! Don't open it.",
    "%t. Ha! Now we wait.",
    "%t. Something to remember me by.",
    "%t. Delightful. Now we wait for it to bite.",
    "%t. That's the good stuff.",
    "%t. Marvellous, marvellous decay.",
    "%t. I do enjoy the slow ones.",
    "%t. Splendid. Off it goes.",
    "You're going to hate this. Wonderful, %t.",
    "/em hums while the curse settles in",
    "%t. There we are! All set.",
    "%t. Ha! Planted.",
    "%t. Best part of my day, this.",
    "Have fun with that, %t.",
}
S["SPELL:Shadow Word: Pain"] = {
    "%t. The rot is applied.",
    "%t. Affliction set. Move to the next.",
    "%t. That will work while I work.",
    "%t. Efficient. Continue.",
    "Marked, %t.",
    "%t. The wound will do the rest.",
    "%t. Applied. Watch the timing.",
    "%t. One curse, correctly placed.",
    "/em sets the affliction with clinical precision",
    "%t. That will not be dispelled easily.",
    "%t. Damage over time. Standard practice.",
    "%t. Set. Do not waste it.",
    "%t. The Shadow does the work now.",
    "%t. Proceeding to the next target.",
    "%t. That is handled.",
    "%t. Affliction confirmed.",
    "%t. It will run its course.",
    "%t. Placed correctly.",
    "%t. The curse holds. Continue.",
    "%t. Noted and applied.",
    "%t. That target is accounted for.",
    "%t. Steady. It is working.",
    "%t. One more marked.",
    "%t. The rot proceeds on schedule.",
    "%t. Applied. Next.",
}
W["SPELL:Shadow Word: Pain"] = {
    "Rot, then. If you must, %t.",
    "%t. There. That will do something eventually.",
    "%t. The usual. Applied.",
    "%t. Another curse. There have been thousands.",
    "/em applies the affliction without looking up",
    "%t. It works whether I care or not.",
    "%t. Fine. Decay.",
    "%t. Same curse. Same result.",
    "%t. I do this in my sleep. If I slept.",
    "%t. There. Now wait.",
    "%t. It hardly requires thought any more.",
    "%t. One more rot on one more thing.",
    "%t. Slowly, then. Everything is slow.",
    "%t. That is applied. Whatever.",
    "Wither if you like, %t.",
    "%t. The usual arrangement.",
    "%t. Fine. Off it goes.",
    "%t. It will finish eventually. Everything does.",
    "%t. Another curse into the pile.",
    "%t. There. Done. Next.",
    "%t. Nothing interesting about it any more.",
    "%t. Applied. As always.",
    "%t. The rot takes its time. So do I.",
    "%t. One more of these.",
    "%t. It works. It always works.",
}
G["SPELL:Shadow Word: Pain"] = {
    "Now it begins inside you, %t.",
    "That will not stop until you do, %t.",
    "Rot from within. Slowly, %t.",
    "You will feel every second of this, %t.",
    "/em sets the curse and watches it take hold",
    "The Shadow is in your blood now, %t.",
    "%t. There is no removing that.",
    "Feel it work, %t.",
    "%t. It spreads. It always spreads.",
    "%t. That is the beginning, not the end.",
    "You carry my mark now, %t.",
    "The dark is inside you. Get used to it, %t.",
    "Nothing you do will stop it, %t.",
    "%t. Slowly. That is the point.",
    "It will finish you long after I leave, %t.",
    "You are already dying. Now you know, %t.",
    "%t. The rot answers to me.",
    "%t. There is no cure and no time.",
    "%t. That is a promise, not a spell.",
    "%t. It eats. Patiently.",
    "You will die of that. Eventually, %t.",
    "The Shadow has you now, %t.",
    "%t. Nothing survives that for long.",
    "Feel it settle in, %t.",
    "That is how it ends for you, %t.",
}

-- Mind Blast --------------------------------------------------------------

H["SPELL:Mind Blast"] = {
    "%t. Knock knock!",
    "%t. Ha! Right between the ears.",
    "%t. Oh, that looked like it hurt.",
    "%t. Anybody home? No. Not now.",
    "/em taps his temple and grins",
    "%t. Wonderful! Straight through.",
    "%t. That's the good part of the brain, that.",
    "Ha! Rattled you, %t.",
    "%t. Splendid noise in there.",
    "%t. Ooh, that's a mess.",
    "Do try to keep your thoughts together, %t.",
    "%t. Marvellous. Absolutely marvellous.",
    "%t. Ha! Whoops.",
    "%t. That'll ring for a while!",
    "%t. Lovely. Something broke.",
    "%t. I do enjoy a good rummage.",
    "%t. Ha! Straight in.",
    "You had a thought. I ended it, %t.",
    "%t. Delightful crunch, that.",
    "%t. Splendid! Again?",
    "%t. Oh, I like that sound.",
    "%t. Ha! Right in the middle of a thought.",
    "%t. That was very satisfying.",
    "%t. Wonderful. Do think of something else.",
    "%t. Ha! And another.",
}
S["SPELL:Mind Blast"] = {
    "%t. Direct. Effective.",
    "%t. Focus fire.",
    "%t. Target's concentration is broken.",
    "%t. That will interrupt them.",
    "/em strikes at the mind without ceremony",
    "%t. Applied. Continue the sequence.",
    "%t. The mind is the weak point. Use it.",
    "%t. Precise damage. Nothing wasted.",
    "%t. That should stagger them.",
    "%t. Strike where it matters.",
    "%t. Confirmed hit.",
    "%t. Efficient. Next.",
    "%t. Their thinking is disrupted.",
    "%t. That is the correct opening.",
    "%t. Standard approach.",
    "%t. Damage delivered.",
    "Keep the pressure on the mind, %t.",
    "%t. That will slow them.",
    "%t. Direct assault. Proceeding.",
    "%t. Effective. Continue.",
    "%t. The Shadow strikes true.",
    "%t. Target staggered. Press it.",
    "%t. That is the opening move.",
    "%t. Correct application.",
    "%t. Hit confirmed. Advance.",
}
W["SPELL:Mind Blast"] = {
    "%t. There. In the head.",
    "%t. Same spell. Same place.",
    "%t. It works. It always works.",
    "%t. Another mind. Another crack.",
    "/em strikes without much interest",
    "%t. Fine. That should do it.",
    "%t. I have done this ten thousand times.",
    "%t. Predictable. Effective. Dull.",
    "%t. There. Nothing to see.",
    "%t. It lands. It usually lands.",
    "%t. One more skull.",
    "%t. That is the whole trick, really.",
    "%t. Fine. Rattle about in there.",
    "%t. The same as yesterday.",
    "%t. It hardly takes effort now.",
    "%t. There. Done.",
    "%t. Another one staggered.",
    "%t. Nothing new about it.",
    "%t. Applied. Move on.",
    "%t. So it goes. Again.",
    "%t. That will do something.",
    "%t. One more mind, briefly disturbed.",
    "%t. Fine. Next.",
    "%t. It always works and I never enjoy it.",
    "%t. There. Whatever.",
}
G["SPELL:Mind Blast"] = {
    "Get out of your own head. I am in it, %t.",
    "That is your thinking, ending, %t.",
    "I have seen what you are. It is small, %t.",
    "%t. Something important just tore.",
    "/em stares and the thought simply stops",
    "Your mind is not yours now, %t.",
    "Feel that? That was a memory, %t.",
    "%t. I take what I find in there.",
    "There is nothing in you worth keeping, %t.",
    "%t. The Shadow walks in without knocking.",
    "You will not think clearly again today, %t.",
    "%t. That is the sound of a mind failing.",
    "%t. I am in your head now. I am not leaving.",
    "Your thoughts belong to the dark now, %t.",
    "Nothing you hide is hidden, %t.",
    "%t. That broke something permanent.",
    "The whispers found you, %t.",
    "You are unravelling from the inside, %t.",
    "I know what you fear now, %t.",
    "%t. Silence in there.",
    "The dark is in your skull, %t.",
    "%t. That is what I do to minds.",
    "You are less than you were a moment ago, %t.",
    "%t. Every strike takes a piece.",
    "%t. Nothing left in there but noise.",
}

-- Mind Flay ---------------------------------------------------------------

H["SPELL:Mind Flay"] = {
    "%t. Ooh, the slow one!",
    "%t. Straight through the middle of a thought!",
    "Ha! Think faster, %t. It will not help.",
    "%t. Lovely. Just lovely.",
    "/em keeps the working going with obvious enjoyment",
    "This is my favourite spell, you know, %t.",
    "%t. Wonderful. There goes another memory.",
    "Do keep thinking, %t. I am reading.",
    "%t. Ha! Marvellous.",
    "%t. Isn't the mind a marvel?",
    "%t. Splendid. One thread at a time.",
    "%t. Oh, I could read all day.",
    "%t. Ha! Arithmetic will not save you either.",
    "%t. That's the spirit. Literally.",
    "%t. Cluttered in here. Delightful, though.",
    "Keep counting, %t. You are doing wonderfully.",
    "%t. Ha! Look at that. A whole childhood.",
    "%t. This never gets old.",
    "%t. Splendid work, if I say so.",
    "%t. Oh, that's a good one. Was that a secret?",
    "Do try to hold on to a thought, %t!",
    "%t. Ha! Nearly through the lot.",
    "%t. Wonderful. Simply wonderful.",
    "%t. The best part of the day, this.",
    "%t. Ha! Delightful.",
}
S["SPELL:Mind Flay"] = {
    "%t. Maintaining. Do not interrupt.",
    "%t. Channelled. Hold the position.",
    "%t. This requires concentration.",
    "%t. Steady. It is working.",
    "/em holds the channel with fixed attention",
    "%t. Sustained damage. Keep them off me.",
    "Do not break my focus, %t.",
    "%t. The working continues.",
    "%t. Applied continuously.",
    "Hold. This takes a moment, %t.",
    "%t. Concentration is the whole spell.",
    "%t. Effective while it lasts.",
    "Watch my flank, %t.",
    "%t. Continuing the channel.",
    "%t. Steady output. Nothing wasted.",
    "%t. It is working. Hold them.",
    "%t. Maintaining pressure.",
    "%t. This is precise work.",
    "Keep them from me, %t.",
    "%t. The channel holds.",
    "%t. Sustained. Continue.",
    "Do not let them reach me, %t.",
    "%t. Working. Stand ready.",
    "%t. It requires only time.",
    "%t. Holding steady.",
}
W["SPELL:Mind Flay"] = {
    "%t. Slowly. Everything slowly.",
    "%t. There. It gets there on its own.",
    "%t. This takes a while. It always does.",
    "%t. Fine. Drag it out, then.",
    "/em maintains the channel out of pure habit",
    "%t. I could do this in my sleep.",
    "%t. It is working. Slowly. As usual.",
    "%t. Another long one.",
    "%t. Fine. Wait for it.",
    "%t. So very slow.",
    "%t. This is the tedious part.",
    "%t. It gets there eventually.",
    "%t. One more long working.",
    "%t. Patience is all I have left.",
    "%t. There. Steady. Dull.",
    "%t. Nothing quick about this.",
    "%t. It will finish. Eventually.",
    "%t. Fine. Wait it out.",
    "%t. Same channel. Same result.",
    "%t. The slow way. Again.",
    "%t. It hardly requires attention.",
    "%t. There. Continuing.",
    "%t. So it goes. Slowly.",
    "%t. One more of these long afternoons.",
    "%t. It ends when it ends.",
}
G["SPELL:Mind Flay"] = {
    "Slowly. One thought at a time, %t.",
    "%t. This is the patient kind of cruelty.",
    "%t. I am in your thoughts. I am not leaving.",
    "%t. Thread by thread.",
    "/em holds the channel and does not blink",
    "%t. Every second of this is deliberate.",
    "Curse me if you like. It changes nothing, %t.",
    "%t. The dark drinks deep.",
    "%t. This will not be quick.",
    "You will remember this if you survive, %t.",
    "%t. Unravelling. Slowly.",
    "%t. There is no rushing this.",
    "%t. The Shadow feeds.",
    "%t. Your mind is arguing with me. It will lose.",
    "I am taking your thoughts one at a time, %t.",
    "%t. Piece by piece.",
    "%t. This is what patience looks like.",
    "You are coming apart quietly, %t.",
    "%t. The whispers are eating.",
    "Nothing of your mind survives this, %t.",
    "Feel it drag, %t.",
    "%t. I have all the time there is.",
    "Slowly, %t. Very slowly.",
    "%t. This is not a spell. It is an appetite.",
    "You will be less when I stop, %t.",
}

-- Smite -------------------------------------------------------------------

H["SPELL:Smite"] = {
    "%t. Ha! The Light, of all things.",
    "%t. Borrowed radiance! Don't tell anyone.",
    "%t. Oh, that's ironic and I love it.",
    "%t. Ha! Blessed be the impact.",
    "/em calls down the Light with a delighted grin",
    "%t. Splendid. Holy fire from an unholy hand.",
    "%t. Ha! Still works.",
    "%t. The Light and I are having a laugh.",
    "%t. Wonderful. Bright and warm.",
    "%t. Ha! Take some faith.",
    "%t. Delightful hypocrisy, that.",
    "%t. Splendid! Right on target.",
    "%t. The old prayers still land.",
    "%t. Ha! Consecrated, and how.",
    "%t. Marvellous. Divine, even.",
    "%t. Oh, I do enjoy this one.",
    "Ha! Bless you. Violently, %t.",
    "%t. That's the Light doing my dirty work.",
    "%t. Splendid stuff.",
    "%t. Ha! Wonderful.",
    "Take that, with the compliments of a corpse, %t.",
    "%t. Marvellous! Again.",
    "%t. Ha! Holy, and hilarious.",
    "%t. The Light doesn't check credentials!",
    "%t. Splendid. Absolutely splendid.",
}
S["SPELL:Smite"] = {
    "%t. The Light answers. Use it.",
    "%t. Direct. Faithful. Effective.",
    "%t. Applied.",
    "%t. That is the old discipline.",
    "/em calls down the Light with practised form",
    "%t. Faith is a weapon. Handle it properly.",
    "%t. Correctly cast.",
    "%t. Confirmed hit.",
    "%t. The Light does not refuse me. Yet.",
    "%t. Steady. Continue the sequence.",
    "%t. That is straightforward work.",
    "%t. Damage delivered.",
    "%t. Precision, not fury.",
    "%t. The prayers still hold.",
    "%t. Applied. Next.",
    "%t. That is a clean strike.",
    "%t. Continue the pressure.",
    "%t. The old training holds.",
    "%t. Efficient.",
    "%t. Target struck.",
    "%t. Nothing wasted.",
    "%t. The Light obeys. Note that.",
    "%t. Proceeding.",
    "%t. Correct and effective.",
    "%t. Steady output.",
}
W["SPELL:Smite"] = {
    "%t. Fine. The Light, then.",
    "%t. It still comes when I call. Tiresome.",
    "%t. There. Bright and pointless.",
    "%t. The old prayers. Again.",
    "/em calls the Light without much conviction",
    "%t. It works. I stopped asking why.",
    "%t. Another borrowed blessing.",
    "%t. Fine. Burn.",
    "%t. The same words I said in Lordaeron.",
    "%t. It answers. It always answers.",
    "%t. There. Holy fire. Whatever.",
    "%t. I stopped meaning the words long ago.",
    "%t. Fine. Take some Light.",
    "%t. One more prayer said badly.",
    "%t. It lands. That is all I ask.",
    "%t. The Light does not care. Neither do I.",
    "%t. There. Done.",
    "%t. Same spell. Same emptiness.",
    "%t. Fine. Bright. Next.",
    "%t. It works despite everything.",
    "%t. Another day of borrowed faith.",
    "%t. There. That will do.",
    "%t. I say the words. Nothing more.",
    "%t. Fine. Onward.",
    "%t. It comes when called. Habit, I suppose.",
}
G["SPELL:Smite"] = {
    "%t. It abandoned me. It still obeys me.",
    "%t. The Light will hurt on command.",
    "%t. I do not pray. I demand.",
    "Take what was taken from me, %t.",
    "/em forces the Light down without reverence",
    "%t. Something holy, wielded by something that is not.",
    "%t. It burns me too. I have grown used to it.",
    "%t. This is what faith becomes when it curdles.",
    "%t. The Light does not care who holds it.",
    "Let it sear. It seared me first, %t.",
    "%t. A gift from the thing that left me in the dirt.",
    "%t. I take it by force now.",
    "It answers me. That should frighten you, %t.",
    "%t. Holy fire from a dead hand.",
    "%t. That is what I do with what remains of faith.",
    "%t. The Light is a tool. Nothing more.",
    "Burn. As I burned, %t.",
    "%t. There is nothing gentle in it.",
    "%t. I use it because it is useful.",
    "It never saved me. It will not save you, %t.",
    "%t. Radiance without mercy.",
    "Take the Light. It is not a blessing, %t.",
    "That is borrowed and it is aimed at you, %t.",
    "%t. Faith, weaponised.",
    "%t. It comes when I call. Consider what that means.",
}

-- Shoot (wand) ------------------------------------------------------------

H["SPELL:Shoot"] = {
    "%t. Plink!",
    "%t. Ha! A stick with opinions.",
    "Do enjoy the splinters, %t.",
    "%t. Marvellous little thing, this wand.",
    "/em waggles the wand cheerfully",
    "%t. Ha! Poke poke.",
    "%t. Even this is fun, somehow.",
    "%t. Splendid! Very undignified.",
    "%t. Ha! Take that. Barely.",
    "%t. Out of power, full of cheer.",
    "%t. This counts as effort, I think.",
    "%t. Ha! Wonderful.",
    "%t. Bit rude, this spell.",
    "%t. Delightfully petty.",
    "%t. Ha! Another splinter.",
    "%t. It's the thought that counts!",
    "%t. Splendid. Ineffective, but splendid.",
    "%t. Ha! Look at it go.",
    "%t. Charmingly useless.",
    "%t. Ha! One more poke.",
    "%t. That'll add up eventually!",
    "%t. Marvellous. Slowly, but marvellous.",
    "Ha! Tickled you, %t.",
    "%t. Better than nothing. Just.",
    "%t. Splendid little stick.",
}
S["SPELL:Shoot"] = {
    "%t. Conserving power.",
    "%t. Wand work. Adequate.",
    "%t. Steady damage while I recover.",
    "%t. Efficient enough.",
    "/em fires the wand with no particular flourish",
    "%t. Managing resources.",
    "%t. That will do until mana returns.",
    "%t. Continuing.",
    "%t. Nothing wasted.",
    "%t. Standard practice.",
    "%t. Maintaining pressure.",
    "%t. Low cost. Acceptable output.",
    "%t. Applied.",
    "%t. Recovering. Still contributing.",
    "%t. That keeps the pressure on.",
    "%t. Steady. Continue.",
    "%t. Not elegant. Effective.",
    "%t. Holding the line with what I have.",
    "%t. Proceeding.",
    "%t. Adequate.",
    "Discipline is using what you have, %t.",
    "%t. Fire and recover.",
    "%t. Continuing the engagement.",
    "%t. That is the correct call here.",
    "%t. Sustained. Watch the flank.",
}
W["SPELL:Shoot"] = {
    "%t. Poke. Poke. Poke.",
    "%t. Out of power. Again.",
    "%t. Fine. The stick, then.",
    "%t. This is what it comes to.",
    "/em fires the wand without enthusiasm",
    "%t. Slowly, then. As always.",
    "%t. One splinter at a time.",
    "%t. It hardly counts as magic.",
    "%t. Fine. Whatever works.",
    "%t. The dull way. Again.",
    "%t. I am too tired for the good spells.",
    "%t. There. Another poke.",
    "%t. It adds up. Eventually. Barely.",
    "%t. Same stick. Same tedium.",
    "%t. Fine. Continue.",
    "%t. Nothing left but this.",
    "%t. Poke. Wait. Poke.",
    "%t. So it goes. Slowly.",
    "%t. One more splinter.",
    "%t. It is something, I suppose.",
    "%t. Fine. Down to the wand.",
    "%t. Tedious, but so is everything.",
    "%t. There. Again.",
    "%t. The last resort, as usual.",
    "%t. It will do. It always does.",
}
G["SPELL:Shoot"] = {
    "Even this will kill you eventually, %t.",
    "A splinter of the dark, just for you, %t.",
    "%t. Cold light. It burns all the same.",
    "This stick has killed better than you, %t.",
    "/em fires the wand with cold precision",
    "Bleed slowly, then, %t.",
    "I do not need power to end you, %t.",
    "%t. Every shot is one closer.",
    "%t. It is slow. So am I. So is the grave.",
    "%t. Nothing about this is merciful.",
    "%t. The wand does not tire. Neither do I.",
    "%t. Little wounds. Many of them.",
    "You will die of small things, %t.",
    "%t. Patience is a weapon too.",
    "Hold still. It only takes a hundred, %t.",
    "This will finish you, %t.",
    "%t. The dark does not require mana.",
    "%t. Slow work. Certain work.",
    "%t. Nothing stops. Not even this.",
    "Count them if you like, %t.",
    "You are bleeding out one splinter at a time, %t.",
    "%t. The end comes cheaply.",
    "%t. I have all night.",
    "%t. Even empty, I am dangerous.",
    "%t. It will be enough. It always is.",
}

-- Psychic Scream ----------------------------------------------------------

H["SPELL:Psychic Scream"] = {
    "%t. Boo!",
    "Ha! Off you go, %t!",
    "Look at them scatter, %t!",
    "%t. Wonderful! Everyone's leaving.",
    "/em shrieks, then laughs at the result",
    "%t. Ha! Marvellous chaos.",
    "Do run! It's more fun that way, %t.",
    "%t. Splendid. A stampede.",
    "%t. Ha! Whoops, that was loud.",
    "Off they go, the darlings, %t.",
    "%t. Marvellous. Absolute panic.",
    "%t. Ha! Bye!",
    "%t. That never stops being funny.",
    "%t. Splendid scattering!",
    "%t. Ha! Look at them go.",
    "%t. Wonderful. Peace and quiet.",
    "Do come back when you're calmer, %t!",
    "%t. Ha! Excellent noise.",
    "%t. That's the way.",
    "%t. Delightful pandemonium.",
    "%t. Ha! Scatter, little things.",
    "%t. Splendid. Now, where was I?",
    "%t. Ha! That was worth it.",
    "%t. Wonderful chaos, that.",
    "Off with you! Ha, %t!",
}
S["SPELL:Psychic Scream"] = {
    "Break their formation, %t.",
    "%t. Scattered. Reposition.",
    "%t. Buying time. Use it.",
    "%t. That should reset the fight.",
    "/em breaks the enemy line with a single word",
    "%t. Disengage while they run.",
    "%t. Control regained.",
    "%t. Use the opening.",
    "%t. That is crowd control. Nothing more.",
    "%t. Reposition now.",
    "%t. They will return. Be ready.",
    "%t. Tactical. Not cruel.",
    "%t. Scattered on my mark.",
    "Take the moment, %t.",
    "%t. That is the reset we needed.",
    "%t. Regroup while they are away.",
    "%t. Effective. Move.",
    "%t. Line broken. Advance or withdraw.",
    "%t. That buys us seconds. Spend them well.",
    "%t. Control the field.",
    "%t. Now. Reposition.",
    "%t. They are out of the fight briefly.",
    "%t. Use it properly.",
    "%t. Applied. Watch the returns.",
    "%t. Formation broken. Proceed.",
}
W["SPELL:Psychic Scream"] = {
    "Go away, %t.",
    "%t. Fine. Run, then.",
    "%t. There. Some peace.",
    "%t. I needed a moment.",
    "/em screams, mostly out of exhaustion",
    "Off with you. Please, %t.",
    "%t. Same trick. Same result.",
    "%t. Fine. Scatter.",
    "%t. A moment's quiet. That is all I wanted.",
    "%t. They always come back.",
    "%t. There. Briefly alone.",
    "%t. It buys nothing but a breath.",
    "%t. Fine. Go.",
    "%t. Another shout into another crowd.",
    "%t. It works. Tiresomely.",
    "%t. There. Quiet. For a second.",
    "Run along, %t.",
    "I have not the energy for all of you, %t.",
    "%t. Fine. Room to think.",
    "%t. They will be back. They always are.",
    "%t. There. Some space.",
    "%t. One more scream in a long career.",
    "Go on. Off you go, %t.",
    "%t. It hardly helps.",
    "%t. Fine. A moment, then.",
}
G["SPELL:Psychic Scream"] = {
    "Hear what I hear, %t.",
    "Now you know what the dark sounds like, %t.",
    "Run. It will not help, %t.",
    "%t. That is my waking hours, given freely.",
    "/em screams with a voice that is not entirely his own",
    "%t. Fear is honest. Wear it.",
    "You cannot outrun what is already inside you, %t.",
    "%t. Scatter, little things.",
    "%t. That noise lives in me always.",
    "Now you have heard the whispers, %t.",
    "Run until it stops. It will not stop, %t.",
    "%t. The dark speaks through me.",
    "You will hear that again tonight, %t.",
    "%t. Terror is a spell like any other.",
    "%t. That is a fraction of what I carry.",
    "Go. I will find you after, %t.",
    "%t. The Shadow screams and the living obey.",
    "You are running from something you brought with you, %t.",
    "That will follow you, %t.",
    "Nothing frightens the dead. Everything frightens you, %t.",
    "Hear it. Remember it, %t.",
    "The whispers have your name now, %t.",
    "%t. Flee. It only delays this.",
    "%t. That sound is what I hear in the silence.",
    "You will not sleep well, %t.",
}
