-- RPVox -- Hunter class pack
--
-- Voice: a Sin'dorei noblewoman of Silvermoon who treats a battlefield as a
-- badly organised court. Imperious, immaculate, genuinely lethal. She is
-- offended by dust, blood, familiarity and bad manners, in roughly that order.
-- The only creature she is soft with is her beast.
--
-- Single voice, no moods yet (as with Warrior). Mood packs can be added later
-- scoped with class = "HUNTER".

RPVox_CLASSES.HUNTER = {
    name = "Hunter",
    spells = {
        { spell = "Auto Shot",             icon = "Interface\\Icons\\INV_Weapon_Bow_07",            chance = 10 },
        { spell = "Hunter's Mark",         icon = "Interface\\Icons\\Ability_Hunter_SniperShot",    chance = 10 },
        { spell = "Arcane Shot",           icon = "Interface\\Icons\\Ability_ImpalingBolt",         chance = 10 },
        { spell = "Steady Shot",           icon = "Interface\\Icons\\Ability_Hunter_SteadyShot",    chance = 10 },
        { spell = "Aimed Shot",            icon = "Interface\\Icons\\INV_Spear_07",                 chance = 10 },
        { spell = "Multi-Shot",            icon = "Interface\\Icons\\Ability_UpgradeMoonGlaive",    chance = 10 },
        { spell = "Serpent Sting",         icon = "Interface\\Icons\\Ability_Poisons",              chance = 10 },
        { spell = "Concussive Shot",       icon = "Interface\\Icons\\Spell_Frost_Stun",             chance = 10 },
        { spell = "Wing Clip",             icon = "Interface\\Icons\\Ability_Rogue_Trip",           chance = 10 },
        { spell = "Raptor Strike",         icon = "Interface\\Icons\\Ability_MeleeDamage",          chance = 10 },
        { spell = "Mongoose Bite",         icon = "Interface\\Icons\\Ability_Hunter_SwiftStrike",   chance = 10 },
        { spell = "Volley",                icon = "Interface\\Icons\\Ability_Marksmanship",         chance = 10 },
        { spell = "Rapid Fire",            icon = "Interface\\Icons\\Ability_Hunter_RunningShot",   chance = 10 },
        { spell = "Freezing Trap",         icon = "Interface\\Icons\\Spell_Frost_ChainsOfIce",      chance = 10 },
        { spell = "Explosive Trap",        icon = "Interface\\Icons\\Spell_Fire_SelfDestruct",      chance = 10 },
        { spell = "Feign Death",           icon = "Interface\\Icons\\Ability_Rogue_FeignDeath",     chance = 10 },
        { spell = "Disengage",             icon = "Interface\\Icons\\Ability_Rogue_Feint",          chance = 10 },
        { spell = "Misdirection",          icon = "Interface\\Icons\\Ability_Hunter_Misdirection",  chance = 10 },
        { spell = "Bestial Wrath",         icon = "Interface\\Icons\\Ability_Druid_FerociousBite",  chance = 10 },
        { spell = "Intimidation",          icon = "Interface\\Icons\\Ability_Devour",               chance = 10 },
        { spell = "Call Pet",              icon = "Interface\\Icons\\Ability_Hunter_BeastCall",     chance = 10 },
        { spell = "Revive Pet",            icon = "Interface\\Icons\\Ability_Hunter_BeastSoothe",   chance = 10 },
        { spell = "Mend Pet",              icon = "Interface\\Icons\\Ability_Hunter_MendPet",       chance = 10 },
        { spell = "Feed Pet",              icon = "Interface\\Icons\\Ability_Hunter_BeastTraining", chance = 10 },
        { spell = "Aspect of the Hawk",    icon = "Interface\\Icons\\Spell_Nature_RavenForm",       chance = 10 },
        { spell = "Aspect of the Cheetah", icon = "Interface\\Icons\\Ability_Mount_JungleTiger",    chance = 10 },
        { spell = "Arcane Torrent",        icon = "Interface\\Icons\\Spell_Shadow_Teleport",        chance = 10 },
    },
    lines = {

        -- Abilities -----------------------------------------------------

        ["MELEE"] = {
            "%t. You have made me use my hands. Unforgivable.",
            "%t. This is not what I am for.",
            "%t. Do you know how far I usually stand from people?",
            "%t. Close work. How vulgar.",
            "%t. I shall want to wash after this.",
            "%t. Stop crowding me.",
            "%t. I am better at range and we both know it.",
        },
        ["SPELL:Hunter's Mark"] = {
            "%t. You are on the list now.",
            "Marked. Do try to be interesting, %t.",
            "%t. I have decided you matter. Briefly.",
            "Someone write down the name. %t.",
            "%t. Consider yourself invited.",
            "%t. There. Now everybody can see you.",
            "You have my attention, %t. Few survive it.",
            "%t. I do hate losing track of a guest.",
            "Stand where the light is best, %t.",
            "%t. Yes. That one. The loud one.",
            "%t. Marked, measured, and mine.",
            "Do not wander off, %t. It would be rude.",
        },

        ["SPELL:Auto Shot"] = {
            "%t. Again. And again.",
            "%t. This is the tedious part.",
            "Hold still, %t. You are spoiling the line of it.",
            "%t. Somebody will have to collect all these.",
            "%t. I could do this all afternoon. I may have to.",
            "%t. Still upright? How stubborn.",
        },

        ["SPELL:Arcane Shot"] = {
            "%t. A little sparkle. It suits you.",
            "%t. Something bright, for the occasion.",
            "That was the polite one, %t.",
            "%t. Quel'Thalas sends its regards.",
            "%t. Do you feel that? That is bleeding.",
            "%t. Even my warning shots are better dressed than you.",
            "A touch of colour, %t. You were so drab.",
            "%t. I hardly aimed. Imagine if I had.",
            "Hold that pose, %t. It flatters the wound.",
            "%t. Consider that an opening remark.",
        },

        ["SPELL:Steady Shot"] = {
            "%t. Slowly. Properly. Once.",
            "%t. Rushing is for infantry.",
            "%t. There is no prize for haste.",
            "One does not hurry a thing worth doing, %t.",
            "%t. Watch the form. You may never see it again.",
            "%t. Every finger exactly where it belongs.",
            "%t. Precision is a courtesy. You are welcome.",
            "Do not flinch, %t. It spoils the picture.",
            "%t. I was taught by people who charged a great deal.",
            "%t. Steady. Steady. There.",
        },

        ["SPELL:Aimed Shot"] = {
            "%t. Hold very still. This one is for the wall.",
            "%t. I have chosen exactly where.",
            "%t. A long breath. A short life.",
            "%t. This is the shot people used to pay to watch.",
            "Chin up, %t. Show me the throat.",
            "%t. I have been aiming since you started talking.",
            "%t. There is a right way to do this. Observe.",
            "%t. One arrow. One story.",
            "%t. Do not blink. You will miss your own ending.",
            "%t. I never miss twice.",
        },

        ["SPELL:Multi-Shot"] = {
            "%t. And your friends. And their friends.",
            "%t. Everyone gets one. I am generous.",
            "%t. Do not crowd. There is enough for all.",
            "%t. Queue properly, please.",
            "%t. I dislike repeating myself, so I did it all at once.",
            "%t. A gift each. Do not thank me.",
            "%t. You came in a group. How thoughtful.",
            "%t. Share nicely.",
            "%t. Three at once. Efficiency is elegant.",
            "%t. I do hate an uneven number of guests.",
        },

        ["SPELL:Serpent Sting"] = {
            "%t. Something for later.",
            "%t. It gets worse. That is the point.",
            "%t. Do sit down. This takes a while.",
            "%t. A slow gift. The best kind.",
            "%t. You will be thinking of me all evening.",
            "Poison is only patience, %t.",
            "%t. I did warn you. Somewhere. Probably.",
            "%t. Green does not suit you either.",
            "%t. It will find its own way to your heart.",
            "%t. Sweat it out if you like. It will not help.",
        },

        ["SPELL:Concussive Shot"] = {
            "%t. Stay.",
            "%t. We are not finished talking.",
            "%t. Where exactly did you think you were going?",
            "%t. Nobody leaves before I do.",
            "%t. Sit. Down.",
            "%t. Running is so undignified.",
            "%t. The door is not for you.",
            "%t. I did not dismiss you.",
            "%t. Slow down and enjoy your last few steps.",
        },

        ["SPELL:Wing Clip"] = {
            "%t. There. Now we walk at my pace.",
            "%t. A hamstring is such a small thing to lose.",
            "%t. Limping suits your manners.",
            "%t. I do not chase. I decline to.",
            "%t. Stay close. I am not finished.",
            "%t. You were leaving. You are not now.",
            "%t. Hobble prettily.",
        },

        ["SPELL:Raptor Strike"] = {
            "%t. Yes, I do this part myself.",
            "%t. Close enough to smell you. Unfortunate.",
            "%t. Do not touch. Ever.",
            "%t. I keep my hands clean. This will not.",
            "%t. Even at arm's length I am better than you.",
            "%t. That was for standing too near.",
            "%t. Manners cost nothing. Bad ones cost that.",
            "%t. I did not want to do this personally.",
        },

        ["SPELL:Mongoose Bite"] = {
            "%t. Never touch a lady's bow.",
            "%t. That was rude, and this is ruder.",
            "%t. Try that again. I dare you to try that again.",
            "%t. I felt that. Now you will.",
            "%t. You have made this personal.",
            "%t. Reflex, darling. Nothing personal. Mostly.",
            "%t. Strike me and I strike back, better dressed.",
        },

        ["SPELL:Volley"] = {
            "%t. The sky is mine for a moment.",
            "%t. Everyone down there. Yes, all of you.",
            "%t. Rain. From me, personally.",
            "%t. Look up. Go on, look up.",
            "%t. I have arrows to spare and no patience at all.",
            "%t. Somebody count them for me afterwards.",
        },

        ["SPELL:Rapid Fire"] = {
            "%t. I am in a hurry, so this will be quick.",
            "%t. Do keep up.",
            "%t. I have somewhere better to be.",
            "%t. Faster. Yes. Like that.",
            "%t. This is what I look like when I am impatient.",
            "%t. Enough of the slow version.",
        },

        ["SPELL:Freezing Trap"] = {
            "%t. Stand there and think about what you have done.",
            "%t. A moment of quiet, please.",
            "%t. You are excused from the conversation.",
            "%t. Do not thaw until I say.",
            "%t. Cold, is it not? Reflect.",
            "%t. I will deal with you when I have finished.",
            "%t. Wait your turn.",
        },

        ["SPELL:Explosive Trap"] = {
            "%t. Mind the floor.",
            "%t. Nobody watches where they step any more.",
            "%t. That is what comes of following me.",
            "%t. A little party underfoot.",
            "%t. Boots ruined. Serves you right.",
            "%t. I redecorate as I go.",
        },

        ["SPELL:Feign Death"] = {
            "%t. Oh no. How terrible. I am quite dead.",
            "%t. Go on, then. Grieve.",
            "%t. You are not worth the effort of a real fight.",
            "%t. Do carry on without me.",
        },

        ["SPELL:Disengage"] = {
            "%t. Do not come closer. I mean it.",
            "%t. I prefer this distance. It flatters us both.",
            "%t. That is quite near enough.",
            "%t. You were breathing on me.",
        },

        ["SPELL:Misdirection"] = {
            "%t. Speak to her. I am busy.",
            "%t. My associate will see you now.",
            "%t. I have people for this.",
            "%t. Not me, dear. Her.",
        },

        ["SPELL:Bestial Wrath"] = {
            "%t. Now you have upset her.",
            "%t. I am the restrained one, you understand.",
            "%t. Run. She does like it when they run.",
            "%t. I did try to be civil.",
            "%t. Whatever happens next is not my doing.",
        },

        ["SPELL:Intimidation"] = {
            "%t. Down.",
            "%t. Kneel, or be knelt.",
            "%t. Ah. Now you are listening.",
            "%t. Everyone bows eventually.",
        },

        ["SPELL:Call Pet"] = {
            "Come along, darling.",
            "Do try to keep up.",
            "There you are. Heel.",
        },

        ["SPELL:Revive Pet"] = {
            "Get up. We are not done.",
            "You are not allowed to leave me.",
            "Up. Up. Good girl.",
            "I have lost enough. Not you.",
        },

        ["SPELL:Mend Pet"] = {
            "Hold still, darling. Let me see it.",
            "Who did this to you? Point.",
            "There. Good. You are worth more than all of them.",
            "You are the only one here with manners.",
            "Shh. I have you.",
            "%t did that to you. Noted.",
        },

        ["SPELL:Feed Pet"] = {
            "Eat. You have earned it.",
            "The best cut, naturally.",
            "Slowly. It is not a race.",
        },

        ["SPELL:Aspect of the Hawk"] = {
            "Better. Now I can see who is worth shooting.",
            "Everything sharpens. Including my mood.",
        },

        ["SPELL:Aspect of the Cheetah"] = {
            "I am not running. I am arriving early.",
            "One does not walk when one can glide.",
            "Try to keep up, darling.",
        },

        ["SPELL:Arcane Torrent"] = {
            "%t. Thank you. I was running low.",
            "%t. Do not look at me like that. Everyone does it.",
            "%t. It is not a weakness. It is a taste.",
            "%t. I will take that, thank you.",
        },

        -- Reactions -----------------------------------------------------

        ["REACT:LOWHEALTH"] = {
            "%t. This was clean an hour ago.",
            "%t. Do you have any idea what this cost?",
            "%t. That is my blood. Mine.",
            "%t. I am going to be very unpleasant about this.",
            "%t. You have made me untidy.",
            "%t. I have never bled in front of anyone before.",
            "%t. Enough. This has stopped being amusing.",
            "%t. Somebody will answer for this. It will be you.",
            "%t. Do not think this makes us equals.",
            "%t. I am not used to this. I dislike it enormously.",
            "%t. You have ruined the line of this coat.",
            "%t. I have been hurt by better.",
            "%t. Stop. Stop that immediately.",
            "%t. I said do not touch me.",
            "%t. This is the part where I stop being polite.",
            "%t. My grandmother held a wall against worse than you.",
            "%t. I refuse to fall over in this dust.",
            "%t. Not here. Not to something like you.",
            "%t. I am still standing, you will notice.",
            "%t. Do you want my rings? Come and take them.",
            "%t. Somebody fetch me a bandage and a better opponent.",
            "%t. I have survived court dinners worse than this.",
            "%t. You will not be the thing that finishes me.",
            "%t. I am tired, and cross, and still better armed.",
            "%t. This is deeply unfair.",
            "%t. I want you to know I am taking this personally.",
            "%t. My name is older than your village. Remember it.",
            "%t. Very well. No more manners.",
            "%t. That hurt. That actually hurt.",
            "%t. I am revising my opinion of you. Downward.",
            "%t. Do not smile. You have won nothing.",
            "%t. I walked out of a burning city. You are nothing.",
        },

        ["REACT:DEATH"] = {
            "%t. Oh, this is humiliating.",
            "%t. Not in the dirt. Anywhere but the dirt.",
            "%t. Tell them I was beautiful about it.",
            "%t. I did not agree to this.",
            "%t. My house will hear of this.",
            "%t. See to my beast. She will not understand.",
            "%t. I want a proper funeral. Flowers. Weeping.",
            "%t. Well. You are going to regret being memorable.",
            "%t. Put out by you, of all things. Absurd.",
            "%t. I was going to be so much more than this.",
            "%t. Do not touch my things.",
            "%t. Is that all? I expected ceremony.",
            "%t. I am not finished. I am merely pausing.",
            "%t. This is the worst evening of my life.",
            "%t. You will not remember my face. I will remember yours.",
            "%t. Nobody saw that. Nobody saw that.",
            "%t. I would rather have died in Silvermoon.",
            "%t. My ring goes home. Somebody see to it.",
            "%t. So this is the ground. I have never spent time down here.",
            "%t. How dreadfully common.",
            "%t. I refuse. I refuse. Oh.",
            "%t. Do not tell the Farstriders. They would enjoy it.",
            "%t. I hope you choke on it.",
            "%t. That was not a fair fight. Nothing ever is.",
            "%t. Wake me when somebody competent arrives.",
            "%t. I have never been this cold. Not even at home.",
            "%t. Very well. You may have the field. Not the story.",
            "%t. I would have made a magnificent queen of something.",
            "%t. Do not let her see me like this.",
            "%t. There is dust on my mouth. That is what I object to.",
            "%t. Enjoy it. It will be brief.",
        },

        ["REACT:RESURRECT"] = {
            "Well. That was undignified.",
            "Nobody speaks of this. Ever.",
            "I have been dead. It is very overrated.",
            "Right. Where was I.",
            "Somebody will be paying for the cleaning.",
            "Back, and in a temper.",
            "I did not care for that at all.",
            "Do not look at me. Look away.",
            "There. Presentable. Almost.",
            "The dead are so badly dressed. I did not fit in.",
            "I want a bath. I want three baths.",
            "You waited. Of course you waited. Good girl.",
            "Nothing has changed. I am merely fashionably late.",
            "Death is a rumour, and I intend to keep it one.",
            "Say nothing. I can hear you thinking.",
            "One does not stay down. One reschedules.",
            "I have decided that did not happen.",
            "Now. Who was responsible.",
            "That is the last time I let anyone get behind me.",
            "Up, and cross about it.",
            "The world carried on without me. How rude.",
            "I am owed an apology. I am not certain by whom.",
            "Well. Nobody important saw.",
            "Again, then. From the top.",
            "I have things to finish and a temper to spend.",
            "Do not fuss. I am perfectly fine.",
            "Vanity brought me back. Do not tell anyone.",
        },

        ["REACT:KILLINGBLOW"] = {
            "%t. There. Was that so difficult?",
            "%t. Somebody move that.",
            "%t. Do not bleed toward me.",
            "%t. I did tell you.",
            "%t. And that is how it is done.",
            "%t. Next.",
            "%t. You were not even a story.",
            "%t. I will not be remembering you.",
            "%t. That is one fewer person who has seen my face.",
            "%t. A shame. You had potential. Very little of it.",
            "%t. My arrows are worth more than your life. I want that one back.",
            "%t. Rest. You have earned nothing, but rest anyway.",
            "%t. That was the polite version.",
            "%t. Good girl. Leave some of him.",
            "%t. And they said I was decorative.",
            "%t. I do hope somebody was watching.",
            "%t. One shot, as advertised.",
            "%t. You should have run when I offered.",
            "%t. Now. Who else has an opinion?",
            "%t. I am going to need new gloves.",
            "%t. Tell your gods a lady sent you.",
            "%t. Quicker than the conversation would have been.",
            "%t. Beautifully done, if I say so myself.",
            "%t. You may go.",
            "%t. Do you know, I did not even use the good arrows.",
            "%t. There is a right way to fall. That was not it.",
            "%t. Poor thing. Wrong field, wrong day, wrong woman.",
            "%t. I shall be dining well tonight regardless.",
            "%t. Nothing personal. Everything personal.",
            "%t. Cross me, and this is the whole of it.",
            "%t. Consider the matter closed.",
        },

        ["REACT:COMBATSTART"] = {
            "%t. Oh. We are doing this.",
            "%t. You have chosen a very bad afternoon.",
            "%t. I was having such a pleasant walk.",
            "%t. Do you know who you are speaking to?",
            "%t. This will be quick and one-sided. Sorry.",
            "%t. Stand where I can see you.",
            "%t. I hope you brought somebody competent.",
            "%t. Very well. Amuse me.",
            "%t. Darling. Fetch.",
            "%t. I do not fight. I conclude.",
            "%t. You are between me and my evening.",
            "%t. Try to be worth the arrows.",
            "%t. I did not dress for this.",
            "%t. How many of you are there? Fine.",
            "%t. Yes, yes. Come along then.",
            "%t. Let us get this over with. I have a dinner.",
            "%t. Rude. Very rude.",
            "%t. Was that meant to frighten me?",
            "%t. I have been shot at by better.",
            "%t. Do not touch the hair.",
            "%t. You may begin. I already have.",
            "%t. I was taught manners and archery. Guess which you get.",
            "%t. This is going to be tiresome.",
            "%t. Say something clever. Quickly.",
            "%t. Right. Chin up. Best foot forward.",
            "%t. I shall try to leave something for the wolves.",
            "%t. You are all very brave and very stupid.",
            "%t. Good. I was bored.",
            "%t. Please do run. It is prettier that way.",
            "%t. I am going to be so cross about the dust.",
            "%t. Very well. Court is in session.",
        },

        ["REACT:COMBATEND"] = {
            "Well. That is that.",
            "Was anyone watching? Nobody? Typical.",
            "I am going to want a very long bath.",
            "Hardly worth the effort.",
            "Good girl. Come away from that.",
            "That is enough excitement for one day.",
            "Somebody owes me a new pair of gloves.",
            "I did warn them. I always warn them.",
            "Nothing broken. Nothing that shows, at least.",
            "Right. Where were we going?",
            "I was magnificent. I should like that noted.",
            "Dreadful. Absolutely dreadful people.",
            "Never again. Until the next time.",
            "This is why I do not go out.",
            "I need a drink, and not water.",
            "A great deal of noise about very little.",
            "Come along, darling. We are leaving.",
            "It is over. Do stop looking at me.",
            "Some days I miss the city terribly.",
            "Not one of them said please.",
            "There. Order restored.",
            "I shall write this down as a triumph.",
            "Quiet again. I do prefer it, whatever I say.",
            "Well fought, darling. You were the better of us.",
            "I want a chair, a fire, and no conversation.",
            "That is the last of them. I counted twice.",
        },

        ["REACT:INTERRUPTED"] = {
            "%t. Did you just interrupt me?",
            "%t. I was speaking.",
            "%t. Nobody interrupts me. Nobody.",
            "%t. That is the rudest thing anyone has done all week.",
            "%t. Say that again. I want to hear it twice.",
            "%t. Now I am going to take my time.",
            "%t. Oh, you will pay for that little trick.",
            "%t. Wait your turn like everybody else.",
            "%t. That was very nearly clever.",
            "%t. Fine. We do it the loud way.",
            "%t. You have not stopped me. You have delayed me.",
            "%t. I was not finished. I am rarely finished.",
            "%t. How many people have you interrupted? How many are alive?",
            "%t. Do not do that again.",
            "%t. I will remember that.",
            "%t. Congratulations. You have my full attention.",
            "%t. That is one. You do not get two.",
            "%t. I am counting, and you are on a poor number.",
            "%t. Very well. Nothing pretty this time.",
            "%t. Was that supposed to impress me?",
            "%t. You should not have touched my hands.",
            "%t. I had that beautifully lined up.",
            "%t. That was rude, and it was cheap.",
            "%t. At home you would have been removed for that.",
            "%t. Again. From the beginning. Because of you.",
            "%t. I hope that was worth it.",
            "%t. You have made this last longer. Well done.",
            "%t. Enough games.",
            "%t. Interrupt me once more and I shall make it artistic.",
            "%t. I do not like being made to repeat myself.",
            "%t. That is not how this goes.",
        },

        ["REACT:LEVELUP"] = {
            "Better. Obviously better.",
            "I am improving. I was already good.",
            "There. Did you feel that? No? Never mind.",
            "One does not stay where one started.",
            "Every day, more difficult to argue with.",
            "I shall be insufferable by spring.",
            "Good. Good. Nearly what I intended to be.",
            "Somebody at home should be told.",
            "I am becoming rather formidable. It suits me.",
            "That is another thing they cannot take.",
            "Sharper. Steadier. Still beautiful.",
            "The city is gone. I am not. I am growing.",
            "Do keep up, darling. I am getting quicker.",
        },

        ["REACT:FALLING"] = {
            "This is not how a lady descends.",
            "Oh, that is a long way down.",
            "Somebody catch me. Anybody. No?",
            "I did not agree to this.",
            "The ground. Of course. It is always the ground.",
            "I meant to do that. Obviously.",
            "This is going to hurt and I shall be loud about it.",
            "Wait. Wait. Wait.",
            "Not the boots. Please not the boots.",
            "Whose idea was that? Mine. Damn.",
            "I have made a serious error.",
            "Oh no. Oh no, no, no.",
            "Undignified in every possible way.",
        },

        ["REACT:DROWNING"] = {
            "This water is filthy, and I am in it.",
            "Up. Up. Which way is up.",
            "My hair. My hair is ruined.",
            "Nobody could swim in this.",
            "Air. I should like some air, please.",
            "Not like this. Not wet.",
            "Somebody. Somebody.",
            "I hate water. I have always hated water.",
            "Darling. Darling, help.",
            "This is a stupid way to die.",
            "My bow. Where is my bow.",
            "Cold, dark and common. Wonderful.",
            "I refuse to drown. It is beneath me.",
        },

        ["REACT:DURABILITY"] = {
            "This is falling apart. I am falling apart.",
            "I cannot be seen like this.",
            "My gear is in tatters. So am I.",
            "Somebody in this world must know how to mend things.",
            "This was made for me. Made. For me.",
            "Held together with string and pride.",
            "I look like a farmhand. A very well armed farmhand.",
            "The string is fraying. Everything is fraying.",
            "I need a smith, a tailor, and a strong drink.",
            "This will not last another fight. Nor will the coat.",
            "Rags. I am wearing rags with a very good name on them.",
            "At home there were people for this.",
            "One more scratch and I shall simply sit down.",
        },

        -- Idle ----------------------------------------------------------

        ["IDLE:EAT"] = {
            "This is not food. These are provisions.",
            "I ate better than this as a child. Considerably better.",
            "Do not watch me eat.",
            "Salt. Would salt be too much to ask?",
            "One eats to continue. That is all this is.",
            "I dream about pastry. Constantly.",
            "Sit with me, darling. Do not beg. Just sit.",
        },

        ["IDLE:DRINK"] = {
            "Water. Always water. Never anything worth drinking.",
            "At home this would have been chilled.",
            "One does miss wine.",
            "Warm. Of course it is warm.",
            "I shall pretend this is something better.",
            "To absent luxuries.",
            "This is what passes for refreshment out here.",
        },

        ["IDLE:MOUNT"] = {
            "Walking is for people with nowhere to be.",
            "Come along. We are expected somewhere.",
            "Sit up straight. Both of us.",
            "I do like to arrive properly.",
            "Onward. Try to keep the dust down.",
            "One should never be seen hurrying on foot.",
            "Do keep up, darling.",
        },

        ["IDLE:QUESTACCEPT"] = {
            "Very well. I shall see to it.",
            "You are fortunate I was passing.",
            "I am not an errand girl. But I am here.",
            "Fine. Yes. Consider it handled.",
            "Do not thank me now. Thank me expensively later.",
            "One helps. It is expected of people like me.",
            "I shall do this properly, since nobody else will.",
            "Point me at it.",
        },

        ["IDLE:SKINNING"] = {
            "This is the part nobody mentions in the songs.",
            "Waste nothing. Even I know that.",
            "I have ruined another pair of gloves.",
            "It is honest work. That is the kindest thing about it.",
            "Somebody at home would faint to see this.",
            "A good hide is a good hide. I have learned that much.",
            "Do not tell anyone I am good at this.",
        },

        ["IDLE:FISHING"] = {
            "This is meant to be restful. I am not restful.",
            "I could buy fish. I could buy a great many fish.",
            "Patience is a virtue I keep for hunting.",
            "The quiet is nice. Do not tell anyone I said so.",
            "Come on, then. Somebody bite.",
            "There is nothing here to shoot. It is unsettling.",
            "If this takes much longer I shall simply shoot one.",
        },

        ["IDLE:DISCOVERY"] = {
            "Oh. That is rather lovely.",
            "Nobody at home has seen this. Only me.",
            "I shall describe this badly to somebody later.",
            "Well. Worth the walk. Almost.",
            "The world is very large when nobody is announcing you.",
            "I have never been here. Nobody has told me what to think of it.",
            "Look, darling. Look at that.",
            "Beautiful. And full of things that want shooting, no doubt.",
        },
    },
}
