-- RPVox -- stock lines
-- Every built-in trigger's default sayings, keyed by trigger key.
-- Voice: a Forsaken shadow priest. Dry, cold, unimpressed, still angry.

RPVox_LINES = {}

-- Combat ------------------------------------------------------------------

RPVox_LINES["MELEE"] = {
    "Have at thee, %t!",
    "Face me, coward, %t!",
    "%t. No mercy!",
    "%t. Such fragile flesh.",
    "Come closer. I insist, %t.",
    "You bleed. How quaint, %t.",
    "%t. Crude, but it works.",
    "%t. I do not need a weapon for you.",
    "Down you go, %t.",
    "Closer than I like. Fatal for you, %t.",
}

RPVox_LINES["SPELL:Shoot"] = {
    "%t. Must I do everything myself?",
    "%t. Out of power, not out of spite.",
    "%t. A tedious way to kill.",
    "%t. Poke, poke, poke.",
    "Even this is more than you deserve, %t.",
    "A splinter of the dark, just for you, %t.",
    "%t. Cold light. It burns all the same.",
    "This stick has killed better than you, %t.",
    "Bleed slowly, then, %t.",
    "Hold still, it's only a little death, %t.",
    "%t. The Shadow has left me. This has not.",
    "Empty. Utterly empty. And still you stand, %t.",
    "%t. When the whispers go quiet, one improvises.",
    "Not a shred of power left, and you still lose, %t.",
}

RPVox_LINES["SPELL:Power Word: Shield"] = {
    "Stand behind the word, %t.",
    "Nothing touches you. Not while I am watching, %t.",
    "A borrowed skin, stronger than your own, %t.",
    "Hold. I have made you difficult to kill, %t.",
    "%t. The Light still answers me. It should not.",
    "%t. This will hold. It always holds.",
    "%t. Wear this. It fits better than it did on me.",
    "%t. Faith hardened into a wall.",
    "You are warded. Do something worthy of it, %t.",
    "I could not shield myself. I can shield you, %t.",
    "Let it break on you and not through you, %t.",
    "%t. A moment of safety. Spend it well.",
    "%t. Guarded. Now stop bleeding on my work.",
    "%t. The word is spoken. Nothing gets past it.",
    "You will feel the blow. You will not feel the ending, %t.",
    "Hold, %t. I have made you difficult to kill.",
    "/em traces a ward in the air with two fingers",
    "Stand behind the word, %t.",
}

RPVox_LINES["SPELL:Mind Blast"] = {
    "Get out of your own head. I am moving in, %t.",
    "Think of nothing. There. Easier already, %t.",
    "I have seen inside you. It is not much, %t.",
    "Something just broke behind your eyes, %t.",
    "Your thoughts are mine to rearrange, %t.",
    "Scream inwardly. It carries better, %t.",
    "%t. That is the sound of a mind giving way.",
    "%t. The whispers say hello.",
    "Hold your skull together. Do try, %t.",
    "I know what you were about to do. So does the dark, %t.",
    "%t. A little rot, applied directly to the mind.",
    "Do you hear them now? Everyone does eventually, %t.",
    "Your memories are unguarded. Careless, %t.",
    "%t. I have been in worse minds. Mine, mostly.",
    "%t. Silence in there. I insist.",
    "Get out of your own head, %t. I am moving in.",
    "/em stares until something behind the eyes gives way",
    "Your thoughts are mine now, %t.",
}

RPVox_LINES["SPELL:Smite"] = {
    "%t. The Light burns me too. I have grown used to it.",
    "%t. It abandoned me. It still obeys me.",
    "%t. Borrowed radiance. Returned with interest.",
    "%t. Even the Light will hurt on command.",
    "%t. I do not pray. I demand.",
    "%t. Something holy, wielded by something that is not.",
    "%t. The Light does not care who holds it. I checked.",
    "%t. Bright. Hot. Brief. Like a life.",
    "%t. This is what faith looks like when it curdles.",
    "%t. I was a priest before I was this. It stuck.",
    "Take it. It was never comfortable to carry, %t.",
    "%t. Blessed be the impact.",
    "%t. The Light and I have an arrangement.",
    "Let it sear. It seared me first, %t.",
    "%t. A gift from the thing that left me in the dirt.",
    "/em calls down a light he no longer believes in",
    "The Light and I have an arrangement, %t.",
    "Take it, %t. It was never comfortable to carry.",
}

RPVox_LINES["SPELL:Renew"] = {
    "%t. Knit. Slowly. As all good things do.",
    "%t. It will mend on its own now. Mostly.",
    "%t. A little life, loaned out.",
    "Hold that together for me, %t.",
    "Your body remembers how to be whole. Mine does not, %t.",
    "Grow back. I envy you the ability, %t.",
    "%t. Patience. Healing is not a moment, it is a while.",
    "%t. There. Rot postponed.",
    "Something in you is repairing. Cherish that, %t.",
    "%t. The Light works slowly through cold hands.",
    "Stay standing. That is all I ask, %t.",
    "%t. This is the closest I come to kindness.",
    "%t. Warmth, seeping in. I remember warmth.",
    "You will feel better shortly. Irritating, isn't it, %t.",
    "%t. Mending. Not undoing. Nothing undoes.",
    "Grow back, %t. I envy you the ability.",
    "/em lays a cold hand briefly on a shoulder",
    "Stay standing, %t. That is all I ask.",
}

RPVox_LINES["SPELL:Lesser Heal"] = {
    "%t. Close. Just close.",
    "Flesh obeys me better than it obeys you, %t.",
    "%t. A small mercy. They are the only ones I have.",
    "Stop bleeding. That is an order, %t.",
    "%t. Held together by will and a little Light.",
    "%t. Not whole. Whole is beyond either of us.",
    "%t. There. Presentable again.",
    "%t. I am better at ending than mending. Consider yourself fortunate.",
    "Take it before I reconsider, %t.",
    "%t. The wound closes. The memory does not.",
    "Do not waste this on dying twice, %t.",
    "Enough to keep you upright. No more, %t.",
    "%t. Skin over the gap. That is all healing is.",
    "You get the Light. I got the grave, %t.",
    "%t. Better. Now stay out of the way.",
    "Stop bleeding, %t. That is an order.",
    "/em closes the wound with visible distaste",
    "Better, %t. Now stay out of the way.",
}

-- Reactions ---------------------------------------------------------------

RPVox_LINES["REACT:LOWHEALTH"] = {
    "%t. This body has failed before. It will hold.",
    "%t. Bones knit. Flesh does not. No matter.",
    "%t. I have died once already. It loses its terror.",
    "%t. Not... yet.",
    "Hold together, wretched thing, %t.",
    "%t. I feel nothing. I feel nothing.",
    "%t. Ribs. Those were ribs.",
    "%t. Still standing. Barely counts as standing.",
    "%t. There is not much left of me to take.",
    "You are wasting your time. I have so little to lose, %t.",
    "%t. The stitching is coming loose again.",
    "%t. Half of me is already in the ground. The rest is stubborn.",
    "%t. Pain is a message. I stopped reading them.",
    "%t. That would have killed the man I was.",
    "Do not mistake this for fear. It is arithmetic, %t.",
    "%t. Dark Lady, not like this. Not again.",
    "%t. Bleeding. Interesting. I thought that had stopped.",
    "%t. I have been worse. I have been buried.",
    "Keep going. See what crawls back up, %t.",
    "%t. The whispers grow louder when I am close to the edge.",
    "%t. So this is what the living feel. Constantly. How exhausting.",
    "Hold. Just... hold, %t.",
    "%t. My grip is going. My spite is not.",
    "%t. Another scar for a body that cannot heal.",
    "%t. I refuse. Simply that. I refuse.",
    "%t. Something important just came apart.",
    "Do you know how hard it is to put me back together, %t?",
    "%t. I am not finished. I decide when I am finished.",
    "%t. Cold. Colder than usual. That is new.",
    "%t. Undeath is a loophole, not a shield.",
    "%t. The Forsaken do not die twice. Usually.",
    "%t. Steady. Steady.",
    "You will have to take me apart piece by piece, %t.",
    "%t. I can still stand. Watch.",
    "%t. Careful. There is less of me than there was.",
    "%t. Leaking. Again.",
    "%t. That is bone. That should not be visible.",
    "Hold the line. Hold the body. Hold something, %t.",
    "%t. This is fine. This is nearly fine.",
    "Do not stop. I want to see you fail, %t.",
    "%t. The seams are going.",
    "%t. I have survived worse in a shallower grave.",
    "%t. Everything is grey. Greyer than usual.",
    "A little more and you will have done something impressive, %t.",
    "%t. My legs are lying to me.",
    "%t. Not much left. There never was.",
    "%t. Enough of me remains to finish this.",
    "%t. It hurts. I notice. I continue.",
    "%t. I will hold this ruin together by spite alone.",
    "%t. One more hit and I go. So do not miss the point.",
    "%t. The dark is very close now.",
    "%t. That was almost the end. Almost.",
    "%t. Patch it later. Fight now.",
    "%t. I have bled out before. It is survivable, apparently.",
    "Do you hear that? Neither do I. Bad sign, %t.",
    "%t. The whispers are shouting.",
    "Stay upright. Stay upright, %t.",
    "%t. Something vital, probably.",
    "%t. I know exactly how much I can lose.",
    "%t. Twice the wounds, half the concern.",
    "%t. Still here. Insultingly still here.",
    "%t. This body owes me one more minute.",
    "%t. Cracked, not finished.",
    "%t. I am running out of self.",
    "%t. The pain is distant. Like everything else.",
    "%t. Ah. That is what breaking feels like from inside.",
    "Keep swinging. See who runs out first, %t.",
    "%t. There is a hole in me. Add it to the collection.",
    "Hurt me. It is what I have left to offer, %t.",
    "%t. I have been dying for years. I am practiced.",
    "Do not look so hopeful, %t.",
    "%t. It takes more than that to unmake me.",
    "%t. The stitches will hold. They must.",
    "%t. My vision narrows. Convenient. Fewer distractions.",
    "%t. Nearly out. Not out.",
    "%t. I felt that one. Congratulations.",
    "%t. The Dark Lady is watching. Do not embarrass me.",
    "%t. A moment. Give me a moment.",
    "%t. Fragments. I am running on fragments.",
    "The rot has done worse than you have, %t.",
    "%t. I can be killed. I simply prefer not to be.",
    "Hold, damn you, hold, %t.",
    "%t. This is the part where I get stubborn.",
    "%t. Empty and standing. My natural state.",
    "You are close. You are not there, %t.",
    "%t. So little between me and the dirt.",
    "%t. I have known this feeling since Lordaeron.",
    "%t. Falling apart on schedule.",
    "%t. The whispers offer terms. I decline.",
    "%t. Every joint is a complaint.",
    "%t. Not the worst wound I have carried.",
    "%t. I do not beg. I recalculate.",
    "%t. Nearly finished. Nearly.",
    "%t. Still moving. That is all that matters.",
    "%t. The pain is not the problem. The stopping is.",
    "%t. A dying man fights better. I would know.",
    "%t. I hold. I always hold.",
    "%t. One more breath I do not need.",
    "%t. I am difficult to kill. Ask the grave.",
    "Break me, then. See what stands up, %t.",
    "/em sways, one hand pressed to a wound that will not close",
    "/em spits something dark into the dirt",
    "Not while %t still stands.",
    "%t. Barely a body left, and I did not want it anyway.",
    "/em grips the wound and keeps walking",
    "You have taken half of me, %t. Take the rest if you can.",
    "/em breathes out slowly, though the breath does nothing",
    "Down to the last of it. Still standing, %t.",
}

RPVox_LINES["REACT:DEATH"] = {
    "%t. Again? Very well.",
    "%t. Death is an old acquaintance.",
    "%t. The Dark Lady is not finished with me.",
    "%t. This changes nothing.",
    "%t. Twice now. It gets no easier.",
    "%t. Ah. There it is.",
    "%t. Back to the cold ground, then.",
    "%t. I hate this part.",
    "You have killed nothing that was alive, %t.",
    "Do not celebrate. I never stay down, %t.",
    "%t. Well. That was undignified.",
    "%t. The dark takes me. It always gives me back.",
    "%t. I have done this before. I remember none of it fondly.",
    "%t. So it ends. Briefly.",
    "%t. My body quits. My grudge does not.",
    "See you shortly, %t.",
    "%t. Tell the Banshee Queen I fell facing forward.",
    "%t. Undercity will want the body. What is left of it.",
    "%t. How embarrassing.",
    "%t. The whispers stop. That is the worst of it.",
    "%t. Nothing. Just... nothing.",
    "%t. I did not fear it the first time either.",
    "%t. Save the eulogy. I will need it again.",
    "%t. This is a formality. Nothing more.",
    "%t. One more death. Add it to the ledger.",
    "%t. The grave and I are on familiar terms.",
    "You will regret leaving me a corpse. I get up, %t.",
    "Rest? No. Merely paused, %t.",
    "%t. Falling. Still falling.",
    "Light take you. That is not a blessing, %t.",
    "I hope that cost you something, %t.",
    "%t. Curse this fragile ruin of a body.",
    "Remember the face. You will see it again, %t.",
    "%t. The dead are patient. I will wait.",
    "%t. Dark Lady, watch over what is left.",
    "Down again. The floor and I are old friends, %t.",
    "%t. Was that supposed to be permanent?",
    "%t. Killing me is a temporary hobby.",
    "%t. I felt that. Barely. Mostly annoyance.",
    "Take the moment. It is all you get, %t.",
    "%t. The cold comes first. Then the quiet.",
    "%t. My knees go before my will does. Always.",
    "%t. Bury me properly this time. Someone should try.",
    "%t. So much for the afternoon.",
    "%t. A hole in me. Another one.",
    "%t. I go where I have already been.",
    "%t. Ended by that. How humiliating.",
    "%t. The whispers will fetch me back.",
    "%t. Dust returns to dust. Then gets up.",
    "%t. I have spent longer dead than alive.",
    "%t. This is not death. It is paperwork.",
    "%t. The ground is cold. I am colder.",
    "Do not touch the body. It is still mine, %t.",
    "%t. A brief intermission.",
    "%t. I have been buried, burned, and raised. Try harder.",
    "%t. That is going to require stitches. Many stitches.",
    "%t. Report it as a setback.",
    "The last thing I see is you. Unfortunate, %t.",
    "%t. Slipping. Fine. Let it slip.",
    "%t. The Forsaken keep terrible funerals.",
    "%t. I did not consent the first time either.",
    "%t. Even the grave is bored of me.",
    "%t. My blood is old and unwilling. Take it anyway.",
    "%t. A body is a loan. Mine is overdue.",
    "%t. So dark. So familiar.",
    "%t. They will find me. They always find me.",
    "%t. There is no rest at the bottom of this.",
    "%t. Every death is practice for the next.",
    "%t. I am not finished. Merely interrupted.",
    "Note the time. I will want revenge on schedule, %t.",
    "%t. Broken again. Predictable.",
    "%t. The Light did not catch me. It never does.",
    "Down I go, into the usual dark, %t.",
    "%t. Nobody mourns the second death.",
    "Have the decency to look away, %t.",
    "%t. Cold. Quiet. Tedious.",
    "%t. One day this will stop working. Not today.",
    "%t. Hollow to hollow. Dust to dust.",
    "Do not follow me down. It is crowded, %t.",
    "%t. Well fought. I still resent it.",
    "%t. The whispers say: get up. In a moment.",
    "%t. The dark is not restful. It is only dark.",
    "%t. Killed by that? I have standards.",
    "%t. My end has no dignity left to lose.",
    "%t. I taste iron. Old habits.",
    "%t. The world tilts. Then goes.",
    "%t. A corpse again. Back to the beginning.",
    "%t. I fell. I will rise. Repeat forever.",
    "%t. That was quicker than the first time.",
    "%t. Somebody take the body to the Apothecarium.",
    "%t. The dead do not scream. I remember screaming.",
    "%t. Enough. Enough for now.",
    "Fine. Have your victory. It is on loan, %t.",
    "%t. I have died in better company.",
    "%t. Silence. At last. Briefly.",
    "%t. The Shadow keeps my seat warm.",
    "Give me a moment. I always come back, %t.",
    "%t. Not the end. Never the end.",
    "Down. Cold. Waiting, %t.",
    "%t. It is only death. I have had worse afternoons.",
    "/em collapses without a sound",
    "Remember the name, %t. I will find you.",
    "/em goes still, eyes open",
    "You win nothing, %t.",
    "/em settles into the dirt, unhurried",
    "Well struck, %t. Enjoy it briefly.",
}

RPVox_LINES["REACT:RESURRECT"] = {
    "Back into the cold.",
    "Rise, and rise again.",
    "The grave keeps spitting me out.",
    "Where was I...",
    "Undeath has its uses.",
    "Stitched up and standing. As usual.",
    "That was a short retirement.",
    "The dark did not want me either.",
    "Breathing. Or the habit of it.",
    "Everything aches. Everything always aches.",
    "Awake. Unfortunately.",
    "Death is a door I keep failing to close.",
    "Ah. Still here. Still this.",
    "The Dark Lady's gift, once more.",
    "Reassembled. Mostly.",
    "Somebody wanted me back. How odd.",
    "I remember dying. I always remember dying.",
    "Give me a moment. The body is slow to obey.",
    "Second wind. Third. Fourth. I lose count.",
    "The Forsaken do not stay buried.",
    "Up. There is work to finish.",
    "Do not thank me for returning. I had no choice.",
    "The world is exactly as I left it. Disappointing.",
    "Cold hands. Cold everything. Familiar.",
    "Well. Where were we.",
    "Rot delayed is not rot denied.",
    "The whispers return first. They always do.",
    "I clawed my way out of a grave once. This was easier.",
    "Consciousness. What a nuisance.",
    "Bones remember how to stand. Good.",
    "Not free. Merely upright.",
    "Whoever raised me: you have poor judgment, %t.",
    "Again into the ruin of the world.",
    "The Light abandoned me. Death keeps returning me. Neither asked.",
    "I return. As I always return.",
    "Standing. The rest is negotiable.",
    "My fingers work. That is a start.",
    "Back in the ruin I call a body.",
    "Do I look better? No. I never do.",
    "The dark spat me out mid-sentence.",
    "Alive is the wrong word. Upright will do.",
    "Dust off the priest. He works again.",
    "Every return costs a little more.",
    "Something is missing. Something always is.",
    "Vision first. Regret second.",
    "I did not miss this place.",
    "Awake, cold, and irritated. The usual.",
    "The grave is a revolving door for my kind.",
    "Whatever pulled me back can answer for it.",
    "Back among the noise.",
    "The seams held. Barely.",
    "A little less of me each time.",
    "Death did not keep me. It never does.",
    "On my feet. Spare me the applause.",
    "The whispers missed me. Only they did.",
    "So. That happened.",
    "I remember the dark better than the light.",
    "The body obeys. Slowly, resentfully.",
    "Returned. Diminished. Present.",
    "One more resurrection on the tally.",
    "The Dark Lady's arithmetic, not mine.",
    "There is no peace on either side. I checked.",
    "Move, you stubborn corpse, %t.",
    "Nothing waits for me down there. Nothing waits up here either.",
    "Standing costs more than it used to.",
    "Right. Vengeance. I was in the middle of that.",
    "Back. Colder. Meaner.",
    "The rot resumes where it left off.",
    "Death is not restful. I keep telling people.",
    "Bones set. Grudges keep.",
    "Awake and unimpressed.",
    "Whoever did this: thank you. Probably.",
    "The world had the decency to continue without me.",
    "Rejoining the living. Loosely.",
    "I have unfinished business. I always do.",
    "Well. The trick still works.",
    "My heart does not start. It never does.",
    "Give the corpse a moment.",
    "Back to being a problem.",
    "The Shadow returns me. It is not kindness.",
    "Every scar I own is older than my death.",
    "Upright and ungrateful.",
    "Let us pretend that did not happen.",
    "The dark released its grip. Reluctantly.",
    "Same body. Same complaints.",
    "I was somewhere quiet. Now I am here.",
    "Existence resumed.",
    "That was restful. Wake me never.",
    "Nothing changes. I simply continue.",
    "Undeath: the gift that keeps demanding.",
    "Feeling returns last. It always does.",
    "Up, up. The dead have work.",
    "I did not finish dying. Typical.",
    "Back on my feet, if you can call them that.",
    "The wound stays. It always stays.",
    "Here again. Cold again. Ready again.",
    "Someone owes me for that.",
    "Reanimated and mildly annoyed.",
    "The Forsaken endure. That is all we do.",
    "Once more, then. Once more.",
    "/em rises stiffly, joints protesting",
    "/em brushes the grave dirt from a threadbare robe",
    "Back on my feet and unimpressed.",
    "/em rolls a shoulder until something clicks into place",
    "Where is %t? I was not finished.",
}

RPVox_LINES["REACT:KILLINGBLOW"] = {
    "Rest. You have earned that much, %t.",
    "%t. One less warm thing in the world.",
    "%t. It was over before it began.",
    "%t. Welcome to the quiet.",
    "You are luckier than you know. You get to stay dead, %t.",
    "Down. Stay there, %t.",
    "Was that all you were, %t?",
    "The Shadow thanks you for your contribution, %t.",
    "%t. Another for the ledger.",
    "You went quietly. I appreciate that, %t.",
    "Do not look so surprised, %t.",
    "Enjoy the silence. I never got to, %t.",
    "Now you know what I know, %t.",
    "%t. Finished. Next.",
    "You will not rise. That mercy is mine alone, %t.",
    "%t. Poor thing. It thought it had time.",
    "%t. Death is not an ending. Ask me how I know.",
    "%t. That is one way to stop the screaming.",
    "Fold up. Go cold. Good, %t.",
    "You made this simple, %t.",
    "Do you understand yet? No. Of course not, %t.",
    "%t. So much noise for so little.",
    "The dirt will have you by morning, %t.",
    "%t. I have made better corpses.",
    "Sleep. Truly sleep. I envy you, %t.",
    "%t. One less voice in the world. It was already too loud.",
    "You should have run, %t.",
    "%t. There. Was that so hard?",
    "%t. A clean end. More than I received.",
    "Your body is honest now, at least, %t.",
    "%t. That is what breaking sounds like.",
    "%t. No last words? Wise.",
    "%t. It stopped moving. They usually do.",
    "%t. The Dark Lady claims another.",
    "%t. Gone. And I remain. As ever.",
    "%t. Cold already. Efficient.",
    "You are finished. I am merely paused, %t.",
    "%t. A short life, honestly lived, badly ended.",
    "Stay dead. It is the kinder path, %t.",
    "%t. That is the whole of it, then.",
    "%t. I would say I am sorry. I am not.",
    "%t. Another to the pile.",
    "%t. Good. Quiet.",
    "You will not be missed. Few are, %t.",
    "%t. Nothing personal. Very little is.",
    "%t. The rot begins. I know the schedule.",
    "Off you go, %t.",
    "I have seen thousands. You were one, %t.",
    "Stop. There. Now stay stopped, %t.",
    "Your defiance was the best part, %t.",
    "Ended cleanly. You are welcome, %t.",
    "%t. The Shadow takes what it is owed.",
    "Peace at last. For you, %t.",
    "%t. A body, cooling. Familiar sight.",
    "%t. Dead is a simple state. Enjoy the simplicity.",
    "%t. That is the sound the living make when they stop.",
    "%t. One more thing that will not get up.",
    "Do not haunt me. I am full, %t.",
    "You had your moment. It was brief, %t.",
    "%t. Complete. Move along.",
    "%t. Warmth leaving. It always looks the same.",
    "%t. I do this well. It is my one talent.",
    "%t. Was it worth it? No. It never is.",
    "The Light did not come for you either, %t.",
    "Sleep well. You will not know the difference, %t.",
    "%t. Finished, and hardly a mark on me.",
    "I have carried worse corpses than yours, %t.",
    "Face down. Fitting, %t.",
    "Silence suits you, %t.",
    "Off to the dark. Say nothing of me, %t.",
    "%t. So the living learn. Briefly.",
    "That is enough out of you, %t.",
    "%t. The end came. It always does.",
    "%t. A neat end. Rare in this world.",
    "Take the rest. You have earned it, %t.",
    "%t. One heartbeat, then none.",
    "%t. The Forsaken remember every one.",
    "That was mercy, though you will not see it that way, %t.",
    "The dark received you. It is not warm, %t.",
    "%t. Empty vessel. Nothing to be done.",
    "You fought. Poorly, but you fought, %t.",
    "%t. Now the truly hard part: staying gone.",
    "%t. Another lesson delivered.",
    "There is no coming back for you. That is the gift, %t.",
    "%t. Quiet. Finally quiet.",
    "%t. The world is one weight lighter.",
    "%t. Nothing left to argue with.",
    "Down, and gratifyingly still, %t.",
    "%t. It is done. It is always done.",
    "Your body was not built for arguments, %t.",
    "Rest, then. It is more than I have, %t.",
    "%t. The whispers are pleased. Rare.",
    "%t. Another ending. My specialty.",
    "You will rot properly. Lucky, %t.",
    "%t. That is all any of us get.",
    "%t. Cold work, cleanly finished.",
    "%t. The Dark Lady counts them all.",
    "So ends whatever you were, %t.",
    "%t. The dirt claims another.",
    "%t. Done. Say nothing more.",
    "Rest, %t. You have earned that much.",
    "/em looks down at the body without expression",
    "Goodbye, %t.",
    "/em steps over the corpse without slowing",
    "Sleep, %t. Truly sleep. I envy you.",
    "/em makes a small, dismissive gesture over the dead",
}

RPVox_LINES["REACT:COMBATSTART"] = {
    "%t. Shadow, attend me.",
    "%t. So it begins.",
    "%t. Must we do this?",
    "Stand aside, or don't. It matters little, %t.",
    "%t. Ah. Trouble found me first.",
    "%t. Very well. Let us be quick.",
    "%t. The whispers wake.",
    "You have chosen poorly, %t.",
    "%t. I was having such a quiet afternoon.",
    "Come then. Show me something new, %t.",
    "%t. Another one who has not heard of me.",
    "%t. This will not take long.",
    "%t. The dark stirs.",
    "Do you know what you are facing? No. They never do, %t.",
    "%t. Fine. Bleed for me.",
    "%t. I did not want this. I am good at it anyway.",
    "Stay back if you value the shape you are in, %t.",
    "Let us see what you are made of. Literally, %t.",
    "%t. The Dark Lady watches. Perform well.",
    "Steel yourself. It will not help, %t.",
    "%t. Trouble. How refreshing.",
    "%t. I have nothing but time and malice.",
    "You want a fight? I have not had a good one in years, %t.",
    "Do try to last, %t.",
    "%t. One moment of peace. That is all I asked.",
    "%t. The Shadow is hungry today.",
    "Approach, then. Everyone does eventually, %t.",
    "%t. Weapons, whispers, whatever is nearest.",
    "%t. This ends one way. It always does.",
    "You smell alive. That is unfortunate for you, %t.",
    "%t. Interrupting my quiet. Rude.",
    "%t. Cast the first stone. I will cast the last.",
    "Let us see how long the living last today, %t.",
    "%t. Here we go again.",
    "Try not to disappoint me, %t.",
    "%t. Oh good. Exercise.",
    "Come here. I will make it educational, %t.",
    "%t. I have killed better before breakfast. I do not eat breakfast.",
    "Your first mistake was noticing me, %t.",
    "The whispers have opinions about you, %t.",
    "%t. Very well. Violence it is.",
    "I would flee, in your position, %t.",
    "%t. Another body for the pile.",
    "Do not make me hurry, %t.",
    "%t. So eager. So brief.",
    "I am already dead. What is your excuse, %t?",
    "%t. Shall we?",
    "%t. The dark leans closer.",
    "%t. Predictable. Proceed anyway.",
    "%t. Something to do at last.",
    "You are wasting the last of your day, %t.",
    "I have patience. You have minutes, %t.",
    "Come on then, warm thing, %t.",
    "That was your last quiet moment. Note it, %t.",
    "The Shadow and I are ready. Are you, %t?",
    "Do you fight, or merely stand there dying slowly, %t?",
    "%t. An interruption. A tedious one.",
    "%t. Careful. I bite back and I do not tire.",
    "You could still walk away. You will not, %t.",
    "Let us find out what you sound like, %t.",
    "%t. So it wants a fight. How quaint.",
    "I will be brief. You will be briefer, %t.",
    "The whispers name you already, %t.",
    "Start whenever you like. I have started, %t.",
    "A pity. You looked almost interesting, %t.",
    "%t. Right. Business.",
    "%t. The living never learn. That is their charm.",
    "Ready when the grave is, %t.",
    "Do not expect mercy. I ran out in Lordaeron, %t.",
    "%t. Something to break. Good.",
    "Face me and be quick about it, %t.",
    "The dark is watching you now, %t.",
    "%t. Fine. Let us settle it.",
    "You will not be the first. Nor the last, %t.",
    "Speak now, while you still can, %t.",
    "%t. Nothing personal. Everything fatal.",
    "Come closer. My reach is poor and my temper worse, %t.",
    "%t. Very well. Bleed on schedule.",
    "%t. I have been looking for a reason.",
    "%t. Another fool with a weapon.",
    "Do we begin, or do we posture, %t?",
    "%t. The Shadow rises. Stand back.",
    "%t. It is going to be one of those days.",
    "There is no version of this you enjoy, %t.",
    "Show me the worst you have, %t.",
    "%t. Trouble again. Always trouble.",
    "%t. The whispers are already counting.",
    "%t. Fine. I will make time.",
    "You picked a corpse to fight. Bold, %t.",
    "%t. To work, then.",
    "%t. I would apologise, but I am not sorry yet.",
    "This will be quick. Or slow. Your choice, %t.",
    "Come on. Disappoint me, %t.",
    "%t. A fight. Wonderful. Truly.",
    "%t. The Dark Lady's work is never finished.",
    "%t. Now then. Let us be unpleasant.",
    "%t. One more thing to put down.",
    "Try to make it last, %t.",
    "%t. Weapons out. Whispers louder.",
    "%t. So be it.",
    "/em fixes %t with a long, colourless stare",
    "You should not have done that, %t.",
    "/em rolls back a sleeve, unhurried",
    "Come along then, %t.",
    "/em chills the air around him noticeably",
}

RPVox_LINES["REACT:COMBATEND"] = {
    "Quiet again.",
    "Is that all?",
    "The whispers settle.",
    "Tedious.",
    "Done. And I am still standing.",
    "The Shadow withdraws. For now.",
    "Peace. Briefly.",
    "That accomplished nothing.",
    "Another mess to leave behind.",
    "Silence. I had almost forgotten it.",
    "Nothing left to kill. Pity.",
    "I am still here. That is the whole trick.",
    "Well. That was hardly worth waking for.",
    "The dead are so much easier to be around.",
    "Catch your breath. I have none to catch.",
    "Over already.",
    "Let us not do that again soon.",
    "My hands have stopped shaking. They never started.",
    "Clean the blade. Or do not. It hardly matters.",
    "And back to the waiting.",
    "That is the trouble with the living. They stop.",
    "Whatever that was, it is finished.",
    "The whispers are disappointed. So am I.",
    "Rest, they say. As if I could.",
    "Nothing follows. Good.",
    "Another fight survived. Survived is a strong word.",
    "The world is quiet and I am still in it.",
    "I felt almost alive for a moment there.",
    "Enough of that.",
    "Back to rotting in peace.",
    "No one left standing but me. As intended.",
    "Tally it and move on.",
    "The dark is patient. So am I.",
    "That will do.",
    "On, then. There is always more.",
    "Finished. Unremarkable.",
    "The bodies can stay where they fell.",
    "Quiet is the only reward there is.",
    "Nothing broken that was not already broken.",
    "Some of that was almost interesting.",
    "The whispers go back to muttering.",
    "I remain. As usual.",
    "A small violence, concluded.",
    "Nothing left to do but continue.",
    "Good. Now leave me be.",
    "Another entry for a very long ledger.",
    "The air smells of endings. I like it.",
    "Rest is wasted on me. Onward.",
    "Was there a point to that?",
    "Still upright. Still cold.",
    "The living have stopped complaining. Finally.",
    "That is settled, then.",
    "Nothing more to break here.",
    "The Shadow sleeps. Briefly.",
    "Silence. Better company than most.",
    "Not a scratch worth mentioning.",
    "Well. Back to my own thoughts. Unfortunately.",
    "It ends as it always ends.",
    "Nothing gained. Nothing much lost.",
    "That is enough excitement for a dead man.",
    "The quiet returns. It never stays.",
    "So much for that.",
    "One more thing survived.",
    "Peace, for whatever it is worth.",
    "The whispers want more. They always want more.",
    "Done bleeding, or done fighting. Both.",
    "Onwards, then, to the next tedium.",
    "Nothing here worth remembering.",
    "I have stopped. That is nearly rest.",
    "A brief unpleasantness, resolved.",
    "The dark settles back into place.",
    "That took longer than it should have.",
    "The dead are quiet. The living should try it.",
    "Still standing, still cold, still here.",
    "Better. Quieter.",
    "That is the end of that noise.",
    "The field is mine. It is not much of a prize.",
    "Back to whatever I was doing.",
    "Nothing follows me. Good.",
    "That was almost worth the trouble.",
    "Finished, and no worse than before.",
    "Now the silence. Now the thinking. Unfortunate.",
    "The Dark Lady's work continues elsewhere.",
    "So it goes.",
    "One less problem. Ten thousand remain.",
    "Quiet enough to hear myself rot.",
    "That is done. Nothing else is.",
    "The whispers rest. I do not.",
    "I have survived smaller things worse.",
    "Wipe it clean and move on.",
    "Nothing more to say about that.",
    "The living scatter. Sensible.",
    "Enough. On with it.",
    "Cold work, finished cold.",
    "Not dead. Again. Remarkable.",
    "The fight leaves. The rot stays.",
    "A pause before the next one.",
    "Nothing broken. Nothing mended.",
    "So. Where was I.",
    "Back to the long waiting.",
    "/em straightens his robes with cold precision",
    "/em surveys the bodies without satisfaction",
    "/em wipes something dark from his hands",
    "/em exhales out of old habit",
}

RPVox_LINES["REACT:INTERRUPTED"] = {
    "Silence me and you only delay it, %t.",
    "%t. Rude.",
    "%t. The Shadow does not forget interruptions.",
    "You will regret that, %t.",
    "Do you think that stops me, %t?",
    "%t. I was speaking.",
    "That was hard-won knowledge you just spoiled, %t.",
    "%t. Clever. Once.",
    "You have bought yourself a second. Spend it well, %t.",
    "%t. The words scatter. I will gather them.",
    "%t. Interrupt me again. Please.",
    "%t. How very tiresome.",
    "You cannot silence what is already dead, %t.",
    "That will cost you more than it cost me, %t.",
    "My tongue, not yours, %t.",
    "%t. A shame. It was going to be beautiful.",
    "%t. The whispers do not appreciate being cut short.",
    "%t. Fine. The slow way, then.",
    "You only postponed the inevitable, %t.",
    "%t. I have all the time the grave gave me.",
    "Noted. Filed. You will pay for it later, %t.",
    "Try that when I am not being polite, %t.",
    "%t. The Shadow remembers. So do I.",
    "%t. Broken syllables. Nothing more.",
    "%t. Was that meant to hurt?",
    "You silenced a dead man. Congratulations, %t.",
    "%t. Again, then. From the beginning.",
    "That is twice you have annoyed me, %t.",
    "%t. Words fail. Hands rarely do.",
    "%t. Patience. I have nothing but.",
    "You know what I am about to do next, %t.",
    "Every interruption lengthens your suffering, %t.",
    "Cut me off again and I will improvise, %t.",
    "%t. A pause. Not a stop.",
    "You should not have done that, %t.",
    "%t. Charming. Do it again.",
    "The sentence was going somewhere unpleasant. For you, %t.",
    "You have delayed a dead man. Impressive, %t.",
    "My concentration is older than your grandmother, %t.",
    "%t. Fine. No more words, then.",
    "%t. That is the third time. I am counting.",
    "%t. A stutter. Nothing more.",
    "You cannot unhear what I have already said, %t.",
    "%t. Interruptions are a living habit. Drop it.",
    "%t. Very well. We do this in silence.",
    "%t. The whispers finish what I start.",
    "You knocked the words loose. They will crawl back, %t.",
    "Do that again and see what answers, %t.",
    "So you have hands. Congratulations, %t.",
    "%t. That accomplished a moment. One.",
    "%t. The spell waits. So do I.",
    "You bought a breath. It was not yours to keep, %t.",
    "%t. Enough. Let me work.",
    "%t. I have been silenced by better and buried them.",
    "Timing. I will give you that much, %t.",
    "The dark does not need my permission. Or yours, %t.",
    "Now I am irritated. That is worse for you, %t.",
    "Try silence on something that breathes, %t.",
    "%t. Rude, and futile. My least favourite combination.",
    "%t. A moment stolen. I keep receipts.",
    "%t. The words are still in me. They fester.",
    "Was that your plan? All of it, %t?",
    "You interrupted a prayer. Bold, %t.",
    "%t. Fine. I will simply repeat myself.",
    "%t. Nothing lost but patience.",
    "%t. The Shadow finds another way in.",
    "%t. Silence changes nothing. It never has.",
    "That is going to cost you a limb, eventually, %t.",
    "%t. A wasted second for both of us.",
    "The whispers are laughing at you, %t.",
    "So you have learned one trick, %t.",
    "%t. Interrupted, not defeated. Learn the difference.",
    "Say that again with your hands off my throat, %t.",
    "%t. Very well. Louder, then.",
    "You cannot stop what is already spoken elsewhere, %t.",
    "%t. That was almost clever.",
    "I will remember this when you are on the ground, %t.",
    "%t. The dark is not so easily hushed.",
    "%t. Fine. I have other means.",
    "%t. One interruption. A thousand consequences.",
    "You silenced the priest. The corpse remains, %t.",
    "Every second you buy is spent poorly, %t.",
    "That word was going to end you, %t.",
    "Do you feel accomplished, %t?",
    "%t. I will finish it. I always finish it.",
    "%t. The Shadow does not stutter for long.",
    "You have annoyed something patient, %t.",
    "Try again. I have nothing else to do, %t.",
    "%t. A pause in a very long sentence.",
    "%t. That is the sound of nothing changing.",
    "I have been interrupted by death itself. You are less, %t.",
    "%t. The whispers will speak for me.",
    "%t. Fine. We will do it the ugly way.",
    "%t. Postponed, not prevented.",
    "Do that once more. I want the excuse, %t.",
    "%t. The words return. They always return.",
    "You cannot outlast a dead man's patience, %t.",
    "%t. Silence me. See how long it holds.",
    "%t. That will be remembered. Everything is.",
    "%t. Very well. Where was I.",
    "That was rude, %t.",
    "/em glares, jaw tight",
    "You will regret that, %t.",
    "/em bites off the ruined syllable",
}

RPVox_LINES["REACT:LEVELUP"] = {
    "Stronger. For whatever that is worth.",
    "The dead can still learn. Who knew.",
    "Another step away from what I was.",
    "I improve. The world does not.",
    "More power. The same hunger.",
    "/em flexes a hand, testing something newly remembered",
    "The Shadow rewards persistence.",
    "Better at this than I ever was at living.",
    "[grim] Growing stronger for a war I did not choose.",
    "[weary] More strength. More weight to carry.",
    "Whatever I am becoming, it is working.",
    "Noted. Onward.",
}

RPVox_LINES["REACT:FALLING"] = {
    "The ground and I disagree about pace.",
    "/em lands badly and straightens with an audible click",
    "Bones. Always the bones.",
    "That is a stupid way to be hurt.",
    "Gravity: the one thing more patient than me.",
    "I have fallen from worse.",
    "Nothing broken that was not already loose.",
    "/em brushes the dirt off without expression",
    "[weary] Everything hurts. This is merely new.",
    "Down is easy. Up is the problem.",
}

RPVox_LINES["REACT:DROWNING"] = {
    "I do not need the air. I resent the reminder.",
    "/em thrashes, more irritated than afraid",
    "Water. The one thing I cannot intimidate.",
    "Corpses float. Eventually.",
    "This body forgets it does not breathe.",
    "Drowning twice would be careless.",
    "[grim] The deep does not care what I am.",
    "Out. Out. Out.",
}

RPVox_LINES["REACT:DURABILITY"] = {
    "This armour has given all it had.",
    "/em examines a split seam with distaste",
    "Falling apart. The armour too.",
    "Held together with thread and habit.",
    "I should see a smith. I will not.",
    "Everything I wear is as ruined as I am.",
    "[weary] Another thing that needs mending.",
    "It will hold. It always nearly holds.",
}

-- Idle --------------------------------------------------------------------

RPVox_LINES["IDLE:MOUNT"] = {
    "Ride, then.",
    "/em settles into the saddle without a sound",
    "The beast does not like me. Sensible.",
    "Faster than walking. Barely worth the trouble.",
    "Even the horses know what I am.",
    "[weary] More miles. Always more miles.",
    "Somewhere else, then. Somewhere always else.",
    "/em takes the reins in cold hands",
}

RPVox_LINES["IDLE:QUESTACCEPT"] = {
    "Very well. I will see it done.",
    "/em takes the task without enthusiasm",
    "Another errand for the dead.",
    "You want it done properly. Hence me.",
    "I will attend to it.",
    "Say no more. It is arranged.",
    "The Forsaken do not refuse useful work.",
    "Consider it already finished.",
    "I have nothing but time. Speak.",
    "Fine. Where am I going?",
}

RPVox_LINES["IDLE:QUEST"] = {
    "Done. Pay me and say nothing.",
    "/em hands over the work without ceremony",
    "Errands. The dead run errands now.",
    "Consider it finished.",
    "You wanted it done. It is done.",
    "[grim] Another small service to a world that owes me.",
    "Take it. I want nothing but the coin.",
    "/em accepts the payment with a curt nod",
}

RPVox_LINES["IDLE:DISCOVERY"] = {
    "I have not stood here before.",
    "/em surveys the ground with faint suspicion",
    "New country. Same rot underneath.",
    "Somewhere else to be unwelcome.",
    "The living built this. It shows.",
    "[grim] Another place that will forget me.",
    "Worth remembering. Briefly.",
    "So. This is here.",
}

RPVox_LINES["IDLE:EAT"] = {
    "Habit, mostly. I taste nothing.",
    "The body still expects to be fed. Strange.",
    "I remember when this was a pleasure.",
    "Chewing. What a ridiculous custom.",
    "Fuel for a furnace that went out years ago.",
    "It sits in me like gravel.",
    "I eat because they stare when I do not.",
    "Ash and memory. Mostly ash.",
}

RPVox_LINES["IDLE:DRINK"] = {
    "It does not warm me. Nothing does.",
    "Dust in the throat. Always dust.",
    "To absent friends. All of them.",
    "I drink to remember. It never works.",
    "Cold going down. Cold everywhere else.",
    "The dead drink out of nostalgia.",
    "A toast to Lordaeron. What is left of it.",
    "It passes through. That is all it does.",
}

RPVox_LINES["IDLE:HEALTHSTONE"] = {
    "Patchwork, holding patchwork together.",
    "Hold still, you miserable carcass.",
    "That will do. For now.",
    "Stitched, bound, and standing.",
    "One more repair on a body long past repairing.",
    "The wound closes badly. They all do.",
    "Better. Marginally.",
}

RPVox_LINES["IDLE:MANAPOTION"] = {
    "The Shadow demands its tithe.",
    "Bitter. Good.",
    "More. There is never enough.",
    "Fuel for the whispers.",
    "It burns going down. I take that as progress.",
    "The dark drinks first. I get what is left.",
}

RPVox_LINES["IDLE:FISHING"] = {
    "The dead have nothing but time.",
    "Patience is easy when you cannot age.",
    "Something down there is as cold as I am.",
    "I could stand here for a century. I may.",
    "The water does not mind what I am.",
    "Quiet work. My favourite kind.",
}

RPVox_LINES["IDLE:MINING"] = {
    "The earth gives up its dead and its metal alike.",
    "Stone does not flinch from me. I like stone.",
    "Down here, everyone is pale.",
    "Dig deep enough and you find only silence.",
    "Cold rock, cold hands. We understand each other.",
    "The mountain keeps its secrets. So do I.",
}

RPVox_LINES["IDLE:HERBALISM"] = {
    "Growing things recoil from my hands.",
    "It withers regardless. I merely hurry it.",
    "Even weeds get to live. Unfair, isn't it.",
    "For the poison, not the posy.",
    "Green things and I have never agreed.",
    "It dies in my grip. Everything does.",
}

RPVox_LINES["IDLE:SKINNING"] = {
    "Skin comes away so easily. I would know.",
    "Waste nothing. The Forsaken can afford to waste nothing.",
    "Careful work. I have the hands for it.",
    "It felt nothing. Neither do I.",
    "A clean cut. Respect the material.",
    "I have seen this done from the other side.",
}

RPVox_LINES["IDLE:CRAFT:Alchemy"] = {
    "Every cure is a poison that changed its mind.",
    "The Apothecarium taught me this much.",
    "Measure twice. The dead have no second chances... well.",
    "It bubbles. That is usually good.",
    "One drop too many and it becomes a weapon. Tempting.",
}

RPVox_LINES["IDLE:CRAFT:Blacksmithing"] = {
    "The forge gives no warmth to me. Only light.",
    "Fold it, beat it, fold it again. Like the Scourge did to me.",
    "Steel is honest. It breaks where you expect.",
    "My hands do not blister. Convenient.",
    "Hammer, heat, patience. I have two of the three.",
}

RPVox_LINES["IDLE:CRAFT:Cooking"] = {
    "I cook from memory. I cannot taste a thing.",
    "Is this how it is meant to smell? No matter.",
    "Someone once told me I had a gift for this. I forget who.",
    "It is edible. Probably.",
    "Feeding the living. A strange charity.",
}

RPVox_LINES["IDLE:CRAFT:Enchanting"] = {
    "Unmake it, and keep what whispers.",
    "There is power in ruined things. I am proof.",
    "Dust and intent. That is all magic ever was.",
    "The threads remember what the cloth forgot.",
    "Break it properly and it thanks you.",
}

RPVox_LINES["IDLE:CRAFT:Engineering"] = {
    "If it explodes, I lose very little.",
    "Gears do not judge. Gears do not flinch.",
    "Goblin schematics. What could go wrong.",
    "A body is only a machine that stopped. This one won't.",
    "Tighten it until something complains.",
}

RPVox_LINES["IDLE:CRAFT:First Aid"] = {
    "Bind it tightly. The flesh will not knit on its own.",
    "I have grown very good at holding bodies together.",
    "Hold still. This helps you more than it ever helped me.",
    "Cloth and prayer. Mostly cloth.",
    "I have wrapped worse. Far worse.",
}

RPVox_LINES["IDLE:CRAFT:Jewelcrafting"] = {
    "Cold, bright, and perfectly dead. Beautiful.",
    "Stones keep their shine. Nothing else does.",
    "A facet for every lie a living thing tells.",
    "I like things that do not rot.",
    "Patience and a steady hand. I have both, permanently.",
}

RPVox_LINES["IDLE:CRAFT:Leatherworking"] = {
    "Cured hide outlasts the beast. And the man.",
    "I know precisely how skin behaves.",
    "Stitch by stitch. As I was.",
    "Waste nothing. That is the Forsaken way.",
    "It wears better than what I am wearing.",
}

RPVox_LINES["IDLE:CRAFT:Tailoring"] = {
    "A stitch here. A stitch there. I know the work intimately.",
    "Thread through cloth, thread through flesh -- the hand is the same.",
    "It should hang well on a frame this thin.",
    "Black suits me. It always did.",
    "Neat seams. I have had practice on myself.",
}

RPVox_LINES["IDLE:CRAFT:Smelting"] = {
    "Burn away the impurity. Would that it worked on me.",
    "Ore into metal. Corpse into soldier. The same trick.",
    "The fire holds no fear for me now.",
    "What survives the flame is worth keeping.",
    "Slag and metal. Most things separate that cleanly.",
}
