-- RPVox -- Hunter class pack
--
-- Voice: a Sin'dorei noblewoman of Silvermoon who treats a battlefield as a
-- badly organised court. Imperious, immaculate, genuinely lethal. She is
-- offended by dust, blood, familiarity and bad manners, in roughly that order.
-- The only creature she is soft with is her beast.
--
-- Single voice, no moods yet (as with Warrior). Mood packs can be added later
-- scoped with class = "HUNTER".

RPVox_CLASSES.HUNTER = {
    name = "Hunter",
    spells = {
        { spell = "Auto Shot",             icon = "Interface\\Icons\\INV_Weapon_Bow_07",            chance = 10 },
        { spell = "Hunter's Mark",         icon = "Interface\\Icons\\Ability_Hunter_SniperShot",    chance = 10 },
        { spell = "Arcane Shot",           icon = "Interface\\Icons\\Ability_ImpalingBolt",         chance = 10 },
        { spell = "Steady Shot",           icon = "Interface\\Icons\\Ability_Hunter_SteadyShot",    chance = 10 },
        { spell = "Aimed Shot",            icon = "Interface\\Icons\\INV_Spear_07",                 chance = 10 },
        { spell = "Multi-Shot",            icon = "Interface\\Icons\\Ability_UpgradeMoonGlaive",    chance = 10 },
        { spell = "Serpent Sting",         icon = "Interface\\Icons\\Ability_Poisons",              chance = 10 },
        { spell = "Concussive Shot",       icon = "Interface\\Icons\\Spell_Frost_Stun",             chance = 10 },
        { spell = "Wing Clip",             icon = "Interface\\Icons\\Ability_Rogue_Trip",           chance = 10 },
        { spell = "Raptor Strike",         icon = "Interface\\Icons\\Ability_MeleeDamage",          chance = 10 },
        { spell = "Mongoose Bite",         icon = "Interface\\Icons\\Ability_Hunter_SwiftStrike",   chance = 10 },
        { spell = "Volley",                icon = "Interface\\Icons\\Ability_Marksmanship",         chance = 10 },
        { spell = "Rapid Fire",            icon = "Interface\\Icons\\Ability_Hunter_RunningShot",   chance = 10 },
        { spell = "Freezing Trap",         icon = "Interface\\Icons\\Spell_Frost_ChainsOfIce",      chance = 10 },
        { spell = "Explosive Trap",        icon = "Interface\\Icons\\Spell_Fire_SelfDestruct",      chance = 10 },
        { spell = "Feign Death",           icon = "Interface\\Icons\\Ability_Rogue_FeignDeath",     chance = 10 },
        { spell = "Disengage",             icon = "Interface\\Icons\\Ability_Rogue_Feint",          chance = 10 },
        { spell = "Misdirection",          icon = "Interface\\Icons\\Ability_Hunter_Misdirection",  chance = 10 },
        { spell = "Bestial Wrath",         icon = "Interface\\Icons\\Ability_Druid_FerociousBite",  chance = 10 },
        { spell = "Intimidation",          icon = "Interface\\Icons\\Ability_Devour",               chance = 10 },
        { spell = "Call Pet",              icon = "Interface\\Icons\\Ability_Hunter_BeastCall",     chance = 10 },
        { spell = "Revive Pet",            icon = "Interface\\Icons\\Ability_Hunter_BeastSoothe",   chance = 10 },
        { spell = "Mend Pet",              icon = "Interface\\Icons\\Ability_Hunter_MendPet",       chance = 10 },
        { spell = "Feed Pet",              icon = "Interface\\Icons\\Ability_Hunter_BeastTraining", chance = 10 },
        { spell = "Aspect of the Hawk",    icon = "Interface\\Icons\\Spell_Nature_RavenForm",       chance = 10 },
        { spell = "Aspect of the Cheetah", icon = "Interface\\Icons\\Ability_Mount_JungleTiger",    chance = 10 },
        { spell = "Arcane Torrent",        icon = "Interface\\Icons\\Spell_Shadow_Teleport",        chance = 10 },
    },
    lines = {

        -- Abilities -----------------------------------------------------

        ["SPELL:Hunter's Mark"] = {
            "%t. You are on the list now.",
            "Marked. Do try to be interesting, %t.",
            "%t. I have decided you matter. Briefly.",
            "Someone write down the name. %t.",
            "%t. Consider yourself invited.",
            "/em points a gloved finger and does not lower it",
            "%t. There. Now everybody can see you.",
            "You have my attention, %t. Few survive it.",
            "%t. I do hate losing track of a guest.",
            "Stand where the light is best, %t.",
            "/em looks a target over the way one looks over a menu",
            "%t. Yes. That one. The loud one.",
            "%t. Marked, measured, and mine.",
            "Do not wander off, %t. It would be rude.",
        },

        ["SPELL:Auto Shot"] = {
            "%t. Again. And again.",
            "/em looses another arrow without looking up",
            "%t. This is the tedious part.",
            "Hold still, %t. You are spoiling the line of it.",
            "%t. Somebody will have to collect all these.",
            "%t. I could do this all afternoon. I may have to.",
            "/em fires with the patience of a woman waiting on a servant",
            "%t. Still upright? How stubborn.",
        },

        ["SPELL:Arcane Shot"] = {
            "%t. A little sparkle. It suits you.",
            "%t. Something bright, for the occasion.",
            "That was the polite one, %t.",
            "%t. Quel'Thalas sends its regards.",
            "/em flicks an arrow alight with a bored gesture",
            "%t. Do you feel that? That is bleeding.",
            "%t. Even my warning shots are better dressed than you.",
            "A touch of colour, %t. You were so drab.",
            "%t. I hardly aimed. Imagine if I had.",
            "Hold that pose, %t. It flatters the wound.",
            "%t. Consider that an opening remark.",
            "/em spends magic on an arrow the way she spends everything: freely",
        },

        ["SPELL:Steady Shot"] = {
            "%t. Slowly. Properly. Once.",
            "%t. Rushing is for infantry.",
            "/em draws, breathes, and lets the string go without hurry",
            "%t. There is no prize for haste.",
            "One does not hurry a thing worth doing, %t.",
            "%t. Watch the form. You may never see it again.",
            "%t. Every finger exactly where it belongs.",
            "%t. Precision is a courtesy. You are welcome.",
            "Do not flinch, %t. It spoils the picture.",
            "%t. I was taught by people who charged a great deal.",
            "/em holds the draw a moment longer than necessary, for effect",
            "%t. Steady. Steady. There.",
        },

        ["SPELL:Aimed Shot"] = {
            "%t. Hold very still. This one is for the wall.",
            "%t. I have chosen exactly where.",
            "/em takes her time, because she can",
            "%t. A long breath. A short life.",
            "%t. This is the shot people used to pay to watch.",
            "Chin up, %t. Show me the throat.",
            "%t. I have been aiming since you started talking.",
            "%t. There is a right way to do this. Observe.",
            "%t. One arrow. One story.",
            "%t. Do not blink. You will miss your own ending.",
            "/em lines up the shot with the calm of a woman ordering dessert",
            "%t. I never miss twice.",
        },

        ["SPELL:Multi-Shot"] = {
            "%t. And your friends. And their friends.",
            "%t. Everyone gets one. I am generous.",
            "/em looses three arrows in the time it takes to sigh",
            "%t. Do not crowd. There is enough for all.",
            "%t. Queue properly, please.",
            "%t. I dislike repeating myself, so I did it all at once.",
            "%t. A gift each. Do not thank me.",
            "%t. You came in a group. How thoughtful.",
            "/em fans the string like a hand of cards",
            "%t. Share nicely.",
            "%t. Three at once. Efficiency is elegant.",
            "%t. I do hate an uneven number of guests.",
        },

        ["SPELL:Serpent Sting"] = {
            "%t. Something for later.",
            "%t. It gets worse. That is the point.",
            "/em wipes the arrowhead clean afterwards, not before",
            "%t. Do sit down. This takes a while.",
            "%t. A slow gift. The best kind.",
            "%t. You will be thinking of me all evening.",
            "Poison is only patience, %t.",
            "%t. I did warn you. Somewhere. Probably.",
            "%t. Green does not suit you either.",
            "/em selects a phial with the care of a woman choosing perfume",
            "%t. It will find its own way to your heart.",
            "%t. Sweat it out if you like. It will not help.",
        },

        ["SPELL:Concussive Shot"] = {
            "%t. Stay.",
            "%t. We are not finished talking.",
            "%t. Where exactly did you think you were going?",
            "/em pins a fleeing shadow to the ground with one arrow",
            "%t. Nobody leaves before I do.",
            "%t. Sit. Down.",
            "%t. Running is so undignified.",
            "%t. The door is not for you.",
            "%t. I did not dismiss you.",
            "%t. Slow down and enjoy your last few steps.",
        },

        ["SPELL:Wing Clip"] = {
            "%t. There. Now we walk at my pace.",
            "%t. A hamstring is such a small thing to lose.",
            "/em takes a knee out from under someone without breaking eye contact",
            "%t. Limping suits your manners.",
            "%t. I do not chase. I decline to.",
            "%t. Stay close. I am not finished.",
            "%t. You were leaving. You are not now.",
            "%t. Hobble prettily.",
        },

        ["SPELL:Raptor Strike"] = {
            "%t. Yes, I do this part myself.",
            "%t. Close enough to smell you. Unfortunate.",
            "/em strikes with a blade that has never once been unpolished",
            "%t. Do not touch. Ever.",
            "%t. I keep my hands clean. This will not.",
            "%t. Even at arm's length I am better than you.",
            "%t. That was for standing too near.",
            "%t. Manners cost nothing. Bad ones cost that.",
            "/em opens a throat and steps back so as not to be splashed",
            "%t. I did not want to do this personally.",
        },

        ["SPELL:Mongoose Bite"] = {
            "%t. Never touch a lady's bow.",
            "%t. That was rude, and this is ruder.",
            "/em answers a blow before the blow has quite finished",
            "%t. Try that again. I dare you to try that again.",
            "%t. I felt that. Now you will.",
            "%t. You have made this personal.",
            "%t. Reflex, darling. Nothing personal. Mostly.",
            "%t. Strike me and I strike back, better dressed.",
        },

        ["SPELL:Volley"] = {
            "%t. The sky is mine for a moment.",
            "/em fills the air with arrows and steps back to admire it",
            "%t. Everyone down there. Yes, all of you.",
            "%t. Rain. From me, personally.",
            "%t. Look up. Go on, look up.",
            "/em empties a quiver into the clouds and lets gravity finish",
            "%t. I have arrows to spare and no patience at all.",
            "%t. Somebody count them for me afterwards.",
        },

        ["SPELL:Rapid Fire"] = {
            "%t. I am in a hurry, so this will be quick.",
            "/em draws faster than is entirely polite",
            "%t. Do keep up.",
            "%t. I have somewhere better to be.",
            "%t. Faster. Yes. Like that.",
            "%t. This is what I look like when I am impatient.",
            "/em nocks and looses and nocks again without pause",
            "%t. Enough of the slow version.",
        },

        ["SPELL:Freezing Trap"] = {
            "%t. Stand there and think about what you have done.",
            "/em sets a trap with two fingers, like laying a place setting",
            "%t. A moment of quiet, please.",
            "%t. You are excused from the conversation.",
            "%t. Do not thaw until I say.",
            "%t. Cold, is it not? Reflect.",
            "%t. I will deal with you when I have finished.",
            "%t. Wait your turn.",
        },

        ["SPELL:Explosive Trap"] = {
            "%t. Mind the floor.",
            "/em walks away from something that is about to be very loud",
            "%t. Nobody watches where they step any more.",
            "%t. That is what comes of following me.",
            "%t. A little party underfoot.",
            "%t. Boots ruined. Serves you right.",
            "%t. I redecorate as I go.",
        },

        ["SPELL:Feign Death"] = {
            "/em collapses gracefully, having chosen the spot in advance",
            "/em lies perfectly still with one arm arranged just so",
            "%t. Oh no. How terrible. I am quite dead.",
            "%t. Go on, then. Grieve.",
            "/em dies beautifully and entirely on purpose",
            "%t. You are not worth the effort of a real fight.",
            "/em arranges her hair before hitting the ground",
            "%t. Do carry on without me.",
        },

        ["SPELL:Disengage"] = {
            "/em springs backwards and lands without a sound",
            "%t. Do not come closer. I mean it.",
            "%t. I prefer this distance. It flatters us both.",
            "/em puts a suitable amount of ground between herself and the help",
            "%t. That is quite near enough.",
            "%t. You were breathing on me.",
        },

        ["SPELL:Misdirection"] = {
            "%t. Speak to her. I am busy.",
            "/em gestures politely toward somebody else",
            "%t. My associate will see you now.",
            "%t. I have people for this.",
            "%t. Not me, dear. Her.",
        },

        ["SPELL:Bestial Wrath"] = {
            "%t. Now you have upset her.",
            "/em lets the leash go entirely",
            "%t. I am the restrained one, you understand.",
            "%t. Run. She does like it when they run.",
            "%t. I did try to be civil.",
            "%t. Whatever happens next is not my doing.",
            "/em steps aside and lets something older than manners past",
        },

        ["SPELL:Intimidation"] = {
            "%t. Down.",
            "/em watches a grown man put on his back and does not intervene",
            "%t. Kneel, or be knelt.",
            "%t. Ah. Now you are listening.",
            "%t. Everyone bows eventually.",
        },

        ["SPELL:Call Pet"] = {
            "/em whistles once, in a key that carries",
            "Come along, darling.",
            "/em snaps her fingers and something large answers",
            "Do try to keep up.",
            "There you are. Heel.",
            "/em greets her companion warmly and nobody else at all",
        },

        ["SPELL:Revive Pet"] = {
            "Get up. We are not done.",
            "/em kneels in the dirt, which she would do for no one else",
            "You are not allowed to leave me.",
            "Up. Up. Good girl.",
            "/em breathes life back into a beast with her jaw set",
            "I have lost enough. Not you.",
        },

        ["SPELL:Mend Pet"] = {
            "/em murmurs to her companion in the old tongue",
            "Hold still, darling. Let me see it.",
            "Who did this to you? Point.",
            "/em fusses over her beast with more tenderness than she shows anyone",
            "There. Good. You are worth more than all of them.",
            "You are the only one here with manners.",
            "/em cleans a wound with a silk handkerchief she will not miss",
            "Shh. I have you.",
            "%t did that to you. Noted.",
        },

        ["SPELL:Feed Pet"] = {
            "/em produces food from a bag that should not contain it",
            "Eat. You have earned it.",
            "The best cut, naturally.",
            "/em feeds her companion before she feeds herself",
            "Slowly. It is not a race.",
        },

        ["SPELL:Aspect of the Hawk"] = {
            "/em rolls her shoulders and the world comes closer",
            "Better. Now I can see who is worth shooting.",
            "/em settles into a stance taught in Silvermoon before the fall",
            "Everything sharpens. Including my mood.",
            "/em lifts her chin and looks a very long way",
        },

        ["SPELL:Aspect of the Cheetah"] = {
            "/em picks up her pace without ever seeming hurried",
            "I am not running. I am arriving early.",
            "/em moves like weather across a field",
            "One does not walk when one can glide.",
            "Try to keep up, darling.",
        },

        ["SPELL:Arcane Torrent"] = {
            "%t. Thank you. I was running low.",
            "/em drinks the magic out of the air as though it were offered on a tray",
            "%t. Do not look at me like that. Everyone does it.",
            "%t. It is not a weakness. It is a taste.",
            "%t. I will take that, thank you.",
            "/em takes what she needs and does not apologise",
        },

        -- Reactions -----------------------------------------------------

        ["REACT:LOWHEALTH"] = {
            "%t. This was clean an hour ago.",
            "%t. Do you have any idea what this cost?",
            "%t. That is my blood. Mine.",
            "/em presses a hand to her side and looks furious about it",
            "%t. I am going to be very unpleasant about this.",
            "%t. You have made me untidy.",
            "%t. I have never bled in front of anyone before.",
            "%t. Enough. This has stopped being amusing.",
            "%t. Somebody will answer for this. It will be you.",
            "/em spits blood and is offended by the taste",
            "%t. Do not think this makes us equals.",
            "%t. I am not used to this. I dislike it enormously.",
            "%t. You have ruined the line of this coat.",
            "/em laughs, and it comes out thinner than she intended",
            "%t. I have been hurt by better.",
            "%t. Stop. Stop that immediately.",
            "%t. I said do not touch me.",
            "%t. This is the part where I stop being polite.",
            "%t. My grandmother held a wall against worse than you.",
            "/em straightens up when it would be easier not to",
            "%t. I refuse to fall over in this dust.",
            "%t. Not here. Not to something like you.",
            "%t. I am still standing, you will notice.",
            "%t. Do you want my rings? Come and take them.",
            "%t. Somebody fetch me a bandage and a better opponent.",
            "/em keeps her chin level out of pure spite",
            "%t. I have survived court dinners worse than this.",
            "%t. You will not be the thing that finishes me.",
            "%t. I am tired, and cross, and still better armed.",
            "/em wipes her mouth and inspects her glove with disgust",
            "%t. This is deeply unfair.",
            "%t. I want you to know I am taking this personally.",
            "%t. My name is older than your village. Remember it.",
            "%t. Very well. No more manners.",
            "/em gives up one careful step and refuses to give a second",
            "%t. That hurt. That actually hurt.",
            "%t. I am revising my opinion of you. Downward.",
            "%t. Do not smile. You have won nothing.",
            "%t. I walked out of a burning city. You are nothing.",
            "/em breathes through her teeth and reaches for another arrow",
        },

        ["REACT:DEATH"] = {
            "%t. Oh, this is humiliating.",
            "%t. Not in the dirt. Anywhere but the dirt.",
            "/em falls with more dignity than the situation deserves",
            "%t. Tell them I was beautiful about it.",
            "%t. I did not agree to this.",
            "%t. My house will hear of this.",
            "/em reaches for her companion and does not quite manage it",
            "%t. See to my beast. She will not understand.",
            "%t. I want a proper funeral. Flowers. Weeping.",
            "%t. Well. You are going to regret being memorable.",
            "/em lets go of the bow last of all",
            "%t. Put out by you, of all things. Absurd.",
            "%t. I was going to be so much more than this.",
            "%t. Do not touch my things.",
            "%t. Is that all? I expected ceremony.",
            "/em collapses like a curtain coming down",
            "%t. I am not finished. I am merely pausing.",
            "%t. This is the worst evening of my life.",
            "%t. You will not remember my face. I will remember yours.",
            "/em closes her eyes with something like exasperation",
            "%t. Nobody saw that. Nobody saw that.",
            "%t. I would rather have died in Silvermoon.",
            "%t. My ring goes home. Somebody see to it.",
            "%t. So this is the ground. I have never spent time down here.",
            "%t. How dreadfully common.",
            "/em dies with her jaw set and her hair somehow perfect",
            "%t. I refuse. I refuse. Oh.",
            "%t. Do not tell the Farstriders. They would enjoy it.",
            "%t. I hope you choke on it.",
            "/em curls her fingers as if closing them around a throat",
            "%t. That was not a fair fight. Nothing ever is.",
            "%t. Wake me when somebody competent arrives.",
            "%t. I have never been this cold. Not even at home.",
            "%t. Very well. You may have the field. Not the story.",
            "/em falls, and takes a long moment to accept it",
            "%t. I would have made a magnificent queen of something.",
            "%t. Do not let her see me like this.",
            "%t. There is dust on my mouth. That is what I object to.",
            "%t. Enjoy it. It will be brief.",
            "/em goes down still trying to draw",
        },

        ["REACT:RESURRECT"] = {
            "/em stands and immediately checks her reflection in a blade",
            "Well. That was undignified.",
            "Nobody speaks of this. Ever.",
            "/em shakes the dust from her coat with theatrical disgust",
            "I have been dead. It is very overrated.",
            "Right. Where was I.",
            "/em retrieves her bow before she retrieves her balance",
            "Somebody will be paying for the cleaning.",
            "Back, and in a temper.",
            "/em rearranges her hair with both hands and considerable feeling",
            "I did not care for that at all.",
            "Do not look at me. Look away.",
            "There. Presentable. Almost.",
            "/em checks that every ring is still on her fingers",
            "The dead are so badly dressed. I did not fit in.",
            "I want a bath. I want three baths.",
            "/em greets her companion first and the world second",
            "You waited. Of course you waited. Good girl.",
            "Nothing has changed. I am merely fashionably late.",
            "/em tests the string and finds it satisfactory",
            "Death is a rumour, and I intend to keep it one.",
            "Say nothing. I can hear you thinking.",
            "/em picks a single leaf from her sleeve as though it were the worst part",
            "One does not stay down. One reschedules.",
            "I have decided that did not happen.",
            "/em rolls a shoulder and winces where nobody can see",
            "Now. Who was responsible.",
            "That is the last time I let anyone get behind me.",
            "/em straightens her collar until it is exactly right",
            "Up, and cross about it.",
            "The world carried on without me. How rude.",
            "/em brushes at a stain that will not come out",
            "I am owed an apology. I am not certain by whom.",
            "Well. Nobody important saw.",
            "/em breathes in and sounds almost grateful",
            "Again, then. From the top.",
            "I have things to finish and a temper to spend.",
            "/em looks at the sky as though it had kept her waiting",
            "Do not fuss. I am perfectly fine.",
            "Vanity brought me back. Do not tell anyone.",
        },

        ["REACT:KILLINGBLOW"] = {
            "%t. There. Was that so difficult?",
            "/em steps over the body without looking down",
            "%t. Somebody move that.",
            "%t. Do not bleed toward me.",
            "%t. I did tell you.",
            "%t. And that is how it is done.",
            "/em retrieves her arrow and wipes it clean",
            "%t. Next.",
            "%t. You were not even a story.",
            "%t. I will not be remembering you.",
            "/em examines a fingernail over the corpse and finds it chipped",
            "%t. That is one fewer person who has seen my face.",
            "%t. A shame. You had potential. Very little of it.",
            "%t. My arrows are worth more than your life. I want that one back.",
            "/em plucks the shaft free and inspects it for damage",
            "%t. Rest. You have earned nothing, but rest anyway.",
            "%t. That was the polite version.",
            "%t. Good girl. Leave some of him.",
            "%t. And they said I was decorative.",
            "/em blows an imaginary speck from the bowstring",
            "%t. I do hope somebody was watching.",
            "%t. One shot, as advertised.",
            "%t. You should have run when I offered.",
            "%t. Now. Who else has an opinion?",
            "/em turns away before the body has finished falling",
            "%t. I am going to need new gloves.",
            "%t. Tell your gods a lady sent you.",
            "%t. Quicker than the conversation would have been.",
            "%t. Beautifully done, if I say so myself.",
            "/em curtseys, very slightly, to nobody",
            "%t. You may go.",
            "%t. Do you know, I did not even use the good arrows.",
            "%t. There is a right way to fall. That was not it.",
            "%t. Poor thing. Wrong field, wrong day, wrong woman.",
            "/em signals her companion off the corpse with two fingers",
            "%t. I shall be dining well tonight regardless.",
            "%t. Nothing personal. Everything personal.",
            "%t. Cross me, and this is the whole of it.",
            "/em steps back from the dark spreading through the grass",
            "%t. Consider the matter closed.",
        },

        ["REACT:COMBATSTART"] = {
            "%t. Oh. We are doing this.",
            "%t. You have chosen a very bad afternoon.",
            "/em unslings her bow with a sigh of pure inconvenience",
            "%t. I was having such a pleasant walk.",
            "%t. Do you know who you are speaking to?",
            "%t. This will be quick and one-sided. Sorry.",
            "%t. Stand where I can see you.",
            "/em takes position as though the field had been arranged for her",
            "%t. I hope you brought somebody competent.",
            "%t. Very well. Amuse me.",
            "%t. Darling. Fetch.",
            "/em whistles once, and something with teeth answers",
            "%t. I do not fight. I conclude.",
            "%t. You are between me and my evening.",
            "%t. Try to be worth the arrows.",
            "/em draws with the unhurried air of a woman who has never lost",
            "%t. I did not dress for this.",
            "%t. How many of you are there? Fine.",
            "%t. Yes, yes. Come along then.",
            "%t. Let us get this over with. I have a dinner.",
            "/em rolls her eyes and nocks an arrow at the same time",
            "%t. Rude. Very rude.",
            "%t. Was that meant to frighten me?",
            "%t. I have been shot at by better.",
            "%t. Do not touch the hair.",
            "/em steps back into the range she prefers, which is all of it",
            "%t. You may begin. I already have.",
            "%t. I was taught manners and archery. Guess which you get.",
            "%t. This is going to be tiresome.",
            "/em sets her feet like a dancer taking position",
            "%t. Say something clever. Quickly.",
            "%t. Right. Chin up. Best foot forward.",
            "%t. I shall try to leave something for the wolves.",
            "%t. You are all very brave and very stupid.",
            "/em sighs the sigh of a woman about to ruin her boots",
            "%t. Good. I was bored.",
            "%t. Please do run. It is prettier that way.",
            "%t. I am going to be so cross about the dust.",
            "/em sends her companion forward with a flick of two fingers",
            "%t. Very well. Court is in session.",
        },

        ["REACT:COMBATEND"] = {
            "/em lowers the bow and immediately checks her sleeves",
            "Well. That is that.",
            "Was anyone watching? Nobody? Typical.",
            "/em shakes out her coat and finds it wanting",
            "I am going to want a very long bath.",
            "Hardly worth the effort.",
            "/em looks for somewhere clean to stand and fails",
            "Good girl. Come away from that.",
            "That is enough excitement for one day.",
            "/em counts her arrows and is annoyed by the total",
            "Somebody owes me a new pair of gloves.",
            "I did warn them. I always warn them.",
            "/em pats her companion and then examines her hand",
            "Nothing broken. Nothing that shows, at least.",
            "Right. Where were we going?",
            "/em breathes out slowly and lets her shoulders come down",
            "I was magnificent. I should like that noted.",
            "Dreadful. Absolutely dreadful people.",
            "/em picks something unpleasant off her boot with an arrow",
            "Never again. Until the next time.",
            "This is why I do not go out.",
            "/em straightens every buckle before she takes a single step",
            "I need a drink, and not water.",
            "A great deal of noise about very little.",
            "/em reties her hair with a short ribbon and no patience",
            "Come along, darling. We are leaving.",
            "It is over. Do stop looking at me.",
            "/em rubs at a mark on her cheek and makes it worse",
            "Some days I miss the city terribly.",
            "Not one of them said please.",
            "/em stows the bow with the care she gives nothing else",
            "There. Order restored.",
            "I shall write this down as a triumph.",
            "/em stands a moment longer than necessary, listening",
            "Quiet again. I do prefer it, whatever I say.",
            "Well fought, darling. You were the better of us.",
            "/em pours a little water for her companion before herself",
            "I want a chair, a fire, and no conversation.",
            "That is the last of them. I counted twice.",
            "/em finally allows herself to look tired",
        },

        ["REACT:INTERRUPTED"] = {
            "%t. Did you just interrupt me?",
            "%t. I was speaking.",
            "/em stares at someone who has just made a serious mistake",
            "%t. Nobody interrupts me. Nobody.",
            "%t. That is the rudest thing anyone has done all week.",
            "%t. Say that again. I want to hear it twice.",
            "/em lowers the bow very slowly, which is worse",
            "%t. Now I am going to take my time.",
            "%t. Oh, you will pay for that little trick.",
            "%t. Wait your turn like everybody else.",
            "/em takes a breath she does not need, entirely for effect",
            "%t. That was very nearly clever.",
            "%t. Fine. We do it the loud way.",
            "%t. You have not stopped me. You have delayed me.",
            "/em resets her stance and does not blink",
            "%t. I was not finished. I am rarely finished.",
            "%t. How many people have you interrupted? How many are alive?",
            "%t. Do not do that again.",
            "%t. I will remember that.",
            "/em bites back something entirely unsuited to her upbringing",
            "%t. Congratulations. You have my full attention.",
            "%t. That is one. You do not get two.",
            "%t. I am counting, and you are on a poor number.",
            "/em flexes her fingers once and begins again",
            "%t. Very well. Nothing pretty this time.",
            "%t. Was that supposed to impress me?",
            "%t. You should not have touched my hands.",
            "%t. I had that beautifully lined up.",
            "/em glares hard enough to be felt across the field",
            "%t. That was rude, and it was cheap.",
            "%t. At home you would have been removed for that.",
            "%t. Again. From the beginning. Because of you.",
            "%t. I hope that was worth it.",
            "%t. You have made this last longer. Well done.",
            "/em draws again with an entirely different expression",
            "%t. Enough games.",
            "%t. Interrupt me once more and I shall make it artistic.",
            "%t. I do not like being made to repeat myself.",
            "%t. That is not how this goes.",
            "/em recovers, exhales, and stops being charming",
        },

        ["REACT:LEVELUP"] = {
            "/em stands a little straighter, as though something has settled",
            "Better. Obviously better.",
            "I am improving. I was already good.",
            "/em looks at her hands as if they belong to somebody slightly finer",
            "There. Did you feel that? No? Never mind.",
            "One does not stay where one started.",
            "/em adjusts to a new sense of her own reach",
            "Every day, more difficult to argue with.",
            "I shall be insufferable by spring.",
            "/em smiles at nothing in particular and means it",
            "Good. Good. Nearly what I intended to be.",
            "Somebody at home should be told.",
            "/em draws to test something and finds it easier than yesterday",
            "I am becoming rather formidable. It suits me.",
            "That is another thing they cannot take.",
            "/em says nothing, and simply looks pleased",
            "Sharper. Steadier. Still beautiful.",
            "The city is gone. I am not. I am growing.",
            "/em nods once, satisfied with herself",
            "Do keep up, darling. I am getting quicker.",
        },

        ["REACT:FALLING"] = {
            "This is not how a lady descends.",
            "/em falls with her arms out and her dignity behind her",
            "Oh, that is a long way down.",
            "Somebody catch me. Anybody. No?",
            "/em plummets, complaining",
            "I did not agree to this.",
            "The ground. Of course. It is always the ground.",
            "/em windmills once, then decides against it",
            "I meant to do that. Obviously.",
            "This is going to hurt and I shall be loud about it.",
            "/em tries very hard to land elegantly",
            "Wait. Wait. Wait.",
            "Not the boots. Please not the boots.",
            "/em drops out of the sky like a very cross bird",
            "Whose idea was that? Mine. Damn.",
            "I have made a serious error.",
            "/em falls silently, refusing to give anyone the satisfaction",
            "Oh no. Oh no, no, no.",
            "Undignified in every possible way.",
            "/em hits the ground and lies still out of embarrassment",
        },

        ["REACT:DROWNING"] = {
            "This water is filthy, and I am in it.",
            "/em thrashes with as much composure as she can manage",
            "Up. Up. Which way is up.",
            "My hair. My hair is ruined.",
            "/em struggles toward a surface she cannot see",
            "Nobody could swim in this.",
            "Air. I should like some air, please.",
            "/em kicks hard and loses a ribbon to the current",
            "Not like this. Not wet.",
            "Somebody. Somebody.",
            "/em claws upward with her jaw clamped shut",
            "I hate water. I have always hated water.",
            "Darling. Darling, help.",
            "/em surfaces just long enough to be furious",
            "This is a stupid way to die.",
            "My bow. Where is my bow.",
            "/em sinks a little and fights back up again",
            "Cold, dark and common. Wonderful.",
            "I refuse to drown. It is beneath me.",
            "/em gasps and takes half a breath of water",
        },

        ["REACT:DURABILITY"] = {
            "This is falling apart. I am falling apart.",
            "/em pokes a finger through a hole that was not there this morning",
            "I cannot be seen like this.",
            "My gear is in tatters. So am I.",
            "/em inspects a broken strap with visible despair",
            "Somebody in this world must know how to mend things.",
            "This was made for me. Made. For me.",
            "/em ties a knot where a buckle used to be, and hates it",
            "Held together with string and pride.",
            "I look like a farmhand. A very well armed farmhand.",
            "/em tries to smooth a dent out of her armour with one thumb",
            "The string is fraying. Everything is fraying.",
            "I need a smith, a tailor, and a strong drink.",
            "/em examines herself and decides not to look again",
            "This will not last another fight. Nor will the coat.",
            "Rags. I am wearing rags with a very good name on them.",
            "/em sighs at the state of absolutely everything",
            "At home there were people for this.",
            "One more scratch and I shall simply sit down.",
            "/em holds a piece of her armour that is no longer attached",
        },

        -- Idle ----------------------------------------------------------

        ["IDLE:EAT"] = {
            "/em eats without letting anything touch her gloves",
            "This is not food. These are provisions.",
            "/em arranges a field meal as though it were a table setting",
            "I ate better than this as a child. Considerably better.",
            "Do not watch me eat.",
            "/em shares the better half with her companion",
            "Salt. Would salt be too much to ask?",
            "One eats to continue. That is all this is.",
            "/em chews politely and looks miserable about it",
            "I dream about pastry. Constantly.",
            "Sit with me, darling. Do not beg. Just sit.",
            "/em lays down a cloth first, because standards",
        },

        ["IDLE:DRINK"] = {
            "/em drinks with her little finger out, from habit",
            "Water. Always water. Never anything worth drinking.",
            "/em grimaces at the taste and drinks it anyway",
            "At home this would have been chilled.",
            "One does miss wine.",
            "/em pours a measure for her companion first",
            "Warm. Of course it is warm.",
            "I shall pretend this is something better.",
            "/em drinks quickly, as though speed improves it",
            "To absent luxuries.",
            "This is what passes for refreshment out here.",
            "/em wipes the rim with a cloth before touching it",
        },

        ["IDLE:MOUNT"] = {
            "/em mounts in one motion, having practised it since childhood",
            "Walking is for people with nowhere to be.",
            "/em settles into the saddle and adjusts her posture twice",
            "Come along. We are expected somewhere.",
            "Sit up straight. Both of us.",
            "/em takes the reins with the ease of a very expensive education",
            "I do like to arrive properly.",
            "/em pats a neck she keeps immaculately groomed",
            "Onward. Try to keep the dust down.",
            "One should never be seen hurrying on foot.",
            "/em rides the way she was taught, which is beautifully",
            "Do keep up, darling.",
        },

        ["IDLE:QUESTACCEPT"] = {
            "Very well. I shall see to it.",
            "/em accepts a task with the air of granting a great favour",
            "You are fortunate I was passing.",
            "I am not an errand girl. But I am here.",
            "/em listens with her head tilted and her patience thinning",
            "Fine. Yes. Consider it handled.",
            "Do not thank me now. Thank me expensively later.",
            "/em takes the parchment with two fingers",
            "One helps. It is expected of people like me.",
            "I shall do this properly, since nobody else will.",
            "/em nods once, which from her is a contract",
            "Point me at it.",
        },

        ["IDLE:SKINNING"] = {
            "/em skins a kill with surprising competence and obvious distaste",
            "This is the part nobody mentions in the songs.",
            "/em holds her sleeve back with one hand while she works",
            "Waste nothing. Even I know that.",
            "I have ruined another pair of gloves.",
            "/em works quickly, breathing through her mouth",
            "It is honest work. That is the kindest thing about it.",
            "Somebody at home would faint to see this.",
            "/em wipes the blade on the grass, not on herself",
            "A good hide is a good hide. I have learned that much.",
            "Do not tell anyone I am good at this.",
            "/em finishes, and immediately wants to wash",
        },

        ["IDLE:FISHING"] = {
            "/em fishes with the posture of a portrait",
            "This is meant to be restful. I am not restful.",
            "/em waits, elegantly, for something stupid to bite",
            "I could buy fish. I could buy a great many fish.",
            "Patience is a virtue I keep for hunting.",
            "/em watches the water and thinks about a city she cannot go back to",
            "The quiet is nice. Do not tell anyone I said so.",
            "/em casts again with far more skill than enthusiasm",
            "Come on, then. Somebody bite.",
            "There is nothing here to shoot. It is unsettling.",
            "/em sits on her folded coat rather than the ground",
            "If this takes much longer I shall simply shoot one.",
        },

        ["IDLE:DISCOVERY"] = {
            "/em stops and looks at a new horizon without saying anything",
            "Oh. That is rather lovely.",
            "Nobody at home has seen this. Only me.",
            "/em commits a view to memory the way she once memorised ballrooms",
            "I shall describe this badly to somebody later.",
            "Well. Worth the walk. Almost.",
            "/em takes one long breath of somewhere entirely new",
            "The world is very large when nobody is announcing you.",
            "I have never been here. Nobody has told me what to think of it.",
            "/em stands at the edge of the map and enjoys herself in private",
            "Look, darling. Look at that.",
            "Beautiful. And full of things that want shooting, no doubt.",
        },
    },
}
