-- RPVox -- Hunter-ValleyGirl class pack
--
-- Voice: song-lyric puns. Every line bends a well-known rock, hip hop or
-- R&B hook into the spell being cast. Kept in the addon rather than in saved
-- variables so it survives reinstalls and can live in version control.

RPVox_CLASSES = RPVox_CLASSES or {}

RPVox_CLASSES.HUNTER_VALLEYGIRL = {
    name = "Hunter-ValleyGirl",
    class = "HUNTER",
    spells = {
        { spell = "Auto Shot",                 icon = "Interface\\Icons\\INV_Weapon_Bow_07",                   chance = 10 },
        { spell = "Hunter's Mark",             icon = "Interface\\Icons\\Ability_Hunter_SniperShot",           chance = 10 },
        { spell = "Arcane Shot",               icon = "Interface\\Icons\\Ability_ImpalingBolt",                chance = 10 },
        { spell = "Steady Shot",               icon = "Interface\\Icons\\Ability_Hunter_SteadyShot",           chance = 10 },
        { spell = "Aimed Shot",                icon = "Interface\\Icons\\INV_Spear_07",                        chance = 10 },
        { spell = "Multi-Shot",                icon = "Interface\\Icons\\Ability_UpgradeMoonGlaive",           chance = 10 },
        { spell = "Volley",                    icon = "Interface\\Icons\\Ability_Marksmanship",                chance = 10 },
        { spell = "Rapid Fire",                icon = "Interface\\Icons\\Ability_Hunter_RunningShot",          chance = 10 },
        { spell = "Kill Command",              icon = "Interface\\Icons\\Ability_Hunter_KillCommand",          chance = 10 },
        { spell = "Silencing Shot",            icon = "Interface\\Icons\\Ability_TheBlackArrow",               chance = 10 },
        { spell = "Scatter Shot",              icon = "Interface\\Icons\\Ability_GolemStormBolt",              chance = 10 },
        { spell = "Distracting Shot",          icon = "Interface\\Icons\\Ability_Rogue_Distract",              chance = 10 },
        { spell = "Concussive Shot",           icon = "Interface\\Icons\\Spell_Frost_Stun",                    chance = 10 },
        { spell = "Serpent Sting",             icon = "Interface\\Icons\\Ability_Poisons",                     chance = 10 },
        { spell = "Scorpid Sting",             icon = "Interface\\Icons\\Ability_Hunter_CriticalShot",         chance = 10 },
        { spell = "Viper Sting",               icon = "Interface\\Icons\\Ability_Hunter_AimedShot",            chance = 10 },
        { spell = "Wyvern Sting",              icon = "Interface\\Icons\\INV_Spear_02",                        chance = 10 },
        { spell = "Raptor Strike",             icon = "Interface\\Icons\\Ability_MeleeDamage",                 chance = 10 },
        { spell = "Mongoose Bite",             icon = "Interface\\Icons\\Ability_Hunter_SwiftStrike",          chance = 10 },
        { spell = "Wing Clip",                 icon = "Interface\\Icons\\Ability_Rogue_Trip",                  chance = 10 },
        { spell = "Counterattack",             icon = "Interface\\Icons\\Ability_Warrior_Challange",           chance = 10 },
        { spell = "Disengage",                 icon = "Interface\\Icons\\Ability_Rogue_Feint",                 chance = 10 },
        { spell = "Deterrence",                icon = "Interface\\Icons\\Ability_Whirlwind",                   chance = 10 },
        { spell = "Readiness",                 icon = "Interface\\Icons\\Spell_Nature_TimeStop",               chance = 10 },
        { spell = "Freezing Trap",             icon = "Interface\\Icons\\Spell_Frost_ChainsOfIce",             chance = 10 },
        { spell = "Explosive Trap",            icon = "Interface\\Icons\\Spell_Fire_SelfDestruct",             chance = 10 },
        { spell = "Immolation Trap",           icon = "Interface\\Icons\\Spell_Fire_FlameShock",               chance = 10 },
        { spell = "Frost Trap",                icon = "Interface\\Icons\\Spell_Frost_FreezingBreath",          chance = 10 },
        { spell = "Snake Trap",                icon = "Interface\\Icons\\Ability_Hunter_SnakeTrap",            chance = 10 },
        { spell = "Flare",                     icon = "Interface\\Icons\\Spell_Fire_Flare",                    chance = 10 },
        { spell = "Feign Death",               icon = "Interface\\Icons\\Ability_Rogue_FeignDeath",            chance = 10 },
        { spell = "Misdirection",              icon = "Interface\\Icons\\Ability_Hunter_Misdirection",         chance = 10 },
        { spell = "Bestial Wrath",             icon = "Interface\\Icons\\Ability_Druid_FerociousBite",         chance = 10 },
        { spell = "Intimidation",              icon = "Interface\\Icons\\Ability_Devour",                      chance = 10 },
        { spell = "Call Pet",                  icon = "Interface\\Icons\\Ability_Hunter_BeastCall",            chance = 10 },
        { spell = "Dismiss Pet",               icon = "Interface\\Icons\\Spell_Nature_SpiritWolf",             chance = 10 },
        { spell = "Revive Pet",                icon = "Interface\\Icons\\Ability_Hunter_BeastSoothe",          chance = 10 },
        { spell = "Mend Pet",                  icon = "Interface\\Icons\\Ability_Hunter_MendPet",              chance = 10 },
        { spell = "Feed Pet",                  icon = "Interface\\Icons\\Ability_Hunter_BeastTraining",        chance = 10 },
        { spell = "Tame Beast",                icon = "Interface\\Icons\\Ability_Hunter_BeastTaming",          chance = 10 },
        { spell = "Beast Lore",                icon = "Interface\\Icons\\Ability_Physical_Taunt",              chance = 10 },
        { spell = "Eyes of the Beast",         icon = "Interface\\Icons\\Ability_EyeOfTheOwl",                 chance = 10 },
        { spell = "Scare Beast",               icon = "Interface\\Icons\\Ability_Druid_Cower",                 chance = 10 },
        { spell = "Aspect of the Hawk",        icon = "Interface\\Icons\\Spell_Nature_RavenForm",              chance = 10 },
        { spell = "Aspect of the Monkey",      icon = "Interface\\Icons\\Ability_Hunter_AspectOfTheMonkey",    chance = 10 },
        { spell = "Aspect of the Cheetah",     icon = "Interface\\Icons\\Ability_Mount_JungleTiger",           chance = 10 },
        { spell = "Aspect of the Pack",        icon = "Interface\\Icons\\Ability_Mount_WhiteTiger",            chance = 10 },
        { spell = "Aspect of the Wild",        icon = "Interface\\Icons\\Spell_Nature_ProtectionformNature",   chance = 10 },
        { spell = "Aspect of the Viper",       icon = "Interface\\Icons\\Ability_Hunter_AspectOfTheViper",     chance = 10 },
        { spell = "Aspect of the Beast",       icon = "Interface\\Icons\\Ability_Mount_PinkTiger",             chance = 10 },
        { spell = "Trueshot Aura",             icon = "Interface\\Icons\\Ability_TrueShot",                    chance = 10 },
        { spell = "Eagle Eye",                 icon = "Interface\\Icons\\Ability_Hunter_EagleEye",             chance = 10 },
        { spell = "Track Beasts",              icon = "Interface\\Icons\\Ability_Tracking",                    chance = 10 },
        { spell = "Track Humanoids",           icon = "Interface\\Icons\\Ability_Tracking",                    chance = 10 },
        { spell = "Arcane Torrent",            icon = "Interface\\Icons\\Spell_Shadow_Teleport",               chance = 10 },
    },
    lines = {

        ["MELEE"] = {
            "Ugh. Melee. This is so not my aesthetic.",
            "Get OFF me, %t.",
            "I have a BOW, %t. A bow!",
            "Personal space, %t. Ever heard of it?",
            "This is beneath me, %t. Literally beneath me.",
            "Okay, fine. FINE, %t.",
            "Do you know how far I can shoot, %t?",
            "I'm going to need to wash my hands, %t.",
            "Ew, %t. Just ew.",
            "Back UP, %t.",
            "You're literally standing on my foot, %t.",
            "This is so undignified, %t.",
            "I did not train for this, %t.",
            "Stop. Touching. Me. %t.",
            "My whole thing is range, %t. RANGE.",
        },

        ["REACT:LOWHEALTH"] = {
            "I'm literally dying?? Like actually??",
            "Okay this is NOT cute, %t.",
            "Somebody? Anybody? Hello??",
            "I cannot even right now, %t.",
            "My HAIR, %t. Look at my hair.",
            "This is so not the vibe, %t.",
            "Oh my god oh my god oh my god.",
            "Healer? HEALER? Bestie??",
            "I'm gonna need a minute, %t.",
            "It's giving near death, %t.",
            "%t, we were literally just talking.",
            "No no no no no.",
            "I did NOT sign up for this, %t.",
            "Okay, panicking. Officially panicking.",
            "Is anyone SEEING this??",
        },

        ["REACT:DEATH"] = {
            "I'm literally dead. Like. Actually dead this time.",
            "Okay so that happened.",
            "Rude.",
            "I can't even. Literally cannot.",
            "This is so embarrassing.",
            "Well. That's a look.",
            "Not me dying right now.",
            "I need everyone to forget they saw that.",
            "Byeee, I guess.",
            "Someone is getting a strongly worded letter.",
            "Ugh. Corpse run.",
            "My whole aesthetic, ruined.",
            "That was NOT my fault.",
            "Okay. Okay. Fine. FINE.",
            "Delete that.",
        },

        ["REACT:RESURRECT"] = {
            "Oh my GOD thank you. Thank you.",
            "Okay we're back. We're so back.",
            "You are literally my favourite person.",
            "Ugh, finally.",
            "Don't tell anyone that happened.",
            "Hair's a mess but we move.",
            "I owe you like, everything.",
            "Back and better, honestly.",
            "That was a whole thing.",
            "Never speak of it.",
        },

        ["REACT:KILLINGBLOW"] = {
            "Byeee, %t.",
            "Sorry! Not sorry, %t.",
            "And that's on me, %t.",
            "%t? Wasn't even trying.",
            "Okay that was kind of iconic.",
            "Down bad, %t.",
            "It's giving... over, %t.",
            "Should've stayed home, %t.",
            "Nailed it. Obviously.",
            "%t. Deleted.",
            "Not my fault you stood there, %t.",
            "Cute outfit though, %t.",
            "Next!",
        },

        ["REACT:COMBATSTART"] = {
            "Okay so we're doing this, %t?",
            "Ugh, fine. FINE.",
            "%t, this is your one warning.",
            "Oh, it's ON.",
            "Excuse me?? %t??",
            "I was having such a nice day, %t.",
            "This better be quick, %t.",
            "Say less, %t.",
            "Okay, %t. Say that again.",
            "Everyone stand back, I've got this.",
            "It's giving confrontation.",
            "%t. Absolutely not.",
        },

        ["REACT:COMBATEND"] = {
            "Okay, we're good. We're good.",
            "That was a whole thing.",
            "Anyway.",
            "Did everyone see that?",
            "I need a minute.",
            "Slay, honestly.",
            "Okay, group photo?",
            "That's enough cardio for today.",
            "Back to what I was doing.",
            "Anyone need anything? No? Cool.",
        },

        ["REACT:INTERRUPTED"] = {
            "EXCUSE me, %t?",
            "I was TALKING, %t.",
            "Rude!",
            "Okay that was so unnecessary, %t.",
            "Do that again, %t. I dare you.",
            "You literally cut me off, %t.",
            "That's giving insecure, %t.",
            "I'm not even mad. I'm mad.",
            "Let me FINISH, %t.",
            "Wow. Okay. Wow.",
        },

        ["REACT:LEVELUP"] = {
            "Okay, growth!",
            "Level up, bestie.",
            "We're evolving.",
            "That's giving main character.",
            "Getting better every day, honestly.",
            "Slay.",
            "New me.",
            "Manifesting more of this.",
        },

        ["REACT:FALLING"] = {
            "OH MY GOD.",
            "Not the ground, not the ground.",
            "This is so not cute.",
            "Aaaaand falling.",
            "Who put that there??",
            "I did not agree to this.",
            "Nope nope nope nope.",
            "Ow. OW.",
        },

        ["REACT:DROWNING"] = {
            "I'm literally drowning??",
            "This is ruining my hair.",
            "Air. AIR.",
            "Okay who thought water was a good idea.",
            "Not like this. Not WET.",
            "Swimming. Ew. Swimming.",
            "Help?? Hello??",
            "I hate it here.",
        },

        ["REACT:DURABILITY"] = {
            "My armour is literally falling apart.",
            "This is so not the aesthetic.",
            "I need a vendor immediately.",
            "Look at the state of this.",
            "It's giving distressed. Not on purpose.",
            "Ugh, repairs.",
            "I can't be seen like this.",
            "This was expensive!",
            "Falling apart, honestly.",
        },

        ["IDLE:EAT"] = {
            "Okay but I'm starving.",
            "Just a bite. A little bite.",
            "This is not on my plan.",
            "Snack time, don't judge.",
            "I'm eating my feelings.",
            "Ugh, conjured food again.",
        },

        ["IDLE:DRINK"] = {
            "Hydration is self care.",
            "Okay, sipping.",
            "Water. Riveting.",
            "Don't talk to me, I'm drinking.",
            "Refill, refill.",
            "Cheers, I guess.",
        },

        ["IDLE:HEALTHSTONE"] = {
            "Okay that's better.",
            "Emergency snack.",
            "Feeling so much better.",
            "Ugh, needed that.",
            "Crisis averted.",
        },

        ["IDLE:MANAPOTION"] = {
            "Blue one. Down the hatch.",
            "Tastes disgusting, works though.",
            "Okay, topped up.",
            "Don't ask what's in it.",
            "Manafied.",
        },

        ["IDLE:FISHING"] = {
            "This is so boring.",
            "Literally nothing is happening.",
            "I'm being so patient right now.",
            "Fishing. The vibe is: nothing.",
            "Anyway.",
            "Still nothing.",
        },

        ["IDLE:MINING"] = {
            "Ew, dirt.",
            "My nails. MY NAILS.",
            "Okay, mining. Fine.",
            "This is manual labour.",
            "Rocks. Great.",
        },

        ["IDLE:HERBALISM"] = {
            "Ooh, pretty.",
            "Okay this one's cute.",
            "Flowers! Yay.",
            "Picking things. Very cottagecore.",
            "This is my favourite part.",
        },

        ["IDLE:SKINNING"] = {
            "Ew. Ew ew ew.",
            "I'm so sorry, buddy.",
            "This is the worst part.",
            "Don't look. Don't look.",
            "Okay that's disgusting.",
        },

        ["IDLE:MOUNT"] = {
            "Okay let's GO.",
            "Zoom.",
            "Walking is for other people.",
            "Hi baby, let's go.",
            "Faster, faster.",
            "This is my main character moment.",
            "Wind in the hair. Iconic.",
        },

        ["IDLE:QUESTACCEPT"] = {
            "Okay, say less.",
            "On it!",
            "Ugh, fine. For you.",
            "Consider it done.",
            "What's in it for me? Kidding. Kind of.",
            "Sure, why not.",
            "I'm literally the best at this.",
        },

        ["IDLE:QUEST"] = {
            "Done! Obviously.",
            "Where's my gold?",
            "That was easy.",
            "Okay, pay up.",
            "Told you I'd do it.",
            "Next!",
        },

        ["IDLE:DISCOVERY"] = {
            "Ooh. Okay this is cute.",
            "Wait, this is actually pretty.",
            "New place! Yay.",
            "This is giving vacation.",
            "Okay I like it here.",
            "Photo op, honestly.",
        },

        ["IDLE:CRAFT:Alchemy"] = {
            "Mixing things. Very science.",
            "Don't drink that one.",
            "Ooh, it changed colour.",
            "Chemistry! Kind of.",
        },

        ["IDLE:CRAFT:Blacksmithing"] = {
            "This is so loud.",
            "Hammering. Very rustic.",
            "Okay, it's a sword now.",
            "My arms hurt.",
        },

        ["IDLE:CRAFT:Cooking"] = {
            "I'm a chef now, apparently.",
            "Smells amazing.",
            "Don't ask what's in it.",
            "Okay this is actually good.",
        },

        ["IDLE:CRAFT:Enchanting"] = {
            "Ooh, sparkly!",
            "Now it glows. Obsessed.",
            "Magic! Yay.",
            "So much prettier.",
        },

        ["IDLE:CRAFT:Engineering"] = {
            "It might explode. It usually explodes.",
            "Okay that was not supposed to happen.",
            "Very steampunk.",
            "Do not stand near me.",
        },

        ["IDLE:CRAFT:First Aid"] = {
            "Hold still, hold still.",
            "Okay that's a lot of blood.",
            "Bandaged! You're fine.",
            "I'm basically a doctor.",
        },

        ["IDLE:CRAFT:Jewelcrafting"] = {
            "Ooh, shiny.",
            "This is my calling.",
            "So sparkly.",
            "Gems! Obsessed.",
        },

        ["IDLE:CRAFT:Leatherworking"] = {
            "Sorry again, buddy.",
            "Okay it's cute though.",
            "Very rustic chic.",
            "Leather. Iconic.",
        },

        ["IDLE:CRAFT:Tailoring"] = {
            "Fashion!",
            "Okay this is coming together.",
            "Stitch stitch stitch.",
            "It's giving couture.",
        },

        ["IDLE:CRAFT:Smelting"] = {
            "So hot in here.",
            "Melting things. Casual.",
            "Ore in, bar out. Science.",
            "This is so loud.",
        },

        ["SPELL:Auto Shot"] = {
            "So anyway, I started shooting.",
            "Okay so like, this is just happening now, %t.",
            "I'm not even aiming, %t. That's the scary part.",
            "Pew. Pew. Pew, %t.",
            "This is my resting state, %t. Shooting.",
            "%t, I can do this literally all day.",
            "Not to be dramatic, %t, but you're full of arrows.",
            "It's giving pincushion, %t.",
            "I'm multitasking, %t. Shooting and judging you.",
            "Auto Shot, %t. It does itself. Like me.",
            "Barely paying attention, %t. No offence.",
            "Still going, %t. Still going.",
        },

        ["SPELL:Hunter's Mark"] = {
            "%t? Yeah, no. I've decided.",
            "Okay so I'm just gonna put a pin in %t.",
            "Marked. Sorry, %t, you were the one.",
            "%t, you have been selected. Congrats?",
            "I'm making this about you now, %t.",
            "Adding %t to the list. There's a list.",
            "It's giving... chosen, %t.",
            "Everyone look at %t. LOOK at them.",
            "%t, you're on my radar now. Literally.",
            "Hunter's Mark, %t. You're kind of famous now.",
            "I've circled you, %t. In my head.",
            "Don't take it personally, %t. Take it a little personally.",
            "Marked. Sorry, you were the one.",
            "You're on my radar now. Literally.",
        },

        ["SPELL:Arcane Shot"] = {
            "Sparkles! Also you're bleeding, %t.",
            "Ooh, that one's pretty, %t.",
            "Arcane Shot, %t. It's cute AND it hurts.",
            "Instant. Because I'm impatient, %t.",
            "That's the sparkly one, %t. You're welcome.",
            "It's giving glitter, %t. Aggressive glitter.",
            "Quick one, %t. I've got things to do.",
            "Purple looks good on you, %t.",
            "Right now, %t. No waiting.",
            "Little zap, %t. Don't be dramatic.",
            "I like this one, %t. It matches my nails.",
            "Boop, %t.",
            "That's the sparkly one. You're welcome.",
            "I like this one. It matches my nails.",
        },

        ["SPELL:Steady Shot"] = {
            "Okay, steady. Steaaaady, %t.",
            "I'm being so patient right now, %t.",
            "Steady Shot, %t. The boring reliable one.",
            "Deep breath, %t. And... there.",
            "This is the one I do like nine hundred times, %t.",
            "Rhythm, %t. It's all about rhythm.",
            "Not flashy, %t. Just constant.",
            "I could do this in my sleep, %t. I have.",
            "Steady, %t. Unlike your life choices.",
            "And again, %t. And again.",
            "It's giving routine, %t.",
            "Muscle memory, %t. Very impressive of me.",
            "Steady Shot. The boring reliable one.",
            "This is the one I do like nine hundred times.",
        },

        ["SPELL:Aimed Shot"] = {
            "Hold on. Hold ON. I'm concentrating?",
            "Okay nobody talk to me, %t.",
            "This one takes a second, %t. Worth it though.",
            "Aimed Shot, %t. I actually looked this time.",
            "Shhh. Shhh. Aiming, %t.",
            "Do NOT interrupt me right now, %t.",
            "Big one incoming, %t. Brace.",
            "I'm being so precise right now, %t.",
            "Wait for it, %t. Wait for it.",
            "That's the money shot, %t.",
            "Perfect, %t. Genuinely perfect.",
            "See? I CAN aim, %t.",
        },

        ["SPELL:Multi-Shot"] = {
            "Everyone. Like, everyone. I'm not picking favourites.",
            "Multi-Shot, %t. Sharing is caring.",
            "One for you, and you, and you, %t.",
            "I'm being so generous right now, %t.",
            "Group activity, %t.",
            "Three at once, %t. I'm efficient.",
            "Nobody's left out, %t. That would be rude.",
            "It's giving crowd work, %t.",
            "Spray and pray, %t. But make it fashion.",
            "All of you, %t. Yes, all.",
            "Everybody gets one, %t.",
            "Don't stand in a line, %t. Rookie mistake.",
        },

        ["SPELL:Volley"] = {
            "Raining. On everyone. Sorry not sorry.",
            "Look up, %t. Actually don't.",
            "Volley, %t. It's a whole weather event.",
            "Everybody in that circle, %t. Byeee.",
            "I'm just gonna leave this here, %t.",
            "It's giving downpour, %t.",
            "Move or don't, %t. Your call.",
            "Arrows. From the sky. Casual, %t.",
            "Area of effect, %t. Very inclusive of me.",
            "That whole spot is a problem now, %t.",
            "Umbrella weather, %t.",
            "Stand there if you want, %t. I dare you.",
        },

        ["SPELL:Rapid Fire"] = {
            "I'm going as fast as I can?? Oh my GOD??",
            "Okay we're speeding up, %t. Buckle in.",
            "Rapid Fire, %t. Everything's faster now.",
            "Zoom zoom zoom, %t.",
            "I have like fifteen seconds, %t. Watch this.",
            "This is my moment, %t. Don't ruin it.",
            "So fast, %t. So so fast.",
            "It's giving machine gun, %t.",
            "Hands are literally a blur, %t.",
            "Can't stop, won't stop, %t.",
            "Peak performance, %t. Take notes.",
            "Everything, all at once, %t.",
        },

        ["SPELL:Kill Command"] = {
            "Get him. GET HIM, baby.",
            "Okay go, go, go, %t!",
            "Kill Command, %t. He's been waiting for this.",
            "Sic 'em, bestie!",
            "That's my BOY, %t.",
            "Do the thing! Do the thing, %t!",
            "He's so good at this, %t. So good.",
            "Go on, baby. Show %t.",
            "Attack! Ooh, good boy!",
            "He does listen, %t. Sometimes.",
            "That's what he trains for, %t.",
            "Yes! YES! Good boy!",
        },

        ["SPELL:Silencing Shot"] = {
            "Nope. Not today, %t.",
            "Okay, and you're done talking, %t.",
            "Silencing Shot, %t. It's giving quiet.",
            "Shhh, %t. Shhhhh.",
            "You were saying, %t? No you weren't.",
            "Cancelled, %t.",
            "I don't want to hear it, %t.",
            "That's enough out of you, %t.",
            "Mute, %t.",
            "Nobody wants to hear that spell, %t.",
            "Read the room, %t.",
            "Bye, %t. Talk later. Or don't.",
            "Silencing Shot. It's giving quiet.",
            "You were saying? No you weren't.",
        },

        ["SPELL:Scatter Shot"] = {
            "Go be confused somewhere else, %t.",
            "Scatter Shot, %t. Have fun with that.",
            "Okay bye, %t. Walk it off.",
            "You're gonna wander for a bit, %t.",
            "It's giving disoriented, %t.",
            "Off you go, %t. Wherever.",
            "That's a you problem now, %t.",
            "Shoo, %t.",
            "Take a lap, %t.",
            "I need a second, %t. So do you, apparently.",
            "Where are you going, %t? Exactly.",
            "Byeee for like four seconds, %t.",
            "Go be confused somewhere else.",
            "Where are you going? Exactly.",
        },

        ["SPELL:Distracting Shot"] = {
            "Hey! Over here, %t!",
            "Look at me, %t. Me. Not them.",
            "Distracting Shot, %t. Rude of me, honestly.",
            "Yoo-hoo, %t!",
            "I'm the interesting one, %t.",
            "Excuse me, %t! Excuse me!",
            "Eyes on me, %t.",
            "I'm making this my problem, %t. Regrettably.",
            "Come here, %t. No, seriously.",
            "That got your attention, %t.",
            "Hi. Hello. Yes, me, %t.",
            "Stop bothering them and bother me, %t.",
            "Distracting Shot. Rude of me, honestly.",
            "Come here. No, seriously.",
        },

        ["SPELL:Concussive Shot"] = {
            "Where are you going? We were literally talking, %t.",
            "Slow DOWN, %t.",
            "Concussive Shot, %t. You're not going anywhere.",
            "Nope. Sit, %t.",
            "That's giving running away, %t. Embarrassing.",
            "Not so fast, %t.",
            "Okay but where, %t? Where are you going?",
            "Come back, %t. Come BACK.",
            "I wasn't finished, %t.",
            "You're walking now, %t. Slowly.",
            "Leaving? Absolutely not, %t.",
            "Stay, %t. I mean it.",
            "Where are you going? We were literally talking.",
            "Concussive Shot. You're not going anywhere.",
        },

        ["SPELL:Serpent Sting"] = {
            "That is gonna be so bad for your skin, %t.",
            "Serpent Sting, %t. It's a whole process.",
            "Ew, %t. That's poison. Enjoy.",
            "Slow and gross, %t. My favourite.",
            "You're gonna feel that for a while, %t.",
            "It's giving toxic, %t. Literally.",
            "Tick, tick, tick, %t.",
            "That's not gonna wash out, %t.",
            "Green is so not your colour, %t.",
            "Set it and forget it, %t.",
            "I'll check back in ten seconds, %t.",
            "You look unwell, %t. Just saying.",
            "That is gonna be so bad for your skin.",
            "You're gonna feel that for a while.",
        },

        ["SPELL:Scorpid Sting"] = {
            "Okay now you can't hit anything, %t.",
            "Scorpid Sting, %t. Good luck aiming.",
            "Your accuracy is a mess now, %t. Sorry!",
            "Swing away, %t. You'll miss.",
            "It's giving clumsy, %t.",
            "That's a debuff, %t. A mean one.",
            "You were bad at this already, %t.",
            "Try me, %t. You'll whiff.",
            "Nice try, %t. And again. Nice try.",
            "I've made you worse, %t. On purpose.",
            "Scorpid venom, %t. Very unpleasant.",
            "Missing feels bad, %t. I'd know. I don't miss.",
            "Okay now you can't hit anything.",
            "Your accuracy is a mess now. Sorry!",
        },

        ["SPELL:Viper Sting"] = {
            "Bye bye, mana, %t.",
            "Viper Sting, %t. That blue bar? Gone.",
            "Okay so you can't cast now, %t. Awkward.",
            "Draining you, %t. Financially.",
            "It's giving empty, %t.",
            "Where'd your mana go, %t? Weird.",
            "No more spells for you, %t.",
            "That's the expensive one, %t. For you.",
            "Running on empty, %t.",
            "Cast something, %t. Go on. Try.",
            "I'm taking it, %t. All of it.",
            "Broke, %t. Magically broke.",
            "Okay so you can't cast now. Awkward.",
            "I'm taking it. All of it.",
        },

        ["SPELL:Wyvern Sting"] = {
            "Nap time, %t.",
            "Wyvern Sting, %t. Go to sleep. Shhh.",
            "Okay you're having a lie down, %t.",
            "Sweet dreams, %t.",
            "It's giving unconscious, %t.",
            "Don't wake up, %t. Please don't.",
            "Nobody touch %t. NOBODY.",
            "Sleeping, then bleeding, %t. In that order.",
            "Sssh, %t. You need the rest.",
            "Out cold, %t.",
            "I'll deal with you later, %t.",
            "Goodnight, %t.",
            "Okay you're having a lie down.",
            "I'll deal with you later.",
        },

        ["SPELL:Raptor Strike"] = {
            "Ugh. Melee. This is so not my aesthetic.",
            "Raptor Strike, %t. I hate this for me.",
            "Fine, %t. FINE. We'll do it your way.",
            "I have a bow, %t. A BOW.",
            "This is so undignified, %t.",
            "Do not tell anyone about this, %t.",
            "Close range. Gross, %t.",
            "I'm hitting you with a stick, %t. Look what you did.",
            "It's giving desperate, %t.",
            "I trained for range, %t. RANGE.",
            "Okay that actually felt good, %t. Don't tell anyone.",
            "Ew ew ew, %t.",
        },

        ["SPELL:Mongoose Bite"] = {
            "Nice dodge, %t. Now take this.",
            "Mongoose Bite, %t. That's what you get.",
            "You missed, %t. I didn't.",
            "Counter! Ooh, that felt good, %t.",
            "That's karma, %t.",
            "Try that again, %t. Please.",
            "It's giving instant regret, %t.",
            "Reflexes, %t. I have them.",
            "You swung first, %t. Remember that.",
            "Ha! Got you, %t.",
            "That's for the dodge, %t.",
            "Bite back, %t. That's the whole spell.",
            "It's giving instant regret.",
            "You swung first. Remember that.",
        },

        ["SPELL:Wing Clip"] = {
            "Nope. Nope nope nope. We are not doing this, %t.",
            "Wing Clip, %t. Enjoy the walk.",
            "Where do you think you're going, %t?",
            "Legs, %t. I went for the legs.",
            "That's giving limping, %t.",
            "Slow, %t. So slow.",
            "You're not outrunning me, %t. Obviously.",
            "Sit down, %t. Metaphorically.",
            "Okay now we're both slow, %t. Kidding, just you.",
            "Hobbling is not a good look, %t.",
            "Stay right there, %t.",
            "I clipped you, %t. Like a coupon.",
            "Nope. Nope nope nope. We are not doing this.",
            "Okay now we're both slow. Kidding, just you.",
        },

        ["SPELL:Counterattack"] = {
            "You started it, %t.",
            "Counterattack, %t. That's on you.",
            "Blocked. Now sit still, %t.",
            "That's what parrying gets you, %t.",
            "Oh, you tried, %t. Cute.",
            "It's giving instant karma, %t.",
            "Rooted, %t. Stay put.",
            "My turn, %t.",
            "You swung, %t. Bad idea.",
            "Nice try, %t. Genuinely, nice try.",
            "That's a counter, %t. Look it up.",
            "Now you're stuck AND hurt, %t.",
            "Blocked. Now sit still.",
            "That's a counter. Look it up.",
        },

        ["SPELL:Disengage"] = {
            "Ew. Personal space, %t.",
            "Disengage, %t. Byeee.",
            "Okay that's too close, %t.",
            "Back UP, %t.",
            "It's giving boundaries, %t.",
            "I need like six more feet, %t.",
            "Nope, %t. Not doing melee today.",
            "Space, %t. Give me space.",
            "Bye! Not permanently. Just spatially, %t.",
            "Much better, %t. From here.",
            "You were breathing on me, %t.",
            "That's my comfort zone, %t. Way over here.",
            "Nope. Not doing melee today.",
            "Bye! Not permanently. Just spatially.",
        },

        ["SPELL:Deterrence"] = {
            "Try it, %t. Go on. Try it.",
            "Deterrence, %t. Nothing's landing.",
            "Miss. Miss. Miss again, %t.",
            "It's giving untouchable, %t.",
            "Swing all you want, %t.",
            "Not today, %t. Literally not today.",
            "I'm just gonna stand here, %t. Deal with it.",
            "Everything bounces, %t.",
            "Whiff, %t. Again.",
            "This is embarrassing for you, %t.",
            "Keep going, %t. I'll wait.",
            "Nope, %t. Nope. Nope.",
            "Miss. Miss. Miss again.",
            "I'm just gonna stand here. Deal with it.",
        },

        ["SPELL:Readiness"] = {
            "Okay, do-over, %t.",
            "Readiness, %t. Everything's back.",
            "Rewind, %t.",
            "I get to do all of that again, %t. Sorry!",
            "It's giving second chances, %t.",
            "Cooldowns? Never heard of them, %t.",
            "Round two, %t.",
            "All of it. Again, %t.",
            "Refreshed, %t.",
            "That's not fair, is it, %t.",
            "Reset, %t. Watch this.",
            "Everything I just did, %t. Again.",
            "It's giving second chances.",
            "Reset. Watch this.",
        },

        ["SPELL:Freezing Trap"] = {
            "It's giving... trapped, %t.",
            "Freezing Trap, %t. Don't touch them, ANYONE.",
            "Okay stay right there, %t. Perfect.",
            "Frozen! Byeee for a bit, %t.",
            "Nobody break that, %t. NOBODY.",
            "That's a whole minute, %t. Enjoy.",
            "You walked right into it, %t. Amazing.",
            "Ice ice, %t.",
            "So satisfying, %t. Genuinely.",
            "You're on ice, %t. Literally.",
            "Don't move. Actually you can't, %t.",
            "Perfect placement, %t. I'm so good at this.",
            "Okay stay right there. Perfect.",
            "You walked right into it. Amazing.",
        },

        ["SPELL:Explosive Trap"] = {
            "Boom, %t.",
            "Explosive Trap, %t. Watch your step!",
            "Oops, %t. Did you step on that?",
            "Fire! Everywhere! Sorry, %t.",
            "It's giving landmine, %t.",
            "That whole spot is a problem now, %t.",
            "Don't stand there, %t. Too late.",
            "I left something for you, %t.",
            "Surprise, %t!",
            "That's gonna burn for a bit, %t.",
            "Everyone's getting one, %t.",
            "Hot, %t. Very hot.",
            "Oops. Did you step on that?",
            "Don't stand there. Too late.",
        },

        ["SPELL:Immolation Trap"] = {
            "You're on fire, %t. Like, actually.",
            "Immolation Trap, %t. Watch your feet!",
            "Ooh, that's warm, %t.",
            "It's giving toasty, %t.",
            "Burning, %t. Slowly.",
            "Stop, drop and roll, %t.",
            "That's gonna sting, %t.",
            "I set that ages ago, %t.",
            "You found it! Congrats, %t.",
            "Fire is such a vibe, %t.",
            "Smells like %t in here.",
            "Careful. Too late, %t.",
            "You're on fire. Like, actually.",
            "You found it! Congrats.",
            "Smells like you in here.",
        },

        ["SPELL:Frost Trap"] = {
            "Everyone's slow now, %t. Sorry!",
            "Frost Trap, %t. Good luck walking.",
            "That whole area is ice, %t.",
            "It's giving glacial, %t.",
            "Slow down, %t. All of you.",
            "Nobody's running anywhere, %t.",
            "Chilly, %t.",
            "That's a lot of ice, %t.",
            "Take your time, %t. You have to.",
            "Skating, %t. Basically skating.",
            "Cold feet, %t. Literally.",
            "You're all walking now, %t.",
            "Everyone's slow now. Sorry!",
            "Take your time. You have to.",
        },

        ["SPELL:Snake Trap"] = {
            "SNAKES, %t. So many snakes.",
            "Snake Trap, %t. You're welcome.",
            "Ew, %t. Even I don't like this one.",
            "They're everywhere, %t.",
            "It's giving infestation, %t.",
            "Don't ask where I keep them, %t.",
            "Surprise! Snakes, %t.",
            "So many little guys, %t.",
            "Have fun with that, %t.",
            "They bite, %t. A lot.",
            "That's a lot of hissing, %t.",
            "Sorry not sorry, %t.",
            "Ew. Even I don't like this one.",
            "It's giving infestation.",
        },

        ["SPELL:Flare"] = {
            "Come out, come out, %t.",
            "Flare, %t. I see you.",
            "Nice try hiding, %t.",
            "It's giving exposed, %t.",
            "There you are, %t.",
            "Nobody's invisible here, %t.",
            "Hi, %t. Found you.",
            "Lights on, %t.",
            "Peekaboo, %t.",
            "Stealth? In this economy, %t?",
            "I literally see everything, %t.",
            "Busted, %t.",
            "Come out, come out.",
            "I literally see everything.",
        },

        ["SPELL:Feign Death"] = {
            "I'm literally dead. Like. Literally dead.",
            "Feign Death, %t. Nothing to see here.",
            "Oh no. So dead. Very dead, %t.",
            "Byeee, %t. I'm gone. Forever. Probably.",
            "It's giving corpse, %t.",
            "Don't look at me, %t. I'm not here.",
            "Whoops! Dead, %t.",
            "Nobody panic. Actually do panic, %t.",
            "I can't hear you, %t. I'm deceased.",
            "That's my whole personality, %t. Faking it.",
            "So sad. So tragic. So fake, %t.",
            "Ta-da, %t. Not dead.",
        },

        ["SPELL:Misdirection"] = {
            "Okay so this is your problem now, %t? Byeee.",
            "Misdirection, %t. Not it!",
            "He wants it more than I do, %t.",
            "That was literally not me, %t.",
            "It's giving delegation, %t.",
            "Blame him, %t. I'm innocent.",
            "Off you go, buddy! Get %t!",
            "I'm just gonna stand back here, %t.",
            "Not my circus, %t.",
            "Someone else's turn, %t.",
            "I didn't do anything, %t. Prove it.",
            "Go on, tank. That's yours, %t.",
            "Okay so this is your problem now? Byeee.",
            "I didn't do anything. Prove it.",
        },

        ["SPELL:Bestial Wrath"] = {
            "He's having a moment, %t. Let him have it.",
            "Bestial Wrath, %t. He's SO mad.",
            "Okay he's not usually like this, %t.",
            "Look at him GO, %t.",
            "He's not angry, %t. He's just... okay he's angry.",
            "That's my boy, %t. That's my ANGRY boy.",
            "Nobody touch him right now, %t.",
            "It's giving feral, %t.",
            "He's been holding that in, %t.",
            "I've never seen him like this, %t. Proud though.",
            "Get 'em, baby! GET 'EM!",
            "Red mist, %t. Big red mist.",
        },

        ["SPELL:Intimidation"] = {
            "Get him. Oh my god, GET HIM.",
            "Intimidation, %t. He's very scary, actually.",
            "Sic 'em! I mean gently! No. No, sic 'em.",
            "Look at %t's FACE.",
            "That's my boy! Good boy!",
            "He's stunned, %t. Not him. You.",
            "It's giving terrified, %t.",
            "Boo, %t.",
            "He does that on command, %t. Very impressive.",
            "Stunned! Ooh, good boy!",
            "Scary, right, %t? He's actually a sweetheart.",
            "Down, %t. Stay down.",
        },

        ["SPELL:Call Pet"] = {
            "Bestie! Oh my god, come here.",
            "Who's a good boy? Who's a... yes. Yes you are.",
            "Call Pet. He's been waiting all day, honestly.",
            "There he is! There's my guy.",
            "Come here, baby. Come to mama.",
            "Okay everyone look at him. LOOK.",
            "He's literally the best. Sorry, he just is.",
            "Hi! Hi hi hi!",
            "My whole heart, honestly.",
            "Yes! Good boy! So good!",
            "Okay we're a team again.",
            "Missed you. Like, so much.",
        },

        ["SPELL:Dismiss Pet"] = {
            "Go rest, baby. You've earned it.",
            "Okay, nap time. Bye bestie.",
            "Dismiss Pet. It's not forever, don't look at me like that.",
            "I'll be back, I promise.",
            "Go on. Go. GO.",
            "This is temporary. Emotionally difficult, but temporary.",
            "Bye baby! Love you!",
            "He hates this part. I hate this part.",
            "See you in a minute, buddy.",
            "Okay this is actually so sad.",
            "Don't be like that. Please don't.",
            "Just for a bit! Just a bit!",
        },

        ["SPELL:Revive Pet"] = {
            "%t killed my BABY.",
            "%t killed my dog. %t killed my DOG.",
            "Revive Pet. Okay. Okay. He's fine. He's fine.",
            "Come back come back come back.",
            "I am literally never forgiving %t for this.",
            "Wake up, baby. Please wake up.",
            "This is the worst day of my life, %t.",
            "Who did this?? WHO DID THIS??",
            "He's okay! He's okay. I'm okay.",
            "I can't even look at you, %t.",
            "Never again, baby. I promise. Never again.",
            "You're safe now. Mama's here.",
        },

        ["SPELL:Mend Pet"] = {
            "Oh my GOD, are you okay? Look at me. Look at me.",
            "You're okay. You're okay. Mama's here.",
            "Mend Pet. Hold still, baby.",
            "Who hurt you?? Who?!",
            "It's okay, it's okay, shhh.",
            "Almost done, baby. Almost done.",
            "You're being so brave right now.",
            "Look at you. Look what they did to you.",
            "Better? Better. Good boy.",
            "I've got you. I've always got you.",
            "Stop wriggling! I'm helping!",
            "There. All better. Who's a brave boy?",
        },

        ["SPELL:Feed Pet"] = {
            "Who wants a treat? Say please. SAY PLEASE.",
            "Okay but he's like, on a diet? Fine. One.",
            "Feed Pet. Don't tell the others.",
            "You've been SO good today.",
            "Open. Open up. Good boy!",
            "This is his favourite. Obviously.",
            "Don't inhale it! Chew!",
            "Yes yes yes okay, here.",
            "He does the eyes. Every time, the eyes.",
            "One more. That's it. That's the last one.",
            "Snack time, bestie.",
            "He earned this. He absolutely earned this.",
        },

        ["SPELL:Tame Beast"] = {
            "Okay don't be scared. Don't be scared.",
            "Tame Beast. You're coming home with me.",
            "Shhh, it's okay. It's okay!",
            "I've decided. You're mine now.",
            "Just a few more seconds, please don't eat me.",
            "You are SO pretty. Oh my god.",
            "Hold still! I'm bonding with you!",
            "It's giving new best friend.",
            "We're gonna be so happy, you and me.",
            "Nearly. Nearly! Almost!",
            "I saw you and I just knew.",
            "Welcome to the family, gorgeous.",
        },

        ["SPELL:Beast Lore"] = {
            "Okay let me just look at your stats, %t.",
            "Beast Lore, %t. I'm doing research.",
            "Ooh, interesting, %t.",
            "Let's see what you've got, %t.",
            "Reading you like a book, %t.",
            "It's giving background check, %t.",
            "Hmm. Hmm! Okay, %t.",
            "Very informative, %t.",
            "I like to know things, %t.",
            "Nothing personal, %t. Just curious.",
            "Numbers! I love numbers, %t.",
            "Noted, %t.",
            "Okay let me just look at your stats.",
            "Reading you like a book.",
        },

        ["SPELL:Eyes of the Beast"] = {
            "Okay, going in. Be good, body.",
            "Eyes of the Beast. This is so weird.",
            "Everything's so LOW down here.",
            "Scouting! Very stealthy of us.",
            "Ooh, everything smells different.",
            "It's giving out of body.",
            "Go on baby, walk. Walk!",
            "I'm literally seeing through my dog.",
            "This never gets less strange.",
            "Don't let anything eat me while I'm in here.",
            "Left. LEFT. Other left.",
            "Okay this is actually kind of fun.",
        },

        ["SPELL:Scare Beast"] = {
            "Boo, %t.",
            "Scare Beast, %t. Off you go!",
            "Shoo! Shoo, %t!",
            "Sorry! Not sorry, %t.",
            "Go be scared over there, %t.",
            "It's giving spooked, %t.",
            "Bad kitty, %t. Go on.",
            "Run along, %t.",
            "I didn't even hurt you, %t. Dramatic.",
            "That's a big animal running very fast, %t.",
            "Byeee, %t.",
            "Not in my house, %t.",
            "Go be scared over there.",
            "I didn't even hurt you. Dramatic.",
        },

        ["SPELL:Aspect of the Hawk"] = {
            "Hawk. Obviously hawk.",
            "Aspect of the Hawk. This is my default, honestly.",
            "Okay, damage mode.",
            "Bird energy. Big bird energy.",
            "It's giving predator.",
            "This one's just better. Sorry.",
            "Faster shots, prettier feathers.",
            "Hawk aspect, always. I don't make the rules.",
            "Attack mode, engaged.",
            "Yes I'm in hawk. I'm always in hawk.",
            "Sharp eyes, sharper nails.",
            "This is the one that matters.",
        },

        ["SPELL:Aspect of the Monkey"] = {
            "Okay, dodging. Ew, but dodging.",
            "Aspect of the Monkey. Not my favourite look.",
            "I'm being evasive. Very slippery.",
            "Monkey. Yes. Monkey.",
            "It's giving nimble.",
            "Only because I have to.",
            "Dodge, duck, whatever the rest is.",
            "This is a defensive choice and I hate it.",
            "Bouncy. I'm bouncy now.",
            "Swinging. Metaphorically.",
            "Nobody's hitting me in this.",
            "Slippery, honestly.",
        },

        ["SPELL:Aspect of the Cheetah"] = {
            "Okay, running. Ew. But running.",
            "Aspect of the Cheetah. Zoom.",
            "I'm so fast right now, it's unreal.",
            "Don't hit me. Do NOT hit me.",
            "It's giving sprint.",
            "Cardio! Unwillingly!",
            "Wind in the hair. Iconic.",
            "If anyone dazes me I will scream.",
            "Faster faster faster.",
            "This is basically flying.",
            "Speed! My favourite thing!",
            "Please nobody touch me right now.",
        },

        ["SPELL:Aspect of the Pack"] = {
            "Everyone's fast now! You're welcome.",
            "Aspect of the Pack. Group zoom.",
            "Okay nobody get hit. NOBODY.",
            "Road trip!",
            "It's giving convoy.",
            "If one of you dazes us I'll lose it.",
            "We're all going fast. Together. Cute.",
            "Keep up, everyone!",
            "This always ends badly. Let's go.",
            "Group cardio! Yay!",
            "Stay close, besties.",
            "Please. Please don't get dazed.",
        },

        ["SPELL:Aspect of the Wild"] = {
            "Nature resist. Very niche of me.",
            "Aspect of the Wild. For the poison people.",
            "Okay, nature-proof.",
            "It's giving immune. Sort of.",
            "Everyone's covered.",
            "This one's situational and you know it.",
            "Poison? Not today.",
            "Nature can't touch us.",
            "Very specific buff, very useful sometimes.",
            "Group protected. Casually.",
            "I read the encounter notes. Once.",
            "Wild aspect. Trust me.",
        },

        ["SPELL:Aspect of the Viper"] = {
            "Okay I'm out of mana. Don't judge me.",
            "Aspect of the Viper. The shame aspect.",
            "This is so embarrassing but I need it.",
            "Refilling. Look away.",
            "It's giving broke.",
            "My damage is TANKING right now.",
            "Just for a second. Just one second.",
            "Nobody look at my meters.",
            "Viper. Ugh. Viper.",
            "I hate this aspect so much.",
            "Necessary evil, honestly.",
            "Back to hawk in a sec, I promise.",
        },

        ["SPELL:Aspect of the Beast"] = {
            "Untrackable. Very mysterious.",
            "Aspect of the Beast. Nobody can find me.",
            "I'm basically invisible to trackers.",
            "It's giving off the grid.",
            "Sneaky sneaky.",
            "Nobody knows where I am.",
            "Very spy of me.",
            "Can't track what you can't see.",
            "This one's underrated, honestly.",
            "Ghost mode.",
            "Beast aspect. Sounds cooler than it is.",
            "Untraceable, bestie.",
        },

        ["SPELL:Trueshot Aura"] = {
            "Everyone hits harder now. Because of me.",
            "Trueshot Aura. You're all welcome.",
            "I'm literally buffing the whole raid.",
            "It's giving generous.",
            "Yes, that's me. That's my aura.",
            "Everyone's better when I'm here.",
            "Free damage, everybody.",
            "Don't thank me all at once.",
            "Passive icon, active gratitude please.",
            "I make everyone around me better. Literally.",
            "Aura's up. Obviously.",
            "That's my contribution and it's a big one.",
        },

        ["SPELL:Eagle Eye"] = {
            "Okay let me just look over there.",
            "Eagle Eye. Scouting! Very tactical.",
            "Ooh, I can see everything.",
            "It's giving surveillance.",
            "Hold on, hold on, I'm looking.",
            "Don't move my body while I'm doing this.",
            "Zooming in. This is so cool.",
            "I see them. I see ALL of them.",
            "Recon, bestie.",
            "Nobody move. I'm scouting.",
            "Long distance vision. Very useful.",
            "Okay yeah, that's a lot of them.",
        },

        ["SPELL:Track Beasts"] = {
            "Okay where are all the animals.",
            "Track Beasts. I see little dots!",
            "Finding all the cute ones.",
            "It's giving radar.",
            "Ooh, there's loads.",
            "Hunting for a new bestie, maybe.",
            "Everything's on the map now.",
            "I know where everything is. Everything.",
            "Tracking! Very professional.",
            "Dots everywhere. Love it.",
            "Where are you hiding, little guys.",
            "Found them. All of them.",
        },

        ["SPELL:Track Humanoids"] = {
            "Okay where is everybody.",
            "Track Humanoids. I see you all.",
            "Nobody's sneaking up on me. Nobody.",
            "It's giving stalker. In a professional way.",
            "All of you. On my map.",
            "I know exactly where you are.",
            "Very useful, very slightly creepy.",
            "Dots! So many dots.",
            "Found you. All of you.",
            "Tracking, bestie.",
            "Hiding is not an option.",
            "I literally always know.",
        },

        ["SPELL:Arcane Torrent"] = {
            "Silence! Blood elf things, %t.",
            "Arcane Torrent, %t. It's a racial. Very exclusive.",
            "Okay everyone stop casting, %t.",
            "That's giving quiet, %t.",
            "Free mana AND you shut up, %t. Iconic.",
            "Not now, %t.",
            "Racial privilege, %t.",
            "Shhh, everyone, %t.",
            "Little pulse, big result, %t.",
            "That's the elf thing, %t. It's very good.",
            "Mana, please. And silence, %t.",
            "You're welcome, %t. And also be quiet.",
            "Okay everyone stop casting.",
            "Free mana AND you shut up. Iconic.",
        },
    },
}
