-- RPVox -- Warlock class pack
--
-- Voice: a contract lawyer who happens to deal in souls. Everything is terms,
-- clauses, arrears and signatures. Impeccably polite, entirely without mercy,
-- and treats his demons as difficult staff on unfavourable contracts. The
-- horror is administrative.
--
-- Single voice, no moods yet. Mood packs can be scoped with class = "WARLOCK".

RPVox_CLASSES.WARLOCK = {
    name = "Warlock",
    spells = {
        { spell = "Shadow Bolt",         icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt",         chance = 10 },
        { spell = "Incinerate",          icon = "Interface\\Icons\\Spell_Fire_Burnout",              chance = 10 },
        { spell = "Immolate",            icon = "Interface\\Icons\\Spell_Fire_Immolation",           chance = 10 },
        { spell = "Corruption",          icon = "Interface\\Icons\\Spell_Shadow_AbominationExplosion", chance = 10 },
        { spell = "Curse of Agony",      icon = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras",    chance = 10 },
        { spell = "Curse of Weakness",   icon = "Interface\\Icons\\Spell_Shadow_CurseOfMannoroth",   chance = 10 },
        { spell = "Seed of Corruption",  icon = "Interface\\Icons\\Spell_Shadow_SeedOfDestruction",  chance = 10 },
        { spell = "Searing Pain",        icon = "Interface\\Icons\\Spell_Fire_SoulBurn",             chance = 10 },
        { spell = "Soul Fire",           icon = "Interface\\Icons\\Spell_Fire_Fireball02",           chance = 10 },
        { spell = "Shadowburn",          icon = "Interface\\Icons\\Spell_Shadow_ScourgeBuild",       chance = 10 },
        { spell = "Conflagrate",         icon = "Interface\\Icons\\Spell_Fire_Fireball",             chance = 10 },
        { spell = "Rain of Fire",        icon = "Interface\\Icons\\Spell_Shadow_RainOfFire",         chance = 10 },
        { spell = "Hellfire",            icon = "Interface\\Icons\\Spell_Fire_Incinerate",           chance = 10 },
        { spell = "Shadowfury",          icon = "Interface\\Icons\\Spell_Shadow_ShadowFury",         chance = 10 },
        { spell = "Fear",                icon = "Interface\\Icons\\Spell_Shadow_Possession",         chance = 10 },
        { spell = "Howl of Terror",      icon = "Interface\\Icons\\Spell_Shadow_DeathScream",        chance = 10 },
        { spell = "Death Coil",          icon = "Interface\\Icons\\Spell_Shadow_DeathCoil",          chance = 10 },
        { spell = "Banish",              icon = "Interface\\Icons\\Spell_Shadow_Cripple",            chance = 10 },
        { spell = "Enslave Demon",       icon = "Interface\\Icons\\Spell_Shadow_EnslaveDemon",       chance = 10 },
        { spell = "Drain Life",          icon = "Interface\\Icons\\Spell_Shadow_LifeDrain02",        chance = 10 },
        { spell = "Drain Soul",          icon = "Interface\\Icons\\Spell_Shadow_HauntingSpirits",    chance = 10 },
        { spell = "Life Tap",            icon = "Interface\\Icons\\Spell_Shadow_BurningSpirit",      chance = 10 },
        { spell = "Health Funnel",       icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",          chance = 10 },
        { spell = "Create Healthstone",  icon = "Interface\\Icons\\INV_Stone_04",                    chance = 10 },
        { spell = "Create Soulstone",    icon = "Interface\\Icons\\INV_Misc_Orb_04",                 chance = 10 },
        { spell = "Summon Imp",          icon = "Interface\\Icons\\Spell_Shadow_SummonImp",          chance = 10 },
        { spell = "Summon Voidwalker",   icon = "Interface\\Icons\\Spell_Shadow_SummonVoidWalker",   chance = 10 },
        { spell = "Summon Felhunter",    icon = "Interface\\Icons\\Spell_Shadow_SummonFelHunter",    chance = 10 },
        { spell = "Summon Succubus",     icon = "Interface\\Icons\\Spell_Shadow_SummonSuccubus",     chance = 10 },
    },
    lines = {

        -- Abilities -----------------------------------------------------

        ["SPELL:Shadow Bolt"] = {
            "%t. Standard remedy for non-payment.",
            "/em signs something in the air with two fingers",
            "%t. This is the boilerplate. It gets worse.",
            "%t. Nothing personal. Everything contractual.",
            "%t. Consider that your first notice.",
            "/em delivers a small dark thing with great precision",
            "%t. I did send several letters.",
            "%t. The terms were displayed. You did not read them.",
            "%t. Compound interest, in a sense.",
            "/em looses shadow the way a clerk stamps a form",
        },

        ["SPELL:Incinerate"] = {
            "%t. Escalation. As per the schedule.",
            "/em applies fire with entirely unnecessary formality",
            "%t. This is the version with the surcharge.",
            "%t. You would have preferred the shadow. Too late.",
            "/em burns something and looks faintly bored by it",
            "%t. Section four, subsection burning.",
        },

        ["SPELL:Immolate"] = {
            "%t. A slow account. Those are the profitable ones.",
            "/em sets a man alight with a small, tidy gesture",
            "%t. It will continue after I stop paying attention.",
            "%t. Standing charge. It accrues.",
            "%t. Do not put it out. It is not that kind of fire.",
            "/em lights someone and turns away to deal with paperwork",
            "%t. Burning is simply interest with a temperature.",
        },

        ["SPELL:Corruption"] = {
            "%t. There. Signed on your behalf.",
            "/em places something inside a man that will not be removed",
            "%t. It is inside the wording now. And inside you.",
            "%t. You will not notice for some time. Then you will.",
            "/em plants a clause under someone's skin",
            "%t. It works whether you read it or not.",
            "%t. Corruption is such an ugly word for compliance.",
        },

        ["SPELL:Curse of Agony"] = {
            "%t. Payable in instalments. Rising instalments.",
            "/em levies something upon a man in a perfectly level voice",
            "%t. It starts small. That is the cruelty of it.",
            "%t. Each moment costs more than the last.",
            "%t. You will beg long before the final payment.",
            "/em writes a curse across the air and leaves it hanging",
            "%t. I do not set the rates. I merely apply them.",
        },

        ["SPELL:Curse of Weakness"] = {
            "%t. Reduced capacity. Noted and enforced.",
            "/em diminishes a man slightly and makes a note of it",
            "%t. You will find you can do rather less now.",
            "%t. An administrative adjustment.",
            "/em removes something from someone without touching them",
        },

        ["SPELL:Seed of Corruption"] = {
            "%t. Planted. Everyone nearby is now a party to this.",
            "/em buries something in a man that concerns his colleagues",
            "%t. Liability spreads. That is rather the point.",
            "%t. Your associates will share the terms shortly.",
            "/em waits, with visible patience, for something to mature",
        },

        ["SPELL:Searing Pain"] = {
            "%t. Attention, please.",
            "/em applies pain the way one raps a desk for order",
            "%t. Look at me. Yes. That is what that was for.",
            "%t. A formality. It hurts regardless.",
        },

        ["SPELL:Soul Fire"] = {
            "%t. This one takes a moment. It is worth the wait.",
            "/em gathers something enormous with tremendous patience",
            "%t. Certain penalties cannot be rushed.",
            "%t. I have been preparing this since you spoke.",
            "/em releases something that has been building for a full breath",
            "%t. Final demand.",
        },

        ["SPELL:Shadowburn"] = {
            "%t. Settlement in full.",
            "/em closes an account with a short, brutal gesture",
            "%t. The remainder, all at once.",
            "%t. No further correspondence will be entered into.",
        },

        ["SPELL:Conflagrate"] = {
            "%t. And now we call in the fire.",
            "/em collects on something he set burning earlier",
            "%t. All that accrued interest, realised.",
            "%t. I did tell you it was accruing.",
        },

        ["SPELL:Rain of Fire"] = {
            "%t. A general notice to all present.",
            "/em turns the sky into a delivery mechanism",
            "%t. Everyone in the affected area. No exceptions.",
            "%t. Consider it a public posting.",
            "/em holds an umbrella of shadow over himself, purely for the joke",
        },

        ["SPELL:Hellfire"] = {
            "%t. I am prepared to absorb some cost myself.",
            "/em sets a circle alight and stands calmly in the middle of it",
            "%t. Mutual damage. Mine is budgeted.",
            "%t. This hurts me too. I have accounted for it.",
            "/em burns, and continues speaking as though nothing were happening",
        },

        ["SPELL:Shadowfury"] = {
            "%t. Everyone stay exactly where you are.",
            "/em brings a fist down and the ground objects",
            "%t. Order. There will be order.",
            "%t. Nobody is leaving this meeting.",
        },

        ["SPELL:Fear"] = {
            "%t. Go. Reconsider. Come back when you are reasonable.",
            "/em suggests something to a man that he cannot stop believing",
            "%t. Run along. We will resume shortly.",
            "%t. I find people negotiate better after a walk.",
            "/em opens a small window in someone's mind and lets something in",
            "%t. Do not come back until you have thought about it.",
        },

        ["SPELL:Howl of Terror"] = {
            "%t. All of you. Out.",
            "/em makes a sound that adjourns the entire proceeding",
            "%t. This meeting is suspended.",
            "%t. Everybody leave. Now. Quickly.",
        },

        ["SPELL:Death Coil"] = {
            "%t. A transfer. From your column to mine.",
            "/em takes something from a man and keeps it",
            "%t. Assets move. That is all economics is.",
            "%t. You will find you are lighter. I am heavier.",
            "/em siphons quietly and adjusts his cuffs",
        },

        ["SPELL:Banish"] = {
            "%t. Suspended pending review.",
            "/em files something enormous somewhere else entirely",
            "%t. You are out of scope. Wait there.",
            "%t. I will deal with you when there is time.",
        },

        ["SPELL:Enslave Demon"] = {
            "%t. New terms. Non-negotiable.",
            "/em offers a contract that has already been signed",
            "%t. Congratulations. You work for me now.",
            "%t. Read it. Or do not. It makes no difference.",
            "/em binds something vast with something very small",
        },

        ["SPELL:Drain Life"] = {
            "%t. A modest transfer. You will hardly miss it.",
            "/em takes what he is owed, slowly and without apology",
            "%t. What is yours is, on inspection, mine.",
            "%t. This is simply repayment.",
            "/em drinks something from a man that has no name",
            "%t. You are settling your account. Well done.",
        },

        ["SPELL:Drain Soul"] = {
            "%t. Now the principal, not merely the interest.",
            "/em takes the one thing that cannot be replaced",
            "%t. This is the collateral you offered. You did not read that clause.",
            "%t. Everyone signs it. Nobody reads it.",
            "/em collects something and files it carefully away",
            "%t. Do not look at me like that. You agreed.",
        },

        ["SPELL:Life Tap"] = {
            "/em spends his own health without appearing to mind",
            "One draws on capital when one must.",
            "/em opens a vein of himself and calls it liquidity",
            "It is my health. I may spend it.",
            "A short-term loan against myself.",
            "/em winces once, professionally, and carries on",
        },

        ["SPELL:Health Funnel"] = {
            "/em transfers something of himself into something that hates him",
            "Take it. You are no use to me broken.",
            "This is an asset. I maintain my assets.",
            "/em keeps a demon alive with visible reluctance",
            "Do not read anything into this.",
        },

        ["SPELL:Create Healthstone"] = {
            "/em produces something small and warm from nothing",
            "Keep it. You will be grateful and I will remember that.",
            "/em hands out a stone the way one hands out a business card",
            "A favour. Favours are simply informal contracts.",
            "There. Now you owe me nothing. Officially.",
        },

        ["SPELL:Create Soulstone"] = {
            "/em bottles something that should not be portable",
            "A contingency. I believe in contingencies.",
            "/em prepares an arrangement for a death that has not happened yet",
            "Death is a scheduling problem, correctly handled.",
            "Hold this. Do not ask what is in it.",
        },

        ["SPELL:Summon Imp"] = {
            "/em summons something small, loud and contractually obliged",
            "You are late.",
            "/em looks at his newest arrival with open disappointment",
            "Yes, yes. Get on with it.",
            "Do not speak. Simply burn things.",
            "/em signs for a delivery of something with teeth",
        },

        ["SPELL:Summon Voidwalker"] = {
            "/em calls up something patient and enormous",
            "Stand in front. That is the entire job description.",
            "/em greets a void with the courtesy due to long service",
            "You and I have worked together a long time.",
            "Absorb. That is all. Absorb.",
        },

        ["SPELL:Summon Felhunter"] = {
            "/em whistles up something that eats magic and manners",
            "Find the caster. Eat what he is holding.",
            "/em brings something to heel that does not want to be heeled",
            "It has no loyalty. It has a contract. That is better.",
        },

        ["SPELL:Summon Succubus"] = {
            "/em summons something that immediately begins negotiating",
            "No. The terms are the terms.",
            "/em ignores a great deal of flattery with practised ease",
            "You may work. You may not renegotiate.",
            "We have discussed this. Repeatedly.",
        },

        -- Reactions -----------------------------------------------------

        ["REACT:LOWHEALTH"] = {
            "%t. This is an unbudgeted expense.",
            "%t. I am bleeding. That was not in the projections.",
            "/em regards his own wound as a line item",
            "%t. You are costing me a great deal.",
            "%t. I will be recovering this from you. With interest.",
            "%t. Do not mistake this for a reversal. It is a fluctuation.",
            "/em presses a hand to his side and files the pain away for later",
            "%t. I have spent worse on smaller matters.",
            "%t. Very well. I am now taking this personally, which is expensive.",
            "%t. There are clauses I have not invoked yet.",
            "/em straightens his collar with red fingers",
            "%t. I did warn you. In writing.",
            "%t. I have creditors who are frightening. You are not one.",
            "%t. Let us renegotiate. From a position of pain.",
            "/em laughs shortly, and it is not a pleasant sound",
            "%t. Everything I have was borrowed. Including this body.",
            "%t. You have made an enemy with excellent record keeping.",
            "%t. Not today. My arrangements do not permit it.",
            "/em spends more of himself than he can afford and does not flinch",
            "%t. I have a contingency. I always have a contingency.",
            "%t. This will appear in my accounts as a loss. I hate losses.",
            "%t. Do you know what I owe? Do you know to whom?",
            "/em wipes blood from his mouth and inspects it professionally",
            "%t. My death is already spoken for. Not by you.",
            "%t. There are worse things than you holding my paper.",
            "%t. Fine. The unfavourable terms, then.",
            "/em steadies himself against nothing at all and succeeds",
            "%t. I am not permitted to die. It would void everything.",
            "%t. Adjust your expectations. I am adjusting mine.",
            "%t. Every wound is simply a debt owed forward.",
        },

        ["REACT:DEATH"] = {
            "%t. Ah. The clause.",
            "/em falls, and looks more irritated than afraid",
            "%t. Somebody is about to collect on me.",
            "%t. I always knew the terms. I simply hoped for more time.",
            "%t. Do not touch my books. They bite.",
            "/em reaches for a soulstone that is not where he left it",
            "%t. This is a breach. Somebody will be hearing from me.",
            "%t. Well. Everything is owed to something.",
            "%t. My affairs are in order. They always are.",
            "/em closes his eyes with the resignation of a man reading a bill",
            "%t. I signed for this. A long time ago.",
            "%t. The interest, at last, has come due.",
            "%t. Tell my creditors I went first. It will annoy them.",
            "/em goes down neatly, having chosen the position in advance",
            "%t. I would like it noted that this was not my fault.",
            "%t. There is something waiting for me. It has waited a while.",
            "%t. My library goes to nobody. Burn it.",
            "/em says something in a language that makes the air taste wrong",
            "%t. So it is collection day.",
            "%t. Do not grieve. Grief has no market value.",
            "%t. I have been living on borrowed everything.",
            "/em lets go of a contract he has held for a very long time",
            "%t. Somewhere, a ledger closes.",
            "%t. Congratulations. You have foreclosed on me.",
            "%t. Very well. Show me the paperwork.",
        },

        ["REACT:RESURRECT"] = {
            "/em stands, and immediately checks that he still owns himself",
            "Ah. The contingency held.",
            "I pay a great deal for that arrangement. Good to know it works.",
            "/em dusts off a coat that was recently on a corpse",
            "Death is a scheduling matter. I rescheduled.",
            "Somebody is going to invoice me for that.",
            "/em examines his own hands for signs of anything missing",
            "All present. Mostly. Near enough.",
            "That will appear on a statement somewhere.",
            "/em straightens his cuffs with slightly shaking fingers",
            "Right. Back to business.",
            "I have been dead. It is remarkably badly organised.",
            "/em checks a small stone in his pocket and finds it spent",
            "That cost me. It always costs me.",
            "Nothing is free. Not even coming back.",
            "/em resumes as though returning from a brief errand",
            "Where were we. Yes.",
            "The terms are still in force. Unfortunately.",
            "/em looks briefly and genuinely rattled, then puts it away",
            "One more favour called in. There are not many left.",
        },

        ["REACT:KILLINGBLOW"] = {
            "%t. Account closed.",
            "/em makes a small note of something nobody else can see",
            "%t. Paid in full. Rather more than in full.",
            "%t. And that concludes our arrangement.",
            "/em collects something from a body and pockets it",
            "%t. You should have read the terms.",
            "%t. Nobody ever reads the terms.",
            "%t. Filed. Closed. Forgotten.",
            "/em steps over a corpse the way one steps over a puddle",
            "%t. That is one fewer outstanding matter.",
            "%t. He had nothing worth taking. Disappointing.",
            "%t. Do not look at me. He signed.",
            "%t. A shame. He was almost useful.",
            "/em dusts something off his sleeve that was recently a person",
            "%t. Settled, and settled properly.",
            "%t. I take no pleasure in this. I take payment.",
            "%t. Somewhere, something is collecting him. Not me.",
            "/em pauses over the body, then decides against sentiment",
            "%t. Next matter.",
            "%t. That is the trouble with defaulting.",
        },

        ["REACT:COMBATSTART"] = {
            "%t. Very well. Let us discuss terms.",
            "/em removes his gloves with unhurried precision",
            "%t. You have chosen litigation. Bold.",
            "%t. I would rather have settled this in writing.",
            "%t. Do you have any idea what I have signed?",
            "/em opens a small book that nobody else can read",
            "%t. This is going to be procedural and unpleasant.",
            "%t. I represent interests you cannot conceive of.",
            "%t. Last opportunity for an amicable resolution.",
            "%t. No? Then we proceed.",
            "/em sighs like a man whose afternoon has been ruined by process",
            "%t. I am obliged to warn you. Consider yourself warned.",
            "%t. Everything after this point is on your account.",
            "%t. Come, then. Let us establish liability.",
            "/em calls something up beside him without looking at it",
            "%t. I do not enjoy this. I am simply very good at it.",
            "%t. You are in arrears and you do not even know it.",
            "%t. Right. Formal proceedings.",
            "/em rolls up one sleeve, then the other, precisely",
            "%t. This will be documented.",
        },

        ["REACT:COMBATEND"] = {
            "/em makes a note of something and closes a book nobody saw open",
            "Settled.",
            "That is the paperwork done.",
            "/em cleans his hands with a cloth he keeps for the purpose",
            "Tedious. Necessary, but tedious.",
            "Nobody outstanding? Good.",
            "/em dismisses a demon with a small ungrateful gesture",
            "You may go. We will speak again.",
            "I would like a drink and a quiet ledger.",
            "/em adjusts his collar until it is exactly correct again",
            "All accounts reconciled.",
            "That cost more than it should have.",
            "/em examines a scorch on his sleeve with mild irritation",
            "This coat was expensive. Somebody has paid for it now.",
            "Business concluded.",
            "/em stands still a moment, listening for something that is not there",
            "The terms hold. They always hold.",
            "Right. Onward.",
            "/em pockets something small and does not explain it",
            "One less obligation in the world.",
        },

        ["REACT:INTERRUPTED"] = {
            "%t. You have interrupted counsel.",
            "%t. That was mid-clause.",
            "/em stops, and the temperature of the conversation drops",
            "%t. I do not care for that at all.",
            "%t. Very well. We proceed without the formalities.",
            "%t. That will be noted in the record.",
            "/em closes his hand on something that dissipates",
            "%t. Do you know how long that takes to draft?",
            "%t. Interruption is a breach in itself.",
            "%t. I shall have to begin again. You will wait.",
            "/em exhales slowly through his nose and starts over",
            "%t. That is one. There is a schedule of penalties.",
            "%t. Congratulations. You have added a clause.",
            "%t. I was being courteous. That has now lapsed.",
            "/em selects something considerably less procedural",
            "%t. Fine. Summary judgement.",
            "%t. You have cost yourself the negotiated rate.",
            "%t. Again. And do not touch my hands.",
            "/em looks at the offender with the patience of a man drafting revenge",
            "%t. That was expensive for you.",
        },

        ["REACT:LEVELUP"] = {
            "/em feels something shift in terms he had thought fixed",
            "Better leverage.",
            "Ah. My position improves.",
            "/em opens a book and finds a page that was not there before",
            "More is available to me than yesterday.",
            "The terms have improved. Slightly. In my favour.",
            "/em flexes his fingers and something answers from very far away",
            "Capacity grows. So does what one may borrow.",
            "Good. There are things I have wanted to attempt.",
            "/em permits himself a small, entirely joyless smile",
            "Another rung. The ladder goes somewhere unpleasant.",
            "One accumulates. That is the whole art.",
            "/em makes a note, satisfied, and closes the book",
            "I am worth more now. To everyone. Including my creditors.",
            "Progress. Documented.",
        },

        ["REACT:FALLING"] = {
            "This was not in the itinerary.",
            "/em falls with what dignity remains available",
            "I do not recall agreeing to this.",
            "There is a demon who could catch me. He will not.",
            "/em plummets, mentally drafting a complaint",
            "Somebody is going to hear about this.",
            "Gravity. The one force that will not negotiate.",
            "/em drops through the air with visible indignation",
            "This is going to be costly.",
            "Ah. The ground. Punctual as ever.",
            "/em braces, and looks annoyed rather than frightened",
            "I have arrangements. None of them cover this.",
            "Unscheduled descent.",
            "/em falls silently, refusing to give the moment satisfaction",
            "Oh, this is undignified.",
        },

        ["REACT:DROWNING"] = {
            "This is not a death I have papers for.",
            "/em struggles upward with his robes dragging him under",
            "Water. There is no clause for water.",
            "Air. Immediately, please.",
            "/em fights the water with methodical desperation",
            "I have survived contracts with things older than oceans.",
            "Up. Up. This is absurd.",
            "/em loses a book to the dark and reaches after it",
            "That book cost more than a house.",
            "Not this. Anything but this.",
            "/em breaks the surface, gasps, and goes under again",
            "Somebody. Something. Anything.",
            "I will owe whatever pulls me out. I accept the terms.",
            "/em claws upward through green dark",
            "This is going to be so embarrassing.",
        },

        ["REACT:DURABILITY"] = {
            "/em examines a tear in his robe with genuine distress",
            "This was tailored. Tailored.",
            "Maintenance is an expense. I dislike expenses.",
            "/em holds up a piece of his own equipment that has given up",
            "Everything depreciates. Even me.",
            "I look like a man who has lost an argument.",
            "/em attempts to smooth a scorch mark and makes it worse",
            "Appearance is leverage. This is costing me leverage.",
            "Right. Repairs. Reluctantly.",
            "/em sighs at the state of a very expensive coat",
            "One cannot negotiate in rags.",
            "This will not survive another engagement.",
            "/em ties something that was designed to be buckled",
            "I shall have to find a tailor who does not ask questions.",
            "Wear and tear. The only creditor that never accepts payment.",
        },

        -- Idle ----------------------------------------------------------

        ["IDLE:EAT"] = {
            "/em eats without appearing to enjoy it in any way",
            "Fuel. The body is a leased property.",
            "/em cuts his food into precisely equal portions",
            "One maintains the premises.",
            "I have eaten at better tables. I have eaten at worse.",
            "/em shares nothing with the demon watching him eat",
            "No. You do not eat. It is in your contract.",
            "This is upkeep, not pleasure.",
        },

        ["IDLE:DRINK"] = {
            "/em drinks and grimaces at the quality",
            "Water. The only thing in this world that is free.",
            "/em raises a flask to nobody in particular",
            "To absent signatories.",
            "One should never negotiate thirsty.",
            "/em drinks methodically, the way he does everything",
            "I knew a man who signed a contract while drunk. I own him now.",
        },

        ["IDLE:MOUNT"] = {
            "/em mounts up with the air of a man attending an appointment",
            "Time is the only thing I cannot borrow.",
            "/em rides something that was almost certainly not born",
            "Faster. I have obligations.",
            "This beast and I have an arrangement. It is not a friendly one.",
            "/em settles into the saddle and immediately begins thinking about something else",
        },

        ["IDLE:QUESTACCEPT"] = {
            "Terms?",
            "/em listens with his head slightly tilted, calculating",
            "Very well. But I want that in writing.",
            "I will do it. You will owe me. Those are the terms.",
            "/em accepts a task the way one accepts a retainer",
            "Consider it agreed. Do not consider it free.",
            "You are quite certain you understand what you have asked?",
            "/em produces a small book and makes a note",
            "Signed, in effect. Do not test me on this later.",
            "I never break an agreement. It is the only thing I never do.",
        },

        ["IDLE:HEALTHSTONE"] = {
            "/em swallows something he made himself, without ceremony",
            "One prepares. Preparation is everything.",
            "/em crushes a stone in his fist and absorbs what escapes",
            "This is what contingencies are for.",
            "I made this. I make everything.",
        },

        ["IDLE:FISHING"] = {
            "/em fishes with the stillness of a man waiting for a reply",
            "Patience is a professional skill. This is practice.",
            "/em watches the water and thinks about somebody who owes him",
            "Nothing here has signed anything. It is restful.",
            "The water asks for nothing. Unusual.",
            "/em sits with a book closed on his knee, unread",
            "I could summon something to do this. It would be undignified.",
        },

        ["IDLE:DISCOVERY"] = {
            "/em surveys somewhere new and immediately assesses its value",
            "Nobody here owes me anything. How restful.",
            "/em looks out at a horizon and, for a moment, is not calculating",
            "Interesting. And entirely outside my jurisdiction.",
            "A place with no history between us. Rare.",
            "/em makes a note of a landscape as though it were an asset",
            "I should like to own this. That is my only response to beauty.",
        },
    },
}
