-- RPVox -- mood pack: GRIM (Mage)
--
-- Lines are stored plain; the addon prefixes each with [grim] when seeding.
-- Voice: the arcanist with the courtesy stripped out. Cold, exact, and utterly
-- willing. Where the default Mage is superior, this one is merciless -- power
-- as a settled fact, and other people as material.

RPVox_MOOD_LINES = RPVox_MOOD_LINES or {}

RPVox_MOOD_LINES.MAGE_GRIM = {
    name  = "grim",
    class = "MAGE",

    -- Abilities -----------------------------------------------------------

    ["SPELL:Frostbolt"] = {
        "%t. Cold is patient. So am I.",
        "You will slow, and then you will stop, %t.",
        "%t. There is no warmth left in this exchange.",
        "Feel the temperature leave you, %t.",
        "%t. Slower. That is how it begins.",
        "%t. Ice does not negotiate. Neither do I.",
        "Every degree is one you do not get back, %t.",
        "You are being taken apart by physics, %t.",
        "%t. The cold reaches the bone eventually.",
        "Stop moving. It is inevitable anyway, %t.",
        "I have all the time you are losing, %t.",
        "%t. That is not pain. That is entropy.",
        "You will freeze before you reach me, %t.",
        "%t. Nothing survives the cold indefinitely.",
        "Consider this a countdown, %t.",
        "The frost knows your name now, %t.",
        "Your blood is thickening. Notice it, %t.",
        "%t. I do not need to rush.",
        "%t. Cold, precise, and unanswerable.",
    },
    ["SPELL:Fireball"] = {
        "Burn. There is no argument after fire, %t.",
        "%t. Combustion is the honest solution.",
        "Everything you are is fuel, %t.",
        "%t. There will not be enough left to bury.",
        "%t. Fire asks nothing and takes all of it.",
        "You are a temporary arrangement of matter, %t.",
        "Watch what heat does to certainty, %t.",
        "That will not stop until you do, %t.",
        "I have reduced better than you to ash, %t.",
        "%t. Nothing endures flame. Nothing.",
        "Feel the conversion, %t.",
        "%t. This is what mana becomes.",
        "Burn quietly, if you can manage it, %t.",
        "%t. The fire is indifferent. I am not.",
        "%t. Ash is a very simple state.",
        "You will smell this for the rest of your short life, %t.",
        "%t. There is nothing merciful about heat.",
        "%t. Reduced to component elements.",
        "%t. Fire is the shortest proof.",
    },
    ["SPELL:Arcane Missiles"] = {
        "You cannot dodge arithmetic, %t.",
        "%t. Each one is a decision already made.",
        "%t. There is no chance involved. Only sequence.",
        "%t. The arcane does not miss. Ever.",
        "Count them if it comforts you, %t.",
        "%t. This is the purest thing I know.",
        "%t. Nothing intervenes. Nothing deflects.",
        "You are inside a conclusion, %t.",
        "%t. The math has already happened.",
        "%t. Precision without pity.",
        "%t. One. Two. Three. It ends the same.",
        "%t. There is no escaping a proof.",
        "The arcane finds you wherever you stand, %t.",
        "%t. Delivered in full.",
        "%t. That is not luck. That is inevitability.",
        "You are being solved, %t.",
        "%t. No cover. No dodging. No point.",
        "%t. Each impact is scheduled.",
        "%t. This is what certainty feels like.",
    },
    ["SPELL:Fire Blast"] = {
        "%t. Immediately.",
        "%t. No incantation. No warning.",
        "%t. That did not require thought.",
        "%t. Instant, and entirely deliberate.",
        "%t. A small cruelty, precisely placed.",
        "You had no time. That was the intent, %t.",
        "%t. There. Punctuation.",
        "Faster than you can reconsider, %t.",
        "It costs me nothing to hurt you, %t.",
        "%t. A reflex. Not a decision.",
        "%t. That was the cheap one.",
        "You are not worth a full working, %t.",
        "%t. Immediate consequence.",
        "%t. There is more where that came from.",
        "%t. Nothing elaborate. Merely effective.",
        "%t. Quick, hot, and unarguable.",
        "%t. The fire answers instantly to me.",
        "You flinched. Good, %t.",
        "%t. That is how little effort this takes.",
    },
    ["SPELL:Pyroblast"] = {
        "%t. I took my time with this one.",
        "%t. Patience produces the worst results.",
        "%t. This is what waiting buys.",
        "You watched me build it. That was your mistake, %t.",
        "%t. Nothing survives a considered decision.",
        "%t. The long cast is always the last one.",
        "%t. I wanted this to be memorable.",
        "%t. That is what deliberate looks like.",
        "You had seconds. You wasted them, %t.",
        "%t. A conclusion, delivered from height.",
        "%t. There will be a crater and a lesson.",
        "%t. I do not rush the important work.",
        "%t. This was calculated to the digit.",
        "%t. Everything before this was preamble.",
        "%t. The sky drops it. I only aimed.",
        "You were given warning. It did not help, %t.",
        "%t. That is the end of the demonstration.",
        "Consider the scale of what I withheld, %t.",
        "%t. Nothing personal. Everything final.",
    },
    ["SPELL:Blizzard"] = {
        "All of you. Simultaneously, %t.",
        "%t. Weather is not merciful.",
        "%t. There is nowhere in that circle to stand.",
        "%t. Everyone receives their portion.",
        "The cold does not distinguish between you, %t.",
        "%t. That ground belongs to me now.",
        "Stay in it. See what happens, %t.",
        "%t. A localised extinction.",
        "%t. Nothing walks out of that unchanged.",
        "Numbers do not help you here, %t.",
        "%t. The storm has no opinion. I do.",
        "Freeze in whatever order you like, %t.",
        "%t. Area denial is a polite phrase for this.",
        "You brought a crowd. I brought weather, %t.",
        "%t. Nothing survives long in that.",
        "%t. Scatter or freeze. Both are acceptable.",
        "%t. That is what I do to formations.",
        "%t. Cold, falling, endless.",
        "%t. The field is uninhabitable now.",
    },
    ["SPELL:Frost Nova"] = {
        "Stay, %t.",
        "You will wait there until I decide, %t.",
        "%t. Rooted. Now we begin properly.",
        "%t. Distance is mine to control.",
        "Do not struggle. It is beneath you, %t.",
        "You are exactly where I want you, %t.",
        "%t. Held. Consider what comes next.",
        "That is the end of your mobility, %t.",
        "You will watch this happen, %t.",
        "%t. Nothing moves without my permission here.",
        "Stand still. It is already arranged, %t.",
        "%t. The ice holds. It always holds.",
        "You came too close. Now you stay, %t.",
        "%t. Immobilised, and entirely aware.",
        "%t. That is the trap closing.",
        "%t. There is no advancing from there.",
        "%t. Frozen in place, precisely as planned.",
        "%t. Now the interesting part.",
        "You will not reach me. Ever, %t.",
    },
    ["SPELL:Blink"] = {
        "%t. Elsewhere. Obviously.",
        "You will not touch me, %t.",
        "%t. Space is negotiable. My safety is not.",
        "%t. Reach for me again.",
        "%t. I decide the distance.",
        "You cannot close on something that refuses to be closed on, %t.",
        "%t. Gone, and better positioned.",
        "%t. That is the difference between us.",
        "You are chasing a conclusion, %t.",
        "%t. Nothing keeps me in reach.",
        "I am never where you swing, %t.",
        "%t. Distance restored. Continue dying.",
        "%t. The geometry favours me.",
        "You will spend this fight arriving late, %t.",
        "Try again from further away, %t.",
        "%t. I move when it suits the calculation.",
        "There. Out of your reach permanently, %t.",
        "You are too slow for the arcane, %t.",
        "%t. That is how one avoids being touched.",
    },
    ["SPELL:Polymorph"] = {
        "You are more useful as livestock, %t.",
        "%t. Be quiet. Be woolly.",
        "%t. That is an improvement on the original.",
        "You will wait your turn as a sheep, %t.",
        "I have removed your hands. And your point, %t.",
        "Consider it a demotion, %t.",
        "Nothing you were is needed right now, %t.",
        "Stay there and chew, %t.",
        "You are stored, not spared, %t.",
        "I will deal with you after, %t.",
        "%t. That is what happens to complications.",
        "%t. Simplified.",
        "Do not struggle. You have hooves, %t.",
        "%t. The transformation holds while I need it.",
        "You have been set aside, %t.",
        "%t. One less variable, temporarily.",
        "%t. There. Manageable.",
        "You will remember this. Sheep do not forget, %t.",
        "%t. Filed for later.",
    },
    ["SPELL:Counterspell"] = {
        "%t. No.",
        "%t. That will not be happening.",
        "Silence suits you better, %t.",
        "You do not get to cast that, %t.",
        "Denied. Permanently, if you like, %t.",
        "%t. I have read that spell. It is beneath both of us.",
        "%t. Not while I am standing here.",
        "Your working was sloppy. Now it is gone, %t.",
        "That is the end of your contribution, %t.",
        "You will not speak again this fight, %t.",
        "Broken. Try something you understand, %t.",
        "The arcane obeys me over you, %t.",
        "%t. That is what happens to amateurs.",
        "%t. Silenced. Now stand there.",
        "Nothing you begin will finish, %t.",
        "I know that incantation better than you do, %t.",
        "Do not embarrass yourself again, %t.",
        "Your magic ends where mine begins, %t.",
        "%t. Cancelled.",
    },
    ["SPELL:Ice Block"] = {
        "Wait there. I am reconsidering, %t.",
        "%t. Nothing reaches me in here.",
        "You have accomplished nothing, %t.",
        "%t. This is not fear. It is scheduling.",
        "Do continue. I will be out shortly, %t.",
        "You cannot touch what does not exist for six seconds, %t.",
        "%t. A pause, entirely on my terms.",
        "Everything you just did is undone, %t.",
        "I will emerge. You will still be there, %t.",
        "The ice holds. You do not, %t.",
        "Consider the futility of the last few seconds, %t.",
        "Come closer. It will not help, %t.",
        "%t. Nothing gets through. Nothing ever does.",
        "%t. I am simply unavailable.",
        "Spend your best work on this. Please, %t.",
        "%t. That was a wasted opening.",
        "%t. Frozen, and entirely in control.",
        "Watch me not die, %t.",
        "%t. Now, where were we.",
    },
    ["SPELL:Evocation"] = {
        "Do not interrupt this, %t.",
        "%t. Refuelling. Then finishing.",
        "You have a few seconds. Use them poorly, %t.",
        "The reservoir refills. Yours does not, %t.",
        "%t. This is the pause before the ending.",
        "I am gathering what will kill you, %t.",
        "Stand back or be included, %t.",
        "Nothing you do stops this recovery, %t.",
        "%t. The arcane returns to me. It always does.",
        "%t. That noise is the sound of my advantage returning.",
        "Wait. It will be worth watching, %t.",
        "You cannot outlast an infinite well, %t.",
        "%t. Restoring. Then concluding.",
        "This is the calm you should be afraid of, %t.",
        "Every second here costs you later, %t.",
        "%t. I will be full again shortly.",
        "Consider running now, %t.",
        "%t. The power comes back. It always comes back.",
        "%t. Nearly ready. Prepare yourself.",
    },
    ["SPELL:Arcane Intellect"] = {
        "There. Think faster. It will not save you, %t.",
        "%t. A modest improvement to a modest mind.",
        "%t. Use it. I will not offer twice.",
        "You are marginally less useless now, %t.",
        "%t. Intellect, loaned at my discretion.",
        "Do something worthy of the enhancement, %t.",
        "That is more cleverness than you had, %t.",
        "%t. I improve my tools. That is all this is.",
        "%t. Sharpened. Now be useful.",
        "You will need this. Badly, %t.",
        "%t. The mind is the only part worth improving.",
        "%t. There. Adequate.",
        "Do not waste what I have given, %t.",
        "%t. A better mind, on loan.",
        "%t. Now think, and keep up.",
    },
    ["SPELL:Conjure Water"] = {
        "%t. Water from nothing. Consider what else I can make.",
        "%t. I create. That is the whole of the difference.",
        "Take it. It costs me nothing, %t.",
        "%t. Matter is a suggestion.",
        "You drink what I decide to make, %t.",
        "%t. The arcane provides because I tell it to.",
        "%t. Nothing here existed a moment ago.",
        "Do not mistake this for generosity, %t.",
        "I can conjure. You can only consume, %t.",
        "%t. Water. Trivial. Like most things.",
        "%t. There. Now stop asking.",
    },
    ["SPELL:Conjure Food"] = {
        "%t. Sustenance from nothing. Remember who made it.",
        "You eat because I permit it, %t.",
        "%t. Matter, on demand.",
        "%t. This is the least of what I can do.",
        "Take it and be quiet, %t.",
        "%t. I create food. Consider the implications.",
        "Nothing here is real. It will still feed you, %t.",
        "Do not thank me. Simply eat, %t.",
        "The arcane feeds you. Not kindness, %t.",
        "%t. There. Fuel.",
        "It is enough to keep you working, %t.",
    },
    ["SPELL:Shoot"] = {
        "%t. Even without power, I am the greater threat.",
        "%t. Small wounds. Sufficient ones.",
        "I do not need mana to end you, %t.",
        "You will die of accumulation, %t.",
        "%t. Patience is a weapon. This is patience.",
        "%t. Every splinter is scheduled.",
        "%t. Empty, and still winning.",
        "%t. The wand does not tire. Neither does my intent.",
        "Count them. It changes nothing, %t.",
        "%t. Slow is not the same as harmless.",
        "You are bleeding out by increments, %t.",
        "%t. This will be enough. It always is.",
        "%t. Nothing about me is ever truly unarmed.",
        "Hold still. It only takes a hundred, %t.",
        "%t. The arithmetic still favours me.",
        "You cannot wait me out, %t.",
        "%t. Even the crude tools obey.",
        "%t. One splinter at a time, then.",
        "It will finish you. Eventually, %t.",
    },

    -- Reactions -----------------------------------------------------------

    ["REACT:LOWHEALTH"] = {
        "%t. Miscalculation. Correcting.",
        "You have done well to reach me. It ends here, %t.",
        "%t. That was closer than the model permits.",
        "Do not mistake proximity for victory, %t.",
        "I am recalculating, and you will not enjoy the result, %t.",
        "%t. Cloth is a poor barrier. My spells are not.",
        "You are inside my range now. That is worse for you, %t.",
        "%t. Nothing about this changes the outcome.",
        "I have contingencies you cannot imagine, %t.",
        "That wound cost me time. You will pay it back, %t.",
        "%t. Close. And still not close enough.",
        "%t. The arcane does not care that I am bleeding.",
        "You have made an error in judgement, %t.",
        "%t. I do not panic. I revise.",
        "Every second you spend on me is one I use, %t.",
        "That is the last blow you land, %t.",
        "%t. Distance. Then consequences.",
        "You should have finished it, %t.",
        "%t. There is a very cold answer coming.",
        "%t. I have been hurt before. It sharpened me.",
        "%t. Nothing survives cornering me.",
        "%t. The margin is thin. My options are not.",
        "You are about to learn what desperation looks like, %t.",
        "That was your window. It closes now, %t.",
        "%t. I am at my most dangerous when the numbers fail.",
        "%t. Wounded. Focused. Worse.",
        "Do not let me reach open ground, %t.",
        "%t. The next working is not for show.",
        "You have my complete attention now, %t.",
        "I intend to survive this. You do not feature in that plan, %t.",
        "%t. There is nothing reckless in what comes next.",
        "%t. That hurt. Note that it did not stop me.",
        "%t. The reservoir is low. The intent is not.",
        "You are running out of chances quietly, %t.",
        "%t. Nothing about my resolve is affected.",
        "%t. I have been in worse positions and buried the cause.",
        "%t. Blood is a variable. Nothing more.",
        "Come closer. See what I do at this range, %t.",
        "%t. The theory holds even when the body does not.",
        "You have wounded a very patient man, %t.",
        "%t. That was permitted. Nothing more.",
        "I do not require health to end you, %t.",
        "%t. Precision does not depend on comfort.",
        "%t. The cold does not care how much I bleed.",
        "You are nearly there. Nearly, %t.",
        "%t. Every wound narrows my mercy.",
        "There is a hard limit and you are approaching mine, %t.",
        "%t. Nothing left but the useful spells.",
        "%t. This is where I stop being polite.",
    },
    ["REACT:DEATH"] = {
        "%t. An error. It will be corrected.",
        "Note the conditions. I will not repeat them, %t.",
        "You have won nothing but a delay, %t.",
        "%t. The model was wrong. That is all.",
        "%t. I will return with better preparation.",
        "Remember this. I intend to, %t.",
        "%t. That should not have worked. It will not again.",
        "You have made an enemy who takes notes, %t.",
        "%t. Nothing here is concluded.",
        "%t. The arcane does not forget its practitioners.",
        "You are now a problem to be solved, %t.",
        "%t. This is a variable, not an ending.",
        "%t. I have died before. It improved my work.",
        "Take the field. I will take it back, %t.",
        "%t. There will be a second experiment.",
        "You should not have let me see how you did it, %t.",
        "%t. That was skill. It will not be enough twice.",
        "%t. Nothing about my intent has changed.",
        "%t. Record the time. I will.",
        "You have earned a place in my calculations, %t.",
        "%t. This is a setback. They are recoverable.",
        "%t. I go, and I take the data with me.",
        "%t. The next meeting will be considerably shorter.",
        "You have not solved me, %t.",
        "Nothing you did was outside the possible, %t.",
        "%t. That was a good hypothesis. Mine is better.",
        "%t. The arcane will return me.",
        "You will not see the next one coming, %t.",
        "%t. I fall. The work does not.",
        "%t. That is one iteration. There are others.",
        "You have my full and cold attention now, %t.",
        "%t. Nothing about this is final.",
        "Consider what returns, %t.",
        "%t. The error is identified. The rest follows.",
        "%t. I have been unmade before. It is temporary.",
        "You should be counting the days, %t.",
        "%t. A poor result. Not a conclusion.",
        "%t. Nothing survives my attention indefinitely.",
        "%t. That will be reversed.",
        "%t. I know precisely what went wrong.",
        "%t. The next version of this fight is already written.",
        "You have delayed something inevitable, %t.",
        "There is nothing you can do about what comes back, %t.",
        "%t. Filed. Under unfinished.",
        "%t. I am not solved. I am interrupted.",
        "The arcane keeps better records than you do, %t.",
        "Enjoy the interval, %t.",
        "That was expensive. You will find out how much, %t.",
        "%t. Nothing ends here but the demonstration.",
    },
    ["REACT:RESURRECT"] = {
        "Returned. The model is updated.",
        "That will not happen twice.",
        "Back, and considerably less patient.",
        "The error is corrected.",
        "You had your interval. It is over, %t.",
        "Nothing about me is improved except the preparation.",
        "I have revised the entire approach.",
        "Where is the one who managed it.",
        "Back. Colder. Better armed.",
        "That gap in the record is closed.",
        "I do not repeat mistakes.",
        "The arcane returns what it values.",
        "You should have used that time better, %t.",
        "Standing. Recalculated. Ready.",
        "Nothing has changed but my precision.",
        "I return with the correct answer.",
        "The experiment resumes under better conditions.",
        "You will find this version considerably worse, %t.",
        "Back, and the variables are mine now.",
        "That interruption cost you more than it cost me, %t.",
        "I have had time to think. That is dangerous.",
        "Nothing survives a second attempt.",
        "The work continues. Immediately.",
        "You are exactly where I left you. Convenient, %t.",
        "Restored, and entirely focused.",
        "I have accounted for what killed me.",
        "That will not be a factor again.",
        "Back. Say nothing.",
        "The reservoir is full. So is the intent.",
        "Nothing about this fight favours you now, %t.",
        "I return prepared. You do not, %t.",
        "Standing again, and colder for it.",
        "The next few minutes are already decided.",
        "You have my complete attention, permanently.",
        "Every death teaches. I learn quickly.",
        "Back to work. Yours is nearly finished.",
        "That was instructive. For me.",
        "The arcane does not abandon its own.",
        "Nothing left to reconsider. Only to execute.",
        "I am returned and the plan has changed.",
        "You will not survive the revision.",
        "Ready. Cold. Precise.",
        "That delay is now your problem.",
        "The model held. The execution improves.",
        "Back, and there will be no third attempt.",
        "Nothing about my return should reassure you.",
        "Recalculated. Proceeding.",
        "I have been patient long enough.",
        "Now we finish it properly.",
    },
    ["REACT:KILLINGBLOW"] = {
        "%t. Resolved.",
        "%t. Predictable from the opening.",
        "%t. One variable removed permanently.",
        "You were never going to survive that, %t.",
        "The maths were never in your favour, %t.",
        "%t. Reduced to component parts.",
        "%t. That concludes the demonstration.",
        "%t. Nothing left to calculate.",
        "You should have studied harder, %t.",
        "%t. Filed. Closed. Forgotten.",
        "%t. The arcane is not interested in effort.",
        "%t. That is what preparation produces.",
        "%t. Cleanly reduced.",
        "You brought nothing I had not modelled, %t.",
        "%t. There is no coming back from that working.",
        "%t. Efficiently concluded.",
        "%t. One less complication in the world.",
        "That was inevitable from the moment you closed, %t.",
        "%t. The result was determined in advance.",
        "%t. Nothing personal. Merely correct.",
        "You are a data point now, %t.",
        "%t. Ash and arithmetic.",
        "%t. That is the difference between us, illustrated.",
        "Concluded, %t.",
        "%t. No part of that was chance.",
        "You had a theory. It failed, %t.",
        "%t. Removed from the equation.",
        "%t. The cold takes everything eventually.",
        "%t. That is what happens to material.",
        "%t. Precisely as calculated.",
        "%t. One more confirmation of the model.",
        "%t. There will be nothing to identify.",
        "You have been solved, %t.",
        "%t. Nothing survives contact with proper preparation.",
        "%t. Reduced. Recorded. Next.",
        "%t. That was the expected outcome.",
        "You will not be getting up, %t.",
        "%t. Elegant. And final.",
        "The demonstration required a subject. You volunteered, %t.",
        "%t. Nothing about that was in doubt.",
        "%t. Ended cleanly. As intended.",
        "You are finished and I am unmarked, %t.",
        "%t. That is the correct result.",
        "%t. Another confirmation. Tedious, almost.",
        "%t. The arcane concludes what it begins.",
        "There is nothing left of you worth naming, %t.",
        "%t. Removed.",
        "%t. That is how it was always going to end.",
        "%t. Next problem.",
    },
    ["REACT:COMBATSTART"] = {
        "You have chosen very poorly, %t.",
        "There is no version of this you survive, %t.",
        "%t. I would advise against closing.",
        "You are already inside the working, %t.",
        "%t. This will be brief and one-sided.",
        "Do not mistake my distance for weakness, %t.",
        "The parameters are set. You are inside them, %t.",
        "Nothing you brought will matter, %t.",
        "Come closer. It changes nothing, %t.",
        "I have prepared for far worse than you, %t.",
        "You will not reach me, %t.",
        "%t. The arcane is already moving.",
        "Consider this your only warning, %t.",
        "That was a decision you cannot unmake, %t.",
        "You are standing in a very poor position, %t.",
        "%t. Nothing about this is a fair fight.",
        "%t. I intend to be thorough.",
        "%t. The cold is already in the air. Notice it.",
        "You have interrupted work more important than you, %t.",
        "%t. Six seconds. That is all this requires.",
        "Do try to be interesting, %t.",
        "%t. There is no negotiation in the arcane.",
        "You will be reduced. It is only a question of order, %t.",
        "%t. I have modelled this fight already.",
        "%t. Nothing survives what I have prepared.",
        "Stand still. It is more efficient, %t.",
        "You are material now, %t.",
        "%t. The demonstration begins.",
        "%t. I do not miss and I do not tire.",
        "%t. Every second from here is scheduled.",
        "You should have kept walking, %t.",
        "Nothing you do alters the conclusion, %t.",
        "%t. The working is already begun.",
        "Distance is my weapon. You have none, %t.",
        "%t. That was the wrong opponent.",
        "I have no interest in your survival, %t.",
        "Come on, then. Be solved, %t.",
        "%t. Nothing here will be merciful.",
        "The equations are unfavourable. For you, %t.",
        "You are about to become an example, %t.",
        "%t. I intend to enjoy the precision, not the violence.",
        "%t. There is no closing this distance.",
        "%t. That is far enough.",
        "You have entered a controlled environment, %t.",
        "Nothing about this ends well for you, %t.",
        "%t. The arcane is patient and I am not.",
        "Prepare. It will not help, %t.",
        "%t. I am going to take this apart carefully.",
        "%t. Begin. I have already finished.",
    },
    ["REACT:COMBATEND"] = {
        "Concluded.",
        "Nothing left standing that was standing before.",
        "As calculated.",
        "The demonstration is complete.",
        "Nothing survived. Correct.",
        "Efficiently done.",
        "Do not touch the residue.",
        "That is the expected result.",
        "The field is clear and cold.",
        "Nothing here requires further attention.",
        "Resolved. Entirely.",
        "The mana was well spent.",
        "That was thorough.",
        "Nothing remains to be solved.",
        "Recorded. Filed. Forgotten.",
        "The cold does its work quietly.",
        "There is nothing left to identify.",
        "A satisfactory conclusion.",
        "Nothing walked away from that.",
        "The equations balanced.",
        "That is what preparation looks like.",
        "Clean. Complete. Cold.",
        "Nothing further from them.",
        "The area is sterilised.",
        "Concluded without complication.",
        "That went precisely as modelled.",
        "Nothing about it was in doubt.",
        "The field belongs to the arcane now.",
        "Efficient. As always.",
        "There is nothing here worth a report.",
        "Reduced, all of them.",
        "The demonstration required no revision.",
        "Nothing survives proper preparation.",
        "Complete. Move on.",
        "That is settled permanently.",
        "The cold settles back into the ground.",
        "Nothing remains that could trouble anyone.",
        "Concluded to specification.",
        "There will be no follow-up.",
        "That is the correct outcome.",
        "Nothing left but material.",
        "The working is finished.",
        "Recorded. Next.",
        "Silence, and I arranged it.",
        "Nothing here breathes.",
        "Precisely as intended.",
        "The field is quiet. Permanently.",
        "Complete. Nothing wasted.",
        "That is the end of the matter.",
    },
    ["REACT:INTERRUPTED"] = {
        "You have no idea what you interrupted, %t.",
        "%t. That was deliberate. So is what follows.",
        "You will regret being quick, %t.",
        "%t. Noted. Filed. Answered shortly.",
        "That cost me six seconds and you considerably more, %t.",
        "Do that again, %t.",
        "%t. Nothing is prevented. Only rescheduled.",
        "You have made this personal, %t.",
        "%t. The working breaks. The intent does not.",
        "That was competent. It was also final for you, %t.",
        "%t. I have other spells. All of them worse.",
        "%t. Silence me. See how long it holds.",
        "You have annoyed something precise, %t.",
        "%t. That will be repaid exactly.",
        "Nothing you break stays broken, %t.",
        "%t. I do not forget interruptions.",
        "%t. Very well. The unpleasant approach.",
        "You bought a second and spent it poorly, %t.",
        "%t. The arcane does not require my voice.",
        "That was your best moment. It has passed, %t.",
        "%t. Adjusting. Coldly.",
        "You have earned my full attention, %t.",
        "There are instant spells for people like you, %t.",
        "%t. That changes the method, not the outcome.",
        "%t. Nothing about this is postponed for long.",
        "You will not manage that twice, %t.",
        "%t. I have accounted for interruption.",
        "%t. That was noted with considerable interest.",
        "Do it again and I stop being careful, %t.",
        "%t. The next working will not be interruptible.",
        "You have made the ending slower, %t.",
        "%t. Nothing survives irritating me.",
        "Recalculating. Unfavourably for you, %t.",
        "%t. That was skill. This will be malice.",
        "%t. I begin again, and colder.",
        "You have delayed a very patient conclusion, %t.",
        "%t. The interruption is recorded.",
        "Nothing you did reached the intent, %t.",
        "%t. Very well. Directly, then.",
        "That will be the last thing you interrupt, %t.",
        "%t. I have a spell that does not require speech.",
        "You are prolonging your own conclusion, %t.",
        "%t. The arcane answers regardless.",
        "%t. That was expected. It was still rude.",
        "Adapting. You will not enjoy the adaptation, %t.",
        "%t. Nothing about my intent is negotiable.",
        "You have chosen a worse ending for yourself, %t.",
        "%t. Beginning again. Watch closely.",
        "%t. That accomplished nothing but my attention.",
    },
}
